#!/bin/sh

set -e

case "${1}" in
	configure)
		update-alternatives --install \
			/usr/bin/tcptraceroute tcptraceroute /usr/bin/tcptraceroute.mt 110 \
			--slave /usr/share/man/man1/tcptraceroute.1.gz tcptraceroute.1.gz \
				/usr/share/man/man1/tcptraceroute.mt.1.gz
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
