# LLVM
export LLVM_HOME=$HOME/LLVM
export LLVM_SRC=$LLVM_HOME/llvm-7.0.0.src
export LLVM_OBJ=$LLVM_HOME/llvm-7.0.0.obj
export LLVM_DIR=$LLVM_HOME/llvm-7.0.0.obj
export PATH=$LLVM_DIR/bin:$PATH

# Trimmer LLVM dependencies
export LLVM_COMPILER=clang
export LLVM_CC_NAME=clang
export LLVM_CXX_NAME=clang++
export LLVM_LINK_NAME=llvm-link
export LLVM_DIS_NAME=llvm-dis
export LLVM_AR_NAME=llvm-ar
export LLVM_AS_NAME=llvm-as
export LLVM_LD_NAME=llvm-ld
export LLVM_LLC_NAME=llc
export LLVM_OPT_NAME=opt
export LLVM_NM_NAME=llvm-nm

# pip
export PATH=/home/vagrant/.local/bin:$PATH

# aircrack-ng
export CPATH=/usr/local/include:$CPATH
export LIBRARY_PATH=/usr/local/lib:/usr/local/lib/engines:$LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
