language: c
compiler:
    - gcc
    - clang
before_script:
    - "mkdir -p m4"
    - "autoreconf -if"
script:
    - "export LIBS=-lrt"
    - "./configure --prefix=/usr --sysconfdir=/etc"
    - "make"
    - "make DESTDIR=/tmp/sysroot install"
branches:
    only:
        - master
