# LLVM
export LLVM_HOME=$HOME/LLVM
export LLVM_SRC=$LLVM_HOME/llvm-7.0.0.src
export LLVM_OBJ=$LLVM_HOME/llvm-7.0.0.obj
export LLVM_DIR=$LLVM_HOME/llvm-7.0.0.obj
export PATH=$LLVM_DIR/bin:$PATH

# Trimmer
export TRIMMER_HOME=$HOME/Trimmer
export LLVM_COMPILER=clang

# aircrack-ng
export CPATH=/usr/local/include:$CPATH
export LIBRARY_PATH=/usr/local/lib:/usr/local/lib/engines:$LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
