.TH tricklectl 8 "Jan 2005"
.SH NAME
tricklectl \-
control utility for \fItrickled\fR
.SH SYNOPSIS
.B tricklectl 
[\fIoptions\fR]
.SH DESCRIPTION
\fBtricklectl\fR is a control utility that lets you query and modify the
current state of a \fItrickled\fR bandwidth shaper daemon. This way you can
for example change up- and download rates. In the moment \fBtricklectl\fR is
of no use, but we hope to have it ready soon!
