array.h File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `vector.h`
*
#include <stdlib.h>
*
Classes
struct data_unset
struct array
struct data_string
struct data_array
struct data_config
struct data_integer
struct data_fastcgi
Macros
#define DATA_IS_STRING(x) (x->type == TYPE_STRING)
#define DATA_UNSET
Typedefs
typedef struct data_unset data_unset
typedef struct data_config data_config
Enumerations
enum data_type_t {
*
TYPE_UNSET,
TYPE_STRING,
TYPE_OTHER,
TYPE_ARRAY,
*
TYPE_INTEGER,
TYPE_FASTCGI,
TYPE_CONFIG
 }
enum config_cond_t {
*
CONFIG_COND_UNSET,
CONFIG_COND_EQ,
CONFIG_COND_MATCH,
CONFIG_COND_NE,
*
CONFIG_COND_NOMATCH,
CONFIG_COND_ELSE
 }
enum comp_key_t {
*
COMP_UNSET,
COMP_SERVER_SOCKET,
COMP_HTTP_URL,
COMP_HTTP_HOST,
*
COMP_HTTP_REFERER,
COMP_HTTP_USER_AGENT,
COMP_HTTP_LANGUAGE,
COMP_HTTP_COOKIE,
*
COMP_HTTP_REMOTE_IP,
COMP_HTTP_QUERY_STRING,
COMP_HTTP_SCHEME,
COMP_HTTP_REQUEST_METHOD,
*
COMP_LAST_ELEMENT
 }
Functions
data_string * data_string_init (void)
data_string * data_response_init (void)
data_array * data_array_init (void)
DEFINE_TYPED_VECTOR_NO_RELEASE (config_weak, data_config *)
data_config * data_config_init (void)
data_integer * data_integer_init (void)
data_fastcgi * data_fastcgi_init (void)
array * array_init (void)
array * array_init_array (array *a)
void array_free (array *a)
void array_reset (array *a)
void array_insert_unique (array *a, data_unset *entry)
data_unset * array_pop (array *a)
int array_print (array *a, int depth)
data_unset * array_get_unused_element (array *a, data_type_t t)
data_unset * array_get_element (array *a, const char *key)
data_unset * array_extract_element (array *a, const char *key)
void array_set_key_value (array *hdrs, const char *key, size_t key_len, const char *value, size_t val_len)
void array_replace (array *a, data_unset *entry)
int array_strcasecmp (const char *a, size_t a_len, const char *b, size_t b_len)
void array_print_indent (int depth)
size_t array_get_max_key_length (array *a)
Macro Definition Documentation
#define DATA_IS_STRING(x) (x->type == TYPE_STRING)
#define DATA_UNSET
Value:
data_type_t type; \
    buffer *key; \
    int is_index_key; /* 1 if key is a array index (autogenerated keys) */ \
    struct data_unset *(*copy)(const struct data_unset *src); \
    void (* free)(struct data_unset *p); \
    void (* reset)(struct data_unset *p); \
    int (*insert_dup)(struct data_unset *dst, struct data_unset *src); \
    void (*print)(const struct data_unset *p, int depth)
Typedef Documentation
typedef struct data_config data_config
typedef struct data_unset data_unset
Enumeration Type Documentation
enum comp_key_t
possible fields to match against
Enumerator
COMP_UNSET
COMP_SERVER_SOCKET
COMP_HTTP_URL
COMP_HTTP_HOST
COMP_HTTP_REFERER
COMP_HTTP_USER_AGENT
COMP_HTTP_LANGUAGE
COMP_HTTP_COOKIE
COMP_HTTP_REMOTE_IP
COMP_HTTP_QUERY_STRING
COMP_HTTP_SCHEME
COMP_HTTP_REQUEST_METHOD
COMP_LAST_ELEMENT
enum config_cond_t
possible compare ops in the configfile parser
Enumerator
CONFIG_COND_UNSET
CONFIG_COND_EQ
CONFIG_COND_MATCH
 ==
CONFIG_COND_NE
 =~
CONFIG_COND_NOMATCH
 !=
CONFIG_COND_ELSE
 !~ (always true if reached)
enum data_type_t
Enumerator
TYPE_UNSET
TYPE_STRING
TYPE_OTHER
TYPE_ARRAY
TYPE_INTEGER
TYPE_FASTCGI
TYPE_CONFIG
Function Documentation
data_unset* array_extract_element (array * a, const char * key)
References array_get_index(), ARRAY_NOT_FOUND, CONST_BUF_LEN, array::data, force_assert, array::sorted, and array::used.
Referenced by yy_reduce().
void array_free (array * a)
References array::data, array::size, and array::sorted.
Referenced by config_insert(), connections_free(), data_array_copy(), data_array_free(), data_config_copy(), data_config_free(), fastcgi_host_free(), FREE_FUNC(), http_auth_require_free(), mod_evhost_uri_handler(), scgi_host_free(), server_free(), SETDEFAULTS_FUNC(), URIHANDLER_FUNC(), yy_destructor(), and yy_reduce().
data_unset* array_get_element (array * a, const char * key)
References array_get_index(), ARRAY_NOT_FOUND, array::data, and force_assert.
Referenced by array_set_key_value(), build_ssi_cgi_vars(), cache_parse_lua(), cgi_demux_response(), config_check_cond_nocache(), config_insert_values_global(), config_insert_values_internal(), configparser_get_variable(), configparser_merge_data(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_write_prepare(), fcgi_demux_response(), http_auth_setenv(), http_request_parse(), http_response_parse_range(), http_response_send_file(), http_response_xsendfile(), is_proxy_trusted(), last_not_in_array(), magnet_attract_array(), magnet_cgi_get(), magnet_reqhdr_get(), main(), mod_auth_check_basic(), mod_auth_check_digest(), mod_auth_check_extern(), mod_authn_gssapi_check(), mod_evhost_uri_handler(), parse_config_entry(), PHYSICALPATH_FUNC(), process_ssi_stmt(), REQUESTDONE_FUNC(), response_header_append(), response_header_overwrite(), scgi_demux_response(), SETDEFAULTS_FUNC(), ssi_expr_tokenizer(), status_counter_get_counter(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_has_lock(), and yy_reduce().
size_t array_get_max_key_length (array * a)
References array::data, and array::used.
Referenced by array_print(), and data_config_print().
data_unset* array_get_unused_element (array * a, data_type_t t)
References array::data, and array::used.
Referenced by array_set_key_value(), cgi_response_parse(), connection_state_machine(), fcgi_response_parse(), http_auth_setenv(), http_request_parse(), http_request_split_value(), process_ssi_stmt(), proxy_append_header(), proxy_response_parse(), proxy_set_header(), response_header_insert(), scgi_response_parse(), split_get_params(), ssi_env_add(), status_counter_get_counter(), and URIHANDLER_FUNC().
array* array_init (void)
References force_assert.
Referenced by array_init_array(), config_insert(), connection_init(), data_array_init(), data_config_init(), extract_forward_array(), fastcgi_host_init(), http_auth_require_init(), INIT_FUNC(), mod_evhost_uri_handler(), scgi_host_init(), server_init(), SETDEFAULTS_FUNC(), and yy_reduce().
array* array_init_array (array * a)
References array_init(), array::data, force_assert, array::size, array::sorted, array::unique_ndx, and array::used.
Referenced by data_array_copy(), and data_config_copy().
void array_insert_unique (array * a, data_unset * entry)
References array_find_or_insert(), and force_assert.
Referenced by array_set_key_value(), cgi_response_parse(), config_insert(), config_insert_values_global(), config_insert_values_internal(), config_read(), config_set_defaults(), configparser_merge_data(), configparser_push(), connection_state_machine(), fcgi_response_parse(), http_auth_setenv(), http_request_parse(), http_request_split_value(), mod_auth_require_parse(), mod_evhost_parse_host(), process_ssi_stmt(), proxy_append_header(), proxy_response_parse(), proxy_set_header(), put_string_into_array_len(), response_header_insert(), scgi_response_parse(), SETDEFAULTS_FUNC(), split_get_params(), ssi_env_add(), status_counter_get_counter(), URIHANDLER_FUNC(), and yy_reduce().
data_unset* array_pop (array * a)
References array::data, force_assert, array::sorted, and array::used.
int array_print (array * a, int depth)
References array_get_max_key_length(), array_print_indent(), array::data, TYPE_INTEGER, TYPE_STRING, and array::used.
Referenced by configparser_get_variable(), and data_array_print().
void array_print_indent (int depth)
Referenced by array_print(), and data_config_print().
void array_replace (array * a, data_unset * entry)
References array_find_or_insert(), and force_assert.
Referenced by fcgi_response_parse().
void array_reset (array * a)
References array::data, array::unique_ndx, and array::used.
Referenced by build_ssi_cgi_vars(), connection_handle_errdoc_init(), connection_reset(), connection_response_reset(), data_array_reset(), data_config_reset(), http_request_parse(), mod_ssi_handle_request(), SETDEFAULTS_FUNC(), and URIHANDLER_FUNC().
void array_set_key_value (array * hdrs, const char * key, size_t key_len, const char * value, size_t val_len)
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), data_string_init(), TYPE_STRING, and data_string::value.
Referenced by magnet_cgi_set(), mod_authn_gssapi_create_krb5_ccache(), mod_compress_note_ratio(), and mod_deflate_note_ratio().
int array_strcasecmp (const char * a, size_t a_len, const char * b, size_t b_len)
data_array* data_array_init (void)
References array_init(), buffer_init(), data_array_copy(), data_array_free(), data_array_insert_dup(), data_array_print(), data_array_reset(), force_assert, TYPE_ARRAY, and data_array::value.
Referenced by data_array_copy(), SETDEFAULTS_FUNC(), and yy_reduce().
data_config* data_config_init (void)
References array_init(), buffer_init(), data_config::children, data_config::comp_key, data_config_copy(), data_config_free(), data_config_insert_dup(), data_config_print(), data_config_reset(), data_config::op, TYPE_CONFIG, and data_config::value.
Referenced by config_read(), data_config_copy(), and yy_reduce().
data_fastcgi* data_fastcgi_init (void)
References buffer_init(), data_fastcgi_copy(), data_fastcgi_free(), data_fastcgi_insert_dup(), data_fastcgi_print(), data_fastcgi_reset(), force_assert, data_fastcgi::host, data_fastcgi::is_disabled, data_fastcgi::port, and TYPE_FASTCGI.
Referenced by data_fastcgi_copy().
data_integer* data_integer_init (void)
References buffer_init(), data_integer_copy(), data_integer_free(), data_integer_insert_dup(), data_integer_print(), data_integer_reset(), force_assert, TYPE_INTEGER, and data_integer::value.
Referenced by config_read(), data_integer_copy(), status_counter_get_counter(), and yy_reduce().
data_string* data_response_init (void)
References data_response_insert_dup(), and data_string_init().
Referenced by cgi_response_parse(), fcgi_response_parse(), proxy_response_parse(), response_header_insert(), scgi_response_parse(), and URIHANDLER_FUNC().
data_string* data_string_init (void)
References buffer_init(), data_string_copy(), data_string_free(), data_string_insert_dup(), data_string_print(), data_string_reset(), force_assert, TYPE_STRING, and data_string::value.
Referenced by array_set_key_value(), config_insert(), config_insert_values_global(), config_read(), config_set_defaults(), configparser_merge_data(), connection_state_machine(), data_response_init(), data_string_copy(), http_auth_setenv(), http_request_parse(), http_request_split_value(), mod_auth_require_parse(), mod_evhost_parse_host(), process_ssi_stmt(), proxy_append_header(), proxy_set_header(), put_string_into_array_len(), split_get_params(), ssi_env_add(), URIHANDLER_FUNC(), and yy_reduce().
DEFINE_TYPED_VECTOR_NO_RELEASE (config_weak , data_config *)