array.c File Reference
#include `first.h`
*
#include `array.h`
*
#include `buffer.h`
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <limits.h>
*
#include <errno.h>
*
#include <assert.h>
*
Macros
#define ARRAY_NOT_FOUND ((size_t)(-1))
Functions
array * array_init (void)
array * array_init_array (array *src)
void array_free (array *a)
void array_reset (array *a)
data_unset * array_pop (array *a)
static size_t array_get_index (array *a, const char *key, size_t keylen, size_t *rndx)
data_unset * array_get_element (array *a, const char *key)
data_unset * array_extract_element (array *a, const char *key)
data_unset * array_get_unused_element (array *a, data_type_t t)
void array_set_key_value (array *hdrs, const char *key, size_t key_len, const char *value, size_t val_len)
static data_unset ** array_find_or_insert (array *a, data_unset *entry)
void array_replace (array *a, data_unset *entry)
void array_insert_unique (array *a, data_unset *entry)
void array_print_indent (int depth)
size_t array_get_max_key_length (array *a)
int array_print (array *a, int depth)
Macro Definition Documentation
#define ARRAY_NOT_FOUND ((size_t)(-1))
Referenced by array_extract_element(), array_find_or_insert(), array_get_element(), and array_get_index().
Function Documentation
data_unset* array_extract_element (array * a, const char * key)
References array_get_index(), ARRAY_NOT_FOUND, CONST_BUF_LEN, array::data, force_assert, array::sorted, and array::used.
Referenced by yy_reduce().
static data_unset** array_find_or_insert (array * a, data_unset * entry) [static]
References array_get_index(), ARRAY_NOT_FOUND, buffer_copy_int(), buffer_is_empty(), CONST_BUF_LEN, array::data, force_assert, array::size, array::sorted, SSIZE_MAX, array::unique_ndx, and array::used.
Referenced by array_insert_unique(), and array_replace().
void array_free (array * a)
References array::data, array::size, and array::sorted.
Referenced by config_insert(), connections_free(), data_array_copy(), data_array_free(), data_config_copy(), data_config_free(), fastcgi_host_free(), FREE_FUNC(), http_auth_require_free(), mod_evhost_uri_handler(), scgi_host_free(), server_free(), SETDEFAULTS_FUNC(), URIHANDLER_FUNC(), yy_destructor(), and yy_reduce().
data_unset* array_get_element (array * a, const char * key)
References array_get_index(), ARRAY_NOT_FOUND, array::data, and force_assert.
Referenced by array_set_key_value(), build_ssi_cgi_vars(), cache_parse_lua(), cgi_demux_response(), config_check_cond_nocache(), config_insert_values_global(), config_insert_values_internal(), configparser_get_variable(), configparser_merge_data(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_write_prepare(), fcgi_demux_response(), http_auth_setenv(), http_request_parse(), http_response_parse_range(), http_response_send_file(), http_response_xsendfile(), is_proxy_trusted(), last_not_in_array(), magnet_attract_array(), magnet_cgi_get(), magnet_reqhdr_get(), main(), mod_auth_check_basic(), mod_auth_check_digest(), mod_auth_check_extern(), mod_authn_gssapi_check(), mod_evhost_uri_handler(), parse_config_entry(), PHYSICALPATH_FUNC(), process_ssi_stmt(), REQUESTDONE_FUNC(), response_header_append(), response_header_overwrite(), scgi_demux_response(), SETDEFAULTS_FUNC(), ssi_expr_tokenizer(), status_counter_get_counter(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_has_lock(), and yy_reduce().
static size_t array_get_index (array * a, const char * key, size_t keylen, size_t * rndx) [static]
References ARRAY_NOT_FOUND, assert, buffer_caseless_compare(), CONST_BUF_LEN, array::data, force_assert, array::sorted, SSIZE_MAX, and array::used.
Referenced by array_extract_element(), array_find_or_insert(), and array_get_element().
size_t array_get_max_key_length (array * a)
References array::data, and array::used.
Referenced by array_print(), and data_config_print().
data_unset* array_get_unused_element (array * a, data_type_t t)
References array::data, and array::used.
Referenced by array_set_key_value(), cgi_response_parse(), connection_state_machine(), fcgi_response_parse(), http_auth_setenv(), http_request_parse(), http_request_split_value(), process_ssi_stmt(), proxy_append_header(), proxy_response_parse(), proxy_set_header(), response_header_insert(), scgi_response_parse(), split_get_params(), ssi_env_add(), status_counter_get_counter(), and URIHANDLER_FUNC().
array* array_init (void)
References force_assert.
Referenced by array_init_array(), config_insert(), connection_init(), data_array_init(), data_config_init(), extract_forward_array(), fastcgi_host_init(), http_auth_require_init(), INIT_FUNC(), mod_evhost_uri_handler(), scgi_host_init(), server_init(), SETDEFAULTS_FUNC(), and yy_reduce().
array* array_init_array (array * src)
References array_init(), array::data, force_assert, array::size, array::sorted, array::unique_ndx, and array::used.
Referenced by data_array_copy(), and data_config_copy().
void array_insert_unique (array * a, data_unset * entry)
References array_find_or_insert(), and force_assert.
Referenced by array_set_key_value(), cgi_response_parse(), config_insert(), config_insert_values_global(), config_insert_values_internal(), config_read(), config_set_defaults(), configparser_merge_data(), configparser_push(), connection_state_machine(), fcgi_response_parse(), http_auth_setenv(), http_request_parse(), http_request_split_value(), mod_auth_require_parse(), mod_evhost_parse_host(), process_ssi_stmt(), proxy_append_header(), proxy_response_parse(), proxy_set_header(), put_string_into_array_len(), response_header_insert(), scgi_response_parse(), SETDEFAULTS_FUNC(), split_get_params(), ssi_env_add(), status_counter_get_counter(), URIHANDLER_FUNC(), and yy_reduce().
data_unset* array_pop (array * a)
References array::data, force_assert, array::sorted, and array::used.
int array_print (array * a, int depth)
References array_get_max_key_length(), array_print_indent(), array::data, TYPE_INTEGER, TYPE_STRING, and array::used.
Referenced by configparser_get_variable(), and data_array_print().
void array_print_indent (int depth)
Referenced by array_print(), and data_config_print().
void array_replace (array * a, data_unset * entry)
References array_find_or_insert(), and force_assert.
Referenced by fcgi_response_parse().
void array_reset (array * a)
References array::data, array::unique_ndx, and array::used.
Referenced by build_ssi_cgi_vars(), connection_handle_errdoc_init(), connection_reset(), connection_response_reset(), data_array_reset(), data_config_reset(), http_request_parse(), mod_ssi_handle_request(), SETDEFAULTS_FUNC(), and URIHANDLER_FUNC().
void array_set_key_value (array * hdrs, const char * key, size_t key_len, const char * value, size_t val_len)
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), data_string_init(), TYPE_STRING, and data_string::value.
Referenced by magnet_cgi_set(), mod_authn_gssapi_create_krb5_ccache(), mod_compress_note_ratio(), and mod_deflate_note_ratio().