base64.c File Reference
#include `first.h`
*
#include `base64.h`
*
Functions
unsigned char * buffer_append_base64_decode (buffer *out, const char *in, size_t in_length, base64_charset charset)
size_t li_to_base64_no_padding (char *out, size_t out_length, const unsigned char *in, size_t in_length, base64_charset charset)
size_t li_to_base64 (char *out, size_t out_length, const unsigned char *in, size_t in_length, base64_charset charset)
char * buffer_append_base64_encode_no_padding (buffer *out, const unsigned char *in, size_t in_length, base64_charset charset)
char * buffer_append_base64_encode (buffer *out, const unsigned char *in, size_t in_length, base64_charset charset)
Variables
static const char base64_standard_table [66] = `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=`
static const short base64_standard_reverse_table [128]
static const char base64_url_table [66] = `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.`
static const short base64_url_reverse_table [128]
Function Documentation
unsigned char* buffer_append_base64_decode (buffer * out, const char * in, size_t in_length, base64_charset charset)
References BASE64_STANDARD, base64_standard_reverse_table, BASE64_URL, base64_url_reverse_table, buffer_commit(), and buffer_string_prepare_append().
Referenced by check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), mod_auth_check_basic(), and mod_authn_gssapi_check_spnego().
char* buffer_append_base64_encode (buffer * out, const unsigned char * in, size_t in_length, base64_charset charset)
References buffer_commit(), buffer_string_prepare_append(), and li_to_base64().
char* buffer_append_base64_encode_no_padding (buffer * out, const unsigned char * in, size_t in_length, base64_charset charset)
References buffer_commit(), buffer_string_prepare_append(), and li_to_base64_no_padding().
size_t li_to_base64 (char * out, size_t out_length, const unsigned char * in, size_t in_length, base64_charset charset)
References BASE64_STANDARD, base64_standard_table, BASE64_URL, base64_url_table, force_assert, and li_to_base64_no_padding().
Referenced by buffer_append_base64_encode().
size_t li_to_base64_no_padding (char * out, size_t out_length, const unsigned char * in, size_t in_length, base64_charset charset)
References BASE64_STANDARD, base64_standard_table, BASE64_URL, base64_url_table, and force_assert.
Referenced by buffer_append_base64_encode_no_padding(), check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), li_to_base64(), and secdl_verify_mac().
Variable Documentation
const short base64_standard_reverse_table[128] [static]
Initial value:
= {
    -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, -1, -1, -1, -3, -1, -1,
    -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, -1, -1, -1,
    -1, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1,
}
Referenced by buffer_append_base64_decode().
const char base64_standard_table[66] = `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=` [static]
Referenced by li_to_base64(), and li_to_base64_no_padding().
const short base64_url_reverse_table[128] [static]
Initial value:
= {
    -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -3, -1,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, -1, -1, -1, -1, -1, -1,
    -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, -1, -1, 63,
    -1, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1,
}
Referenced by buffer_append_base64_decode().
const char base64_url_table[66] = `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.` [static]
Referenced by li_to_base64(), and li_to_base64_no_padding().