base64.h File Reference
#include `first.h`
*
#include `buffer.h`
*
Enumerations
enum base64_charset { BASE64_STANDARD,
BASE64_URL
 }
Functions
unsigned char * buffer_append_base64_decode (buffer *out, const char *in, size_t in_length, base64_charset charset)
size_t li_to_base64_no_padding (char *out, size_t out_length, const unsigned char *in, size_t in_length, base64_charset charset)
size_t li_to_base64 (char *out, size_t out_length, const unsigned char *in, size_t in_length, base64_charset charset)
char * buffer_append_base64_encode_no_padding (buffer *out, const unsigned char *in, size_t in_length, base64_charset charset)
char * buffer_append_base64_encode (buffer *out, const unsigned char *in, size_t in_length, base64_charset charset)
Enumeration Type Documentation
enum base64_charset
Enumerator
BASE64_STANDARD
BASE64_URL
Function Documentation
unsigned char* buffer_append_base64_decode (buffer * out, const char * in, size_t in_length, base64_charset charset)
References BASE64_STANDARD, base64_standard_reverse_table, BASE64_URL, base64_url_reverse_table, buffer_commit(), and buffer_string_prepare_append().
Referenced by check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), mod_auth_check_basic(), and mod_authn_gssapi_check_spnego().
char* buffer_append_base64_encode (buffer * out, const unsigned char * in, size_t in_length, base64_charset charset)
References buffer_commit(), buffer_string_prepare_append(), and li_to_base64().
char* buffer_append_base64_encode_no_padding (buffer * out, const unsigned char * in, size_t in_length, base64_charset charset)
References buffer_commit(), buffer_string_prepare_append(), and li_to_base64_no_padding().
size_t li_to_base64 (char * out, size_t out_length, const unsigned char * in, size_t in_length, base64_charset charset)
References BASE64_STANDARD, base64_standard_table, BASE64_URL, base64_url_table, force_assert, and li_to_base64_no_padding().
Referenced by buffer_append_base64_encode().
size_t li_to_base64_no_padding (char * out, size_t out_length, const unsigned char * in, size_t in_length, base64_charset charset)
References BASE64_STANDARD, base64_standard_table, BASE64_URL, base64_url_table, and force_assert.
Referenced by buffer_append_base64_encode_no_padding(), check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), li_to_base64(), and secdl_verify_mac().