buffer.h File Reference
#include `first.h`
*
#include `settings.h`
*
#include <stdlib.h>
*
#include <sys/types.h>
*
#include <stdio.h>
*
#include <time.h>
*
Classes
struct buffer
Macros
#define LI_ITOSTRING_LENGTH (2 + (8 * sizeof(intmax_t) * 31 + 99) / 100)
#define BUFFER_APPEND_STRING_CONST(x, y) buffer_append_string_len(x, y, sizeof(y) - 1)
#define BUFFER_COPY_STRING_CONST(x, y) buffer_copy_string_len(x, y, sizeof(y) - 1)
#define CONST_STR_LEN(x) x, (x) ? sizeof(x) - 1 : 0
#define CONST_BUF_LEN(x) ((x) ? (x)->ptr : NULL), buffer_string_length(x)
#define force_assert(x) do { if (!(x)) log_failed_assert(__FILE__, __LINE__, `assertion failed: ` #x); } while(0)
#define SEGFAULT() log_failed_assert(__FILE__, __LINE__, `aborted`);
Enumerations
enum buffer_encoding_t {
*
ENCODING_REL_URI,
ENCODING_REL_URI_PART,
ENCODING_HTML,
ENCODING_MINIMAL_XML,
*
ENCODING_HEX,
ENCODING_HTTP_HEADER
 }
Functions
buffer * buffer_init (void)
buffer * buffer_init_buffer (const buffer *src)
buffer * buffer_init_string (const char *str)
void buffer_free (buffer *b)
void buffer_reset (buffer *b)
void buffer_move (buffer *b, buffer *src)
char * buffer_string_prepare_copy (buffer *b, size_t size)
char * buffer_string_prepare_append (buffer *b, size_t size)
void buffer_commit (buffer *b, size_t size)
void buffer_string_set_length (buffer *b, size_t len)
void buffer_copy_string (buffer *b, const char *s)
void buffer_copy_string_len (buffer *b, const char *s, size_t s_len)
void buffer_copy_buffer (buffer *b, const buffer *src)
void buffer_copy_string_hex (buffer *b, const char *in, size_t in_len)
void buffer_append_string (buffer *b, const char *s)
void buffer_append_string_len (buffer *b, const char *s, size_t s_len)
void buffer_append_string_buffer (buffer *b, const buffer *src)
void buffer_append_uint_hex (buffer *b, uintmax_t len)
void buffer_append_int (buffer *b, intmax_t val)
void buffer_copy_int (buffer *b, intmax_t val)
void buffer_append_strftime (buffer *b, const char *format, const struct tm *tm)
void li_itostrn (char *buf, size_t buf_len, intmax_t val)
void li_utostrn (char *buf, size_t buf_len, uintmax_t val)
void li_tohex (char *buf, size_t buf_len, const char *s, size_t s_len)
char * buffer_search_string_len (buffer *b, const char *needle, size_t len)
int buffer_is_empty (const buffer *b)
int buffer_string_is_empty (const buffer *b)
int buffer_is_equal (const buffer *a, const buffer *b)
int buffer_is_equal_right_len (const buffer *a, const buffer *b, size_t len)
int buffer_is_equal_string (const buffer *a, const char *s, size_t b_len)
int buffer_is_equal_caseless_string (const buffer *a, const char *s, size_t b_len)
int buffer_caseless_compare (const char *a, size_t a_len, const char *b, size_t b_len)
void buffer_append_string_encoded (buffer *b, const char *s, size_t s_len, buffer_encoding_t encoding)
void buffer_append_string_c_escaped (buffer *b, const char *s, size_t s_len)
void buffer_copy_string_encoded_cgi_varnames (buffer *b, const char *s, size_t s_len, int is_http_header)
void buffer_urldecode_path (buffer *url)
void buffer_urldecode_query (buffer *url)
void buffer_path_simplify (buffer *dest, buffer *src)
void buffer_to_lower (buffer *b)
void buffer_to_upper (buffer *b)
char hex2int (unsigned char c)
char int2hex (char i)
int light_isdigit (int c)
int light_isxdigit (int c)
int light_isalpha (int c)
int light_isalnum (int c)
static size_t buffer_string_length (const buffer *b)
static size_t buffer_string_space (const buffer *b)
static void buffer_append_slash (buffer *b)
void print_backtrace (FILE *file)
void log_failed_assert (const char *filename, unsigned int line, const char *msg) LI_NORETURN
Macro Definition Documentation
#define BUFFER_APPEND_STRING_CONST(x, y) buffer_append_string_len(x, y, sizeof(y) - 1)
Referenced by accesslog_append_escaped(), buffer_append_slash(), and mod_authn_gssapi_basic().
#define BUFFER_COPY_STRING_CONST(x, y) buffer_copy_string_len(x, y, sizeof(y) - 1)
#define CONST_BUF_LEN(x) ((x) ? (x)->ptr : NULL), buffer_string_length(x)
Referenced by array_extract_element(), array_find_or_insert(), array_get_index(), cache_parse_lua(), config_check_cond_nocache(), config_parse_cmd(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_write_prepare(), deflate_file_to_file(), fcgi_host_assign(), fcgi_host_reset(), fcgi_proc_load_dec(), fcgi_proc_load_inc(), fcgi_write_request(), FREE_FUNC(), http_cgi_headers(), http_chunk_append_to_tempfile(), http_list_directory(), http_list_directory_header(), http_request_parse(), http_response_parse_range(), http_response_redirect_to_directory(), http_response_send_file(), http_response_write_header(), log_buffer_append_printf(), log_write(), magnet_array_next(), magnet_cgi_get(), magnet_env_get(), magnet_env_next(), magnet_reqhdr_get(), magnet_stat(), main(), mod_auth_check_basic(), mod_auth_send_401_unauthorized_basic(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_proxy_extension_host_get(), mod_redirect_uri_handler(), mod_rrdtool_create_rrd(), mod_ssi_handle_request(), mod_status_handle_server_status_html(), PHYSICALPATH_FUNC(), proc_open_buffer(), process_ssi_stmt(), REQUESTDONE_FUNC(), secdl_verify_mac(), SETDEFAULTS_FUNC(), SIGHUP_FUNC(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), URIHANDLER_FUNC(), webdav_copy_dir(), webdav_copy_file(), webdav_delete_dir(), webdav_delete_file(), webdav_get_property(), and webdav_has_lock().
#define CONST_STR_LEN(x) x, (x) ? sizeof(x) - 1 : 0
Referenced by buffer_copy_string_encoded_cgi_varnames(), cache_parse_lua(), cgi_create_env(), chunkqueue_get_append_tempfile(), config_check_cond_nocache(), config_insert(), config_insert_values_global(), config_insert_values_internal(), config_patch_connection(), config_read(), config_tokenizer(), configparser_remoteip_normalize_compat(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_write_prepare(), connection_state_machine(), data_response_insert_dup(), data_string_insert_dup(), deflate_file_to_file(), etag_create(), etag_mutate(), fastcgi_status_copy_procname(), fcgi_demux_response(), fcgi_establish_connection(), fcgi_host_assign(), fcgi_host_reset(), fcgi_patch_connection(), fcgi_proc_load_dec(), fcgi_proc_load_inc(), fcgi_response_parse(), fcgi_write_request(), http_auth_setenv(), http_cgi_headers(), http_chunk_append_data(), http_chunk_append_file_fd_range(), http_chunk_append_len(), http_chunk_append_to_tempfile(), http_chunk_close(), http_dirlist_append_js_table_resort(), http_list_directory(), http_list_directory_footer(), http_list_directory_header(), http_list_directory_include_file(), http_request_header_finished(), http_request_host_normalize(), http_request_parse(), http_response_parse_range(), http_response_prepare(), http_response_redirect_to_directory(), http_response_send_file(), http_response_write_header(), log_buffer_append_printf(), log_buffer_prepare(), log_write(), main(), mod_access_patch_connection(), mod_accesslog_patch_connection(), mod_alias_patch_connection(), mod_auth_check_basic(), mod_auth_check_digest(), mod_auth_patch_connection(), mod_auth_require_parse(), mod_auth_send_401_unauthorized_basic(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_htpasswd_basic(), mod_authn_file_patch_connection(), mod_authn_file_plain_digest(), mod_authn_gssapi_check_spnego(), mod_authn_gssapi_create_krb5_ccache(), mod_authn_gssapi_log_gss_error(), mod_authn_gssapi_patch_connection(), mod_authn_gssapi_send_401_unauthorized_basic(), mod_authn_gssapi_send_401_unauthorized_negotiate(), mod_authn_ldap_basic(), mod_authn_ldap_patch_connection(), mod_authn_mysql_patch_connection(), mod_cgi_patch_connection(), mod_cml_patch_connection(), mod_compress_note_ratio(), mod_compress_patch_connection(), mod_deflate_note_ratio(), mod_deflate_patch_connection(), mod_dirlisting_patch_connection(), mod_evasive_patch_connection(), mod_evhost_parse_host(), mod_evhost_patch_connection(), mod_evhost_uri_handler(), mod_expire_patch_connection(), mod_extforward_patch_connection(), mod_flv_streaming_patch_connection(), mod_geoip_patch_connection(), mod_indexfile_patch_connection(), mod_magnet_patch_connection(), mod_mysql_vhost_patch_connection(), mod_proxy_patch_connection(), mod_redirect_uri_handler(), mod_rrd_patch_connection(), mod_rrdtool_create_rrd(), mod_secdownload_patch_connection(), mod_setenv_patch_connection(), mod_simple_vhost_patch_connection(), mod_skeleton_patch_connection(), mod_ssi_handle_request(), mod_ssi_patch_connection(), mod_ssi_read_fd(), mod_staticfile_patch_connection(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), mod_status_header_append(), mod_status_header_append_sort(), mod_status_patch_connection(), mod_status_row_append(), mod_trigger_b4_dl_patch_connection(), mod_uploadprogress_patch_connection(), mod_userdir_patch_connection(), mod_usertrack_patch_connection(), mod_webdav_patch_connection(), network_init(), network_server_init(), PHYSICALPATH_FUNC(), plugins_load(), process_ssi_stmt(), proxy_create_env(), proxy_demux_response(), REQUESTDONE_FUNC(), response_header_append(), scgi_create_env(), scgi_patch_connection(), SETDEFAULTS_FUNC(), ssi_expr_tokenizer(), SUBREQUEST_FUNC(), test_buffer_path_simplify_with(), TRIGGER_FUNC(), URIHANDLER_FUNC(), webdav_gen_prop_tag(), webdav_gen_response_status_tag(), webdav_get_live_property(), and yy_reduce().
#define force_assert(x) do { if (!(x)) log_failed_assert(__FILE__, __LINE__, `assertion failed: ` #x); } while(0)
Referenced by array_extract_element(), array_find_or_insert(), array_get_element(), array_get_index(), array_init(), array_init_array(), array_insert_unique(), array_pop(), array_replace(), buffer_alloc(), buffer_append_int(), buffer_append_strftime(), buffer_append_string_c_escaped(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_commit(), buffer_copy_int(), buffer_copy_string_encoded_cgi_varnames(), buffer_copy_string_hex(), buffer_copy_string_len(), buffer_init(), buffer_is_equal(), buffer_is_equal_caseless_string(), buffer_is_equal_string(), buffer_path_simplify(), buffer_realloc(), buffer_search_string_len(), buffer_string_prepare_append(), buffer_string_prepare_copy(), buffer_string_set_length(), buffer_urldecode_internal(), build_doc_root(), cache_parse_lua(), cgi_create_env(), cgi_env_add(), cgi_handler_ctx_init(), cgi_pid_add(), cgi_write_file_chunk_mmap(), check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), chunk_init(), chunk_remaining_length(), chunkqueue_append_buffer(), chunkqueue_get_memory(), chunkqueue_get_unused_chunk(), chunkqueue_init(), chunkqueue_mark_written(), chunkqueue_prepend_buffer(), chunkqueue_push_unused_chunk(), chunkqueue_steal(), chunkqueue_steal_with_tempfiles(), chunkqueue_use_memory(), config_insert(), config_parse(), config_read(), config_skip_comment(), config_skip_newline(), configparser_merge_data(), configparser_push(), connection_handle_read_post_chunked(), connection_handle_read_post_cq_compact(), connection_init(), connections_get_new_connection(), data_array_init(), data_auth_init(), data_fastcgi_init(), data_integer_init(), data_string_init(), env_add(), fastcgi_extension_insert(), fcgi_env_add(), fcgi_header(), fcgi_restart_dead_procs(), fd_close_on_exec(), fdevent_init(), fdnode_init(), fdwaitqueue_append(), handler_ctx_init(), http_auth_backend_set(), http_auth_require_init(), http_auth_scheme_set(), http_cgi_headers(), http_chunk_append_buffer(), http_chunk_append_len(), http_chunk_append_mem(), http_chunk_close(), http_list_directory(), INIT_FUNC(), joblist_append(), li_itostrn(), li_to_base64(), li_to_base64_no_padding(), li_tohex(), li_utostrn(), lua_to_c_get_string(), lua_to_c_is_table(), magnet_attach_content(), magnet_attract(), magnet_copy_response_header(), mmap_align_offset(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_deflate_file_chunk(), mod_proxy_extension_host_get(), mod_ssi_read_fd(), network_open_file_chunk(), network_server_init(), network_write_file_chunk_no_mmap(), network_write_mem_chunk(), pcre_keyvalue_buffer_append(), pcre_keyvalue_buffer_init(), PHYSICALPATH_FUNC(), plugin_init(), plugins_call_init(), plugins_register(), proxy_demux_response(), scgi_extension_insert(), scgi_extensions_init(), scgi_process_init(), script_cache_get_script(), server_init(), SETDEFAULTS_FUNC(), ssi_eval_expr(), stat_cache_entry_init(), stat_cache_free(), stat_cache_get_entry(), stat_cache_init(), stat_cache_trigger_cleanup(), SUBREQUEST_FUNC(), vector_realloc(), webdav_copy_file(), write_all(), and yy_reduce().
#define LI_ITOSTRING_LENGTH (2 + (8 * sizeof(intmax_t) * 31 + 99) / 100)
Referenced by buffer_append_int(), http_cgi_headers(), li_itostrn(), li_utostrn(), mod_auth_send_401_unauthorized_digest(), mod_compress_note_ratio(), mod_deflate_note_ratio(), and URIHANDLER_FUNC().
#define SEGFAULT() log_failed_assert(__FILE__, __LINE__, `aborted`);
Referenced by fdevent_event_get_fd(), fdevent_event_get_revent(), fdevent_get_context(), fdevent_get_handler(), fdevent_poll(), mod_rrd_create_pipe(), process_ssi_stmt(), and URIHANDLER_FUNC().
Enumeration Type Documentation
enum buffer_encoding_t
Enumerator
ENCODING_REL_URI
ENCODING_REL_URI_PART
ENCODING_HTML
ENCODING_MINIMAL_XML
ENCODING_HEX
ENCODING_HTTP_HEADER
Function Documentation
void buffer_append_int (buffer * b, intmax_t val)
References buffer_append_string_len(), force_assert, itostr(), and LI_ITOSTRING_LENGTH.
Referenced by buffer_copy_int(), config_check_cond_nocache(), configparser_merge_data(), CONNECTION_FUNC(), connection_handle_write_prepare(), connection_state_machine(), etag_create(), etag_mutate(), fastcgi_status_copy_procname(), fcgi_establish_connection(), http_request_host_normalize(), http_response_parse_range(), http_response_redirect_to_directory(), http_response_write_header(), log_buffer_append_printf(), log_buffer_prepare(), mod_evhost_parse_host(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), network_init(), REQUESTDONE_FUNC(), scgi_create_env(), SETDEFAULTS_FUNC(), stat_cache_get_entry(), TRIGGER_FUNC(), URIHANDLER_FUNC(), webdav_gen_response_status_tag(), webdav_get_live_property(), and yy_reduce().
static void buffer_append_slash (buffer * b) [inline], [static]
References BUFFER_APPEND_STRING_CONST, buffer_string_length(), and buffer::ptr.
Referenced by build_doc_root(), chunkqueue_get_append_tempfile(), config_set_defaults(), CONNECTION_FUNC(), deflate_file_to_file(), http_list_directory_footer(), http_list_directory_header(), http_response_prepare(), mod_evhost_uri_handler(), SETDEFAULTS_FUNC(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_copy_dir(), and webdav_delete_dir().
void buffer_append_strftime (buffer * b, const char * format, const struct tm * tm)
References buffer_commit(), buffer_string_prepare_append(), buffer_string_space(), and force_assert.
Referenced by CONNECTION_FUNC(), http_response_write_header(), log_buffer_prepare(), REQUESTDONE_FUNC(), and strftime_cache_get().
void buffer_append_string (buffer * b, const char * s)
References buffer_append_string_len().
Referenced by cache_parse_lua(), config_parse_file(), CONNECTION_FUNC(), connection_handle_write_prepare(), deflate_file_to_file(), http_list_directory(), http_list_directory_include_file(), http_request_parse(), http_response_parse_range(), http_response_redirect_to_directory(), http_response_write_header(), log_buffer_prepare(), mod_auth_send_401_unauthorized_digest(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_gssapi_log_gss_error(), mod_redirect_uri_handler(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), mod_status_header_append(), mod_status_header_append_sort(), mod_status_row_append(), PHYSICALPATH_FUNC(), plugins_load(), process_ssi_stmt(), proxy_append_header(), REQUESTDONE_FUNC(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_copy_dir(), webdav_delete_dir(), webdav_gen_prop_tag(), webdav_gen_response_status_tag(), webdav_get_live_property(), and yy_reduce().
void buffer_append_string_buffer (buffer * b, const buffer * src)
References buffer_append_string_len(), buffer_string_length(), and buffer::ptr.
Referenced by build_doc_root(), cache_parse_lua(), cgi_demux_response(), config_set_defaults(), configparser_merge_data(), configparser_remoteip_normalize_compat(), data_response_insert_dup(), data_string_insert_dup(), deflate_file_to_file(), fastcgi_status_copy_procname(), fcgi_create_env(), fcgi_demux_response(), fcgi_establish_connection(), fcgi_recv_response(), http_cgi_headers(), http_list_directory(), http_list_directory_footer(), http_list_directory_header(), http_response_parse_range(), http_response_prepare(), http_response_redirect_to_directory(), http_response_write_header(), mod_auth_send_401_unauthorized_basic(), mod_auth_send_401_unauthorized_digest(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_ldap_basic(), mod_evhost_uri_handler(), mod_rrdtool_create_rrd(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), process_ssi_stmt(), proxy_create_env(), REQUESTDONE_FUNC(), scgi_create_env(), scgi_demux_response(), SETDEFAULTS_FUNC(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), URIHANDLER_FUNC(), webdav_gen_response_status_tag(), webdav_get_live_property(), and yy_reduce().
void buffer_append_string_c_escaped (buffer * b, const char * s, size_t s_len)
References buffer_commit(), buffer_string_prepare_append(), force_assert, and hex_chars.
Referenced by log_buffer_append_printf().
void buffer_append_string_encoded (buffer * b, const char * s, size_t s_len, buffer_encoding_t encoding)
References buffer_commit(), buffer_string_prepare_append(), encoded_chars_hex, encoded_chars_html, encoded_chars_http_header, encoded_chars_minimal_xml, encoded_chars_rel_uri, encoded_chars_rel_uri_part, ENCODING_HEX, ENCODING_HTML, ENCODING_HTTP_HEADER, ENCODING_MINIMAL_XML, ENCODING_REL_URI, ENCODING_REL_URI_PART, force_assert, and hex_chars.
Referenced by http_list_directory(), http_list_directory_header(), http_list_directory_include_file(), http_response_redirect_to_directory(), http_response_write_header(), mod_status_handle_server_status_html(), process_ssi_stmt(), SUBREQUEST_FUNC(), and URIHANDLER_FUNC().
void buffer_append_string_len (buffer * b, const char * s, size_t s_len)
append a string to the end of the buffer
the resulting buffer is terminated with a '\0' s is treated as a un-terminated string (a \0 is handled a normal character)
Parameters
b a buffer
s the string
s_len size of the string (without the terminating \0)
References buffer_commit(), buffer_string_prepare_append(), and force_assert.
Referenced by accesslog_append_escaped(), buffer_append_int(), buffer_append_string(), buffer_append_string_buffer(), build_doc_root(), chunkqueue_get_append_tempfile(), config_append_cond_match_buffer(), config_check_cond_nocache(), config_tokenizer(), configparser_remoteip_normalize_compat(), CONNECTION_FUNC(), connection_handle_read_post_cq_compact(), connection_handle_read_state(), connection_handle_write_prepare(), data_response_insert_dup(), data_string_insert_dup(), deflate_file_to_file(), etag_create(), etag_mutate(), fastcgi_get_packet(), fastcgi_status_copy_procname(), fcgi_create_env(), fcgi_env_add(), fcgi_establish_connection(), fcgi_host_assign(), fcgi_host_reset(), fcgi_proc_load_dec(), fcgi_proc_load_inc(), fcgi_write_request(), http_chunk_append_len(), http_chunk_append_to_tempfile(), http_dirlist_append_js_table_resort(), http_list_directory(), http_list_directory_footer(), http_list_directory_header(), http_list_directory_include_file(), http_request_host_normalize(), http_response_parse_range(), http_response_prepare(), http_response_redirect_to_directory(), http_response_write_header(), log_buffer_append_printf(), log_buffer_prepare(), log_error_write_multiline_buffer(), log_write(), main(), mod_auth_send_401_unauthorized_basic(), mod_auth_send_401_unauthorized_digest(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_gssapi_log_gss_error(), mod_authn_ldap_basic(), mod_evhost_uri_handler(), mod_redirect_uri_handler(), mod_rrdtool_create_rrd(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), mod_status_header_append(), mod_status_header_append_sort(), mod_status_row_append(), network_init(), PHYSICALPATH_FUNC(), plugins_load(), process_ssi_stmt(), proxy_create_env(), proxy_demux_response(), REQUESTDONE_FUNC(), response_header_append(), scgi_create_env(), scgi_env_add_scgi(), scgi_env_add_uwsgi(), SETDEFAULTS_FUNC(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), URIHANDLER_FUNC(), webdav_gen_prop_tag(), webdav_gen_response_status_tag(), webdav_get_live_property(), and yy_reduce().
void buffer_append_uint_hex (buffer * b, uintmax_t len)
References buffer_commit(), buffer_string_prepare_append(), and hex_chars.
Referenced by connection_handle_write_prepare(), http_chunk_append_len(), http_chunk_append_to_tempfile(), log_buffer_append_printf(), and mod_auth_send_401_unauthorized_digest().
int buffer_caseless_compare (const char * a, size_t a_len, const char * b, size_t b_len)
Referenced by array_get_index(), and http_request_parse().
void buffer_commit (buffer * b, size_t size)
References force_assert, buffer::ptr, buffer::size, and buffer::used.
Referenced by buffer_append_base64_decode(), buffer_append_base64_encode(), buffer_append_base64_encode_no_padding(), buffer_append_strftime(), buffer_append_string_c_escaped(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_append_uint_hex(), buffer_copy_string_len(), cgi_demux_response(), chunkqueue_use_memory(), config_read(), CONNECTION_FUNC(), mod_rrdtool_create_rrd(), proc_read_fd_to_buffer(), proxy_demux_response(), scgi_create_env(), scgi_demux_response(), and TRIGGER_FUNC().
void buffer_copy_buffer (buffer * b, const buffer * src)
References buffer_copy_string_len(), buffer_string_length(), buffer_string_prepare_copy(), buffer::ptr, and buffer::used.
Referenced by buffer_init_buffer(), build_doc_root(), cache_call_lua(), cache_parse_lua(), cgi_demux_response(), cgi_response_parse(), chunkqueue_append_file(), chunkqueue_append_file_fd(), chunkqueue_get_append_tempfile(), config_check_cond_nocache(), config_insert_values_global(), config_insert_values_internal(), config_parse(), config_patch_connection(), config_set_defaults(), config_setup_connection(), CONNECTION_FUNC(), connection_handle_write_prepare(), connection_map_insert(), connection_state_machine(), data_array_copy(), data_config_copy(), data_fastcgi_copy(), data_integer_copy(), data_response_insert_dup(), data_string_copy(), data_string_insert_dup(), deflate_file_to_file(), excludes_buffer_append(), fastcgi_extension_insert(), fcgi_recv_response(), http_cgi_headers(), http_list_directory_footer(), http_list_directory_header(), http_request_parse(), http_response_prepare(), http_response_redirect_to_directory(), log_buffer_prepare(), mod_evhost_uri_handler(), mod_redirect_uri_handler(), mod_simple_vhost_docroot(), mod_status_handle_server_config(), network_init(), network_server_init(), PHYSICALPATH_FUNC(), plugins_load(), process_ssi_stmt(), proxy_response_parse(), run_buffer_path_simplify(), scgi_extension_insert(), scgi_response_parse(), script_cache_get_script(), SETDEFAULTS_FUNC(), ssi_expr_tokenizer(), stat_cache_get_entry(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), URIHANDLER_FUNC(), webdav_copy_dir(), webdav_delete_dir(), and yy_reduce().
void buffer_copy_int (buffer * b, intmax_t val)
References buffer_append_int(), force_assert, and buffer::used.
Referenced by array_find_or_insert(), connection_handle_write_prepare(), fcgi_response_parse(), main(), process_ssi_stmt(), and yy_reduce().
void buffer_copy_string (buffer * b, const char * s)
References buffer_copy_string_len().
Referenced by buffer_init_string(), cache_parse_lua(), cgi_response_parse(), config_check_cond_nocache(), config_parse_file(), config_set_defaults(), connection_accepted(), CONNECTION_FUNC(), fcgi_check_extension(), fcgi_response_parse(), http_request_host_normalize(), http_response_prepare(), lua_to_c_get_string(), magnet_env_get_buffer_by_id(), main(), mod_authn_gssapi_check_spnego(), plugins_load(), process_ssi_stmt(), proxy_append_header(), proxy_create_env(), proxy_response_parse(), proxy_set_header(), response_header_overwrite(), scgi_check_extension(), scgi_response_parse(), SUBREQUEST_FUNC(), test_configfile_addrbuf_eq_remote_ip_mask(), and URIHANDLER_FUNC().
void buffer_copy_string_encoded_cgi_varnames (buffer * b, const char * s, size_t s_len, int is_http_header)
References buffer_copy_string_len(), buffer_reset(), buffer_string_length(), buffer_string_prepare_append(), CONST_STR_LEN, force_assert, light_isalpha(), light_isdigit(), buffer::ptr, and buffer::used.
Referenced by http_cgi_headers().
void buffer_copy_string_hex (buffer * b, const char * in, size_t in_len)
References buffer_string_length(), buffer_string_set_length(), force_assert, li_tohex(), and buffer::ptr.
void buffer_copy_string_len (buffer * b, const char * s, size_t s_len)
References buffer_commit(), buffer_string_prepare_copy(), force_assert, and buffer::ptr.
Referenced by accesslog_parse_format(), array_set_key_value(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_encoded_cgi_varnames(), cgi_response_parse(), chunkqueue_append_mem(), config_check_cond_nocache(), config_insert(), config_insert_values_global(), config_read(), config_tokenizer(), configparser_remoteip_normalize_compat(), CONNECTION_FUNC(), connection_handle_write_prepare(), connection_state_machine(), etag_mutate(), fastcgi_status_copy_procname(), fcgi_create_env(), fcgi_demux_response(), fcgi_establish_connection(), fcgi_response_parse(), http_auth_setenv(), http_list_directory(), http_request_parse(), http_request_split_value(), http_response_parse_range(), http_response_prepare(), http_response_write_header(), log_buffer_prepare(), magnet_checkbuffer(), magnet_env_set(), mod_auth_check_digest(), mod_auth_require_parse(), mod_auth_send_401_unauthorized_basic(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htpasswd_get(), mod_evhost_parse_host(), mod_evhost_parse_pattern(), mod_rrdtool_create_rrd(), mod_ssi_handle_request(), mod_status_handle_server_config(), mod_status_handle_server_status_html(), PHYSICALPATH_FUNC(), process_ssi_stmt(), proxy_response_parse(), put_string_into_array_len(), REQUESTDONE_FUNC(), response_header_insert(), run_buffer_path_simplify(), scgi_response_parse(), SETDEFAULTS_FUNC(), split_get_params(), ssi_env_add(), ssi_expr_tokenizer(), status_counter_get_counter(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), URIHANDLER_FUNC(), and webdav_gen_response_status_tag().
void buffer_free (buffer * b)
References buffer::ptr.
Referenced by cache_parse_lua(), cgi_handler_ctx_free(), check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), chunk_free(), chunkqueue_get_append_tempfile(), config_insert(), config_parse(), config_parse_cmd(), config_parse_file(), config_read(), configparser_remoteip_normalize_compat(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_write_prepare(), connection_map_free(), context_free(), data_array_free(), data_auth_free(), data_config_free(), data_fastcgi_free(), data_integer_free(), data_string_free(), excludes_buffer_free(), fastcgi_extensions_free(), fastcgi_get_packet(), fastcgi_host_free(), fastcgi_process_free(), fcgi_create_env(), fcgi_demux_response(), FREE_FUNC(), handler_ctx_free(), http_auth_require_free(), http_list_directory(), http_request_parse(), http_response_parse_range(), http_response_redirect_to_directory(), http_response_write_header(), magnet_atpanic(), magnet_attach_content(), magnet_print(), magnet_stat(), mod_auth_check_basic(), mod_auth_check_digest(), mod_authn_file_htdigest_digest(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), mod_authn_file_plain_digest(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_gssapi_create_krb5_ccache(), mod_authn_gssapi_log_gss_error(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), network_close(), network_init(), network_server_init(), pcre_keyvalue_buffer_free(), plugin_free(), proc_open_buffer(), process_ssi_stmt(), proxy_create_env(), REQUESTDONE_FUNC(), scgi_create_env(), scgi_extensions_free(), scgi_host_free(), scgi_process_free(), script_free(), server_free(), SERVER_FUNC(), SETDEFAULTS_FUNC(), ssi_eval_expr(), ssi_val_free(), stat_cache_entry_free(), stat_cache_free(), stat_cache_get_entry(), SUBREQUEST_FUNC(), test_buffer_path_simplify(), test_configfile_addrbuf_eq_remote_ip_mask(), URIHANDLER_FUNC(), webdav_copy_dir(), webdav_delete_dir(), yy_destructor(), and yy_reduce().
buffer* buffer_init (void)
init the buffer
References force_assert, buffer::ptr, buffer::size, and buffer::used.
Referenced by accesslog_parse_format(), buffer_init_buffer(), buffer_init_string(), cache_parse_lua(), cgi_handler_ctx_init(), check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), chunk_init(), config_insert(), config_parse(), config_parse_cmd(), configparser_remoteip_normalize_compat(), connection_handle_write_prepare(), connection_map_insert(), context_init(), data_array_init(), data_auth_init(), data_config_init(), data_fastcgi_init(), data_integer_init(), data_string_init(), excludes_buffer_append(), fastcgi_extension_insert(), fastcgi_get_packet(), fastcgi_host_init(), fastcgi_process_init(), fcgi_create_env(), handler_ctx_init(), http_auth_require_init(), http_list_directory(), http_request_parse(), http_response_parse_range(), http_response_redirect_to_directory(), http_response_write_header(), INIT_FUNC(), magnet_checkbuffer(), magnet_stat(), mod_auth_check_basic(), mod_auth_check_digest(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), mod_authn_file_plain_digest(), mod_authn_gssapi_check_spnego(), mod_evhost_parse_pattern(), mod_mysql_vhost_connection_data(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), network_init(), network_server_init(), proc_open_buffer(), process_ssi_stmt(), proxy_create_env(), REQUESTDONE_FUNC(), scgi_create_env(), scgi_extension_insert(), scgi_host_init(), scgi_process_init(), script_init(), SERVER_FUNC(), server_init(), SETDEFAULTS_FUNC(), ssi_eval_expr(), stat_cache_entry_init(), stat_cache_get_entry(), stat_cache_init(), SUBREQUEST_FUNC(), test_buffer_path_simplify(), test_configfile_addrbuf_eq_remote_ip_mask(), URIHANDLER_FUNC(), webdav_copy_dir(), webdav_delete_dir(), and yy_reduce().
buffer* buffer_init_buffer (const buffer * src)
References buffer_copy_buffer(), and buffer_init().
Referenced by config_insert(), config_parse_file(), connection_handle_errdoc_init(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), process_ssi_stmt(), and yy_reduce().
buffer* buffer_init_string (const char * str)
References buffer_copy_string(), and buffer_init().
Referenced by chunkqueue_get_append_tempfile(), config_insert(), config_parse(), config_parse_cmd(), config_parse_file(), config_read(), mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_htdigest_digest(), mod_authn_file_plain_digest(), mod_authn_file_plugin_init(), mod_authn_gssapi_create_krb5_ccache(), mod_authn_gssapi_log_gss_error(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), mod_webdav_plugin_init(), pcre_keyvalue_buffer_append(), server_init(), SETDEFAULTS_FUNC(), and yy_reduce().
int buffer_is_empty (const buffer * b)
References buffer::used.
Referenced by accesslog_parse_format(), array_find_or_insert(), cgi_get_handler(), configparser_merge_data(), CONNECTION_FUNC(), data_response_insert_dup(), data_string_insert_dup(), fcgi_check_extension(), http_cgi_headers(), http_list_directory(), http_list_directory_footer(), http_request_parse(), http_response_prepare(), http_response_redirect_to_directory(), http_response_write_header(), magnet_array_next(), magnet_cgi_get(), magnet_env_get(), magnet_env_next(), magnet_reqhdr_get(), mod_auth_check_basic(), mod_auth_check_digest(), mod_authn_file_htdigest_get(), mod_authn_file_htpasswd_get(), mod_authn_gssapi_basic(), mod_authn_gssapi_check(), mod_authn_gssapi_check_spnego(), mod_proxy_check_extension(), network_server_init(), PHYSICALPATH_FUNC(), proxy_create_env(), REQUESTDONE_FUNC(), scgi_check_extension(), SETDEFAULTS_FUNC(), stat_cache_get_entry(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_get_live_property(), and yy_reduce().
int buffer_is_equal (const buffer * a, const buffer * b)
check if two buffer contain the same data
HISTORY: this function was pretty much optimized, but didn't handled alignment properly.
References force_assert, buffer::ptr, and buffer::used.
Referenced by config_check_cond_nocache(), config_set_defaults(), CONNECTION_FUNC(), connection_map_get_connection(), fastcgi_extension_insert(), fcgi_check_extension(), http_cgi_headers(), http_response_send_file(), mod_simple_vhost_docroot(), mod_status_handler(), network_init(), PHYSICALPATH_FUNC(), plugins_load(), process_ssi_stmt(), scgi_extension_insert(), script_cache_get_script(), SETDEFAULTS_FUNC(), stat_cache_get_entry(), SUBREQUEST_FUNC(), unixsocket_is_dup(), and URIHANDLER_FUNC().
int buffer_is_equal_caseless_string (const buffer * a, const char * s, size_t b_len)
References force_assert, buffer::ptr, and buffer::used.
Referenced by http_cgi_headers(), http_response_redirect_to_directory(), proxy_create_env(), and URIHANDLER_FUNC().
int buffer_is_equal_right_len (const buffer * a, const buffer * b, size_t len)
References buffer::ptr, and buffer::used.
Referenced by process_ssi_stmt(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), and webdav_get_live_property().
int buffer_is_equal_string (const buffer * a, const char * s, size_t b_len)
References force_assert, buffer::ptr, and buffer::used.
Referenced by check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), config_insert(), config_insert_values_internal(), config_patch_connection(), fcgi_patch_connection(), http_auth_array_contains(), mod_access_patch_connection(), mod_accesslog_patch_connection(), mod_alias_patch_connection(), mod_auth_check_digest(), mod_auth_patch_connection(), mod_auth_require_parse(), mod_authn_file_patch_connection(), mod_authn_file_plain_basic(), mod_authn_gssapi_patch_connection(), mod_authn_ldap_patch_connection(), mod_authn_mysql_patch_connection(), mod_cgi_patch_connection(), mod_cml_patch_connection(), mod_compress_patch_connection(), mod_deflate_patch_connection(), mod_dirlisting_patch_connection(), mod_evasive_patch_connection(), mod_evhost_patch_connection(), mod_expire_patch_connection(), mod_extforward_patch_connection(), mod_flv_streaming_patch_connection(), mod_geoip_patch_connection(), mod_indexfile_patch_connection(), mod_magnet_patch_connection(), mod_mysql_vhost_patch_connection(), mod_proxy_patch_connection(), mod_rrd_patch_connection(), mod_secdownload_patch_connection(), mod_setenv_patch_connection(), mod_simple_vhost_patch_connection(), mod_skeleton_patch_connection(), mod_ssi_patch_connection(), mod_staticfile_patch_connection(), mod_status_handle_server_status(), mod_status_patch_connection(), mod_trigger_b4_dl_patch_connection(), mod_uploadprogress_patch_connection(), mod_userdir_patch_connection(), mod_usertrack_patch_connection(), mod_webdav_patch_connection(), network_init(), network_server_init(), run_buffer_path_simplify(), scgi_patch_connection(), SETDEFAULTS_FUNC(), and yy_reduce().
void buffer_move (buffer * b, buffer * src)
References buffer_reset().
Referenced by chunkqueue_append_buffer(), and chunkqueue_prepend_buffer().
void buffer_path_simplify (buffer * dest, buffer * src)
References buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_append(), buffer_string_prepare_copy(), buffer_string_set_length(), force_assert, buffer::ptr, and buffer::used.
Referenced by fcgi_response_parse(), http_response_prepare(), http_response_xsendfile(), process_ssi_stmt(), run_buffer_path_simplify(), SETDEFAULTS_FUNC(), and SUBREQUEST_FUNC().
void buffer_reset (buffer * b)
References BUFFER_MAX_REUSE_SIZE, buffer::ptr, buffer::size, and buffer::used.
Referenced by buffer_copy_string_encoded_cgi_varnames(), buffer_move(), cache_parse_lua(), check_all_len_0(), check_all_len_1(), check_all_len_2(), check_all_len_3(), chunk_reset(), chunkqueue_use_memory(), config_set_defaults(), connection_del(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_read_state(), connection_handle_write_prepare(), connection_map_remove_connection(), connection_response_reset(), connection_state_machine(), data_array_reset(), data_config_reset(), data_fastcgi_reset(), data_integer_reset(), data_string_reset(), deflate_file_to_buffer(), deflate_file_to_file(), etag_create(), etag_mutate(), handler_ctx_clear(), http_request_parse(), http_response_prepare(), http_response_xsendfile(), magnet_env_set(), main(), mod_evhost_uri_handler(), mod_redirect_uri_handler(), mod_ssi_handle_request(), plugins_load(), proxy_demux_response(), REQUESTDONE_FUNC(), SETDEFAULTS_FUNC(), SIGHUP_FUNC(), stat_cache_get_entry(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), and webdav_get_live_property().
char* buffer_search_string_len (buffer * b, const char * needle, size_t len)
References force_assert, buffer::ptr, and buffer::used.
Referenced by fcgi_demux_response(), and proxy_demux_response().
int buffer_string_is_empty (const buffer * b)
References buffer_string_length().
Referenced by accesslog_append_escaped(), algorithm_from_string(), buffer_path_simplify(), buffer_string_prepare_append(), buffer_urldecode_internal(), build_doc_root(), cache_parse_lua(), cgi_create_env(), cgi_handle_fdevent(), chunk_reset(), chunkqueue_append_buffer(), chunkqueue_get_memory(), chunkqueue_prepend_buffer(), chunkqueue_use_memory(), config_check_cond_nocache(), config_insert(), config_parse_cmd(), config_set_defaults(), CONNECTION_FUNC(), connection_handle_write_prepare(), connection_state_machine(), data_string_print(), etag_is_equal(), extract_forward_array(), fcgi_check_extension(), fcgi_demux_response(), fcgi_establish_connection(), fcgi_recv_response(), fcgi_restart_dead_procs(), FREE_FUNC(), http_cgi_headers(), http_dirlist_append_js_table_resort(), http_list_directory(), http_list_directory_footer(), http_list_directory_header(), http_request_parse(), http_request_split_value(), http_response_prepare(), http_response_redirect_to_directory(), http_response_send_file(), http_response_write_header(), log_error_open(), log_error_write_multiline_buffer(), magnet_attract_array(), magnet_stat(), main(), mod_authn_file_htdigest_get(), mod_authn_file_htpasswd_get(), mod_authn_ldap_basic(), mod_authn_ldap_host_init(), mod_authn_ldap_search(), mod_authn_mysql_query(), mod_authn_mysql_sock_connect(), mod_evhost_uri_handler(), mod_expire_get_offset(), mod_proxy_check_extension(), mod_simple_vhost_docroot(), mod_ssi_handle_request(), mod_status_handle_server_status_html(), mod_status_handle_server_status_text(), mod_status_handler(), network_init(), PHYSICALPATH_FUNC(), proc_open_buffer(), process_ssi_stmt(), proxy_create_env(), remove_pid_file(), REQUESTDONE_FUNC(), scgi_check_extension(), scgi_establish_connection(), SERVER_FUNC(), SETDEFAULTS_FUNC(), SIGHUP_FUNC(), ssi_val_tobool(), stat_cache_get_entry(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), unixsocket_is_dup(), and URIHANDLER_FUNC().
static size_t buffer_string_length (const buffer * b) [inline], [static]
References buffer::used.
Referenced by accesslog_append_escaped(), accesslog_parse_format(), buffer_append_slash(), buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string_encoded_cgi_varnames(), buffer_copy_string_hex(), buffer_path_simplify(), buffer_string_is_empty(), build_doc_root(), cache_call_lua(), cache_export_get_params(), cgi_demux_response(), cgi_get_handler(), cgi_write_request(), chunk_remaining_length(), chunkqueue_get_memory(), config_set_defaults(), configparser_remoteip_normalize_compat(), CONNECTION_FUNC(), connection_handle_read_post_chunked(), connection_handle_read_post_chunked_crlf(), connection_handle_read_post_cq_compact(), connection_handle_read_state(), data_string_print(), deflate_compress_response(), deflate_file_to_buffer(), deflate_file_to_file(), etag_mutate(), fastcgi_get_packet(), fcgi_check_extension(), fcgi_create_env(), fcgi_demux_response(), fcgi_env_add(), fcgi_establish_connection(), fcgi_response_parse(), http_cgi_headers(), http_chunk_append_buffer(), http_list_directory(), http_request_header_finished(), http_request_host_normalize(), http_request_parse(), http_request_split_value(), http_response_parse_range(), http_response_prepare(), http_response_write_header(), http_response_xsendfile(), log_error_write_multiline_buffer(), mod_auth_check_basic(), mod_auth_check_digest(), mod_auth_uri_handler(), mod_authn_file_htdigest_get(), mod_authn_file_htpasswd_basic(), mod_authn_file_htpasswd_get(), mod_authn_file_plain_digest(), mod_authn_gssapi_check_spnego(), mod_authn_gssapi_create_krb5_ccache(), mod_authn_ldap_basic(), mod_evhost_parse_host(), mod_evhost_uri_handler(), mod_proxy_check_extension(), mod_redirect_uri_handler(), mod_status_handle_server_status(), mod_status_handle_server_status_json(), network_server_init(), network_write_mem_chunk(), parse_binpath(), PHYSICALPATH_FUNC(), proc_read_fd_to_buffer(), process_ssi_stmt(), proxy_create_env(), proxy_demux_response(), proxy_establish_connection(), request_check_hostname(), REQUESTDONE_FUNC(), scgi_check_extension(), scgi_create_env(), scgi_demux_response(), scgi_establish_connection(), SETDEFAULTS_FUNC(), split_get_params(), stat_cache_get_entry(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_get_live_property(), and yy_reduce().
char* buffer_string_prepare_append (buffer * b, size_t size)
References buffer_realloc(), buffer_string_is_empty(), buffer_string_prepare_copy(), force_assert, buffer::ptr, and buffer::used.
Referenced by accesslog_append_escaped(), buffer_append_base64_decode(), buffer_append_base64_encode(), buffer_append_base64_encode_no_padding(), buffer_append_strftime(), buffer_append_string_c_escaped(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_append_uint_hex(), buffer_copy_string_encoded_cgi_varnames(), buffer_path_simplify(), chunkqueue_get_memory(), CONNECTION_FUNC(), fcgi_env_add(), proc_read_fd_to_buffer(), proxy_demux_response(), scgi_env_add_scgi(), and scgi_env_add_uwsgi().
char* buffer_string_prepare_copy (buffer * b, size_t size)
References buffer_alloc(), force_assert, buffer::ptr, and buffer::used.
Referenced by buffer_copy_buffer(), buffer_copy_string_len(), buffer_path_simplify(), buffer_string_prepare_append(), build_doc_root(), cgi_demux_response(), chunkqueue_get_memory(), config_read(), CONNECTION_FUNC(), fcgi_create_env(), http_response_write_header(), INIT_FUNC(), log_buffer_prepare(), mod_rrdtool_create_rrd(), network_write_file_chunk_no_mmap(), proxy_demux_response(), REQUESTDONE_FUNC(), scgi_create_env(), scgi_demux_response(), strftime_cache_get(), and TRIGGER_FUNC().
void buffer_string_set_length (buffer * b, size_t len)
References buffer_realloc(), force_assert, buffer::ptr, and buffer::used.
Referenced by buffer_copy_string_hex(), buffer_path_simplify(), cache_call_lua(), cgi_demux_response(), config_set_defaults(), CONNECTION_FUNC(), connection_handle_write_prepare(), fastcgi_get_packet(), fcgi_check_extension(), fcgi_demux_response(), http_chunk_append_len(), http_chunk_append_to_tempfile(), http_request_host_normalize(), http_response_prepare(), log_error_write_multiline_buffer(), mod_auth_check_basic(), mod_authn_ldap_basic(), request_check_hostname(), REQUESTDONE_FUNC(), scgi_check_extension(), scgi_demux_response(), SETDEFAULTS_FUNC(), stat_cache_get_entry(), and yy_reduce().
static size_t buffer_string_space (const buffer * b) [inline], [static]
References buffer::size, and buffer::used.
Referenced by buffer_append_strftime(), chunkqueue_get_memory(), proc_read_fd_to_buffer(), and proxy_demux_response().
void buffer_to_lower (buffer * b)
References buffer::ptr, and buffer::used.
Referenced by config_set_defaults(), fcgi_response_parse(), http_response_prepare(), http_response_xsendfile(), process_ssi_stmt(), SUBREQUEST_FUNC(), and URIHANDLER_FUNC().
void buffer_to_upper (buffer * b)
References buffer::ptr, and buffer::used.
Referenced by config_set_defaults().
void buffer_urldecode_path (buffer * url)
References buffer_urldecode_internal().
Referenced by fcgi_response_parse(), http_response_prepare(), http_response_xsendfile(), process_ssi_stmt(), and SUBREQUEST_FUNC().
void buffer_urldecode_query (buffer * url)
References buffer_urldecode_internal().
char hex2int (unsigned char c)
deprecated
Referenced by buffer_urldecode_internal(), connection_handle_read_post_chunked(), mod_auth_check_digest(), and URIHANDLER_FUNC().
char int2hex (char i)
References hex_chars.
void li_itostrn (char * buf, size_t buf_len, intmax_t val)
References force_assert, itostr(), and LI_ITOSTRING_LENGTH.
Referenced by http_cgi_headers(), http_list_directory_sizefmt(), mod_auth_send_401_unauthorized_digest(), mod_compress_note_ratio(), mod_deflate_note_ratio(), and URIHANDLER_FUNC().
void li_tohex (char * buf, size_t buf_len, const char * s, size_t s_len)
References force_assert, and hex_chars.
Referenced by buffer_copy_string_hex(), CvtHex(), f_crypto_md5(), mod_authn_file_htpasswd_basic(), and secdl_verify_mac().
void li_utostrn (char * buf, size_t buf_len, uintmax_t val)
References force_assert, LI_ITOSTRING_LENGTH, and utostr().
Referenced by http_cgi_headers().
int light_isalnum (int c)
References light_isalpha(), and light_isdigit().
Referenced by mod_status_handle_server_status_json(), and request_check_hostname().
int light_isalpha (int c)
Referenced by buffer_copy_string_encoded_cgi_varnames(), light_isalnum(), mod_ssi_parse_ssi_stmt_offlen(), and mod_status_handle_server_status_json().
int light_isdigit (int c)
Referenced by buffer_copy_string_encoded_cgi_varnames(), http_request_host_normalize(), light_isalnum(), light_isxdigit(), mod_evhost_parse_pattern(), and request_check_hostname().
int light_isxdigit (int c)
References light_isdigit().
Referenced by mod_auth_check_digest(), request_check_hostname(), and URIHANDLER_FUNC().
void log_failed_assert (const char * filename, unsigned int line, const char * msg)
References print_backtrace().
void print_backtrace (FILE * file)
References UNUSED.
Referenced by log_failed_assert().