chunk.c File Reference
#include `first.h`
*
#include `chunk.h`
*
#include `base.h`
*
#include `log.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include `sys-mmap.h`
*
#include <stdlib.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <stdio.h>
*
#include <errno.h>
*
#include <string.h>
*
Macros
#define DEFAULT_TEMPFILE_SIZE (1 * 1024 * 1024)
#define MAX_TEMPFILE_SIZE (128 * 1024 * 1024)
Functions
chunkqueue * chunkqueue_init (void)
static chunk * chunk_init (void)
static void chunk_reset (chunk *c)
static void chunk_free (chunk *c)
static off_t chunk_remaining_length (const chunk *c)
void chunkqueue_free (chunkqueue *cq)
static void chunkqueue_push_unused_chunk (chunkqueue *cq, chunk *c)
static chunk * chunkqueue_get_unused_chunk (chunkqueue *cq)
static void chunkqueue_prepend_chunk (chunkqueue *cq, chunk *c)
static void chunkqueue_append_chunk (chunkqueue *cq, chunk *c)
void chunkqueue_reset (chunkqueue *cq)
void chunkqueue_append_file_fd (chunkqueue *cq, buffer *fn, int fd, off_t offset, off_t len)
void chunkqueue_append_file (chunkqueue *cq, buffer *fn, off_t offset, off_t len)
void chunkqueue_append_buffer (chunkqueue *cq, buffer *mem)
void chunkqueue_prepend_buffer (chunkqueue *cq, buffer *mem)
void chunkqueue_append_mem (chunkqueue *cq, const char *mem, size_t len)
void chunkqueue_append_chunkqueue (chunkqueue *cq, chunkqueue *src)
void chunkqueue_get_memory (chunkqueue *cq, char **mem, size_t *len, size_t min_size, size_t alloc_size)
void chunkqueue_use_memory (chunkqueue *cq, size_t len)
void chunkqueue_set_tempdirs_default (array *tempdirs, unsigned int upload_temp_file_size)
void chunkqueue_steal (chunkqueue *dest, chunkqueue *src, off_t len)
static chunk * chunkqueue_get_append_tempfile (chunkqueue *cq)
static void chunkqueue_remove_empty_chunks (chunkqueue *cq)
int chunkqueue_append_mem_to_tempfile (server *srv, chunkqueue *dest, const char *mem, size_t len)
int chunkqueue_steal_with_tempfiles (server *srv, chunkqueue *dest, chunkqueue *src, off_t len)
off_t chunkqueue_length (chunkqueue *cq)
int chunkqueue_is_empty (chunkqueue *cq)
void chunkqueue_mark_written (chunkqueue *cq, off_t len)
void chunkqueue_remove_finished_chunks (chunkqueue *cq)
Variables
static array * chunkqueue_default_tempdirs = NULL
static unsigned int chunkqueue_default_tempfile_size = DEFAULT_TEMPFILE_SIZE
Macro Definition Documentation
#define DEFAULT_TEMPFILE_SIZE (1 * 1024 * 1024)
the network chunk-API
Referenced by chunkqueue_set_tempdirs_default().
#define MAX_TEMPFILE_SIZE (128 * 1024 * 1024)
Referenced by chunkqueue_set_tempdirs_default().
Function Documentation
static void chunk_free (chunk * c) [static]
References buffer_free(), chunk_reset(), chunk::file, chunk::mem, and chunk::name.
Referenced by chunkqueue_free(), and chunkqueue_push_unused_chunk().
static chunk* chunk_init (void) [static]
References buffer_init(), chunk::fd, chunk::file, force_assert, chunk::is_temp, chunk::length, MAP_FAILED, chunk::mem, chunk::mmap, chunk::name, chunk::next, chunk::offset, chunk::start, and chunk::type.
Referenced by chunkqueue_get_unused_chunk().
static off_t chunk_remaining_length (const chunk * c) [static]
References buffer_string_length(), chunk::file, force_assert, chunk::length, chunk::mem, chunk::offset, and chunk::type.
Referenced by chunkqueue_append_chunk(), chunkqueue_append_mem_to_tempfile(), chunkqueue_length(), chunkqueue_mark_written(), chunkqueue_prepend_chunk(), chunkqueue_remove_empty_chunks(), chunkqueue_remove_finished_chunks(), chunkqueue_steal(), and chunkqueue_steal_with_tempfiles().
static void chunk_reset (chunk * c) [static]
References buffer_reset(), buffer_string_is_empty(), chunk::fd, chunk::file, chunk::is_temp, chunk::length, MAP_FAILED, chunk::mem, chunk::mmap, munmap, chunk::name, chunk::next, chunk::offset, buffer::ptr, chunk::start, and chunk::type.
Referenced by chunk_free(), and chunkqueue_push_unused_chunk().
void chunkqueue_append_buffer (chunkqueue * cq, buffer * mem)
References buffer_move(), buffer_string_is_empty(), chunkqueue_append_chunk(), chunkqueue_get_unused_chunk(), force_assert, chunk::mem, and chunk::type.
Referenced by deflate_file_to_buffer(), fcgi_create_env(), http_chunk_append_data(), http_chunk_append_len(), http_list_directory(), http_response_parse_range(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), process_ssi_stmt(), proxy_create_env(), scgi_create_env(), SUBREQUEST_FUNC(), and URIHANDLER_FUNC().
static void chunkqueue_append_chunk (chunkqueue * cq, chunk * c) [static]
References chunkqueue::bytes_in, chunk_remaining_length(), chunkqueue::first, chunkqueue::last, and chunk::next.
Referenced by chunkqueue_append_buffer(), chunkqueue_append_file(), chunkqueue_append_file_fd(), chunkqueue_append_mem(), chunkqueue_get_append_tempfile(), chunkqueue_get_memory(), chunkqueue_steal(), and chunkqueue_steal_with_tempfiles().
void chunkqueue_append_chunkqueue (chunkqueue * cq, chunkqueue * src)
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue::first, chunkqueue::last, and chunk::next.
Referenced by deflate_compress_response(), proxy_create_env(), scgi_create_env(), and SUBREQUEST_FUNC().
void chunkqueue_append_file (chunkqueue * cq, buffer * fn, off_t offset, off_t len)
References buffer_copy_buffer(), chunkqueue_append_chunk(), chunkqueue_get_unused_chunk(), chunk::file, chunk::length, chunk::name, chunk::offset, chunk::start, and chunk::type.
Referenced by chunkqueue_steal(), chunkqueue_steal_with_tempfiles(), http_response_parse_range(), and process_ssi_stmt().
void chunkqueue_append_file_fd (chunkqueue * cq, buffer * fn, int fd, off_t offset, off_t len)
References buffer_copy_buffer(), chunkqueue_append_chunk(), chunkqueue_get_unused_chunk(), chunk::fd, chunk::file, chunk::length, chunk::name, chunk::offset, chunk::start, and chunk::type.
Referenced by cache_parse_lua(), and http_chunk_append_file_fd_range().
void chunkqueue_append_mem (chunkqueue * cq, const char * mem, size_t len)
References buffer_copy_string_len(), chunkqueue_append_chunk(), chunkqueue_get_unused_chunk(), chunk::mem, and chunk::type.
Referenced by chunkqueue_steal(), connection_handle_write_prepare(), fcgi_stdin_append(), http_chunk_append_data(), http_chunk_append_file_fd_range(), http_chunk_close(), magnet_attach_content(), mod_ssi_parse_ssi_stmt(), mod_ssi_read_fd(), process_ssi_stmt(), and URIHANDLER_FUNC().
int chunkqueue_append_mem_to_tempfile (server * srv, chunkqueue * dest, const char * mem, size_t len)
References chunkqueue::bytes_in, chunk_remaining_length(), chunkqueue_get_append_tempfile(), chunkqueue_remove_empty_chunks(), chunk::fd, chunk::file, chunk::is_temp, chunkqueue::last, chunk::length, log_error_write(), chunk::name, chunk::offset, chunkqueue::tempdir_idx, chunkqueue::tempdirs, chunk::type, chunkqueue::upload_temp_file_size, and array::used.
Referenced by chunkqueue_steal_with_tempfiles(), and http_chunk_append_to_tempfile().
void chunkqueue_free (chunkqueue * cq)
References chunk_free(), chunkqueue::first, chunk::next, and chunkqueue::unused.
Referenced by connections_free(), and handler_ctx_free().
static chunk* chunkqueue_get_append_tempfile (chunkqueue * cq) [static]
References buffer_append_slash(), buffer_append_string_len(), buffer_copy_buffer(), buffer_free(), buffer_init_string(), chunkqueue_append_chunk(), chunkqueue_get_unused_chunk(), CONST_STR_LEN, array::data, chunk::fd, fd_close_on_exec(), chunk::file, chunk::is_temp, chunk::length, chunk::name, chunkqueue::tempdir_idx, chunkqueue::tempdirs, chunk::type, array::used, and data_string::value.
Referenced by chunkqueue_append_mem_to_tempfile().
void chunkqueue_get_memory (chunkqueue * cq, char ** mem, size_t * len, size_t min_size, size_t alloc_size)
References buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_append(), buffer_string_prepare_copy(), buffer_string_space(), chunkqueue_append_chunk(), chunkqueue_get_unused_chunk(), force_assert, chunkqueue::last, chunk::mem, buffer::ptr, and chunk::type.
Referenced by connection_handle_read(), connection_handle_read_ssl(), fcgi_demux_response(), and process_ssi_stmt().
static chunk* chunkqueue_get_unused_chunk (chunkqueue * cq) [static]
References chunk_init(), force_assert, chunk::next, chunkqueue::unused, and chunkqueue::unused_chunks.
Referenced by chunkqueue_append_buffer(), chunkqueue_append_file(), chunkqueue_append_file_fd(), chunkqueue_append_mem(), chunkqueue_get_append_tempfile(), chunkqueue_get_memory(), and chunkqueue_prepend_buffer().
chunkqueue* chunkqueue_init (void)
References chunkqueue_default_tempdirs, chunkqueue_default_tempfile_size, chunkqueue::first, force_assert, chunkqueue::last, chunkqueue::tempdirs, chunkqueue::unused, and chunkqueue::upload_temp_file_size.
Referenced by connection_init(), and handler_ctx_init().
int chunkqueue_is_empty (chunkqueue * cq)
References chunkqueue::first.
Referenced by chunkqueue_remove_empty_chunks(), connection_handle_fdevent(), connection_handle_read_post_chunked_crlf(), connection_handle_read_state(), connection_state_machine(), deflate_compress_response(), magnet_attract(), network_write_chunkqueue(), and SUBREQUEST_FUNC().
off_t chunkqueue_length (chunkqueue * cq)
References chunk_remaining_length(), chunkqueue::first, and chunk::next.
Referenced by cgi_demux_response(), cgi_handle_fdevent_send(), cgi_write_request(), CONNECTION_FUNC(), connection_handle_read_state(), connection_handle_write_prepare(), deflate_compress_response(), fcgi_demux_response(), mod_status_handle_server_status_html(), proxy_demux_response(), scgi_demux_response(), and SUBREQUEST_FUNC().
void chunkqueue_mark_written (chunkqueue * cq, off_t len)
References chunkqueue::bytes_out, chunk_remaining_length(), chunkqueue_push_unused_chunk(), chunkqueue::first, force_assert, chunkqueue::last, chunk::next, and chunk::offset.
Referenced by cgi_handle_fdevent_send(), cgi_write_file_chunk_mmap(), cgi_write_request(), connection_handle_read_post_chunked(), deflate_compress_response(), fastcgi_get_packet(), network_write_file_chunk_no_mmap(), network_write_mem_chunk(), and SUBREQUEST_FUNC().
void chunkqueue_prepend_buffer (chunkqueue * cq, buffer * mem)
References buffer_move(), buffer_string_is_empty(), chunkqueue_get_unused_chunk(), chunkqueue_prepend_chunk(), force_assert, chunk::mem, and chunk::type.
Referenced by connection_handle_write_prepare(), and http_response_write_header().
static void chunkqueue_prepend_chunk (chunkqueue * cq, chunk * c) [static]
References chunkqueue::bytes_in, chunk_remaining_length(), chunkqueue::first, chunkqueue::last, and chunk::next.
Referenced by chunkqueue_prepend_buffer().
static void chunkqueue_push_unused_chunk (chunkqueue * cq, chunk * c) [static]
References chunk_free(), chunk_reset(), force_assert, chunk::next, chunkqueue::unused, and chunkqueue::unused_chunks.
Referenced by chunkqueue_mark_written(), chunkqueue_remove_empty_chunks(), chunkqueue_remove_finished_chunks(), chunkqueue_reset(), chunkqueue_steal(), and chunkqueue_steal_with_tempfiles().
static void chunkqueue_remove_empty_chunks (chunkqueue * cq) [static]
References chunk_remaining_length(), chunkqueue_is_empty(), chunkqueue_push_unused_chunk(), chunkqueue_remove_finished_chunks(), chunkqueue::first, chunkqueue::last, and chunk::next.
Referenced by chunkqueue_append_mem_to_tempfile().
void chunkqueue_remove_finished_chunks (chunkqueue * cq)
References chunk_remaining_length(), chunkqueue_push_unused_chunk(), chunkqueue::first, chunkqueue::last, and chunk::next.
Referenced by cgi_write_file_chunk_mmap(), chunkqueue_remove_empty_chunks(), connection_handle_read_post_cq_compact(), connection_handle_read_post_state(), connection_handle_read_state(), deflate_compress_response(), fcgi_write_request(), network_write_chunkqueue(), network_write_file_chunk_no_mmap(), network_write_mem_chunk(), proxy_write_request(), and scgi_write_request().
void chunkqueue_reset (chunkqueue * cq)
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_push_unused_chunk(), chunkqueue::first, chunkqueue::last, chunk::next, and chunkqueue::tempdir_idx.
Referenced by cache_parse_lua(), cgi_demux_response(), CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_read_post_error(), connection_handle_write_prepare(), connection_reset(), connection_response_reset(), connection_state_machine(), deflate_file_to_buffer(), handler_ctx_clear(), http_response_prepare(), mod_ssi_handle_request(), and URIHANDLER_FUNC().
void chunkqueue_set_tempdirs_default (array * tempdirs, unsigned int upload_temp_file_size)
References chunkqueue_default_tempfile_size, DEFAULT_TEMPFILE_SIZE, and MAX_TEMPFILE_SIZE.
Referenced by config_set_defaults().
void chunkqueue_steal (chunkqueue * dest, chunkqueue * src, off_t len)
References chunkqueue::bytes_out, chunk_remaining_length(), chunkqueue_append_chunk(), chunkqueue_append_file(), chunkqueue_append_mem(), chunkqueue_push_unused_chunk(), chunk::file, chunkqueue::first, force_assert, chunkqueue::last, chunk::mem, chunk::name, chunk::next, chunk::offset, buffer::ptr, chunk::start, and chunk::type.
Referenced by connection_handle_read_post_chunked(), connection_handle_read_post_state(), and fcgi_stdin_append().
int chunkqueue_steal_with_tempfiles (server * srv, chunkqueue * dest, chunkqueue * src, off_t len)
References chunkqueue::bytes_out, chunk_remaining_length(), chunkqueue_append_chunk(), chunkqueue_append_file(), chunkqueue_append_mem_to_tempfile(), chunkqueue_push_unused_chunk(), chunk::file, chunkqueue::first, force_assert, chunkqueue::last, chunk::mem, chunk::name, chunk::next, chunk::offset, buffer::ptr, chunk::start, and chunk::type.
Referenced by connection_handle_read_post_chunked(), and connection_handle_read_post_state().
void chunkqueue_use_memory (chunkqueue * cq, size_t len)
References buffer_commit(), buffer_reset(), buffer_string_is_empty(), chunkqueue::bytes_in, force_assert, chunkqueue::last, chunk::mem, and chunk::type.
Referenced by connection_handle_read(), connection_handle_read_ssl(), fcgi_demux_response(), and process_ssi_stmt().
Variable Documentation
array* chunkqueue_default_tempdirs = NULL [static]
Referenced by chunkqueue_init().
unsigned int chunkqueue_default_tempfile_size = DEFAULT_TEMPFILE_SIZE [static]
Referenced by chunkqueue_init(), and chunkqueue_set_tempdirs_default().