configfile.h File Reference
#include `first.h`
*
#include `array.h`
*
#include `buffer.h`
*
#include `server.h`
*
Classes
struct config_t
Functions
void * configparserAlloc (void *(*mallocProc)(size_t))
void configparserFree (void *p, void(*freeProc)(void *))
void configparser (void *yyp, int yymajor, buffer *yyminor, config_t *ctx)
int config_parse_file (server *srv, config_t *context, const char *fn)
int config_parse_cmd (server *srv, config_t *context, const char *cmd)
data_unset * configparser_merge_data (data_unset *op1, const data_unset *op2)
int config_setup_connection (server *srv, connection *con)
int config_patch_connection (server *srv, connection *con)
void config_cond_cache_reset (server *srv, connection *con)
void config_cond_cache_reset_item (server *srv, connection *con, comp_key_t item)
Function Documentation
void config_cond_cache_reset (server * srv, connection * con)
reset the config cache to its initial state at connection start
References COMP_LAST_ELEMENT, cond_cache_t::comp_value, connection::cond_cache, COND_RESULT_UNSET, connection::conditional_is_valid, server::config_context, cond_cache_t::local_result, cond_cache_t::patterncount, cond_cache_t::result, and array::used.
Referenced by http_response_prepare().
void config_cond_cache_reset_item (server * srv, connection * con, comp_key_t item)
reset the config-cache for a named item
if the item is COND_LAST_ELEMENT we reset all items
References data_config::comp, connection::cond_cache, COND_RESULT_UNSET, config_cond_clear_node(), server::config_context, array::data, cond_cache_t::local_result, and array::used.
Referenced by clean_cond_cache().
int config_parse_cmd (server * srv, config_t * context, const char * cmd)
References config_t::basedir, buffer_free(), buffer_init(), buffer_init_string(), buffer_string_is_empty(), config_parse(), CONST_BUF_LEN, getCWD(), log_error_write(), proc_open_buffer(), buffer::ptr, and tokenizer_init().
Referenced by yy_reduce().
int config_parse_file (server * srv, config_t * context, const char * fn)
References config_t::basedir, buffer_append_string(), buffer_copy_string(), buffer_free(), buffer_init_buffer(), buffer_init_string(), config_parse_file_stream(), log_error_write(), and buffer::ptr.
Referenced by yy_reduce().
int config_patch_connection (server * srv, connection * con)
References buffer_copy_buffer(), buffer_is_equal_string(), connection::conf, config_check_cond(), server::config_context, server::config_storage, CONST_STR_LEN, array::data, connection::etag_flags, ETAG_USE_INODE, specific_config::etag_use_inode, ETAG_USE_MTIME, specific_config::etag_use_mtime, ETAG_USE_SIZE, specific_config::etag_use_size, specific_config::global_bytes_per_second_cnt_ptr, PATCH, connection::server_name, array::used, and data_config::value.
Referenced by http_response_prepare().
int config_setup_connection (server * srv, connection * con)
References buffer_copy_buffer(), connection::conf, server::config_storage, specific_config::global_bytes_per_second_cnt, specific_config::global_bytes_per_second_cnt_ptr, PATCH, specific_config::server_name, and connection::server_name.
Referenced by connection_init(), connection_reset(), and http_response_prepare().
void configparser (void * yyp, int yymajor, buffer * yyminor, config_t * ctx)
Referenced by config_parse().
data_unset* configparser_merge_data (data_unset * op1, const data_unset * op2)
References array_get_element(), array_insert_unique(), buffer_append_int(), buffer_append_string_buffer(), buffer_is_empty(), array::data, data_string_init(), force_assert, TYPE_ARRAY, TYPE_INTEGER, TYPE_STRING, array::used, and data_string::value.
Referenced by yy_reduce().
void* configparserAlloc (void *(*)(size_t) mallocProc)
References yyParser::yyidx.
Referenced by config_parse().
void configparserFree (void * p, void(*)(void *) freeProc)
References yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by config_parse().