configfile-glue.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `buffer.h`
*
#include `array.h`
*
#include `log.h`
*
#include `plugin.h`
*
#include `configfile.h`
*
#include <string.h>
*
#include <stdlib.h>
*
#include <arpa/inet.h>
*
Functions
int config_insert_values_internal (server *srv, array *ca, const config_values_t cv[], config_scope_type_t scope)
int config_insert_values_global (server *srv, array *ca, const config_values_t cv[], config_scope_type_t scope)
static unsigned short sock_addr_get_port (sock_addr *addr)
static const char * cond_result_to_string (cond_result_t cond_result)
static int config_addrstr_eq_remote_ip_mask (server *srv, const char *addrstr, int nm_bits, sock_addr *rmt)
static int config_addrbuf_eq_remote_ip_mask (server *srv, buffer *string, char *nm_slash, sock_addr *rmt)
static cond_result_t config_check_cond_cached (server *srv, connection *con, data_config *dc)
static cond_result_t config_check_cond_nocache (server *srv, connection *con, data_config *dc)
static void config_cond_clear_node (server *srv, connection *con, data_config *dc)
void config_cond_cache_reset_item (server *srv, connection *con, comp_key_t item)
void config_cond_cache_reset (server *srv, connection *con)
int config_check_cond (server *srv, connection *con, data_config *dc)
int config_append_cond_match_buffer (connection *con, data_config *dc, buffer *buf, int n)
Function Documentation
static const char* cond_result_to_string (cond_result_t cond_result) [static]
References COND_RESULT_FALSE, COND_RESULT_SKIP, COND_RESULT_TRUE, and COND_RESULT_UNSET.
Referenced by config_check_cond_cached().
static int config_addrbuf_eq_remote_ip_mask (server * srv, buffer * string, char * nm_slash, sock_addr * rmt) [static]
References config_addrstr_eq_remote_ip_mask(), log_error_write(), and buffer::ptr.
Referenced by config_check_cond_nocache(), and test_configfile_addrbuf_eq_remote_ip_mask().
static int config_addrstr_eq_remote_ip_mask (server * srv, const char * addrstr, int nm_bits, sock_addr * rmt) [static]
References sock_addr::ipv4, log_error_write(), sock_addr::plain, and uint32_t.
Referenced by config_addrbuf_eq_remote_ip_mask().
int config_append_cond_match_buffer (connection * con, data_config * dc, buffer * buf, int n)
References buffer_append_string_len(), cond_cache_t::comp_value, connection::cond_cache, data_config::context_ndx, cond_cache_t::matches, cond_cache_t::patterncount, and buffer::ptr.
Referenced by mod_redirect_uri_handler().
int config_check_cond (server * srv, connection * con, data_config * dc)
References COND_RESULT_TRUE, connection::conf, config_check_cond_cached(), specific_config::log_condition_handling, and log_error_write().
Referenced by config_patch_connection(), fcgi_patch_connection(), mod_access_patch_connection(), mod_accesslog_patch_connection(), mod_alias_patch_connection(), mod_auth_patch_connection(), mod_authn_file_patch_connection(), mod_authn_gssapi_patch_connection(), mod_authn_ldap_patch_connection(), mod_authn_mysql_patch_connection(), mod_cgi_patch_connection(), mod_cml_patch_connection(), mod_compress_patch_connection(), mod_deflate_patch_connection(), mod_dirlisting_patch_connection(), mod_evasive_patch_connection(), mod_evhost_patch_connection(), mod_expire_patch_connection(), mod_extforward_patch_connection(), mod_flv_streaming_patch_connection(), mod_geoip_patch_connection(), mod_indexfile_patch_connection(), mod_magnet_patch_connection(), mod_mysql_vhost_patch_connection(), mod_proxy_patch_connection(), mod_rrd_patch_connection(), mod_secdownload_patch_connection(), mod_setenv_patch_connection(), mod_simple_vhost_patch_connection(), mod_skeleton_patch_connection(), mod_ssi_patch_connection(), mod_staticfile_patch_connection(), mod_status_patch_connection(), mod_trigger_b4_dl_patch_connection(), mod_uploadprogress_patch_connection(), mod_userdir_patch_connection(), mod_usertrack_patch_connection(), mod_webdav_patch_connection(), and scgi_patch_connection().
static cond_result_t config_check_cond_cached (server * srv, connection * con, data_config * dc) [static]
References connection::cond_cache, COND_RESULT_FALSE, cond_result_to_string(), COND_RESULT_TRUE, COND_RESULT_UNSET, connection::conf, config_check_cond_nocache(), data_config::context_ndx, cond_cache_t::local_result, specific_config::log_condition_handling, log_error_write(), and cond_cache_t::result.
Referenced by config_check_cond(), and config_check_cond_nocache().
static cond_result_t config_check_cond_nocache (server * srv, connection * con, data_config * dc) [static]
a nested conditional
if the parent is not decided yet or false, we can't be true either
a else branch; can only be executed if the previous branch was evaluated as `false` (not unset/skipped/true)
References server_socket::addr, array_get_element(), request_uri::authority, buffer_append_int(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), buffer_is_equal(), buffer_string_is_empty(), data_config::comp, COMP_HTTP_COOKIE, COMP_HTTP_HOST, COMP_HTTP_LANGUAGE, COMP_HTTP_QUERY_STRING, COMP_HTTP_REFERER, COMP_HTTP_REMOTE_IP, COMP_HTTP_REQUEST_METHOD, COMP_HTTP_SCHEME, COMP_HTTP_URL, COMP_HTTP_USER_AGENT, data_config::comp_key, COMP_SERVER_SOCKET, cond_cache_t::comp_value, data_config::cond, connection::cond_cache, server::cond_check_buf, COND_RESULT_FALSE, COND_RESULT_SKIP, COND_RESULT_TRUE, COND_RESULT_UNSET, connection::conditional_is_valid, connection::conf, config_addrbuf_eq_remote_ip_mask(), config_check_cond_cached(), CONFIG_COND_ELSE, CONFIG_COND_EQ, CONFIG_COND_MATCH, CONFIG_COND_NE, CONFIG_COND_NOMATCH, CONST_BUF_LEN, CONST_STR_LEN, data_config::context_ndx, connection::dst_addr, connection::dst_addr_buf, server::empty_string, get_http_method_name(), request::headers, request::http_method, cond_cache_t::local_result, specific_config::log_condition_handling, log_error_write(), cond_cache_t::matches, data_config::parent, request_uri::path, cond_cache_t::patterncount, data_config::prev, buffer::ptr, request_uri::query, connection::request, request_uri::scheme, sock_addr_get_port(), connection::srv_socket, server_socket::srv_token, data_config::string, server::tmp_buf, connection::uri, and data_string::value.
Referenced by config_check_cond_cached().
void config_cond_cache_reset (server * srv, connection * con)
reset the config cache to its initial state at connection start
References COMP_LAST_ELEMENT, cond_cache_t::comp_value, connection::cond_cache, COND_RESULT_UNSET, connection::conditional_is_valid, server::config_context, cond_cache_t::local_result, cond_cache_t::patterncount, cond_cache_t::result, and array::used.
Referenced by http_response_prepare().
void config_cond_cache_reset_item (server * srv, connection * con, comp_key_t item)
reset the config-cache for a named item
if the item is COND_LAST_ELEMENT we reset all items
References data_config::comp, connection::cond_cache, COND_RESULT_UNSET, config_cond_clear_node(), server::config_context, array::data, cond_cache_t::local_result, and array::used.
Referenced by clean_cond_cache().
static void config_cond_clear_node (server * srv, connection * con, data_config * dc) [static]
References data_config::children, cond_cache_t::comp_value, connection::cond_cache, COND_RESULT_UNSET, data_config::context_ndx, data_config::next, cond_cache_t::patterncount, data_config::prev, and cond_cache_t::result.
Referenced by config_cond_cache_reset_item().
int config_insert_values_global (server * srv, array * ca, const config_values_t cv[], config_scope_type_t scope)
References array_get_element(), array_insert_unique(), buffer_copy_buffer(), buffer_copy_string_len(), config_insert_values_internal(), server::config_touched, CONST_STR_LEN, data_string_init(), config_values_t::key, and data_string::value.
Referenced by config_insert(), SERVER_FUNC(), and SETDEFAULTS_FUNC().
int config_insert_values_internal (server * srv, array * ca, const config_values_t cv[], config_scope_type_t scope)
like all glue code this file contains functions which are the external interface of lighttpd. The functions are used by the server itself and the plugins.
The main-goal is to have a small library in the end which is linked against both and which will define the interface itself in the end.
References array_get_element(), array_insert_unique(), buffer_copy_buffer(), buffer_is_equal_string(), server::config_deprecated, server::config_unsupported, CONST_STR_LEN, array::data, config_values_t::key, log_error_write(), buffer::ptr, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_DEPRECATED, T_CONFIG_INT, T_CONFIG_LOCAL, T_CONFIG_SCOPE_SERVER, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, T_CONFIG_UNSUPPORTED, TYPE_ARRAY, TYPE_INTEGER, TYPE_STRING, array::used, data_string::value, data_array::value, and data_integer::value.
Referenced by config_insert_values_global(), and SETDEFAULTS_FUNC().
static unsigned short sock_addr_get_port (sock_addr * addr) [static]
References sock_addr::ipv4, and sock_addr::plain.
Referenced by config_check_cond_nocache().