configparser.c File Reference
#include `first.h`
*
#include <stdio.h>
*
#include `configfile.h`
*
#include `buffer.h`
*
#include `array.h`
*
#include `request.h`
*
#include <assert.h>
*
#include <ctype.h>
*
#include <errno.h>
*
#include <string.h>
*
Classes
union YYMINORTYPE
struct yyStackEntry
struct yyParser
Macros
#define INTERFACE 1
#define YYCODETYPE unsigned char
#define YYNOCODE 50
#define YYACTIONTYPE unsigned char
#define configparserTOKENTYPE buffer *
#define YYSTACKDEPTH 100
#define configparserARG_SDECL config_t *ctx;
#define configparserARG_PDECL ,config_t *ctx
#define configparserARG_FETCH config_t *ctx = yypParser->ctx
#define configparserARG_STORE yypParser->ctx = ctx
#define YYNSTATE 68
#define YYNRULE 43
#define YYERRORSYMBOL 26
#define YYERRSYMDT yy99
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
#define YY_SHIFT_USE_DFLT (-2)
#define YY_REDUCE_USE_DFLT (-38)
#define YY_SZ_ACTTAB (sizeof(yy_action)/sizeof(yy_action[0]))
#define TOKEN (yyminor.yy0)
Typedefs
typedef struct yyStackEntry yyStackEntry
typedef struct yyParser yyParser
Functions
static void configparser_push (config_t *ctx, data_config *dc, int isnew)
static data_config * configparser_pop (config_t *ctx)
static data_unset * configparser_get_variable (config_t *ctx, const buffer *key)
data_unset * configparser_merge_data (data_unset *op1, const data_unset *op2)
static int configparser_remoteip_normalize_compat (buffer *rvalue)
void * configparserAlloc (void *(*mallocProc)(size_t))
static void yy_destructor (YYCODETYPE yymajor, YYMINORTYPE *yypminor)
static int yy_pop_parser_stack (yyParser *pParser)
void configparserFree (void *p, void(*freeProc)(void *))
static int yy_find_shift_action (yyParser *pParser, int iLookAhead)
static int yy_find_reduce_action (yyParser *pParser, int iLookAhead)
static void yy_shift (yyParser *yypParser, int yyNewState, int yyMajor, YYMINORTYPE *yypMinor)
static void yy_accept (yyParser *)
static void yy_reduce (yyParser *yypParser, int yyruleno)
static void yy_parse_failed (yyParser *yypParser)
static void yy_syntax_error (yyParser *yypParser, int yymajor, YYMINORTYPE yyminor)
void configparser (void *yyp, int yymajor, configparserTOKENTYPE yyminorconfigparserARG_PDECL)
Variables
static YYACTIONTYPE yy_action []
static YYCODETYPE yy_lookahead []
static signed char yy_shift_ofst []
static signed char yy_reduce_ofst []
static YYACTIONTYPE yy_default []
static FILE * yyTraceFILE = NULL
static char * yyTracePrompt = NULL
static const char * yyTokenName []
static const char * yyRuleName []
xx xx xx xx xx xx xx xx xx
struct {
 YYCODETYPE lhs
 unsigned char nrhs
} yyRuleInfo []
Macro Definition Documentation
#define configparserARG_FETCH config_t *ctx = yypParser->ctx
Referenced by yy_accept(), yy_parse_failed(), yy_reduce(), yy_shift(), and yy_syntax_error().
#define configparserARG_PDECL ,config_t *ctx
#define configparserARG_SDECL config_t *ctx;
#define configparserARG_STORE yypParser->ctx = ctx
Referenced by configparser(), yy_accept(), yy_parse_failed(), yy_shift(), and yy_syntax_error().
#define configparserTOKENTYPE buffer *
#define INTERFACE 1
#define TOKEN (yyminor.yy0)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
Referenced by configparser().
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YY_REDUCE_USE_DFLT (-38)
Referenced by yy_find_reduce_action().
#define YY_SHIFT_USE_DFLT (-2)
Referenced by yy_find_shift_action().
#define YY_SZ_ACTTAB (sizeof(yy_action)/sizeof(yy_action[0]))
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YYACTIONTYPE unsigned char
#define YYCODETYPE unsigned char
Referenced by yy_pop_parser_stack().
#define YYERRORSYMBOL 26
Referenced by configparser(), and Parse().
#define YYERRSYMDT yy99
#define YYNOCODE 50
Referenced by configparser(), Parse(), yy_find_reduce_action(), and yy_find_shift_action().
#define YYNRULE 43
Referenced by configparser(), Parse(), and yy_reduce().
#define YYNSTATE 68
Referenced by configparser(), Parse(), and yy_reduce().
#define YYSTACKDEPTH 100
Referenced by yy_shift().
Typedef Documentation
typedef struct yyParser yyParser
typedef struct yyStackEntry yyStackEntry
Function Documentation
void configparser (void * yyp, int yymajor, configparserTOKENTYPE yyminor configparserARG_PDECL)
References configparserARG_STORE, yyStackEntry::major, yyStackEntry::stateno, YYMINORTYPE::yy0, yy_accept(), yy_destructor(), YY_ERROR_ACTION, yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), yy_syntax_error(), yyParser::yyerrcnt, YYERRORSYMBOL, yyParser::yyidx, YYNOCODE, YYNRULE, YYNSTATE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
static data_unset* configparser_get_variable (config_t * ctx, const buffer * key) [static]
References array_get_element(), array_print(), config_t::current, data_config::parent, buffer::ptr, and data_config::value.
Referenced by yy_reduce().
data_unset* configparser_merge_data (data_unset * op1, const data_unset * op2)
References array_get_element(), array_insert_unique(), buffer_append_int(), buffer_append_string_buffer(), buffer_is_empty(), array::data, data_string_init(), force_assert, TYPE_ARRAY, TYPE_INTEGER, TYPE_STRING, array::used, and data_string::value.
Referenced by yy_reduce().
static data_config* configparser_pop (config_t * ctx) [static]
References config_t::configs_stack, and config_t::current.
Referenced by yy_reduce().
static void configparser_push (config_t * ctx, data_config * dc, int isnew) [static]
References config_t::all_configs, array_insert_unique(), data_config::children, config_t::configs_stack, data_config::context_ndx, config_t::current, force_assert, data_config::parent, and array::used.
Referenced by yy_reduce().
static int configparser_remoteip_normalize_compat (buffer * rvalue) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_string_length(), CONST_STR_LEN, http_request_host_normalize(), and buffer::ptr.
Referenced by yy_reduce().
void* configparserAlloc (void *(*)(size_t) mallocProc)
References yyParser::yyidx.
Referenced by config_parse().
void configparserFree (void * p, void(*)(void *) freeProc)
References yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by config_parse().
static void yy_accept (yyParser * yypParser) [static]
References configparserARG_FETCH, configparserARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by configparser(), and yy_reduce().
static void yy_destructor (YYCODETYPE yymajor, YYMINORTYPE * yypminor) [static]
References array_free(), buffer_free(), YYMINORTYPE::yy0, YYMINORTYPE::yy22, YYMINORTYPE::yy59, and YYMINORTYPE::yy87.
Referenced by configparser(), yy_pop_parser_stack(), and yy_reduce().
static int yy_find_reduce_action (yyParser * pParser, int iLookAhead) [static]
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_NO_ACTION, yy_reduce_ofst, YY_REDUCE_USE_DFLT, YY_SZ_ACTTAB, yyParser::yyidx, YYNOCODE, and yyParser::yystack.
Referenced by yy_reduce().
static int yy_find_shift_action (yyParser * pParser, int iLookAhead) [static]
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_NO_ACTION, yy_shift_ofst, YY_SHIFT_USE_DFLT, YY_SZ_ACTTAB, yyParser::yyidx, YYNOCODE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by configparser().
static void yy_parse_failed (yyParser * yypParser) [static]
References configparserARG_FETCH, configparserARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by configparser().
static int yy_pop_parser_stack (yyParser * pParser) [static]
References yyStackEntry::major, yyStackEntry::minor, yy_destructor(), YYCODETYPE, yyParser::yyidx, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by configparser(), configparserFree(), yy_accept(), yy_parse_failed(), and yy_shift().
static void yy_reduce (yyParser * yypParser, int yyruleno) [static]
References array_extract_element(), array_free(), array_get_element(), array_init(), array_insert_unique(), buffer_append_int(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_int(), buffer_free(), buffer_init(), buffer_init_buffer(), buffer_init_string(), buffer_is_empty(), buffer_is_equal_string(), buffer_string_length(), buffer_string_set_length(), data_config::comp, COMP_HTTP_COOKIE, COMP_HTTP_HOST, COMP_HTTP_LANGUAGE, COMP_HTTP_QUERY_STRING, COMP_HTTP_REFERER, COMP_HTTP_REMOTE_IP, COMP_HTTP_REQUEST_METHOD, COMP_HTTP_SCHEME, COMP_HTTP_URL, COMP_HTTP_USER_AGENT, data_config::comp_key, COMP_SERVER_SOCKET, COMP_UNSET, data_config::cond, CONFIG_COND_ELSE, CONFIG_COND_EQ, CONFIG_COND_MATCH, CONFIG_COND_NE, CONFIG_COND_NOMATCH, CONFIG_COND_UNSET, config_parse_cmd(), config_parse_file(), configparser_get_variable(), configparser_merge_data(), configparser_pop(), configparser_push(), configparser_remoteip_normalize_compat(), configparserARG_FETCH, CONST_STR_LEN, data_config::context_ndx, data_array_init(), data_config_init(), data_integer_init(), data_string_init(), force_assert, http_request_host_normalize(), yyStackEntry::minor, data_config::next, data_config::op, op, data_config::prev, buffer::ptr, data_config::string, TYPE_INTEGER, TYPE_STRING, data_string::value, YYMINORTYPE::yy0, YYMINORTYPE::yy2, YYMINORTYPE::yy22, YYMINORTYPE::yy59, YYMINORTYPE::yy75, YYMINORTYPE::yy87, yy_accept(), yy_destructor(), yy_find_reduce_action(), yy_shift(), yyParser::yyidx, YYNRULE, YYNSTATE, yyRuleInfo, yyRuleName, yyParser::yystack, yyTraceFILE, and yyTracePrompt.
Referenced by configparser().
static void yy_shift (yyParser * yypParser, int yyNewState, int yyMajor, YYMINORTYPE * yypMinor) [static]
References configparserARG_FETCH, configparserARG_STORE, yyStackEntry::major, yyStackEntry::minor, yyStackEntry::stateno, yy_pop_parser_stack(), yyParser::yyidx, yyParser::yystack, YYSTACKDEPTH, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by configparser(), and yy_reduce().
static void yy_syntax_error (yyParser * yypParser, int yymajor, YYMINORTYPE yyminor) [static]
References configparserARG_FETCH, configparserARG_STORE, and UNUSED.
Referenced by configparser().
Variable Documentation
YYCODETYPE lhs
unsigned char nrhs
YYACTIONTYPE yy_action[] [static]
Initial value:
= {
      2, 3, 4, 5, 14, 15, 112, 1, 7, 46,
     68, 16, 103, 17, 21, 47, 16, 42, 11, 21,
     18, 39, 41, 9, 10, 12, 47, 41, 93, 63,
     13, 47, 11, 64, 59, 61, 29, 28, 38, 59,
     61, 31, 26, 23, 35, 16, 20, 8, 21, 36,
     16, 20, 108, 21, 32, 33, 41, 20, 45, 102,
     47, 41, 44, 67, 48, 47, 95, 52, 59, 61,
     29, 28, 34, 59, 61, 43, 26, 23, 35, 21,
     53, 24, 25, 27, 30, 49, 29, 50, 6, 29,
     50, 65, 26, 23, 51, 26, 23, 60, 66, 29,
     50, 94, 94, 94, 94, 26, 23, 62, 94, 94,
     21, 94, 24, 25, 27, 29, 19, 29, 37, 29,
     40, 26, 23, 26, 23, 26, 23, 55, 56, 57,
     58, 29, 54, 22, 94, 94, 94, 26, 23, 26,
     23,
}
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
YYACTIONTYPE yy_default[] [static]
Initial value:
= {
     70, 111, 69, 71, 72, 111, 73, 111, 111, 97,
     98, 111, 70, 111, 74, 75, 76, 111, 111, 77,
    111, 79, 80, 82, 83, 84, 85, 111, 91, 81,
     86, 111, 87, 89, 88, 111, 111, 92, 90, 111,
     78, 111, 111, 70, 111, 96, 99, 111, 111, 111,
    108, 111, 111, 111, 111, 104, 105, 106, 107, 111,
    109, 111, 110, 100, 111, 70, 111, 101,
}
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
YYCODETYPE yy_lookahead[] [static]
Initial value:
= {
     29, 30, 31, 32, 33, 34, 27, 28, 45, 38,
      0, 1, 13, 42, 4, 16, 1, 46, 47, 4,
      2, 3, 12, 38, 39, 13, 16, 12, 15, 14,
     28, 16, 47, 48, 24, 25, 35, 36, 37, 24,
     25, 40, 41, 42, 43, 1, 5, 15, 4, 11,
      1, 5, 11, 4, 9, 10, 12, 5, 14, 13,
     16, 12, 28, 14, 17, 16, 13, 19, 24, 25,
     35, 36, 37, 24, 25, 13, 41, 42, 43, 4,
     44, 6, 7, 8, 9, 18, 35, 36, 1, 35,
     36, 13, 41, 42, 43, 41, 42, 43, 28, 35,
     36, 49, 15, 49, 49, 41, 42, 43, 49, 49,
      4, 49, 6, 7, 8, 35, 36, 35, 36, 35,
     36, 41, 42, 41, 42, 41, 42, 20, 21, 22,
     23, 35, 36, 35, 49, 49, 49, 41, 42, 41,
     42,
}
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
signed char yy_reduce_ofst[] [static]
Initial value:
= {
    -21, -29, -38, -38, -38, -37, -38, -38, -15, -38,
    -38, -38, 2, -29, -38, -38, -38, -38, 80, -38,
     98, -38, -38, -38, -38, -38, -38, 1, -38, -38,
    -38, -38, -38, 35, -38, -38, 82, -38, -38, 84,
    -38, -38, -38, 34, -29, -38, -38, -38, -38, 51,
    -38, -38, 36, 96, -38, -38, -38, -38, -38, 54,
    -38, 64, -38, -38, -38, 70, -29, -38,
}
Referenced by yy_find_reduce_action().
signed char yy_shift_ofst[] [static]
Initial value:
= {
     -2, 10, -2, -2, -2, 87, 13, 32, -1, -2,
     -2, 12, -2, 15, -2, -2, -2, 18, 106, 52,
    106, -2, -2, -2, -2, -2, -2, 75, 41, -2,
     -2, 45, -2, 106, -2, 38, 106, 52, -2, 106,
     52, 53, 62, -2, 44, -2, -2, 47, 67, 106,
     52, 48, 107, 106, 46, -2, -2, -2, -2, 106,
     -2, 106, -2, -2, 78, -2, 49, -2,
}
Referenced by yy_find_shift_action().
struct { ... } yyRuleInfo[] [static]
Referenced by yy_reduce().
const char* yyRuleName[] [static]
Referenced by yy_reduce().
const char* yyTokenName[] [static]
Initial value:
= {
  "$", "EOL", "ASSIGN", "APPEND",
  "LKEY", "PLUS", "STRING", "INTEGER",
  "LPARAN", "RPARAN", "COMMA", "ARRAY_ASSIGN",
  "GLOBAL", "LCURLY", "RCURLY", "ELSE",
  "DOLLAR", "SRVVARNAME", "LBRACKET", "RBRACKET",
  "EQ", "MATCH", "NE", "NOMATCH",
  "INCLUDE", "INCLUDE_SHELL", "error", "input",
  "metalines", "metaline", "varline", "global",
  "condlines", "include", "include_shell", "value",
  "expression", "aelement", "condline", "cond_else",
  "aelements", "array", "key", "stringop",
  "cond", "eols", "globalstart", "context",
  "context_else",
}
Referenced by configparser(), yy_find_shift_action(), yy_pop_parser_stack(), and yy_shift().
FILE* yyTraceFILE = NULL [static]
Referenced by configparser(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), and yy_shift().
char* yyTracePrompt = NULL [static]
Referenced by configparser(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), and yy_shift().