configfile.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `log.h`
*
#include `stream.h`
*
#include `plugin.h`
*
#include `configparser.h`
*
#include `configfile.h`
*
#include `proc_open.h`
*
#include `request.h`
*
#include `version.h`
*
#include <sys/stat.h>
*
#include <stdlib.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <string.h>
*
#include <stdio.h>
*
#include <ctype.h>
*
#include <limits.h>
*
#include <assert.h>
*
#include <glob.h>
*
Classes
struct tokenizer_t
Macros
#define PATCH(x) con->conf.x = s->x
Functions
static int config_insert (server *srv)
int config_setup_connection (server *srv, connection *con)
int config_patch_connection (server *srv, connection *con)
static int config_skip_newline (tokenizer_t *t)
static int config_skip_comment (tokenizer_t *t)
static int config_tokenizer (server *srv, tokenizer_t *t, int *token_id, buffer *token)
static int config_parse (server *srv, config_t *context, tokenizer_t *t)
static int tokenizer_init (tokenizer_t *t, const buffer *source, const char *input, size_t size)
static int config_parse_file_stream (server *srv, config_t *context, const buffer *filename)
int config_parse_file (server *srv, config_t *context, const char *fn)
static char * getCWD (void)
int config_parse_cmd (server *srv, config_t *context, const char *cmd)
static void context_init (server *srv, config_t *context)
static void context_free (config_t *context)
int config_read (server *srv, const char *fn)
int config_set_defaults (server *srv)
Macro Definition Documentation
#define PATCH(x) con->conf.x = s->x
Referenced by config_patch_connection(), and config_setup_connection().
Function Documentation
static int config_insert (server * srv) [static]
References array_free(), array_init(), array_insert_unique(), server_config::bindhost, server_config::breakagelog_file, buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_init_buffer(), buffer_init_string(), buffer_is_equal_string(), buffer_string_is_empty(), server_config::changeroot, server::config_context, config_insert_values_global(), server::config_storage, CONST_STR_LEN, array::data, data_string_init(), specific_config::defer_accept, config_values_t::destination, server_config::enable_cores, server_config::errorlog_file, server_config::errorlog_use_syslog, server_config::event_handler, FDEVENT_STREAM_REQUEST, FDEVENT_STREAM_REQUEST_BUFMIN, FDEVENT_STREAM_RESPONSE, FDEVENT_STREAM_RESPONSE_BUFMIN, force_assert, server_config::groupname, HANDLER_ERROR, server_config::http_header_strict, server_config::http_host_normalize, server_config::http_host_strict, HTTP_PARSEOPT_HEADER_STRICT, HTTP_PARSEOPT_HOST_NORMALIZE, HTTP_PARSEOPT_HOST_STRICT, specific_config::http_parseopts, specific_config::listen_backlog, log_error_write(), server_config::log_request_header_on_error, server_config::log_state_handling, server_config::max_conns, server_config::max_fds, server_config::max_request_field_size, server_config::max_worker, server_config::modules, server_config::network_backend, PACKAGE_DESC, server_config::pid_file, server_config::port, server_config::reject_expect_100_with_417, specific_config::set_v6only, server::srvconf, specific_config::ssl_read_ahead, server_config::stat_cache_engine, specific_config::stream_request_body, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_INT, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, T_CONFIG_UNSUPPORTED, server_config::upload_temp_file_size, server_config::upload_tempdirs, specific_config::use_ipv6, array::used, server_config::username, data_string::value, data_config::value, and server_config::xattr_name.
Referenced by config_read().
static int config_parse (server * srv, config_t * context, tokenizer_t * t) [static]
References buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_init_string(), config_tokenizer(), configparser(), configparserAlloc(), configparserFree(), force_assert, tokenizer_t::line, tokenizer_t::line_pos, log_error_write(), config_t::ok, tokenizer_t::source, and TK_EOL.
Referenced by config_parse_cmd(), and config_parse_file_stream().
int config_parse_cmd (server * srv, config_t * context, const char * cmd)
References config_t::basedir, buffer_free(), buffer_init(), buffer_init_string(), buffer_string_is_empty(), config_parse(), CONST_BUF_LEN, getCWD(), log_error_write(), proc_open_buffer(), buffer::ptr, and tokenizer_init().
Referenced by yy_reduce().
int config_parse_file (server * srv, config_t * context, const char * fn)
References config_t::basedir, buffer_append_string(), buffer_copy_string(), buffer_free(), buffer_init_buffer(), buffer_init_string(), config_parse_file_stream(), log_error_write(), and buffer::ptr.
Referenced by yy_reduce().
static int config_parse_file_stream (server * srv, config_t * context, const buffer * filename) [static]
References config_parse(), log_error_write(), stream::size, stream::start, stream_close(), stream_open(), and tokenizer_init().
Referenced by config_parse_file(), and config_read().
int config_patch_connection (server * srv, connection * con)
References buffer_copy_buffer(), buffer_is_equal_string(), connection::conf, config_check_cond(), server::config_context, server::config_storage, CONST_STR_LEN, array::data, connection::etag_flags, ETAG_USE_INODE, specific_config::etag_use_inode, ETAG_USE_MTIME, specific_config::etag_use_mtime, ETAG_USE_SIZE, specific_config::etag_use_size, specific_config::global_bytes_per_second_cnt_ptr, PATCH, connection::server_name, array::used, and data_config::value.
Referenced by http_response_prepare().
int config_read (server * srv, const char * fn)
References config_t::all_configs, array_insert_unique(), config_t::basedir, buffer_commit(), buffer_copy_string_len(), buffer_free(), buffer_init_string(), buffer_string_prepare_copy(), server::config_context, config_insert(), config_parse_file_stream(), config_t::configs_stack, CONST_STR_LEN, context_free(), context_init(), data_config::context_ndx, config_t::current, data_config_init(), data_integer_init(), data_string_init(), force_assert, config_t::ok, buffer::ptr, buffer::size, array::used, data_string::value, data_config::value, and data_integer::value.
Referenced by main().
int config_set_defaults (server * srv)
References array_insert_unique(), buffer_append_slash(), buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string(), buffer_is_equal(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), buffer_to_lower(), buffer_to_upper(), server_config::changeroot, chunkqueue_set_tempdirs_default(), server::config_storage, array::data, data_string_init(), specific_config::document_root, server_config::event_handler, server::event_handler, FDEVENT_HANDLER_FREEBSD_KQUEUE, FDEVENT_HANDLER_LIBEV, FDEVENT_HANDLER_LINUX_SYSEPOLL, FDEVENT_HANDLER_POLL, FDEVENT_HANDLER_SELECT, FDEVENT_HANDLER_SOLARIS_DEVPOLL, FDEVENT_HANDLER_SOLARIS_PORT, FDEVENT_HANDLER_UNSET, specific_config::force_lowercase_filenames, log_error_write(), server_config::port, buffer::ptr, server::srvconf, specific_config::ssl_enabled, specific_config::ssl_pemfile, server::tmp_buf, server_config::upload_temp_file_size, server_config::upload_tempdirs, array::used, and data_string::value.
Referenced by main().
int config_setup_connection (server * srv, connection * con)
References buffer_copy_buffer(), connection::conf, server::config_storage, specific_config::global_bytes_per_second_cnt, specific_config::global_bytes_per_second_cnt_ptr, PATCH, specific_config::server_name, and connection::server_name.
Referenced by connection_init(), connection_reset(), and http_response_prepare().
static int config_skip_comment (tokenizer_t * t) [static]
References force_assert, tokenizer_t::input, and tokenizer_t::offset.
Referenced by config_tokenizer().
static int config_skip_newline (tokenizer_t * t) [static]
References force_assert, tokenizer_t::input, and tokenizer_t::offset.
Referenced by config_tokenizer().
static int config_tokenizer (server * srv, tokenizer_t * t, int * token_id, buffer * token) [static]
References buffer_append_string_len(), buffer_copy_string_len(), config_skip_comment(), config_skip_newline(), CONST_STR_LEN, tokenizer_t::in_brace, tokenizer_t::in_cond, tokenizer_t::in_key, tokenizer_t::input, tokenizer_t::line, tokenizer_t::line_pos, log_error_write(), tokenizer_t::offset, buffer::ptr, tokenizer_t::size, tokenizer_t::source, TK_APPEND, TK_ARRAY_ASSIGN, TK_ASSIGN, TK_COMMA, TK_DOLLAR, TK_ELSE, TK_EOL, TK_EQ, TK_GLOBAL, TK_INCLUDE, TK_INCLUDE_SHELL, TK_INTEGER, TK_LBRACKET, TK_LCURLY, TK_LKEY, TK_LPARAN, TK_MATCH, TK_NE, TK_NOMATCH, TK_PLUS, TK_RBRACKET, TK_RCURLY, TK_RPARAN, TK_SRVVARNAME, TK_STRING, and buffer::used.
Referenced by config_parse().
static void context_free (config_t * context) [static]
References config_t::basedir, buffer_free(), and config_t::configs_stack.
Referenced by config_read().
static void context_init (server * srv, config_t * context) [static]
References config_t::basedir, buffer_init(), config_t::configs_stack, config_t::ok, and config_t::srv.
Referenced by config_read().
static char* getCWD (void) [static]
References SSIZE_MAX.
Referenced by config_parse_cmd().
static int tokenizer_init (tokenizer_t * t, const buffer * source, const char * input, size_t size) [static]
References tokenizer_t::in_brace, tokenizer_t::in_cond, tokenizer_t::in_key, tokenizer_t::input, tokenizer_t::line, tokenizer_t::line_pos, tokenizer_t::offset, tokenizer_t::size, and tokenizer_t::source.
Referenced by config_parse_cmd(), and config_parse_file_stream().