connections.c File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `log.h`
*
#include `connections.h`
*
#include `fdevent.h`
*
#include `configfile.h`
*
#include `request.h`
*
#include `response.h`
*
#include `network.h`
*
#include `http_chunk.h`
*
#include `stat_cache.h`
*
#include `joblist.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include <sys/stat.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <string.h>
*
#include <fcntl.h>
*
#include <assert.h>
*
#include `sys-socket.h`
*
Classes
struct plugin_data
Macros
#define CLEAN(x) con->x = buffer_init();
#define CLEAN(x) buffer_free(con->x);
#define CLEAN(x) if (con->x) buffer_reset(con->x);
#define CLEAN(x) if (con->x) con->x->used = 0;
#define CLEAN(x) con->request.x = NULL;
Functions
static connection * connections_get_new_connection (server *srv)
static int connection_del (server *srv, connection *con)
static int connection_close (server *srv, connection *con)
static void connection_read_for_eos (server *srv, connection *con)
static void connection_handle_close_state (server *srv, connection *con)
static void connection_handle_shutdown (server *srv, connection *con)
static void connection_handle_response_end_state (server *srv, connection *con)
static void connection_handle_errdoc_init (server *srv, connection *con)
static int connection_handle_write_prepare (server *srv, connection *con)
static int connection_handle_write (server *srv, connection *con)
connection * connection_init (server *srv)
void connections_free (server *srv)
int connection_reset (server *srv, connection *con)
static int connection_handle_read_state (server *srv, connection *con)
static handler_t connection_handle_fdevent (server *srv, void *context, int revents)
connection * connection_accept (server *srv, server_socket *srv_socket)
connection * connection_accepted (server *srv, server_socket *srv_socket, sock_addr *cnt_addr, int cnt)
int connection_state_machine (server *srv, connection *con)
Macro Definition Documentation
#define CLEAN(x) con->x = buffer_init();
Referenced by connection_init(), connection_reset(), and connections_free().
#define CLEAN(x) buffer_free(con->x);
#define CLEAN(x) if (con->x) buffer_reset(con->x);
#define CLEAN(x) if (con->x) con->x->used = 0;
#define CLEAN(x) con->request.x = NULL;
Function Documentation
connection* connection_accept (server * srv, server_socket * srv_socket)
check if we can still open a new connections
see #1216
References connection_accepted(), server::conns, server_socket::fd, log_error_write(), server::max_conns, network_accept_tcp_nagle_disable(), sock_addr::plain, and connections::used.
Referenced by network_server_handle_fdevent().
connection* connection_accepted (server * srv, server_socket * srv_socket, sock_addr * cnt_addr, int cnt)
References buffer_copy_string(), server::con_opened, CON_STATE_REQUEST_START, connection_close(), connection_handle_fdevent(), connection_set_state(), connection::connection_start, connections_get_new_connection(), server::cur_fds, server::cur_ts, connection::dst_addr, connection::dst_addr_buf, server::ev, connection::fd, connection::fde_ndx, fdevent_fcntl_set_nb_cloexec_sock(), fdevent_register(), inet_ntop_cache_get_ip(), server_socket::is_ssl, log_error_write(), and connection::srv_socket.
Referenced by connection_accept(), and server_oneshot_init().
static int connection_close (server * srv, connection * con) [static]
References CON_STATE_CONNECT, connection_del(), connection_set_state(), server::cur_fds, server::ev, connection::fd, connection::fde_ndx, fdevent_event_del(), fdevent_unregister(), server_socket::is_ssl, log_error_write(), server_config::log_state_handling, connection::srv_socket, and server::srvconf.
Referenced by connection_accepted(), connection_handle_close_state(), and connection_handle_shutdown().
static int connection_del (server * srv, connection * con) [static]
References request_uri::authority, buffer_reset(), server::conns, connection::fd, connection::ndx, request::orig_uri, request_uri::path, connections::ptr, request_uri::query, connection::request, connection::uri, and connections::used.
Referenced by connection_close().
static void connection_handle_close_state (server * srv, connection * con) [static]
References connection::close_timeout_ts, connection_close(), connection_read_for_eos(), server::cur_ts, and HTTP_LINGER_TIMEOUT.
Referenced by connection_state_machine().
static void connection_handle_errdoc_init (server * srv, connection * con) [static]
References array_get_element(), array_reset(), buffer_free(), buffer_init_buffer(), buffer_reset(), chunkqueue_reset(), CONST_BUF_LEN, CONST_STR_LEN, response::headers, connection::http_status, physical::path, connection::physical, connection::response, response_header_insert(), response::transfer_encoding, data_string::value, and connection::write_queue.
Referenced by connection_handle_write_prepare(), and connection_state_machine().
static handler_t connection_handle_fdevent (server * srv, void * context, int revents) [static]
References chunkqueue_is_empty(), connection::close_timeout_ts, CON_STATE_CLOSE, CON_STATE_ERROR, CON_STATE_READ, CON_STATE_WRITE, connection_handle_read_state(), connection_handle_write(), connection_read_for_eos(), connection_set_state(), server::cur_ts, connection::fd, FDEVENT_ERR, FDEVENT_HUP, FDEVENT_IN, fdevent_is_tcp_half_closed(), FDEVENT_OUT, HANDLER_FINISHED, HTTP_LINGER_TIMEOUT, connection::is_readable, server_socket::is_ssl, connection::is_writable, joblist_append(), connection::keep_alive, log_error_write(), connection::srv_socket, connection::state, and connection::write_queue.
Referenced by connection_accepted().
static int connection_handle_read_state (server * srv, connection * con) [static]
handle all header and content read
we get called by the state-engine and by the fdevent-handler
References buffer_append_string_len(), buffer_reset(), buffer_string_length(), chunkqueue::bytes_out, chunkqueue_is_empty(), chunkqueue_length(), chunkqueue_remove_finished_chunks(), CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_REQUEST_END, connection::conf, connection_handle_read(), connection_set_state(), server::cur_ts, chunkqueue::first, specific_config::high_precision_timestamps, connection::http_status, connection::is_readable, connection::keep_alive, log_clock_gettime_realtime(), log_error_write(), server_config::max_request_field_size, chunk::mem, chunk::next, chunk::offset, buffer::ptr, connection::read_idle_ts, connection::read_queue, request::request, connection::request, connection::request_count, connection::request_start, connection::request_start_hp, and server::srvconf.
Referenced by connection_handle_fdevent(), and connection_state_machine().
static void connection_handle_response_end_state (server * srv, connection * con) [static]
References chunkqueue::bytes_in, CON_STATE_ERROR, CON_STATE_REQUEST_START, server::con_written, connection_handle_shutdown(), connection_reset(), connection_set_state(), request::content_length, server::cur_ts, connection::http_status, connection::keep_alive, plugins_call_handle_request_done(), connection::read_idle_ts, connection::request, connection::request_content_queue, connection::request_start, and connection::state.
Referenced by connection_state_machine().
static void connection_handle_shutdown (server * srv, connection * con) [static]
References connection::close_timeout_ts, server::con_closed, CON_STATE_CLOSE, connection_close(), connection_reset(), connection_set_state(), server::cur_ts, plugin::data, connection::fd, HANDLER_FINISHED, HANDLER_GO_ON, server_socket::is_ssl, log_error_write(), server_config::log_state_handling, plugin::name, connection::plugin_ctx, server::plugins, plugins_call_handle_connection_close(), buffer_plugin::ptr, SHUT_WR, connection::srv_socket, server::srvconf, and buffer_plugin::used.
Referenced by connection_handle_response_end_state().
static int connection_handle_write (server * srv, connection * con) [static]
References CON_STATE_ERROR, CON_STATE_RESPONSE_END, connection_set_state(), server::cur_ts, connection::fd, connection::file_finished, connection::is_writable, log_error_write(), MAX_WRITE_LIMIT, network_write_chunkqueue(), connection::write_queue, and connection::write_request_ts.
Referenced by connection_handle_fdevent(), and connection_state_machine().
static int connection_handle_write_prepare (server * srv, connection * con) [static]
The Content-Length header only can be sent if we have content:
HEAD doesn't have a content-body (but have a content-length)
1xx, 204 and 304 don't have a content-body (RFC 2616 Section 4.3)
Otherwise generate a Content-Length header as chunked encoding is not available
the file isn't finished yet, but we have all headers
to get keep-alive we either need:
Content-Length: ... (HTTP/1.0 and HTTP/1.0) or
Transfer-Encoding: chunked (HTTP/1.1)
if the backend sent a Connection: close, follow the wish
NOTE: if the backend sent Connection: Keep-Alive, but no Content-Length, we will close the connection. That's fine. We can always decide the close the connection
FIXME: to be nice we should remove the Connection: ...
a HEAD request has the same as a GET without the content
References array_get_element(), buffer_append_int(), buffer_append_string(), buffer_append_string_len(), buffer_append_uint_hex(), buffer_copy_buffer(), buffer_copy_int(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_reset(), buffer_string_is_empty(), buffer_string_set_length(), chunkqueue_append_mem(), chunkqueue_length(), chunkqueue_prepend_buffer(), chunkqueue_reset(), connection::conf, connection_handle_errdoc_init(), CONST_BUF_LEN, CONST_STR_LEN, stat_cache_entry::content_type, DIRECT, specific_config::errorfile_prefix, connection::file_finished, get_http_status_name(), HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, response::headers, http_chunk_append_buffer(), http_chunk_append_file(), HTTP_CONNECTION, HTTP_CONTENT_LENGTH, request::http_method, HTTP_METHOD_GET, HTTP_METHOD_HEAD, HTTP_METHOD_OPTIONS, HTTP_METHOD_POST, http_response_write_header(), connection::http_status, request::http_version, HTTP_VERSION_1_1, response::keep_alive, connection::keep_alive, log_error_write(), connection::mode, connection::parsed_response, request_uri::path, physical::path, connection::physical, plugins_call_handle_response_start(), buffer::ptr, connection::request, connection::response, response_header_insert(), response_header_overwrite(), stat_cache_get_entry(), server::tmp_buf, server::tmp_chunk_len, response::transfer_encoding, connection::uri, data_string::value, and connection::write_queue.
Referenced by connection_state_machine().
connection* connection_init (server * srv)
References array_init(), physical::basedir, connection::bytes_header, connection::bytes_read, connection::bytes_written, chunkqueue_init(), CLEAN, connection::cond_cache, server::config_context, config_setup_connection(), physical::doc_root, connection::environment, physical::etag, connection::fd, connection::fde_ndx, force_assert, request::headers, response::headers, connection::loops_per_request, connection::ndx, request::orig_uri, physical::path, request::pathinfo, connection::plugin_ctx, server::plugins, connection::read_queue, physical::rel_path, request::request, connection::request, connection::request_content_queue, request::request_line, connection::response, UNUSED, request::uri, array::used, buffer_plugin::used, and connection::write_queue.
Referenced by connections_get_new_connection().
static void connection_read_for_eos (server * srv, connection * con) [static]
References connection::close_timeout_ts, server::cur_ts, connection::fd, and HTTP_LINGER_TIMEOUT.
Referenced by connection_handle_close_state(), and connection_handle_fdevent().
int connection_reset (server * srv, connection * con)
References array_reset(), connection::bytes_header, connection::bytes_read, connection::bytes_written, connection::bytes_written_cur_second, chunkqueue_reset(), CLEAN, config_setup_connection(), connection_response_reset(), request::content_length, connection::environment, connection::error_handler_saved_status, connection::header_len, request::headers, request::http_if_modified_since, request::http_if_none_match, request::http_method, HTTP_METHOD_UNSET, request::http_version, HTTP_VERSION_UNSET, connection::is_readable, connection::loops_per_request, request::pathinfo, plugins_call_connection_reset(), request::request, connection::request, connection::request_content_queue, request::request_line, request::te_chunked, and request::uri.
Referenced by connection_handle_response_end_state(), connection_handle_shutdown(), connections_free(), connections_get_new_connection(), and plugins_call_init().
int connection_state_machine (server * srv, connection * con)
References array_get_unused_element(), array_insert_unique(), request_uri::authority, buffer_append_int(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_reset(), buffer_string_is_empty(), chunkqueue::bytes_in, chunkqueue_is_empty(), chunkqueue_reset(), CON_STATE_CLOSE, CON_STATE_CONNECT, CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_READ, CON_STATE_READ_POST, CON_STATE_REQUEST_END, CON_STATE_REQUEST_START, CON_STATE_RESPONSE_END, CON_STATE_RESPONSE_START, CON_STATE_WRITE, connection::conf, connection_get_state(), connection_handle_close_state(), connection_handle_errdoc_init(), connection_handle_read_state(), connection_handle_response_end_state(), connection_handle_write(), connection_handle_write_prepare(), connection_set_state(), CONST_STR_LEN, request::content_length, response::content_length, server::cur_ts, data_string_init(), DIRECT, connection::environment, specific_config::error_handler, specific_config::error_handler_404, connection::error_handler_saved_method, connection::error_handler_saved_status, server::ev, connection::fd, connection::fde_ndx, fdevent_event_get_interest, fdevent_event_set(), FDEVENT_IN, FDEVENT_OUT, FDEVENT_STREAM_REQUEST_POLLIN, fdwaitqueue_append(), connection::file_finished, connection::file_started, connection::got_response, HANDLER_COMEBACK, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, HANDLER_WAIT_FOR_FD, specific_config::high_precision_timestamps, request::http_method, HTTP_METHOD_GET, http_request_parse(), http_response_prepare(), connection::http_status, connection::is_readable, connection::is_writable, response::keep_alive, connection::keep_alive, log_clock_gettime_realtime(), log_error_write(), server_config::log_state_handling, connection::loops_per_request, connection::mode, request::orig_uri, connection::parsed_response, request_uri::path, plugins_call_connection_reset(), plugins_call_handle_subrequest(), request_uri::query, connection::read_idle_ts, connection::read_queue, connection::request, connection::request_content_queue, connection::request_count, connection::request_start, connection::request_start_hp, connection::response, server::srvconf, connection::state, specific_config::stream_request_body, specific_config::stream_response_body, connection::traffic_limit_reached, response::transfer_encoding, TYPE_STRING, request::uri, connection::uri, data_string::value, server::want_fds, connection::write_queue, and connection::write_request_ts.
Referenced by main(), network_server_handle_fdevent(), and server_oneshot_init().
void connections_free (server * srv)
References array_free(), physical::basedir, chunkqueue_free(), CLEAN, connection::cond_cache, connection_reset(), server::conns, physical::doc_root, connection::environment, physical::etag, request::headers, response::headers, request::orig_uri, physical::path, request::pathinfo, connection::plugin_ctx, connections::ptr, connection::read_queue, physical::rel_path, request::request, connection::request, connection::request_content_queue, request::request_line, connection::response, connections::size, request::uri, and connection::write_queue.
Referenced by main().
static connection* connections_get_new_connection (server * srv) [static]
References connection_init(), connection_reset(), server::conns, connection::fd, force_assert, connection::ndx, connections::ptr, connections::size, and connections::used.
Referenced by connection_accepted().