connections-glue.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `connections.h`
*
#include `joblist.h`
*
#include `log.h`
*
#include <errno.h>
*
Functions
const char * connection_get_state (connection_state_t state)
const char * connection_get_short_state (connection_state_t state)
int connection_set_state (server *srv, connection *con, connection_state_t state)
static int connection_handle_read_ssl (server *srv, connection *con)
int connection_handle_read (server *srv, connection *con)
static int connection_handle_read_post_cq_compact (chunkqueue *cq)
static int connection_handle_read_post_chunked_crlf (chunkqueue *cq)
handler_t connection_handle_read_post_error (server *srv, connection *con, int http_status)
static handler_t connection_handle_read_post_chunked (server *srv, connection *con, chunkqueue *cq, chunkqueue *dst_cq)
handler_t connection_handle_read_post_state (server *srv, connection *con)
void connection_response_reset (server *srv, connection *con)
Function Documentation
const char* connection_get_short_state (connection_state_t state)
References CON_STATE_CLOSE, CON_STATE_CONNECT, CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_READ, CON_STATE_READ_POST, CON_STATE_REQUEST_END, CON_STATE_REQUEST_START, CON_STATE_RESPONSE_END, CON_STATE_RESPONSE_START, and CON_STATE_WRITE.
Referenced by mod_status_handle_server_status_html(), and mod_status_handle_server_status_text().
const char* connection_get_state (connection_state_t state)
References CON_STATE_CLOSE, CON_STATE_CONNECT, CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_READ, CON_STATE_READ_POST, CON_STATE_REQUEST_END, CON_STATE_REQUEST_START, CON_STATE_RESPONSE_END, CON_STATE_RESPONSE_START, and CON_STATE_WRITE.
Referenced by cgi_demux_response(), cgi_recv_response(), connection_state_machine(), main(), mod_status_handle_server_status_html(), and scgi_demux_response().
int connection_handle_read (server * srv, connection * con)
References connection::bytes_read, chunkqueue_get_memory(), chunkqueue_use_memory(), CON_STATE_ERROR, connection_handle_read_ssl(), connection_set_state(), connection::fd, connection::is_readable, server_socket::is_ssl, log_error_write(), MAX_READ_LIMIT, connection::read_queue, and connection::srv_socket.
Referenced by connection_handle_read_post_state(), and connection_handle_read_state().
static handler_t connection_handle_read_post_chunked (server * srv, connection * con, chunkqueue * cq, chunkqueue * dst_cq) [static]
References buffer_string_length(), chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_mark_written(), chunkqueue_steal(), chunkqueue_steal_with_tempfiles(), connection::conf, connection_handle_read_post_chunked_crlf(), connection_handle_read_post_cq_compact(), connection_handle_read_post_error(), request::content_length, chunkqueue::first, force_assert, hex2int(), connection::keep_alive, log_error_write(), server_config::max_request_field_size, specific_config::max_request_size, chunk::mem, chunk::offset, buffer::ptr, connection::request, server::srvconf, request::te_chunked, and chunk::type.
Referenced by connection_handle_read_post_state().
static int connection_handle_read_post_chunked_crlf (chunkqueue * cq) [static]
References buffer_string_length(), chunkqueue_is_empty(), chunkqueue::first, chunk::mem, chunk::next, chunk::offset, and buffer::ptr.
Referenced by connection_handle_read_post_chunked().
static int connection_handle_read_post_cq_compact (chunkqueue * cq) [static]
References buffer_append_string_len(), buffer_string_length(), chunkqueue_remove_finished_chunks(), chunkqueue::first, force_assert, chunk::mem, chunk::next, chunk::offset, buffer::ptr, and chunk::type.
Referenced by connection_handle_read_post_chunked().
handler_t connection_handle_read_post_error (server * srv, connection * con, int http_status)
References connection::bytes_header, chunkqueue_reset(), DIRECT, HANDLER_ERROR, HANDLER_FINISHED, http_status, connection::http_status, connection::keep_alive, connection::mode, UNUSED, and connection::write_queue.
Referenced by connection_handle_read_post_chunked(), connection_handle_read_post_state(), and SUBREQUEST_FUNC().
handler_t connection_handle_read_post_state (server * srv, connection * con)
References chunkqueue::bytes_in, chunkqueue_remove_finished_chunks(), chunkqueue_steal(), chunkqueue_steal_with_tempfiles(), CON_STATE_HANDLE_REQUEST, CON_STATE_READ_POST, connection::conf, connection_handle_read(), connection_handle_read_post_chunked(), connection_handle_read_post_error(), connection_set_state(), request::content_length, server::cur_ts, FDEVENT_STREAM_REQUEST, FDEVENT_STREAM_REQUEST_POLLIN, HANDLER_ERROR, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, connection::is_readable, connection::read_idle_ts, connection::read_queue, connection::request, connection::request_content_queue, connection::state, and specific_config::stream_request_body.
Referenced by SUBREQUEST_FUNC().
static int connection_handle_read_ssl (server * srv, connection * con) [static]
References connection::bytes_read, chunkqueue_get_memory(), chunkqueue_use_memory(), CON_STATE_ERROR, connection::conf, connection_set_state(), connection::is_readable, server_socket::is_ssl, connection::is_writable, log_error_write(), specific_config::log_ssl_noise, connection::read_queue, connection::srv_socket, specific_config::ssl_disable_client_renegotiation, specific_config::ssl_read_ahead, and UNUSED.
Referenced by connection_handle_read().
void connection_response_reset (server * srv, connection * con)
References array_reset(), physical::basedir, buffer_reset(), chunkqueue_reset(), response::content_length, DIRECT, physical::doc_root, physical::etag, connection::file_finished, connection::file_started, connection::got_response, response::headers, connection::http_status, connection::is_writable, response::keep_alive, connection::mode, connection::parsed_response, physical::path, connection::physical, physical::rel_path, connection::response, response::transfer_encoding, UNUSED, and connection::write_queue.
Referenced by cgi_demux_response(), connection_reset(), and fcgi_recv_response().
int connection_set_state (server * srv, connection * con, connection_state_t state)
References connection::state, and UNUSED.
Referenced by connection_accepted(), connection_close(), connection_handle_fdevent(), connection_handle_read(), connection_handle_read_post_state(), connection_handle_read_ssl(), connection_handle_read_state(), connection_handle_response_end_state(), connection_handle_shutdown(), connection_handle_write(), connection_state_machine(), and main().