connections.h File Reference
#include `first.h`
*
#include `server.h`
*
#include `fdevent.h`
*
Functions
connection * connection_init (server *srv)
int connection_reset (server *srv, connection *con)
void connections_free (server *srv)
connection * connection_accept (server *srv, server_socket *srv_sock)
connection * connection_accepted (server *srv, server_socket *srv_socket, sock_addr *cnt_addr, int cnt)
int connection_set_state (server *srv, connection *con, connection_state_t state)
const char * connection_get_state (connection_state_t state)
const char * connection_get_short_state (connection_state_t state)
int connection_state_machine (server *srv, connection *con)
int connection_handle_read (server *srv, connection *con)
handler_t connection_handle_read_post_state (server *srv, connection *con)
handler_t connection_handle_read_post_error (server *srv, connection *con, int http_status)
void connection_response_reset (server *srv, connection *con)
Function Documentation
connection* connection_accept (server * srv, server_socket * srv_sock)
check if we can still open a new connections
see #1216
References connection_accepted(), server::conns, server_socket::fd, log_error_write(), server::max_conns, network_accept_tcp_nagle_disable(), sock_addr::plain, and connections::used.
Referenced by network_server_handle_fdevent().
connection* connection_accepted (server * srv, server_socket * srv_socket, sock_addr * cnt_addr, int cnt)
References buffer_copy_string(), server::con_opened, CON_STATE_REQUEST_START, connection_close(), connection_handle_fdevent(), connection_set_state(), connection::connection_start, connections_get_new_connection(), server::cur_fds, server::cur_ts, connection::dst_addr, connection::dst_addr_buf, server::ev, connection::fd, connection::fde_ndx, fdevent_fcntl_set_nb_cloexec_sock(), fdevent_register(), inet_ntop_cache_get_ip(), server_socket::is_ssl, log_error_write(), and connection::srv_socket.
Referenced by connection_accept(), and server_oneshot_init().
const char* connection_get_short_state (connection_state_t state)
References CON_STATE_CLOSE, CON_STATE_CONNECT, CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_READ, CON_STATE_READ_POST, CON_STATE_REQUEST_END, CON_STATE_REQUEST_START, CON_STATE_RESPONSE_END, CON_STATE_RESPONSE_START, and CON_STATE_WRITE.
Referenced by mod_status_handle_server_status_html(), and mod_status_handle_server_status_text().
const char* connection_get_state (connection_state_t state)
References CON_STATE_CLOSE, CON_STATE_CONNECT, CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_READ, CON_STATE_READ_POST, CON_STATE_REQUEST_END, CON_STATE_REQUEST_START, CON_STATE_RESPONSE_END, CON_STATE_RESPONSE_START, and CON_STATE_WRITE.
Referenced by cgi_demux_response(), cgi_recv_response(), connection_state_machine(), main(), mod_status_handle_server_status_html(), and scgi_demux_response().
int connection_handle_read (server * srv, connection * con)
References connection::bytes_read, chunkqueue_get_memory(), chunkqueue_use_memory(), CON_STATE_ERROR, connection_handle_read_ssl(), connection_set_state(), connection::fd, connection::is_readable, server_socket::is_ssl, log_error_write(), MAX_READ_LIMIT, connection::read_queue, and connection::srv_socket.
Referenced by connection_handle_read_post_state(), and connection_handle_read_state().
handler_t connection_handle_read_post_error (server * srv, connection * con, int http_status)
References connection::bytes_header, chunkqueue_reset(), DIRECT, HANDLER_ERROR, HANDLER_FINISHED, http_status, connection::http_status, connection::keep_alive, connection::mode, UNUSED, and connection::write_queue.
Referenced by connection_handle_read_post_chunked(), connection_handle_read_post_state(), and SUBREQUEST_FUNC().
handler_t connection_handle_read_post_state (server * srv, connection * con)
References chunkqueue::bytes_in, chunkqueue_remove_finished_chunks(), chunkqueue_steal(), chunkqueue_steal_with_tempfiles(), CON_STATE_HANDLE_REQUEST, CON_STATE_READ_POST, connection::conf, connection_handle_read(), connection_handle_read_post_chunked(), connection_handle_read_post_error(), connection_set_state(), request::content_length, server::cur_ts, FDEVENT_STREAM_REQUEST, FDEVENT_STREAM_REQUEST_POLLIN, HANDLER_ERROR, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, connection::is_readable, connection::read_idle_ts, connection::read_queue, connection::request, connection::request_content_queue, connection::state, and specific_config::stream_request_body.
Referenced by SUBREQUEST_FUNC().
connection* connection_init (server * srv)
References array_init(), physical::basedir, connection::bytes_header, connection::bytes_read, connection::bytes_written, chunkqueue_init(), CLEAN, connection::cond_cache, server::config_context, config_setup_connection(), physical::doc_root, connection::environment, physical::etag, connection::fd, connection::fde_ndx, force_assert, request::headers, response::headers, connection::loops_per_request, connection::ndx, request::orig_uri, physical::path, request::pathinfo, connection::plugin_ctx, server::plugins, connection::read_queue, physical::rel_path, request::request, connection::request, connection::request_content_queue, request::request_line, connection::response, UNUSED, request::uri, array::used, buffer_plugin::used, and connection::write_queue.
Referenced by connections_get_new_connection().
int connection_reset (server * srv, connection * con)
References array_reset(), connection::bytes_header, connection::bytes_read, connection::bytes_written, connection::bytes_written_cur_second, chunkqueue_reset(), CLEAN, config_setup_connection(), connection_response_reset(), request::content_length, connection::environment, connection::error_handler_saved_status, connection::header_len, request::headers, request::http_if_modified_since, request::http_if_none_match, request::http_method, HTTP_METHOD_UNSET, request::http_version, HTTP_VERSION_UNSET, connection::is_readable, connection::loops_per_request, request::pathinfo, plugins_call_connection_reset(), request::request, connection::request, connection::request_content_queue, request::request_line, request::te_chunked, and request::uri.
Referenced by connection_handle_response_end_state(), connection_handle_shutdown(), connections_free(), connections_get_new_connection(), and plugins_call_init().
void connection_response_reset (server * srv, connection * con)
References array_reset(), physical::basedir, buffer_reset(), chunkqueue_reset(), response::content_length, DIRECT, physical::doc_root, physical::etag, connection::file_finished, connection::file_started, connection::got_response, response::headers, connection::http_status, connection::is_writable, response::keep_alive, connection::mode, connection::parsed_response, physical::path, connection::physical, physical::rel_path, connection::response, response::transfer_encoding, UNUSED, and connection::write_queue.
Referenced by cgi_demux_response(), connection_reset(), and fcgi_recv_response().
int connection_set_state (server * srv, connection * con, connection_state_t state)
References connection::state, and UNUSED.
Referenced by connection_accepted(), connection_close(), connection_handle_fdevent(), connection_handle_read(), connection_handle_read_post_state(), connection_handle_read_ssl(), connection_handle_read_state(), connection_handle_response_end_state(), connection_handle_shutdown(), connection_handle_write(), connection_state_machine(), and main().
int connection_state_machine (server * srv, connection * con)
References array_get_unused_element(), array_insert_unique(), request_uri::authority, buffer_append_int(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_reset(), buffer_string_is_empty(), chunkqueue::bytes_in, chunkqueue_is_empty(), chunkqueue_reset(), CON_STATE_CLOSE, CON_STATE_CONNECT, CON_STATE_ERROR, CON_STATE_HANDLE_REQUEST, CON_STATE_READ, CON_STATE_READ_POST, CON_STATE_REQUEST_END, CON_STATE_REQUEST_START, CON_STATE_RESPONSE_END, CON_STATE_RESPONSE_START, CON_STATE_WRITE, connection::conf, connection_get_state(), connection_handle_close_state(), connection_handle_errdoc_init(), connection_handle_read_state(), connection_handle_response_end_state(), connection_handle_write(), connection_handle_write_prepare(), connection_set_state(), CONST_STR_LEN, request::content_length, response::content_length, server::cur_ts, data_string_init(), DIRECT, connection::environment, specific_config::error_handler, specific_config::error_handler_404, connection::error_handler_saved_method, connection::error_handler_saved_status, server::ev, connection::fd, connection::fde_ndx, fdevent_event_get_interest, fdevent_event_set(), FDEVENT_IN, FDEVENT_OUT, FDEVENT_STREAM_REQUEST_POLLIN, fdwaitqueue_append(), connection::file_finished, connection::file_started, connection::got_response, HANDLER_COMEBACK, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, HANDLER_WAIT_FOR_FD, specific_config::high_precision_timestamps, request::http_method, HTTP_METHOD_GET, http_request_parse(), http_response_prepare(), connection::http_status, connection::is_readable, connection::is_writable, response::keep_alive, connection::keep_alive, log_clock_gettime_realtime(), log_error_write(), server_config::log_state_handling, connection::loops_per_request, connection::mode, request::orig_uri, connection::parsed_response, request_uri::path, plugins_call_connection_reset(), plugins_call_handle_subrequest(), request_uri::query, connection::read_idle_ts, connection::read_queue, connection::request, connection::request_content_queue, connection::request_count, connection::request_start, connection::request_start_hp, connection::response, server::srvconf, connection::state, specific_config::stream_request_body, specific_config::stream_response_body, connection::traffic_limit_reached, response::transfer_encoding, TYPE_STRING, request::uri, connection::uri, data_string::value, server::want_fds, connection::write_queue, and connection::write_request_ts.
Referenced by main(), network_server_handle_fdevent(), and server_oneshot_init().
void connections_free (server * srv)
References array_free(), physical::basedir, chunkqueue_free(), CLEAN, connection::cond_cache, connection_reset(), server::conns, physical::doc_root, connection::environment, physical::etag, request::headers, response::headers, request::orig_uri, physical::path, request::pathinfo, connection::plugin_ctx, connections::ptr, connection::read_queue, physical::rel_path, request::request, connection::request, connection::request_content_queue, request::request_line, connection::response, connections::size, request::uri, and connection::write_queue.
Referenced by main().