data_fastcgi.c File Reference
#include `first.h`
*
#include `array.h`
*
#include `fastcgi.h`
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
Functions
static data_unset * data_fastcgi_copy (const data_unset *s)
static void data_fastcgi_free (data_unset *d)
static void data_fastcgi_reset (data_unset *d)
static int data_fastcgi_insert_dup (data_unset *dst, data_unset *src)
static void data_fastcgi_print (const data_unset *d, int depth)
data_fastcgi * data_fastcgi_init (void)
Function Documentation
static data_unset* data_fastcgi_copy (const data_unset * s) [static]
References buffer_copy_buffer(), data_fastcgi_init(), and data_fastcgi::host.
Referenced by data_fastcgi_init().
static void data_fastcgi_free (data_unset * d) [static]
References buffer_free(), and data_fastcgi::host.
Referenced by data_fastcgi_init().
data_fastcgi* data_fastcgi_init (void)
References buffer_init(), data_fastcgi_copy(), data_fastcgi_free(), data_fastcgi_insert_dup(), data_fastcgi_print(), data_fastcgi_reset(), force_assert, data_fastcgi::host, data_fastcgi::is_disabled, data_fastcgi::port, and TYPE_FASTCGI.
Referenced by data_fastcgi_copy().
static int data_fastcgi_insert_dup (data_unset * dst, data_unset * src) [static]
References UNUSED.
Referenced by data_fastcgi_init().
static void data_fastcgi_print (const data_unset * d, int depth) [static]
References data_fastcgi::host, buffer::ptr, and UNUSED.
Referenced by data_fastcgi_init().
static void data_fastcgi_reset (data_unset * d) [static]
References buffer_reset(), and data_fastcgi::host.
Referenced by data_fastcgi_init().