data_config.c File Reference
#include `first.h`
*
#include `array.h`
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
Functions
static data_unset * data_config_copy (const data_unset *s)
static void data_config_free (data_unset *d)
static void data_config_reset (data_unset *d)
static int data_config_insert_dup (data_unset *dst, data_unset *src)
static void data_config_print (const data_unset *d, int depth)
data_config * data_config_init (void)
Function Documentation
static data_unset* data_config_copy (const data_unset * s) [static]
References array_free(), array_init_array(), buffer_copy_buffer(), data_config::comp_key, data_config_init(), and data_config::value.
Referenced by data_config_init().
static void data_config_free (data_unset * d) [static]
References array_free(), buffer_free(), data_config::children, data_config::comp_key, data_config::op, data_config::string, and data_config::value.
Referenced by data_config_init().
data_config* data_config_init (void)
References array_init(), buffer_init(), data_config::children, data_config::comp_key, data_config_copy(), data_config_free(), data_config_insert_dup(), data_config_print(), data_config_reset(), data_config::op, TYPE_CONFIG, and data_config::value.
Referenced by config_read(), data_config_copy(), and yy_reduce().
static int data_config_insert_dup (data_unset * dst, data_unset * src) [static]
References UNUSED.
Referenced by data_config_init().
static void data_config_print (const data_unset * d, int depth) [static]
References array_get_max_key_length(), array_print_indent(), data_config::children, data_config::comp_key, data_config::cond, CONFIG_COND_ELSE, data_config::context_ndx, array::data, data_config::next, data_config::op, data_config::prev, buffer::ptr, data_config::string, array::used, and data_config::value.
Referenced by data_config_init().
static void data_config_reset (data_unset * d) [static]
References array_reset(), buffer_reset(), data_config::comp_key, and data_config::value.
Referenced by data_config_init().