data_array.c File Reference
#include `first.h`
*
#include `array.h`
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
Functions
static data_unset * data_array_copy (const data_unset *s)
static void data_array_free (data_unset *d)
static void data_array_reset (data_unset *d)
static int data_array_insert_dup (data_unset *dst, data_unset *src)
static void data_array_print (const data_unset *d, int depth)
data_array * data_array_init (void)
Function Documentation
static data_unset* data_array_copy (const data_unset * s) [static]
References array_free(), array_init_array(), buffer_copy_buffer(), data_array_init(), and data_array::value.
Referenced by data_array_init().
static void data_array_free (data_unset * d) [static]
References array_free(), buffer_free(), and data_array::value.
Referenced by data_array_init().
data_array* data_array_init (void)
References array_init(), buffer_init(), data_array_copy(), data_array_free(), data_array_insert_dup(), data_array_print(), data_array_reset(), force_assert, TYPE_ARRAY, and data_array::value.
Referenced by data_array_copy(), SETDEFAULTS_FUNC(), and yy_reduce().
static int data_array_insert_dup (data_unset * dst, data_unset * src) [static]
References UNUSED.
Referenced by data_array_init().
static void data_array_print (const data_unset * d, int depth) [static]
References array_print(), and data_array::value.
Referenced by data_array_init().
static void data_array_reset (data_unset * d) [static]
References array_reset(), buffer_reset(), and data_array::value.
Referenced by data_array_init().