data_string.c File Reference
#include `first.h`
*
#include `array.h`
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <assert.h>
*
Functions
static data_unset * data_string_copy (const data_unset *s)
static void data_string_free (data_unset *d)
static void data_string_reset (data_unset *d)
static int data_string_insert_dup (data_unset *dst, data_unset *src)
static int data_response_insert_dup (data_unset *dst, data_unset *src)
static void data_string_print (const data_unset *d, int depth)
data_string * data_string_init (void)
data_string * data_response_init (void)
Function Documentation
data_string* data_response_init (void)
References data_response_insert_dup(), and data_string_init().
Referenced by cgi_response_parse(), fcgi_response_parse(), proxy_response_parse(), response_header_insert(), scgi_response_parse(), and URIHANDLER_FUNC().
static int data_response_insert_dup (data_unset * dst, data_unset * src) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_is_empty(), CONST_STR_LEN, and data_string::value.
Referenced by data_response_init().
static data_unset* data_string_copy (const data_unset * s) [static]
References buffer_copy_buffer(), data_string_init(), and data_string::value.
Referenced by data_string_init().
static void data_string_free (data_unset * d) [static]
References buffer_free(), and data_string::value.
Referenced by data_string_init().
data_string* data_string_init (void)
References buffer_init(), data_string_copy(), data_string_free(), data_string_insert_dup(), data_string_print(), data_string_reset(), force_assert, TYPE_STRING, and data_string::value.
Referenced by array_set_key_value(), config_insert(), config_insert_values_global(), config_read(), config_set_defaults(), configparser_merge_data(), connection_state_machine(), data_response_init(), data_string_copy(), http_auth_setenv(), http_request_parse(), http_request_split_value(), mod_auth_require_parse(), mod_evhost_parse_host(), process_ssi_stmt(), proxy_append_header(), proxy_set_header(), put_string_into_array_len(), split_get_params(), ssi_env_add(), URIHANDLER_FUNC(), and yy_reduce().
static int data_string_insert_dup (data_unset * dst, data_unset * src) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_is_empty(), CONST_STR_LEN, and data_string::value.
Referenced by data_string_init().
static void data_string_print (const data_unset * d, int depth) [static]
References buffer_string_is_empty(), buffer_string_length(), buffer::ptr, UNUSED, and data_string::value.
Referenced by data_string_init().
static void data_string_reset (data_unset * d) [static]
References buffer_reset(), and data_string::value.
Referenced by data_string_init().