data_integer.c File Reference
#include `first.h`
*
#include `array.h`
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Functions
static data_unset * data_integer_copy (const data_unset *s)
static void data_integer_free (data_unset *d)
static void data_integer_reset (data_unset *d)
static int data_integer_insert_dup (data_unset *dst, data_unset *src)
static void data_integer_print (const data_unset *d, int depth)
data_integer * data_integer_init (void)
Function Documentation
static data_unset* data_integer_copy (const data_unset * s) [static]
References buffer_copy_buffer(), data_integer_init(), and data_integer::value.
Referenced by data_integer_init().
static void data_integer_free (data_unset * d) [static]
References buffer_free().
Referenced by data_integer_init().
data_integer* data_integer_init (void)
References buffer_init(), data_integer_copy(), data_integer_free(), data_integer_insert_dup(), data_integer_print(), data_integer_reset(), force_assert, TYPE_INTEGER, and data_integer::value.
Referenced by config_read(), data_integer_copy(), status_counter_get_counter(), and yy_reduce().
static int data_integer_insert_dup (data_unset * dst, data_unset * src) [static]
References UNUSED.
Referenced by data_integer_init().
static void data_integer_print (const data_unset * d, int depth) [static]
References UNUSED, and data_integer::value.
Referenced by data_integer_init().
static void data_integer_reset (data_unset * d) [static]
References buffer_reset(), and data_integer::value.
Referenced by data_integer_init().