etag.h File Reference
#include `first.h`
*
#include `buffer.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <unistd.h>
*
Enumerations
enum etag_flags_t { ETAG_USE_INODE = 1,
ETAG_USE_MTIME = 2,
ETAG_USE_SIZE = 4
 }
Functions
int etag_is_equal (buffer *etag, const char *matches, int weak_ok)
int etag_create (buffer *etag, struct stat *st, etag_flags_t flags)
int etag_mutate (buffer *mut, buffer *etag)
Enumeration Type Documentation
enum etag_flags_t
Enumerator
ETAG_USE_INODE
ETAG_USE_MTIME
ETAG_USE_SIZE
Function Documentation
int etag_create (buffer * etag, struct stat * st, etag_flags_t flags)
References buffer_append_int(), buffer_append_string_len(), buffer_reset(), CONST_STR_LEN, ETAG_USE_INODE, ETAG_USE_MTIME, and ETAG_USE_SIZE.
Referenced by mod_ssi_handle_request(), stat_cache_get_entry(), and webdav_get_live_property().
int etag_is_equal (buffer * etag, const char * matches, int weak_ok)
References buffer_string_is_empty(), current, and buffer::ptr.
Referenced by http_response_handle_cachable().
int etag_mutate (buffer * mut, buffer * etag)
References buffer_append_int(), buffer_append_string_len(), buffer_copy_string_len(), buffer_reset(), buffer_string_length(), CONST_STR_LEN, buffer::ptr, and uint32_t.
Referenced by http_response_send_file(), magnet_stat(), and PHYSICALPATH_FUNC().