fdevent.h File Reference
#include `first.h`
*
#include `settings.h`
*
#include <sys/types.h>
*
Classes
struct _fdnode
struct buffer_int
struct fdevents
Macros
#define FDEVENT_IN BV(0)
#define FDEVENT_PRI BV(1)
#define FDEVENT_OUT BV(2)
#define FDEVENT_ERR BV(3)
#define FDEVENT_HUP BV(4)
#define FDEVENT_NVAL BV(5)
#define FDEVENT_STREAM_REQUEST BV(0)
#define FDEVENT_STREAM_REQUEST_BUFMIN BV(1)
#define FDEVENT_STREAM_REQUEST_POLLIN BV(15)
#define FDEVENT_STREAM_RESPONSE BV(0)
#define FDEVENT_STREAM_RESPONSE_BUFMIN BV(1)
#define fdevent_event_get_interest(ev, fd) ((fd) >= 0 ? (ev)->fdarray[(fd)]->events : 0)
Typedefs
typedef handler_t(* fdevent_handler)(struct server *srv, void *ctx, int revents)
typedef struct _fdnode fdnode
typedef struct fdevents fdevents
Enumerations
enum fd_event_t {
*
FD_EVENT_TYPE_UNSET = -1,
FD_EVENT_TYPE_CONNECTION,
FD_EVENT_TYPE_FCGI_CONNECTION,
FD_EVENT_TYPE_DIRWATCH,
*
FD_EVENT_TYPE_CGI_CONNECTION
 }
enum fdevent_handler_t {
*
FDEVENT_HANDLER_UNSET,
FDEVENT_HANDLER_SELECT,
FDEVENT_HANDLER_POLL,
FDEVENT_HANDLER_LINUX_SYSEPOLL,
*
FDEVENT_HANDLER_SOLARIS_DEVPOLL,
FDEVENT_HANDLER_SOLARIS_PORT,
FDEVENT_HANDLER_FREEBSD_KQUEUE,
FDEVENT_HANDLER_LIBEV
 }
Functions
fdevents * fdevent_init (struct server *srv, size_t maxfds, fdevent_handler_t type)
int fdevent_reset (fdevents *ev)
void fdevent_free (fdevents *ev)
void fdevent_event_set (fdevents *ev, int *fde_ndx, int fd, int events)
void fdevent_event_add (fdevents *ev, int *fde_ndx, int fd, int event)
void fdevent_event_clr (fdevents *ev, int *fde_ndx, int fd, int event)
void fdevent_event_del (fdevents *ev, int *fde_ndx, int fd)
int fdevent_event_get_revent (fdevents *ev, size_t ndx)
int fdevent_event_get_fd (fdevents *ev, size_t ndx)
fdevent_handler fdevent_get_handler (fdevents *ev, int fd)
void * fdevent_get_context (fdevents *ev, int fd)
int fdevent_event_next_fdndx (fdevents *ev, int ndx)
int fdevent_poll (fdevents *ev, int timeout_ms)
int fdevent_register (fdevents *ev, int fd, fdevent_handler handler, void *ctx)
int fdevent_unregister (fdevents *ev, int fd)
void fdevent_sched_close (fdevents *ev, int fd, int issock)
void fdevent_sched_run (struct server *srv, fdevents *ev)
void fd_close_on_exec (int fd)
int fdevent_fcntl_set (fdevents *ev, int fd)
int fdevent_fcntl_set_nb (fdevents *ev, int fd)
int fdevent_fcntl_set_nb_cloexec (fdevents *ev, int fd)
int fdevent_fcntl_set_nb_cloexec_sock (fdevents *ev, int fd)
int fdevent_socket_cloexec (int domain, int type, int protocol)
int fdevent_socket_nb_cloexec (int domain, int type, int protocol)
int fdevent_open_cloexec (const char *pathname, int flags, mode_t mode)
int fdevent_select_init (fdevents *ev)
int fdevent_poll_init (fdevents *ev)
int fdevent_linux_sysepoll_init (fdevents *ev)
int fdevent_solaris_devpoll_init (fdevents *ev)
int fdevent_solaris_port_init (fdevents *ev)
int fdevent_freebsd_kqueue_init (fdevents *ev)
int fdevent_libev_init (fdevents *ev)
int fdevent_is_tcp_half_closed (int fd)
Macro Definition Documentation
#define FDEVENT_ERR BV(3)
Referenced by cgi_handle_fdevent(), cgi_handle_fdevent_send(), connection_handle_fdevent(), fcgi_handle_fdevent(), proxy_handle_fdevent(), and scgi_handle_fdevent().
#define fdevent_event_get_interest(ev, fd) ((fd) >= 0 ? (ev)->fdarray[(fd)]->events : 0)
Referenced by cgi_write_request(), connection_state_machine(), main(), and SUBREQUEST_FUNC().
#define FDEVENT_HUP BV(4)
Referenced by cgi_handle_fdevent(), cgi_handle_fdevent_send(), connection_handle_fdevent(), fcgi_handle_fdevent(), proxy_handle_fdevent(), and scgi_handle_fdevent().
#define FDEVENT_IN BV(0)
Referenced by cgi_create_env(), cgi_demux_response(), cgi_handle_fdevent(), connection_handle_fdevent(), connection_state_machine(), fcgi_demux_response(), fcgi_handle_fdevent(), fcgi_write_request(), main(), network_register_fdevents(), network_server_handle_fdevent(), proxy_demux_response(), proxy_handle_fdevent(), proxy_write_request(), scgi_demux_response(), scgi_handle_fdevent(), scgi_write_request(), and SUBREQUEST_FUNC().
#define FDEVENT_NVAL BV(5)
#define FDEVENT_OUT BV(2)
Referenced by cgi_handle_fdevent_send(), cgi_write_request(), connection_handle_fdevent(), connection_state_machine(), fcgi_handle_fdevent(), fcgi_write_request(), proxy_handle_fdevent(), proxy_write_request(), scgi_handle_fdevent(), scgi_write_request(), and SUBREQUEST_FUNC().
#define FDEVENT_PRI BV(1)
#define FDEVENT_STREAM_REQUEST BV(0)
Referenced by config_insert(), and connection_handle_read_post_state().
#define FDEVENT_STREAM_REQUEST_BUFMIN BV(1)
Referenced by config_insert(), and SUBREQUEST_FUNC().
#define FDEVENT_STREAM_REQUEST_POLLIN BV(15)
Referenced by cgi_write_request(), connection_handle_read_post_state(), connection_state_machine(), fcgi_write_request(), proxy_write_request(), scgi_write_request(), and SUBREQUEST_FUNC().
#define FDEVENT_STREAM_RESPONSE BV(0)
Referenced by config_insert().
#define FDEVENT_STREAM_RESPONSE_BUFMIN BV(1)
Referenced by cgi_demux_response(), config_insert(), fcgi_demux_response(), http_chunk_append_data(), proxy_demux_response(), scgi_demux_response(), and SUBREQUEST_FUNC().
Typedef Documentation
typedef handler_t(* fdevent_handler)(struct server *srv, void *ctx, int revents)
typedef struct fdevents fdevents
fd-event handler for select(), poll() and rt-signals on Linux 2.4
typedef struct _fdnode fdnode
Enumeration Type Documentation
enum fd_event_t
Enumerator
FD_EVENT_TYPE_UNSET
FD_EVENT_TYPE_CONNECTION
FD_EVENT_TYPE_FCGI_CONNECTION
FD_EVENT_TYPE_DIRWATCH
FD_EVENT_TYPE_CGI_CONNECTION
enum fdevent_handler_t
Enumerator
FDEVENT_HANDLER_UNSET
FDEVENT_HANDLER_SELECT
FDEVENT_HANDLER_POLL
FDEVENT_HANDLER_LINUX_SYSEPOLL
FDEVENT_HANDLER_SOLARIS_DEVPOLL
FDEVENT_HANDLER_SOLARIS_PORT
FDEVENT_HANDLER_FREEBSD_KQUEUE
FDEVENT_HANDLER_LIBEV
Function Documentation
void fd_close_on_exec (int fd)
References force_assert, and UNUSED.
Referenced by chunkqueue_get_append_tempfile(), fdevent_fcntl_set_nb_cloexec(), log_error_cycle(), log_error_open(), main(), mod_rrd_create_pipe(), open_logfile_or_pipe(), SERVER_FUNC(), and SETDEFAULTS_FUNC().
void fdevent_event_add (fdevents * ev, int * fde_ndx, int fd, int event)
References fdevents::event_set, _fdnode::events, and fdevents::fdarray.
Referenced by cgi_demux_response(), fcgi_demux_response(), fcgi_write_request(), proxy_demux_response(), proxy_write_request(), scgi_demux_response(), and scgi_write_request().
void fdevent_event_clr (fdevents * ev, int * fde_ndx, int fd, int event)
References fdevents::event_set, _fdnode::events, and fdevents::fdarray.
Referenced by cgi_demux_response(), fcgi_demux_response(), fcgi_write_request(), proxy_demux_response(), proxy_write_request(), scgi_demux_response(), scgi_write_request(), and SUBREQUEST_FUNC().
void fdevent_event_del (fdevents * ev, int * fde_ndx, int fd)
References fdevents::event_del, _fdnode::events, and fdevents::fdarray.
Referenced by cgi_connection_close(), cgi_connection_close_fdtocgi(), connection_close(), fcgi_backend_close(), main(), network_close(), network_server_init(), proxy_backend_close(), and scgi_backend_close().
int fdevent_event_get_fd (fdevents * ev, size_t ndx)
References fdevents::event_get_fd, and SEGFAULT.
Referenced by main().
int fdevent_event_get_revent (fdevents * ev, size_t ndx)
References fdevents::event_get_revent, and SEGFAULT.
Referenced by main().
int fdevent_event_next_fdndx (fdevents * ev, int ndx)
References fdevents::event_next_fdndx.
Referenced by main().
void fdevent_event_set (fdevents * ev, int * fde_ndx, int fd, int events)
References fdevents::event_set, _fdnode::events, and fdevents::fdarray.
Referenced by cgi_create_env(), cgi_write_request(), connection_state_machine(), fcgi_write_request(), main(), network_register_fdevents(), proxy_write_request(), and scgi_write_request().
int fdevent_fcntl_set (fdevents * ev, int fd)
References fdevents::fcntl_set.
Referenced by fcgi_write_request(), proxy_write_request(), and scgi_write_request().
int fdevent_fcntl_set_nb (fdevents * ev, int fd)
References fdevents::fcntl_set, and O_NONBLOCK.
Referenced by cgi_create_env(), fdevent_fcntl_set_nb_cloexec(), and network_server_init().
int fdevent_fcntl_set_nb_cloexec (fdevents * ev, int fd)
References fd_close_on_exec(), and fdevent_fcntl_set_nb().
Referenced by fdevent_fcntl_set_nb_cloexec_sock().
int fdevent_fcntl_set_nb_cloexec_sock (fdevents * ev, int fd)
References fdevents::fcntl_set, and fdevent_fcntl_set_nb_cloexec().
Referenced by connection_accepted(), and main().
void fdevent_free (fdevents * ev)
References fdevents::fdarray, fdevents::free, and fdevents::maxfds.
Referenced by server_free().
int fdevent_freebsd_kqueue_init (fdevents * ev)
References log_error_write(), fdevents::srv, and UNUSED.
Referenced by fdevent_init().
void* fdevent_get_context (fdevents * ev, int fd)
References _fdnode::ctx, _fdnode::fd, fdevents::fdarray, and SEGFAULT.
Referenced by main().
fdevent_handler fdevent_get_handler (fdevents * ev, int fd)
References _fdnode::fd, fdevents::fdarray, _fdnode::handler, and SEGFAULT.
Referenced by main().
fdevents* fdevent_init (struct server * srv, size_t maxfds, fdevent_handler_t type)
References fdevents::fdarray, fdevent_freebsd_kqueue_init(), FDEVENT_HANDLER_FREEBSD_KQUEUE, FDEVENT_HANDLER_LIBEV, FDEVENT_HANDLER_LINUX_SYSEPOLL, FDEVENT_HANDLER_POLL, FDEVENT_HANDLER_SELECT, FDEVENT_HANDLER_SOLARIS_DEVPOLL, FDEVENT_HANDLER_SOLARIS_PORT, FDEVENT_HANDLER_UNSET, fdevent_libev_init(), fdevent_linux_sysepoll_init(), fdevent_poll_init(), fdevent_select_init(), fdevent_solaris_devpoll_init(), fdevent_solaris_port_init(), force_assert, fdevents::highfd, log_error_write(), fdevents::maxfds, and fdevents::srv.
Referenced by main().
int fdevent_is_tcp_half_closed (int fd)
References UNUSED.
Referenced by connection_handle_fdevent().
int fdevent_libev_init (fdevents * ev)
References log_error_write(), fdevents::srv, and UNUSED.
Referenced by fdevent_init().
int fdevent_linux_sysepoll_init (fdevents * ev)
References log_error_write(), fdevents::srv, and UNUSED.
Referenced by fdevent_init().
int fdevent_open_cloexec (const char * pathname, int flags, mode_t mode)
References O_NOCTTY.
Referenced by cgi_write_file_chunk_mmap(), li_rand_device_bytes(), main(), mod_deflate_file_chunk(), network_open_file_chunk(), and SIGHUP_FUNC().
int fdevent_poll (fdevents * ev, int timeout_ms)
References fdevents::poll, and SEGFAULT.
Referenced by main().
int fdevent_poll_init (fdevents * ev)
References log_error_write(), fdevents::srv, and UNUSED.
Referenced by fdevent_init().
int fdevent_register (fdevents * ev, int fd, fdevent_handler handler, void * ctx)
References _fdnode::ctx, _fdnode::events, _fdnode::fd, fdevents::fdarray, fdnode_init(), _fdnode::handler, and _fdnode::handler_ctx.
Referenced by cgi_create_env(), cgi_write_request(), connection_accepted(), fcgi_write_request(), main(), network_register_fdevents(), proxy_write_request(), and scgi_write_request().
int fdevent_reset (fdevents * ev)
References fdevents::reset.
Referenced by network_register_fdevents().
void fdevent_sched_close (fdevents * ev, int fd, int issock)
References fdevents::fdarray, and fdevents::highfd.
Referenced by cgi_connection_close(), cgi_connection_close_fdtocgi(), fcgi_backend_close(), proxy_backend_close(), and scgi_backend_close().
void fdevent_sched_run (struct server * srv, fdevents * ev)
References server::cur_fds, fdevents::fdarray, fdevents::highfd, and log_error_write().
Referenced by main().
int fdevent_select_init (fdevents * ev)
References UNUSED.
Referenced by fdevent_init().
int fdevent_socket_cloexec (int domain, int type, int protocol)
Referenced by network_server_init().
int fdevent_socket_nb_cloexec (int domain, int type, int protocol)
References O_NONBLOCK.
Referenced by fcgi_write_request(), network_server_init(), proxy_write_request(), and scgi_write_request().
int fdevent_solaris_devpoll_init (fdevents * ev)
References log_error_write(), fdevents::srv, and UNUSED.
Referenced by fdevent_init().
int fdevent_solaris_port_init (fdevents * ev)
References log_error_write(), fdevents::srv, and UNUSED.
Referenced by fdevent_init().
int fdevent_unregister (fdevents * ev, int fd)
References fdevents::fdarray, and fdnode_free().
Referenced by cgi_connection_close(), cgi_connection_close_fdtocgi(), connection_close(), fcgi_backend_close(), main(), network_close(), network_server_init(), proxy_backend_close(), scgi_backend_close(), and server_free().