http_auth.h File Reference
#include `first.h`
*
#include `base.h`
*
Classes
struct http_auth_require_t
struct http_auth_backend_t
struct http_auth_scheme_t
Typedefs
typedef struct http_auth_require_t http_auth_require_t
typedef struct http_auth_backend_t http_auth_backend_t
typedef struct http_auth_scheme_t http_auth_scheme_t
Functions
http_auth_require_t * http_auth_require_init (void)
void http_auth_require_free (http_auth_require_t *require)
int http_auth_match_rules (const http_auth_require_t *require, const char *user, const char *group, const char *host)
const http_auth_scheme_t * http_auth_scheme_get (const buffer *name)
void http_auth_scheme_set (const http_auth_scheme_t *scheme)
const http_auth_backend_t * http_auth_backend_get (const buffer *name)
void http_auth_backend_set (const http_auth_backend_t *backend)
void http_auth_setenv (array *env, const char *username, size_t ulen, const char *auth_type, size_t alen)
int http_auth_md5_hex2bin (const char *md5hex, size_t len, unsigned char md5bin[16])
Typedef Documentation
typedef struct http_auth_backend_t http_auth_backend_t
typedef struct http_auth_require_t http_auth_require_t
typedef struct http_auth_scheme_t http_auth_scheme_t
Function Documentation
const http_auth_backend_t* http_auth_backend_get (const buffer * name)
References buffer::ptr.
Referenced by SETDEFAULTS_FUNC().
void http_auth_backend_set (const http_auth_backend_t * backend)
References force_assert.
Referenced by INIT_FUNC().
int http_auth_match_rules (const http_auth_require_t * require, const char * user, const char * group, const char * host)
References http_auth_require_t::group, http_auth_require_t::host, http_auth_array_contains(), http_auth_require_t::user, and http_auth_require_t::valid_user.
Referenced by mod_auth_check_digest(), mod_auth_check_extern(), mod_authn_file_htdigest_basic(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_ldap_basic(), and mod_authn_mysql_basic().
int http_auth_md5_hex2bin (const char * md5hex, size_t len, unsigned char md5bin[16])
Referenced by mod_authn_file_htdigest_get(), mod_authn_mysql_password_cmp(), and mod_authn_mysql_result().
void http_auth_require_free (http_auth_require_t * require)
References array_free(), buffer_free(), http_auth_require_t::group, http_auth_require_t::host, http_auth_require_t::realm, and http_auth_require_t::user.
Referenced by data_auth_free().
http_auth_require_t* http_auth_require_init (void)
References array_init(), buffer_init(), force_assert, http_auth_require_t::group, http_auth_require_t::host, http_auth_require_t::realm, http_auth_require_t::user, and http_auth_require_t::valid_user.
Referenced by data_auth_init().
const http_auth_scheme_t* http_auth_scheme_get (const buffer * name)
References buffer::ptr.
Referenced by SETDEFAULTS_FUNC().
void http_auth_scheme_set (const http_auth_scheme_t * scheme)
References force_assert.
Referenced by INIT_FUNC().
void http_auth_setenv (array * env, const char * username, size_t ulen, const char * auth_type, size_t alen)
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), CONST_STR_LEN, data_string_init(), TYPE_STRING, and data_string::value.
Referenced by mod_auth_check_basic(), mod_auth_check_digest(), and mod_authn_gssapi_check_spnego().