http_chunk.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `chunk.h`
*
#include `http_chunk.h`
*
#include `stat_cache.h`
*
#include `log.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <stdlib.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <stdio.h>
*
#include <errno.h>
*
#include <string.h>
*
Functions
static void http_chunk_append_len (server *srv, connection *con, uintmax_t len)
static int http_chunk_append_file_open_fstat (server *srv, connection *con, buffer *fn, struct stat *st)
static void http_chunk_append_file_fd_range (server *srv, connection *con, buffer *fn, int fd, off_t offset, off_t len)
int http_chunk_append_file_range (server *srv, connection *con, buffer *fn, off_t offset, off_t len)
int http_chunk_append_file (server *srv, connection *con, buffer *fn)
static int http_chunk_append_to_tempfile (server *srv, connection *con, const char *mem, size_t len)
static int http_chunk_append_data (server *srv, connection *con, buffer *b, const char *mem, size_t len)
int http_chunk_append_buffer (server *srv, connection *con, buffer *mem)
int http_chunk_append_mem (server *srv, connection *con, const char *mem, size_t len)
void http_chunk_close (server *srv, connection *con)
Function Documentation
int http_chunk_append_buffer (server * srv, connection * con, buffer * mem)
References buffer_string_length(), force_assert, and http_chunk_append_data().
Referenced by cgi_demux_response(), cgi_handle_fdevent(), connection_handle_write_prepare(), fcgi_demux_response(), proxy_demux_response(), and scgi_demux_response().
static int http_chunk_append_data (server * srv, connection * con, buffer * b, const char * mem, size_t len) [static]
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_append_buffer(), chunkqueue_append_mem(), connection::conf, CONST_STR_LEN, FDEVENT_STREAM_RESPONSE_BUFMIN, chunk::file, http_chunk_append_len(), http_chunk_append_to_tempfile(), chunk::is_temp, chunkqueue::last, buffer::ptr, connection::response, specific_config::stream_response_body, response::transfer_encoding, chunk::type, and connection::write_queue.
Referenced by http_chunk_append_buffer(), and http_chunk_append_mem().
int http_chunk_append_file (server * srv, connection * con, buffer * fn)
References http_chunk_append_file_fd_range(), and http_chunk_append_file_open_fstat().
Referenced by connection_handle_write_prepare(), and http_response_send_file().
static void http_chunk_append_file_fd_range (server * srv, connection * con, buffer * fn, int fd, off_t offset, off_t len) [static]
References chunkqueue_append_file_fd(), chunkqueue_append_mem(), CONST_STR_LEN, http_chunk_append_len(), connection::response, response::transfer_encoding, and connection::write_queue.
Referenced by http_chunk_append_file(), and http_chunk_append_file_range().
static int http_chunk_append_file_open_fstat (server * srv, connection * con, buffer * fn, struct stat * st) [static]
References connection::conf, specific_config::follow_symlink, HANDLER_ERROR, stat_cache_get_entry(), and stat_cache_open_rdonly_fstat().
Referenced by http_chunk_append_file(), and http_chunk_append_file_range().
int http_chunk_append_file_range (server * srv, connection * con, buffer * fn, off_t offset, off_t len)
References http_chunk_append_file_fd_range(), and http_chunk_append_file_open_fstat().
Referenced by fcgi_response_parse(), magnet_attach_content(), and URIHANDLER_FUNC().
static void http_chunk_append_len (server * srv, connection * con, uintmax_t len) [static]
the HTTP chunk-API
References buffer_append_string_len(), buffer_append_uint_hex(), buffer_string_set_length(), chunkqueue_append_buffer(), CONST_STR_LEN, force_assert, server::tmp_chunk_len, and connection::write_queue.
Referenced by http_chunk_append_data(), and http_chunk_append_file_fd_range().
int http_chunk_append_mem (server * srv, connection * con, const char * mem, size_t len)
References force_assert, and http_chunk_append_data().
Referenced by cgi_demux_response(), proxy_demux_response(), scgi_demux_response(), and URIHANDLER_FUNC().
static int http_chunk_append_to_tempfile (server * srv, connection * con, const char * mem, size_t len) [static]
References buffer_append_string_len(), buffer_append_uint_hex(), buffer_string_set_length(), chunkqueue_append_mem_to_tempfile(), CONST_BUF_LEN, CONST_STR_LEN, connection::response, server::tmp_chunk_len, response::transfer_encoding, and connection::write_queue.
Referenced by http_chunk_append_data().
void http_chunk_close (server * srv, connection * con)
References chunkqueue_append_mem(), CONST_STR_LEN, force_assert, connection::response, response::transfer_encoding, UNUSED, and connection::write_queue.
Referenced by http_response_backend_done().