http_auth.c File Reference
#include `first.h`
*
#include `http_auth.h`
*
#include <string.h>
*
Functions
const http_auth_scheme_t * http_auth_scheme_get (const buffer *name)
void http_auth_scheme_set (const http_auth_scheme_t *scheme)
const http_auth_backend_t * http_auth_backend_get (const buffer *name)
void http_auth_backend_set (const http_auth_backend_t *backend)
http_auth_require_t * http_auth_require_init (void)
void http_auth_require_free (http_auth_require_t *const require)
static int http_auth_array_contains (const array *const a, const char *const k, const size_t klen)
int http_auth_match_rules (const http_auth_require_t *const require, const char *const user, const char *const group, const char *const host)
void http_auth_setenv (array *env, const char *username, size_t ulen, const char *auth_type, size_t alen)
int http_auth_md5_hex2bin (const char *md5hex, size_t len, unsigned char md5bin[16])
Variables
static http_auth_scheme_t http_auth_schemes [8]
static http_auth_backend_t http_auth_backends [8]
Function Documentation
static int http_auth_array_contains (const array *const a, const char *const k, const size_t klen) [static]
References buffer_is_equal_string(), array::data, and array::used.
Referenced by http_auth_match_rules().
const http_auth_backend_t* http_auth_backend_get (const buffer * name)
References buffer::ptr.
Referenced by SETDEFAULTS_FUNC().
void http_auth_backend_set (const http_auth_backend_t * backend)
References force_assert.
Referenced by INIT_FUNC().
int http_auth_match_rules (const http_auth_require_t *const require, const char *const user, const char *const group, const char *const host)
References http_auth_require_t::group, http_auth_require_t::host, http_auth_array_contains(), http_auth_require_t::user, and http_auth_require_t::valid_user.
Referenced by mod_auth_check_digest(), mod_auth_check_extern(), mod_authn_file_htdigest_basic(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_ldap_basic(), and mod_authn_mysql_basic().
int http_auth_md5_hex2bin (const char * md5hex, size_t len, unsigned char md5bin[16])
Referenced by mod_authn_file_htdigest_get(), mod_authn_mysql_password_cmp(), and mod_authn_mysql_result().
void http_auth_require_free (http_auth_require_t *const require)
References array_free(), buffer_free(), http_auth_require_t::group, http_auth_require_t::host, http_auth_require_t::realm, and http_auth_require_t::user.
Referenced by data_auth_free().
http_auth_require_t* http_auth_require_init (void)
References array_init(), buffer_init(), force_assert, http_auth_require_t::group, http_auth_require_t::host, http_auth_require_t::realm, http_auth_require_t::user, and http_auth_require_t::valid_user.
Referenced by data_auth_init().
const http_auth_scheme_t* http_auth_scheme_get (const buffer * name)
References buffer::ptr.
Referenced by SETDEFAULTS_FUNC().
void http_auth_scheme_set (const http_auth_scheme_t * scheme)
References force_assert.
Referenced by INIT_FUNC().
void http_auth_setenv (array * env, const char * username, size_t ulen, const char * auth_type, size_t alen)
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), CONST_STR_LEN, data_string_init(), TYPE_STRING, and data_string::value.
Referenced by mod_auth_check_basic(), mod_auth_check_digest(), and mod_authn_gssapi_check_spnego().
Variable Documentation
http_auth_backend_t http_auth_backends[8] [static]
http_auth_scheme_t http_auth_schemes[8] [static]