http_chunk.h File Reference
#include `first.h`
*
#include `server.h`
*
#include <sys/types.h>
*
Functions
int http_chunk_append_mem (server *srv, connection *con, const char *mem, size_t len)
int http_chunk_append_buffer (server *srv, connection *con, buffer *mem)
int http_chunk_append_file (server *srv, connection *con, buffer *fn)
int http_chunk_append_file_range (server *srv, connection *con, buffer *fn, off_t offset, off_t len)
void http_chunk_close (server *srv, connection *con)
Function Documentation
int http_chunk_append_buffer (server * srv, connection * con, buffer * mem)
References buffer_string_length(), force_assert, and http_chunk_append_data().
Referenced by cgi_demux_response(), cgi_handle_fdevent(), connection_handle_write_prepare(), fcgi_demux_response(), proxy_demux_response(), and scgi_demux_response().
int http_chunk_append_file (server * srv, connection * con, buffer * fn)
References http_chunk_append_file_fd_range(), and http_chunk_append_file_open_fstat().
Referenced by connection_handle_write_prepare(), and http_response_send_file().
int http_chunk_append_file_range (server * srv, connection * con, buffer * fn, off_t offset, off_t len)
References http_chunk_append_file_fd_range(), and http_chunk_append_file_open_fstat().
Referenced by fcgi_response_parse(), magnet_attach_content(), and URIHANDLER_FUNC().
int http_chunk_append_mem (server * srv, connection * con, const char * mem, size_t len)
References force_assert, and http_chunk_append_data().
Referenced by cgi_demux_response(), proxy_demux_response(), scgi_demux_response(), and URIHANDLER_FUNC().
void http_chunk_close (server * srv, connection * con)
References chunkqueue_append_mem(), CONST_STR_LEN, force_assert, connection::response, response::transfer_encoding, UNUSED, and connection::write_queue.
Referenced by http_response_backend_done().