inet_ntop_cache.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `inet_ntop_cache.h`
*
#include `sys-socket.h`
*
#include <sys/types.h>
*
#include <string.h>
*
Functions
const char * inet_ntop_cache_get_ip (server *srv, sock_addr *addr)
Function Documentation
const char* inet_ntop_cache_get_ip (server * srv, sock_addr * addr)
References server::cur_ts, INET_NTOP_CACHE_MAX, sock_addr::ipv4, sock_addr::plain, and UNUSED.
Referenced by connection_accepted(), mod_status_handle_server_status_html(), proxy_create_env(), and URIHANDLER_FUNC().