joblist.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `joblist.h`
*
#include `log.h`
*
#include <stdlib.h>
*
#include <string.h>
*
Functions
int joblist_append (server *srv, connection *con)
void joblist_free (server *srv, connections *joblist)
connection * fdwaitqueue_unshift (server *srv, connections *fdwaitqueue)
int fdwaitqueue_append (server *srv, connection *con)
void fdwaitqueue_free (server *srv, connections *fdwaitqueue)
Function Documentation
int fdwaitqueue_append (server * srv, connection * con)
References server::fdwaitqueue, force_assert, connections::ptr, connections::size, and connections::used.
Referenced by connection_state_machine().
void fdwaitqueue_free (server * srv, connections * fdwaitqueue)
References connections::ptr, and UNUSED.
Referenced by server_free().
connection* fdwaitqueue_unshift (server * srv, connections * fdwaitqueue)
References connections::ptr, UNUSED, and connections::used.
Referenced by main().
int joblist_append (server * srv, connection * con)
References force_assert, connection::in_joblist, server::joblist, connections::ptr, connections::size, and connections::used.
Referenced by cgi_handle_fdevent(), cgi_handle_fdevent_send(), connection_handle_fdevent(), fcgi_handle_fdevent(), proxy_handle_fdevent(), and scgi_handle_fdevent().
void joblist_free (server * srv, connections * joblist)
References connections::ptr, and UNUSED.
Referenced by server_free().