keyvalue.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include <stdlib.h>
*
#include <string.h>
*
#include <stdio.h>
*
Functions
const char * keyvalue_get_value (keyvalue *kv, int k)
int keyvalue_get_key (keyvalue *kv, const char *s)
const char * get_http_version_name (int i)
const char * get_http_status_name (int i)
const char * get_http_method_name (http_method_t i)
const char * get_http_status_body_name (int i)
int get_http_version_key (const char *s)
http_method_t get_http_method_key (const char *s)
pcre_keyvalue_buffer * pcre_keyvalue_buffer_init (void)
int pcre_keyvalue_buffer_append (server *srv, pcre_keyvalue_buffer *kvb, const char *key, const char *value)
void pcre_keyvalue_buffer_free (pcre_keyvalue_buffer *kvb)
Variables
static keyvalue http_versions []
static keyvalue http_methods []
static keyvalue http_status []
static keyvalue http_status_body []
Function Documentation
http_method_t get_http_method_key (const char * s)
References keyvalue_get_key().
Referenced by http_request_parse().
const char* get_http_method_name (http_method_t i)
References keyvalue_get_value().
Referenced by config_check_cond_nocache(), http_cgi_headers(), magnet_env_get_buffer_by_id(), mod_auth_check_digest(), proxy_create_env(), and REQUESTDONE_FUNC().
const char* get_http_status_body_name (int i)
References keyvalue_get_value().
const char* get_http_status_name (int i)
References keyvalue_get_value().
Referenced by connection_handle_write_prepare(), http_response_write_header(), and webdav_gen_response_status_tag().
int get_http_version_key (const char * s)
References keyvalue_get_key().
const char* get_http_version_name (int i)
References keyvalue_get_value().
Referenced by http_cgi_headers(), and magnet_env_get_buffer_by_id().
int keyvalue_get_key (keyvalue * kv, const char * s)
References keyvalue::key, and keyvalue::value.
Referenced by get_http_method_key(), and get_http_version_key().
const char* keyvalue_get_value (keyvalue * kv, int k)
References keyvalue::value.
Referenced by get_http_method_name(), get_http_status_body_name(), get_http_status_name(), and get_http_version_name().
int pcre_keyvalue_buffer_append (server * srv, pcre_keyvalue_buffer * kvb, const char * key, const char * value)
References buffer_init_string(), force_assert, pcre_keyvalue_buffer::kv, log_error_write(), pcre_keyvalue_buffer::size, UNUSED, pcre_keyvalue_buffer::used, and pcre_keyvalue::value.
Referenced by SETDEFAULTS_FUNC().
void pcre_keyvalue_buffer_free (pcre_keyvalue_buffer * kvb)
References buffer_free(), pcre_keyvalue_buffer::kv, pcre_keyvalue_buffer::size, and pcre_keyvalue::value.
Referenced by FREE_FUNC().
pcre_keyvalue_buffer* pcre_keyvalue_buffer_init (void)
References force_assert.
Referenced by SETDEFAULTS_FUNC().
Variable Documentation
keyvalue http_methods[] [static]
keyvalue http_status[] [static]
Referenced by connection_handle_read_post_error().
keyvalue http_status_body[] [static]
Initial value:
= {
    { 400, "400.html" },
    { 401, "401.html" },
    { 403, "403.html" },
    { 404, "404.html" },
    { 411, "411.html" },
    { 416, "416.html" },
    { 500, "500.html" },
    { 501, "501.html" },
    { 503, "503.html" },
    { 505, "505.html" },
    { -1, NULL }
}
keyvalue http_versions[] [static]
Initial value:
= {
    { HTTP_VERSION_1_1, "HTTP/1.1" },
    { HTTP_VERSION_1_0, "HTTP/1.0" },
    { HTTP_VERSION_UNSET, NULL }
}