keyvalue.h File Reference
#include `first.h`
*
Classes
struct keyvalue
struct pcre_keyvalue
struct pcre_keyvalue_buffer
Enumerations
enum http_method_t {
*
HTTP_METHOD_UNSET = -1,
HTTP_METHOD_GET,
HTTP_METHOD_HEAD,
HTTP_METHOD_POST,
*
HTTP_METHOD_PUT,
HTTP_METHOD_DELETE,
HTTP_METHOD_CONNECT,
HTTP_METHOD_OPTIONS,
*
HTTP_METHOD_TRACE,
HTTP_METHOD_ACL,
HTTP_METHOD_BASELINE_CONTROL,
HTTP_METHOD_BIND,
*
HTTP_METHOD_CHECKIN,
HTTP_METHOD_CHECKOUT,
HTTP_METHOD_COPY,
HTTP_METHOD_LABEL,
*
HTTP_METHOD_LINK,
HTTP_METHOD_LOCK,
HTTP_METHOD_MERGE,
HTTP_METHOD_MKACTIVITY,
*
HTTP_METHOD_MKCALENDAR,
HTTP_METHOD_MKCOL,
HTTP_METHOD_MKREDIRECTREF,
HTTP_METHOD_MKWORKSPACE,
*
HTTP_METHOD_MOVE,
HTTP_METHOD_ORDERPATCH,
HTTP_METHOD_PATCH,
HTTP_METHOD_PROPFIND,
*
HTTP_METHOD_PROPPATCH,
HTTP_METHOD_REBIND,
HTTP_METHOD_REPORT,
HTTP_METHOD_SEARCH,
*
HTTP_METHOD_UNBIND,
HTTP_METHOD_UNCHECKOUT,
HTTP_METHOD_UNLINK,
HTTP_METHOD_UNLOCK,
*
HTTP_METHOD_UPDATE,
HTTP_METHOD_UPDATEREDIRECTREF,
HTTP_METHOD_VERSION_CONTROL
 }
enum http_version_t { HTTP_VERSION_UNSET = -1,
HTTP_VERSION_1_0,
HTTP_VERSION_1_1
 }
Functions
const char * get_http_status_name (int i)
const char * get_http_version_name (int i)
const char * get_http_method_name (http_method_t i)
const char * get_http_status_body_name (int i)
int get_http_version_key (const char *s)
http_method_t get_http_method_key (const char *s)
const char * keyvalue_get_value (keyvalue *kv, int k)
int keyvalue_get_key (keyvalue *kv, const char *s)
pcre_keyvalue_buffer * pcre_keyvalue_buffer_init (void)
int pcre_keyvalue_buffer_append (struct server *srv, pcre_keyvalue_buffer *kvb, const char *key, const char *value)
void pcre_keyvalue_buffer_free (pcre_keyvalue_buffer *kvb)
Enumeration Type Documentation
enum http_method_t
Enumerator
HTTP_METHOD_UNSET
HTTP_METHOD_GET
HTTP_METHOD_HEAD
HTTP_METHOD_POST
HTTP_METHOD_PUT
HTTP_METHOD_DELETE
HTTP_METHOD_CONNECT
HTTP_METHOD_OPTIONS
HTTP_METHOD_TRACE
HTTP_METHOD_ACL
HTTP_METHOD_BASELINE_CONTROL
HTTP_METHOD_BIND
HTTP_METHOD_CHECKIN
HTTP_METHOD_CHECKOUT
HTTP_METHOD_COPY
HTTP_METHOD_LABEL
HTTP_METHOD_LINK
HTTP_METHOD_LOCK
HTTP_METHOD_MERGE
HTTP_METHOD_MKACTIVITY
HTTP_METHOD_MKCALENDAR
HTTP_METHOD_MKCOL
HTTP_METHOD_MKREDIRECTREF
HTTP_METHOD_MKWORKSPACE
HTTP_METHOD_MOVE
HTTP_METHOD_ORDERPATCH
HTTP_METHOD_PATCH
HTTP_METHOD_PROPFIND
HTTP_METHOD_PROPPATCH
HTTP_METHOD_REBIND
HTTP_METHOD_REPORT
HTTP_METHOD_SEARCH
HTTP_METHOD_UNBIND
HTTP_METHOD_UNCHECKOUT
HTTP_METHOD_UNLINK
HTTP_METHOD_UNLOCK
HTTP_METHOD_UPDATE
HTTP_METHOD_UPDATEREDIRECTREF
HTTP_METHOD_VERSION_CONTROL
enum http_version_t
Enumerator
HTTP_VERSION_UNSET
HTTP_VERSION_1_0
HTTP_VERSION_1_1
Function Documentation
http_method_t get_http_method_key (const char * s)
References keyvalue_get_key().
Referenced by http_request_parse().
const char* get_http_method_name (http_method_t i)
References keyvalue_get_value().
Referenced by config_check_cond_nocache(), http_cgi_headers(), magnet_env_get_buffer_by_id(), mod_auth_check_digest(), proxy_create_env(), and REQUESTDONE_FUNC().
const char* get_http_status_body_name (int i)
References keyvalue_get_value().
const char* get_http_status_name (int i)
References keyvalue_get_value().
Referenced by connection_handle_write_prepare(), http_response_write_header(), and webdav_gen_response_status_tag().
int get_http_version_key (const char * s)
References keyvalue_get_key().
const char* get_http_version_name (int i)
References keyvalue_get_value().
Referenced by http_cgi_headers(), and magnet_env_get_buffer_by_id().
int keyvalue_get_key (keyvalue * kv, const char * s)
References keyvalue::key, and keyvalue::value.
Referenced by get_http_method_key(), and get_http_version_key().
const char* keyvalue_get_value (keyvalue * kv, int k)
References keyvalue::value.
Referenced by get_http_method_name(), get_http_status_body_name(), get_http_status_name(), and get_http_version_name().
int pcre_keyvalue_buffer_append (struct server * srv, pcre_keyvalue_buffer * kvb, const char * key, const char * value)
References buffer_init_string(), force_assert, pcre_keyvalue_buffer::kv, log_error_write(), pcre_keyvalue_buffer::size, UNUSED, pcre_keyvalue_buffer::used, and pcre_keyvalue::value.
Referenced by SETDEFAULTS_FUNC().
void pcre_keyvalue_buffer_free (pcre_keyvalue_buffer * kvb)
References buffer_free(), pcre_keyvalue_buffer::kv, pcre_keyvalue_buffer::size, and pcre_keyvalue::value.
Referenced by FREE_FUNC().
pcre_keyvalue_buffer* pcre_keyvalue_buffer_init (void)
References force_assert.
Referenced by SETDEFAULTS_FUNC().