lemon.c File Reference
#include <stdio.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <inttypes.h>
*
#include <unistd.h>
*
Classes
struct symbol
struct rule
struct config
struct action
struct state
struct plink
struct lemon
struct acttab
struct pstate
struct axset
struct s_x1
struct s_x1node
struct s_x2
struct s_x2node
struct s_x3
struct s_x3node
struct s_x4
struct s_x4node
Macros
#define _GNU_SOURCE
#define UNUSED(x) ((void)(x))
#define NORETURN
#define PRIVATE static
#define MAXRHS 1000
#define assert(X) if(!(X))myassert(__FILE__,__LINE__)
#define SetFind(X, Y) (X[Y]) /* True if Y is in set X */
#define NO_OFFSET (-2147483647)
#define MemoryCheck(X)
#define acttab_size(X) ((X)->nAction)
#define acttab_yyaction(X, N) ((X)->aAction[N].action)
#define acttab_yylookahead(X, N) ((X)->aAction[N].lookahead)
#define ERRMSGSIZE 10000 /* Hope this is big enough. No way to error check */
#define LINEWIDTH 79 /* Max width of any output line */
#define PREFIXLIMIT 30 /* Max width of the prefix on each line */
#define NEXT(A) (*(char**)(((unsigned long)A)+offset))
#define LISTSIZE 30
#define ISOPT(X) ((X)[0]=='-'||(X)[0]=='+'||strchr((X),'=')!=0)
#define LINESIZE 1000
Typedefs
typedef struct acttab acttab
typedef struct s_x1node x1node
typedef struct s_x2node x2node
typedef struct s_x3node x3node
typedef struct s_x4node x4node
Enumerations
enum Boolean { Bo_FALSE =0,
Bo_TRUE
 }
Functions
void * msort (void *list, void **next, int(*cmp)(void *, void *))
static void memory_error ()
int OptInit ()
int OptNArgs ()
char * OptArg ()
void OptErr ()
void OptPrint ()
void Parse ()
struct plink * Plink_new ()
void Plink_add ()
void Plink_copy ()
void Plink_delete ()
void Reprint ()
void ReportOutput ()
void ReportTable ()
void ReportHeader ()
void CompressTables ()
void SetSize ()
char * SetNew ()
void SetFree ()
int SetAdd ()
int SetUnion ()
char * Strsafe ()
void Strsafe_init ()
int Strsafe_insert ()
char * Strsafe_find ()
struct symbol * Symbol_new ()
int Symbolcmpp ()
void Symbol_init ()
int Symbol_insert ()
struct symbol * Symbol_find ()
struct symbol * Symbol_Nth ()
int Symbol_count ()
int State_count (void)
struct symbol ** Symbol_arrayof ()
int Configcmp ()
struct state * State_new ()
void State_init ()
int State_insert ()
struct state * State_find ()
struct state ** State_arrayof ()
void Configtable_init ()
int Configtable_insert ()
struct config * Configtable_find ()
void Configtable_clear ()
struct action * Action_new ()
static int actioncmp (struct action *ap1, struct action *ap2)
struct action * Action_sort (struct action *ap)
void Action_add (struct action **app, enum e_action type, struct symbol *sp, void *arg)
PRIVATE acttab * acttab_alloc (void)
PRIVATE void acttab_action (acttab *p, int lookahead, int action)
PRIVATE int acttab_insert (acttab *p)
void myassert (char *file, int line)
void FindRulePrecedences (struct lemon *xp)
void FindFirstSets (struct lemon *lemp)
PRIVATE struct state * getstate ()
void FindStates (struct lemon *lemp)
PRIVATE void buildshifts ()
PRIVATE struct state * getstate (struct lemon *lemp)
PRIVATE void buildshifts (struct lemon *lemp, struct state *stp)
void FindLinks (struct lemon *lemp)
void FindFollowSets (struct lemon *lemp)
static int resolve_conflict ()
void FindActions (struct lemon *lemp)
static int resolve_conflict (struct action *apx, struct action *apy, struct symbol *errsym)
PRIVATE struct config * newconfig ()
PRIVATE void deleteconfig (struct config *old)
void Configlist_init ()
void Configlist_reset ()
struct config * Configlist_add (struct rule *rp, int dot)
struct config * Configlist_addbasis (struct rule *rp, int dot)
void Configlist_closure (struct lemon *lemp)
void Configlist_sort ()
void Configlist_sortbasis ()
struct config * Configlist_return ()
struct config * Configlist_basis ()
void Configlist_eat (struct config *cfp)
static int findbreak (char *msg, int min, int max)
void ErrorMsg (const char *filename, int lineno, const char *format,...)
int main (int argc, char **argv)
static char * merge (char *a, char *b, int(*cmp)(), int offset)
static void errline (int n, int k, FILE *err)
static int argindex (int n)
static int handleflags (int i, FILE *err)
static int handleswitch (int i, FILE *err)
int OptInit (char **a, struct s_options *o, FILE *err)
char * OptArg (int n)
void OptErr (int n)
static void parseonetoken (struct pstate *psp)
void Parse (struct lemon *gp)
void Plink_add (struct plink **plpp, struct config *cfp)
void Plink_copy (struct plink **to, struct plink *from)
void Plink_delete (struct plink *plp)
PRIVATE char * file_makename (struct lemon *lemp, char *suffix)
PRIVATE FILE * file_open (struct lemon *lemp, char *suffix, char *mode)
void Reprint (struct lemon *lemp)
PRIVATE void ConfigPrint (FILE *fp, struct config *cfp)
PRIVATE int PrintAction (struct action *ap, FILE *fp, int indent)
void ReportOutput (struct lemon *lemp)
PRIVATE char * pathsearch (char *argv0, char *name, int modemask)
PRIVATE int compute_action (struct lemon *lemp, struct action *ap)
PRIVATE void tplt_xfer (char *name, FILE *in, FILE *out, int *lineno)
PRIVATE FILE * tplt_open (struct lemon *lemp)
PRIVATE void tplt_print (FILE *out, struct lemon *lemp, char *str, int strln, int *lineno)
PRIVATE void emit_destructor_code (FILE *out, struct symbol *sp, struct lemon *lemp, int *lineno)
PRIVATE int has_destructor (struct symbol *sp, struct lemon *lemp)
PRIVATE void emit_code (FILE *out, struct rule *rp, struct lemon *lemp, int *lineno)
PRIVATE void print_stack_union (FILE *out, struct lemon *lemp, int *plineno, int mhflag)
static const char * minimum_size_type (int lwr, int upr)
static int axset_compare (const void *a, const void *b)
void ReportTable (struct lemon *lemp, int mhflag)
void ReportHeader (struct lemon *lemp)
void CompressTables (struct lemon *lemp)
void SetSize (int n)
void SetFree (char *s)
int SetAdd (char *s, int e)
int SetUnion (char *s1, char *s2)
PRIVATE int strhash (char *x)
char * Strsafe (char *y)
int Strsafe_insert (char *data)
char * Strsafe_find (char *key)
struct symbol * Symbol_new (char *x)
int Symbolcmpp (struct symbol **a, struct symbol **b)
int Symbol_insert (struct symbol *data, char *key)
struct symbol * Symbol_find (char *key)
struct symbol * Symbol_Nth (int n)
int Configcmp (struct config *a, struct config *b)
PRIVATE int statecmp (struct config *a, struct config *b)
PRIVATE int statehash (struct config *a)
int State_insert (struct state *data, struct config *key)
struct state * State_find (struct config *key)
PRIVATE int confighash (struct config *a)
int Configtable_insert (struct config *data)
struct config * Configtable_find (struct config *key)
void Configtable_clear (int(*f)())
Variables
static struct config * freelist = 0
static struct config * current = 0
static struct config ** currentend = 0
static struct config * basis = 0
static struct config ** basisend = 0
static char ** argv
static struct s_options * op
static FILE * errstream
static char emsg [] = `Command line syntax error: `
struct pstate ps
static struct plink * plink_freelist = 0
static int global_size = 0
static struct s_x1 * x1a
static struct s_x2 * x2a
static struct s_x3 * x3a
static struct s_x4 * x4a
Macro Definition Documentation
#define _GNU_SOURCE
#define acttab_size(X) ((X)->nAction)
Referenced by ReportTable().
#define acttab_yyaction(X, N) ((X)->aAction[N].action)
Referenced by ReportTable().
#define acttab_yylookahead(X, N) ((X)->aAction[N].lookahead)
Referenced by ReportTable().
#define assert(X) if(!(X))myassert(__FILE__,__LINE__)
Referenced by actioncmp(), acttab_insert(), array_get_index(), CompressTables(), Configlist_add(), Configlist_addbasis(), Configlist_closure(), Configlist_eat(), FindActions(), ReportTable(), Reprint(), resolve_conflict(), splaytree_insert(), and test_configfile_addrbuf_eq_remote_ip_mask().
#define ERRMSGSIZE 10000 /* Hope this is big enough. No way to error check */
Referenced by ErrorMsg().
#define ISOPT(X) ((X)[0]=='-'||(X)[0]=='+'||strchr((X),'=')!=0)
Referenced by argindex(), and OptNArgs().
#define LINESIZE 1000
Referenced by ReportHeader(), ReportTable(), and tplt_xfer().
#define LINEWIDTH 79 /* Max width of any output line */
Referenced by ErrorMsg().
#define LISTSIZE 30
Referenced by msort().
#define MAXRHS 1000
Referenced by emit_code(), and parseonetoken().
#define MemoryCheck(X)
Value:
if((X)==0){ \
  memory_error(); \
}
Referenced by getstate(), State_new(), Strsafe(), and Symbol_new().
#define NEXT(A) (*(char**)(((unsigned long)A)+offset))
Referenced by merge(), and msort().
#define NO_OFFSET (-2147483647)
Referenced by ReportTable().
#define NORETURN
#define PREFIXLIMIT 30 /* Max width of the prefix on each line */
Referenced by ErrorMsg().
#define PRIVATE static
#define SetFind(X, Y) (X[Y]) /* True if Y is in set X */
Referenced by FindActions().
#define UNUSED(x) ((void)(x))
Referenced by cgi_create_env(), cgi_pid_add(), cgi_pid_del(), cgi_response_parse(), cgi_write_file_chunk_mmap(), CONNECTION_FUNC(), connection_handle_read_post_error(), connection_handle_read_ssl(), connection_init(), connection_response_reset(), connection_set_state(), data_array_insert_dup(), data_config_insert_dup(), data_fastcgi_insert_dup(), data_fastcgi_print(), data_integer_insert_dup(), data_integer_print(), data_string_print(), excludes_buffer_append(), fcgi_extension_host_get(), fcgi_response_parse(), fcgi_spawn_connection(), fd_close_on_exec(), fdevent_freebsd_kqueue_init(), fdevent_is_tcp_half_closed(), fdevent_libev_init(), fdevent_linux_sysepoll_init(), fdevent_poll_init(), fdevent_select_init(), fdevent_solaris_devpoll_init(), fdevent_solaris_port_init(), fdwaitqueue_free(), fdwaitqueue_unshift(), FREE_FUNC(), http_chunk_close(), http_list_directory_footer(), http_list_directory_header(), http_request_header_finished(), http_response_backend_error(), http_response_handle_cachable(), inet_ntop_cache_get_ip(), joblist_free(), li_getentropy(), magnet_env_get_buffer_by_id(), main(), mod_auth_check_basic(), mod_auth_check_digest(), mod_auth_check_extern(), mod_auth_send_400_bad_request(), mod_authn_file_htdigest_basic(), mod_authn_file_htdigest_digest(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), mod_authn_file_plain_digest(), mod_authn_gssapi_check(), mod_authn_gssapi_log_krb5_error(), mod_authn_gssapi_send_400_bad_request(), mod_authn_mysql_sock_error(), mod_authn_mysql_sock_release(), mod_compress_note_ratio(), mod_deflate_choose_encoding(), mod_deflate_compress(), mod_deflate_note_ratio(), mod_deflate_stream_end(), mod_deflate_stream_flush(), mod_expire_get_offset(), mod_mysql_vhost_connection_data(), mod_redirect_uri_handler(), mod_ssi_connection_reset(), mod_status_handle_server_statistics(), mod_webdav_connection_reset(), network_open_file_chunk(), network_server_handle_fdevent(), network_write_mem_chunk(), pcre_keyvalue_buffer_append(), PHYSICALPATH_FUNC(), print_backtrace(), proxy_response_parse(), REQUESTDONE_FUNC(), resolve_conflict(), response_header_append(), response_header_insert(), response_header_overwrite(), scgi_extension_host_get(), scgi_proclist_sort_down(), scgi_proclist_sort_up(), scgi_response_parse(), scgi_spawn_connection(), secdl_verify_mac(), SERVER_FUNC(), SETDEFAULTS_FUNC(), ssi_expr_tokenizer(), stat_cache_open_rdonly_fstat(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), webdav_copy_file(), webdav_delete_file(), webdav_gen_prop_tag(), webdav_gen_response_status_tag(), webdav_get_live_property(), webdav_has_lock(), and yy_syntax_error().
Typedef Documentation
typedef struct acttab acttab
typedef struct s_x1node x1node
typedef struct s_x2node x2node
typedef struct s_x3node x3node
typedef struct s_x4node x4node
Enumeration Type Documentation
enum Boolean
Enumerator
Bo_FALSE
Bo_TRUE
Function Documentation
void Action_add (struct action ** app, enum e_action type, struct symbol * sp, void * arg)
References Action_new(), action::SHIFT, action::sp, and action::type.
Referenced by buildshifts(), and FindActions().
struct action* Action_new ()
References freelist, and action::next.
Referenced by Action_add().
struct action* Action_sort (struct action * ap)
References actioncmp(), and msort().
Referenced by CompressTables(), and FindActions().
static int actioncmp (struct action * ap1, struct action * ap2) [static]
References assert, action::CONFLICT, symbol::index, rule::index, action::RD_RESOLVED, action::REDUCE, action::rp, action::sp, action::type, and action::x.
Referenced by Action_sort().
PRIVATE void acttab_action (acttab * p, int lookahead, int action)
References acttab::action, acttab::aLookahead, acttab::lookahead, acttab::mnAction, acttab::mnLookahead, acttab::mxLookahead, acttab::nLookahead, and acttab::nLookaheadAlloc.
Referenced by ReportTable().
PRIVATE acttab* acttab_alloc (void)
Referenced by ReportTable().
PRIVATE int acttab_insert (acttab * p)
References acttab::aAction, acttab::action, acttab::aLookahead, assert, acttab::lookahead, acttab::mnAction, acttab::mnLookahead, acttab::mxLookahead, acttab::nAction, acttab::nActionAlloc, and acttab::nLookahead.
Referenced by ReportTable().
static int argindex (int n) [static]
References ISOPT.
Referenced by OptArg(), and OptErr().
static int axset_compare (const void * a, const void * b) [static]
References axset::nAction.
Referenced by ReportTable().
PRIVATE void buildshifts ()
Referenced by getstate().
PRIVATE void buildshifts (struct lemon * lemp, struct state * stp)
References Action_add(), state::ap, state::cfp, Configlist_addbasis(), Configlist_reset(), config::dot, getstate(), config::next, rule::nrhs, Plink_add(), rule::rhs, config::rp, and config::status.
void CompressTables ()
Referenced by main().
void CompressTables (struct lemon * lemp)
References Action_sort(), state::ap, assert, action::next, action::rp, action::sp, Symbol_new(), action::type, and action::x.
PRIVATE int compute_action (struct lemon * lemp, struct action * ap)
References action::ACCEPT, action::ERROR, rule::index, state::index, action::REDUCE, action::rp, action::SHIFT, action::stp, action::type, and action::x.
Referenced by ReportTable().
int Configcmp ()
Referenced by Configlist_sort(), Configlist_sortbasis(), Configtable_find(), and Configtable_insert().
int Configcmp (struct config * a, struct config * b)
References config::dot, rule::index, and config::rp.
PRIVATE int confighash (struct config * a)
References rule::index, and config::rp.
Referenced by Configtable_find(), and Configtable_insert().
struct config* Configlist_add (struct rule * rp, int dot)
References assert, config::bp, config::bplp, Configtable_find(), Configtable_insert(), config::dot, config::fplp, config::fws, newconfig(), config::next, config::rp, SetNew(), and config::stp.
Referenced by Configlist_closure().
struct config* Configlist_addbasis (struct rule * rp, int dot)
References assert, config::bp, config::bplp, Configtable_find(), Configtable_insert(), config::dot, config::fplp, config::fws, newconfig(), config::next, config::rp, SetNew(), and config::stp.
Referenced by buildshifts(), and FindStates().
struct config* Configlist_basis ()
References basis.
Referenced by getstate().
void Configlist_closure (struct lemon * lemp)
References assert, Bo_FALSE, Configlist_add(), config::dot, ErrorMsg(), symbol::firstset, config::fplp, config::fws, symbol::index, symbol::lambda, rule::line, symbol::name, config::next, rule::nextlhs, symbol::NONTERMINAL, rule::nrhs, Plink_add(), rule::rhs, config::rp, symbol::rule, SetAdd(), SetUnion(), symbol::TERMINAL, and symbol::type.
Referenced by getstate().
void Configlist_eat (struct config * cfp)
References assert, deleteconfig(), config::next, and SetFree().
Referenced by getstate().
void Configlist_init ()
References basis, Configtable_init(), and current.
Referenced by FindStates().
void Configlist_reset ()
References basis, Configtable_clear(), and current.
Referenced by buildshifts().
struct config* Configlist_return ()
References current.
Referenced by getstate().
void Configlist_sort ()
References Configcmp(), msort(), and config::next.
Referenced by getstate().
void Configlist_sortbasis ()
References config::bp, Configcmp(), and msort().
Referenced by getstate().
PRIVATE void ConfigPrint (FILE * fp, struct config * cfp)
References config::dot, rule::lhs, symbol::name, rule::nrhs, rule::rhs, and config::rp.
Referenced by ReportOutput().
void Configtable_clear ()
Referenced by Configlist_reset().
void Configtable_clear (int(*)() f)
References s_x4::count, s_x4node::data, s_x4::ht, s_x4::size, and s_x4::tbl.
struct config* Configtable_find ()
Referenced by Configlist_add(), and Configlist_addbasis().
struct config* Configtable_find (struct config * key)
References Configcmp(), confighash(), s_x4node::data, s_x4::ht, s_x4node::next, and s_x4::size.
void Configtable_init ()
References s_x4::count, s_x4::ht, s_x4::size, and s_x4::tbl.
Referenced by Configlist_init().
int Configtable_insert ()
Referenced by Configlist_add(), and Configlist_addbasis().
int Configtable_insert (struct config * data)
References Configcmp(), confighash(), s_x4::count, s_x4node::data, s_x4node::from, s_x4::ht, s_x4node::next, s_x4::size, and s_x4::tbl.
PRIVATE void deleteconfig (struct config * old)
References freelist, and config::next.
Referenced by Configlist_eat().
PRIVATE void emit_code (FILE * out, struct rule * rp, struct lemon * lemp, int * lineno)
References rule::code, symbol::dtnum, lemon::errorcnt, ErrorMsg(), lemon::filename, has_destructor(), symbol::index, rule::lhs, rule::lhsalias, rule::line, MAXRHS, symbol::name, rule::nrhs, lemon::outname, rule::rhs, rule::rhsalias, and rule::ruleline.
Referenced by ReportTable().
PRIVATE void emit_destructor_code (FILE * out, struct symbol * sp, struct lemon * lemp, int * lineno)
References symbol::destructor, symbol::destructorln, symbol::dtnum, lemon::filename, lemon::outname, lemon::tokendest, lemon::tokendestln, symbol::type, lemon::vardest, and lemon::vardestln.
Referenced by ReportTable().
static void errline (int n, int k, FILE * err) [static]
Referenced by handleflags(), handleswitch(), and OptErr().
void ErrorMsg (const char * filename, int lineno, const char * format, ...)
References ERRMSGSIZE, findbreak(), LINEWIDTH, and PREFIXLIMIT.
Referenced by Configlist_closure(), emit_code(), FindActions(), FindStates(), Parse(), parseonetoken(), and ReportTable().
PRIVATE char* file_makename (struct lemon * lemp, char * suffix)
Referenced by file_open(), and ReportTable().
PRIVATE FILE* file_open (struct lemon * lemp, char * suffix, char * mode)
References file_makename().
Referenced by ReportHeader(), ReportOutput(), and ReportTable().
void FindActions (struct lemon * lemp)
References Action_add(), Action_sort(), state::ap, assert, Bo_FALSE, Bo_TRUE, rule::canReduce, state::cfp, config::dot, ErrorMsg(), config::fws, rule::lhs, rule::next, config::next, action::next, rule::nrhs, action::REDUCE, resolve_conflict(), config::rp, action::rp, symbol::rule, rule::ruleline, SetFind, action::sp, Symbol_find(), action::type, and action::x.
Referenced by main().
static int findbreak (char * msg, int min, int max) [static]
Referenced by ErrorMsg().
void FindFirstSets (struct lemon * lemp)
References Bo_FALSE, Bo_TRUE, symbol::firstset, symbol::index, symbol::lambda, rule::lhs, rule::next, rule::nrhs, rule::rhs, SetAdd(), SetNew(), SetUnion(), symbol::TERMINAL, and symbol::type.
Referenced by main().
void FindFollowSets (struct lemon * lemp)
References state::cfp, plink::cfp, config::fplp, config::fws, config::next, plink::next, SetUnion(), and config::status.
Referenced by main().
void FindLinks (struct lemon * lemp)
References config::bplp, state::cfp, plink::cfp, config::fplp, config::next, plink::next, Plink_add(), and config::stp.
Referenced by main().
void FindRulePrecedences (struct lemon * xp)
References rule::next, rule::nrhs, symbol::prec, rule::precsym, and rule::rhs.
Referenced by main().
void FindStates (struct lemon * lemp)
References Configlist_addbasis(), Configlist_init(), ErrorMsg(), config::fws, getstate(), rule::lhs, symbol::name, rule::next, rule::nextlhs, rule::nrhs, rule::rhs, symbol::rule, SetAdd(), and Symbol_find().
Referenced by main().
PRIVATE struct state* getstate ()
Referenced by buildshifts(), and FindStates().
PRIVATE struct state* getstate (struct lemon * lemp)
References state::ap, config::bp, state::bp, config::bplp, buildshifts(), state::cfp, Configlist_basis(), Configlist_closure(), Configlist_eat(), Configlist_return(), Configlist_sort(), Configlist_sortbasis(), config::fplp, state::index, MemoryCheck, Plink_copy(), Plink_delete(), State_find(), State_insert(), State_new(), and config::stp.
static int handleflags (int i, FILE * err) [static]
References errline().
Referenced by OptInit().
static int handleswitch (int i, FILE * err) [static]
References errline().
Referenced by OptInit().
PRIVATE int has_destructor (struct symbol * sp, struct lemon * lemp)
References lemon::tokendest, and lemon::vardest.
Referenced by emit_code().
int main (int argc, char ** argv)
References lemon::accept, lemon::arg, lemon::argv0, lemon::basisflag, CompressTables(), lemon::error, lemon::errorcnt, lemon::errsym, lemon::extracode, lemon::failure, lemon::filename, FindActions(), FindFirstSets(), FindFollowSets(), FindLinks(), FindRulePrecedences(), FindStates(), lemon::has_fallback, lemon::include, symbol::index, symbol::name, lemon::name, lemon::nconflict, lemon::nrule, lemon::nstate, lemon::nsymbol, lemon::nterminal, OptArg(), OptInit(), OptNArgs(), lemon::outname, lemon::overflow, Parse(), ReportHeader(), ReportOutput(), ReportTable(), Reprint(), lemon::rule, SetSize(), lemon::sorted, lemon::stacksize, lemon::start, State_arrayof(), State_count(), State_init(), Strsafe_init(), Symbol_arrayof(), Symbol_count(), Symbol_init(), Symbol_new(), Symbolcmpp(), lemon::symbols, lemon::tablesize, lemon::tmplname, lemon::tokendest, lemon::tokenprefix, lemon::tokentype, UNUSED, lemon::vardest, and lemon::vartype.
void memory_error () [static]
Referenced by SetNew().
static char* merge (char * a, char * b, int (*)() cmp, int offset) [static]
References NEXT.
Referenced by msort().
static const char* minimum_size_type (int lwr, int upr) [static]
Referenced by ReportTable().
void * msort (void * list, void ** next, int(*)(void *, void *) cmp)
References LISTSIZE, merge(), and NEXT.
Referenced by Action_sort(), Configlist_sort(), and Configlist_sortbasis().
void myassert (char * file, int line)
PRIVATE struct config* newconfig ()
References freelist, and config::next.
Referenced by Configlist_add(), and Configlist_addbasis().
char* OptArg ()
Referenced by main().
char* OptArg (int n)
References argindex().
void OptErr ()
void OptErr (int n)
References argindex(), and errline().
int OptInit ()
Referenced by main().
int OptInit (char ** a, struct s_options * o, FILE * err)
References handleflags(), handleswitch(), and OptPrint().
int OptNArgs ()
References ISOPT.
Referenced by main().
void OptPrint ()
Referenced by OptInit().
void Parse ()
Referenced by main().
void Parse (struct lemon * gp)
References pstate::errorcnt, ErrorMsg(), pstate::filename, pstate::firstrule, pstate::gp, pstate::INITIALIZE, parseonetoken(), ps, pstate::state, pstate::tokenlineno, and pstate::tokenstart.
static void parseonetoken (struct pstate * psp) [static]
References symbol::assoc, rule::code, symbol::datatype, symbol::destructor, symbol::destructorln, ErrorMsg(), symbol::fallback, rule::index, symbol::LEFT, rule::lhs, rule::lhsalias, MAXRHS, rule::next, rule::nextlhs, symbol::NONE, rule::nrhs, symbol::prec, rule::precsym, rule::rhs, rule::rhsalias, symbol::RIGHT, symbol::rule, rule::ruleline, Strsafe(), and Symbol_new().
Referenced by Parse().
PRIVATE char* pathsearch (char * argv0, char * name, int modemask)
Referenced by tplt_open().
void Plink_add ()
Referenced by buildshifts(), Configlist_closure(), and FindLinks().
void Plink_add (struct plink ** plpp, struct config * cfp)
References plink::cfp, and Plink_new().
void Plink_copy ()
Referenced by getstate().
void Plink_copy (struct plink ** to, struct plink * from)
References plink::next.
void Plink_delete ()
Referenced by getstate().
void Plink_delete (struct plink * plp)
References plink::next, and plink_freelist.
struct plink * Plink_new ()
References plink::next, and plink_freelist.
Referenced by Plink_add().
PRIVATE void print_stack_union (FILE * out, struct lemon * lemp, int * plineno, int mhflag)
References symbol::datatype, symbol::dtnum, lemon::errsym, lemon::name, symbol::NONTERMINAL, lemon::nsymbol, lemon::symbols, lemon::tokentype, symbol::type, and lemon::vartype.
Referenced by ReportTable().
PRIVATE int PrintAction (struct action * ap, FILE * fp, int indent)
References rule::index, state::index, symbol::name, action::rp, action::sp, action::stp, action::type, and action::x.
Referenced by ReportOutput().
void ReportHeader ()
Referenced by main().
void ReportHeader (struct lemon * lemp)
References file_open(), LINESIZE, and lemon::tokenprefix.
void ReportOutput ()
Referenced by main().
void ReportOutput (struct lemon * lemp)
References state::ap, config::bp, state::bp, config::bplp, state::cfp, ConfigPrint(), config::dot, file_open(), config::fplp, config::fws, rule::index, state::index, config::next, action::next, rule::nrhs, PrintAction(), and config::rp.
void ReportTable ()
Referenced by main().
void ReportTable (struct lemon * lemp, int mhflag)
References acttab_action(), acttab_alloc(), acttab_insert(), acttab_size, acttab_yyaction, acttab_yylookahead, state::ap, assert, axset_compare(), compute_action(), symbol::destructor, emit_code(), emit_destructor_code(), ErrorMsg(), symbol::fallback, file_makename(), file_open(), state::iDflt, symbol::index, rule::index, state::iNtOfst, axset::isTkn, state::iTknOfst, rule::lhs, LINESIZE, minimum_size_type(), axset::nAction, symbol::name, rule::next, action::next, state::nNtAct, NO_OFFSET, rule::nrhs, state::nTknAct, print_stack_union(), rule::rhs, action::sp, axset::stp, symbol::TERMINAL, tplt_open(), tplt_print(), tplt_xfer(), and symbol::type.
void Reprint ()
Referenced by main().
void Reprint (struct lemon * lemp)
References assert, symbol::index, rule::lhs, symbol::name, rule::next, rule::nrhs, rule::precsym, and rule::rhs.
static int resolve_conflict () [static]
Referenced by FindActions().
static int resolve_conflict (struct action * apx, struct action * apy, struct symbol * errsym) [static]
References assert, symbol::assoc, symbol::LEFT, symbol::NONE, symbol::prec, rule::precsym, symbol::RIGHT, action::rp, action::sp, action::type, UNUSED, and action::x.
int SetAdd ()
Referenced by Configlist_closure(), FindFirstSets(), and FindStates().
int SetAdd (char * s, int e)
void SetFree ()
Referenced by Configlist_eat().
void SetFree (char * s)
char * SetNew ()
References global_size, and memory_error().
Referenced by Configlist_add(), Configlist_addbasis(), and FindFirstSets().
void SetSize ()
Referenced by main().
void SetSize (int n)
int SetUnion ()
Referenced by Configlist_closure(), FindFirstSets(), and FindFollowSets().
int SetUnion (char * s1, char * s2)
References global_size.
struct state ** State_arrayof ()
References s_x3::count, s_x3node::data, and s_x3::tbl.
Referenced by main().
int State_count (void)
References s_x3::count.
Referenced by main().
struct state* State_find ()
Referenced by getstate().
struct state* State_find (struct config * key)
References s_x3node::data, s_x3::ht, s_x3node::key, s_x3node::next, s_x3::size, statecmp(), and statehash().
void State_init ()
References s_x3::count, s_x3::ht, s_x3::size, and s_x3::tbl.
Referenced by main().
int State_insert ()
Referenced by getstate().
int State_insert (struct state * data, struct config * key)
References s_x3::count, s_x3node::data, s_x3node::from, s_x3::ht, s_x3node::key, s_x3node::next, s_x3::size, statecmp(), statehash(), and s_x3::tbl.
struct state * State_new ()
References MemoryCheck.
Referenced by getstate().
PRIVATE int statecmp (struct config * a, struct config * b)
References config::bp, rule::index, and config::rp.
Referenced by State_find(), and State_insert().
PRIVATE int statehash (struct config * a)
References rule::index, and config::rp.
Referenced by State_find(), and State_insert().
PRIVATE int strhash (char * x)
Referenced by Strsafe_find(), Strsafe_insert(), Symbol_find(), and Symbol_insert().
char* Strsafe ()
Referenced by parseonetoken(), and Symbol_new().
char* Strsafe (char * y)
References MemoryCheck, Strsafe_find(), and Strsafe_insert().
char* Strsafe_find ()
Referenced by Strsafe().
char* Strsafe_find (char * key)
References s_x1node::data, s_x1::ht, s_x1node::next, s_x1::size, and strhash().
void Strsafe_init ()
References s_x1::count, s_x1::ht, s_x1::size, and s_x1::tbl.
Referenced by main().
int Strsafe_insert ()
Referenced by Strsafe().
int Strsafe_insert (char * data)
References s_x1::count, s_x1node::data, s_x1node::from, s_x1::ht, s_x1node::next, s_x1::size, strhash(), and s_x1::tbl.
struct symbol ** Symbol_arrayof ()
References s_x2::count, s_x2node::data, and s_x2::tbl.
Referenced by main().
int Symbol_count ()
References s_x2::count.
Referenced by main().
struct symbol* Symbol_find ()
Referenced by FindActions(), FindStates(), and Symbol_new().
struct symbol* Symbol_find (char * key)
References s_x2node::data, s_x2::ht, s_x2node::key, s_x2node::next, s_x2::size, and strhash().
void Symbol_init ()
References s_x2::count, s_x2::ht, s_x2::size, and s_x2::tbl.
Referenced by main().
int Symbol_insert ()
Referenced by Symbol_new().
int Symbol_insert (struct symbol * data, char * key)
References s_x2::count, s_x2node::data, s_x2node::from, s_x2::ht, s_x2node::key, s_x2node::next, s_x2::size, strhash(), and s_x2::tbl.
struct symbol* Symbol_new ()
Referenced by CompressTables(), main(), and parseonetoken().
struct symbol* Symbol_new (char * x)
References symbol::assoc, Bo_FALSE, symbol::datatype, symbol::destructor, symbol::fallback, symbol::firstset, symbol::lambda, MemoryCheck, symbol::name, symbol::NONTERMINAL, symbol::prec, symbol::rule, Strsafe(), Symbol_find(), Symbol_insert(), symbol::TERMINAL, symbol::type, and symbol::UNK.
struct symbol* Symbol_Nth ()
struct symbol* Symbol_Nth (int n)
References s_x2node::data, and s_x2::tbl.
int Symbolcmpp ()
Referenced by main().
int Symbolcmpp (struct symbol ** a, struct symbol ** b)
PRIVATE FILE* tplt_open (struct lemon * lemp)
References pathsearch().
Referenced by ReportTable().
PRIVATE void tplt_print (FILE * out, struct lemon * lemp, char * str, int strln, int * lineno)
References lemon::filename, and lemon::outname.
Referenced by ReportTable().
PRIVATE void tplt_xfer (char * name, FILE * in, FILE * out, int * lineno)
References LINESIZE.
Referenced by ReportTable().
Variable Documentation
char** argv [static]
struct config* basis = 0 [static]
Referenced by Configlist_basis(), Configlist_init(), and Configlist_reset().
struct config** basisend = 0 [static]
struct config* current = 0 [static]
Referenced by Configlist_init(), Configlist_reset(), Configlist_return(), etag_is_equal(), and http_request_split_value().
struct config** currentend = 0 [static]
char emsg[] = `Command line syntax error: ` [static]
FILE* errstream [static]
struct config* freelist = 0 [static]
Referenced by Action_new(), deleteconfig(), and newconfig().
int global_size = 0 [static]
Referenced by SetNew(), and SetUnion().
struct s_options* op [static]
Referenced by yy_reduce().
struct plink* plink_freelist = 0 [static]
Referenced by Plink_delete(), and Plink_new().
struct pstate ps
Referenced by mod_status_handle_server_config(), Parse(), plugins_call_init(), and plugins_register().
struct s_x1* x1a [static]
struct s_x2* x2a [static]
struct s_x3* x3a [static]
struct s_x4* x4a [static]