lempar.c File Reference
#include `first.h`
*
#include <stdio.h>
*
Classes
struct yyStackEntry
struct yyParser
Macros
#define INTERFACE 1
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
#define YY_SZ_ACTTAB (sizeof(yy_action)/sizeof(yy_action[0]))
#define TOKEN (yyminor.yy0)
Typedefs
typedef struct yyStackEntry yyStackEntry
typedef struct yyParser yyParser
Functions
void * ParseAlloc (void *(*mallocProc)(size_t))
static void yy_destructor (YYCODETYPE yymajor, YYMINORTYPE *yypminor)
static int yy_pop_parser_stack (yyParser *pParser)
void ParseFree (void *p, void(*freeProc)(void *))
static int yy_find_shift_action (yyParser *pParser, int iLookAhead)
static int yy_find_reduce_action (yyParser *pParser, int iLookAhead)
static void yy_shift (yyParser *yypParser, int yyNewState, int yyMajor, YYMINORTYPE *yypMinor)
static void yy_accept (yyParser *)
static void yy_reduce (yyParser *yypParser, int yyruleno)
static void yy_parse_failed (yyParser *yypParser)
static void yy_syntax_error (yyParser *yypParser, int yymajor, YYMINORTYPE yyminor)
void Parse (void *yyp, int yymajor, ParseTOKENTYPE yyminorParseARG_PDECL)
Variables
static FILE * yyTraceFILE = NULL
static char * yyTracePrompt = NULL
static const char * yyTokenName []
static const char * yyRuleName []
xx xx xx xx xx xx xx xx xx
struct {
 YYCODETYPE lhs
 unsigned char nrhs
} yyRuleInfo []
Macro Definition Documentation
#define INTERFACE 1
#define TOKEN (yyminor.yy0)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
Referenced by Parse().
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YY_SZ_ACTTAB (sizeof(yy_action)/sizeof(yy_action[0]))
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
Typedef Documentation
typedef struct yyParser yyParser
typedef struct yyStackEntry yyStackEntry
Function Documentation
void Parse (void * yyp, int yymajor, ParseTOKENTYPE yyminor ParseARG_PDECL)
References yyStackEntry::major, yyStackEntry::stateno, YYMINORTYPE::yy0, yy_accept(), yy_destructor(), YY_ERROR_ACTION, yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), yy_syntax_error(), yyParser::yyerrcnt, YYERRORSYMBOL, yyParser::yyidx, YYNOCODE, YYNRULE, YYNSTATE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
void* ParseAlloc (void *(*)(size_t) mallocProc)
References yyParser::yyidx.
void ParseFree (void * p, void(*)(void *) freeProc)
References yy_pop_parser_stack(), and yyParser::yyidx.
static void yy_accept (yyParser * yypParser) [static]
References yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), and yy_reduce().
static void yy_destructor (YYCODETYPE yymajor, YYMINORTYPE * yypminor) [static]
Referenced by Parse(), and yy_pop_parser_stack().
static int yy_find_reduce_action (yyParser * pParser, int iLookAhead) [static]
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_NO_ACTION, yy_reduce_ofst, YY_REDUCE_USE_DFLT, YY_SZ_ACTTAB, yyParser::yyidx, YYNOCODE, and yyParser::yystack.
Referenced by yy_reduce().
static int yy_find_shift_action (yyParser * pParser, int iLookAhead) [static]
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_NO_ACTION, yy_shift_ofst, YY_SHIFT_USE_DFLT, YY_SZ_ACTTAB, yyParser::yyidx, YYNOCODE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by Parse().
static void yy_parse_failed (yyParser * yypParser) [static]
References yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by Parse().
static int yy_pop_parser_stack (yyParser * pParser) [static]
References yyStackEntry::major, yyStackEntry::minor, yy_destructor(), YYCODETYPE, yyParser::yyidx, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), ParseFree(), yy_accept(), yy_parse_failed(), and yy_shift().
static void yy_reduce (yyParser * yypParser, int yyruleno) [static]
References yy_accept(), yy_find_reduce_action(), yy_shift(), yyParser::yyidx, YYNRULE, YYNSTATE, yyRuleInfo, yyRuleName, yyParser::yystack, yyTraceFILE, and yyTracePrompt.
Referenced by Parse().
static void yy_shift (yyParser * yypParser, int yyNewState, int yyMajor, YYMINORTYPE * yypMinor) [static]
References yyStackEntry::major, yyStackEntry::minor, yyStackEntry::stateno, yy_pop_parser_stack(), yyParser::yyidx, yyParser::yystack, YYSTACKDEPTH, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by Parse(), and yy_reduce().
static void yy_syntax_error (yyParser * yypParser, int yymajor, YYMINORTYPE yyminor) [static]
References UNUSED.
Referenced by Parse().
Variable Documentation
YYCODETYPE lhs
unsigned char nrhs
struct { ... } yyRuleInfo[] [static]
Initial value:
= {
%%
}
Referenced by yy_reduce().
const char* yyRuleName[] [static]
Initial value:
= {
%%
}
Referenced by yy_reduce().
const char* yyTokenName[] [static]
Initial value:
= {
%%
}
Referenced by Parse(), yy_find_shift_action(), yy_pop_parser_stack(), and yy_shift().
FILE* yyTraceFILE = NULL [static]
Referenced by Parse(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), and yy_shift().
char* yyTracePrompt = NULL [static]
Referenced by Parse(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), and yy_shift().