log.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `array.h`
*
#include <sys/types.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <time.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <stdarg.h>
*
#include <stdio.h>
*
Functions
int log_clock_gettime_realtime (struct timespec *ts)
ssize_t write_all (int fd, const void *buf, size_t count)
int openDevNull (int fd)
int open_logfile_or_pipe (server *srv, const char *logfile)
int log_error_open (server *srv)
int log_error_cycle (server *srv)
int log_error_close (server *srv)
static void log_buffer_append_printf (buffer *out, const char *fmt, va_list ap)
static int log_buffer_prepare (buffer *b, server *srv, const char *filename, unsigned int line)
static void log_write (server *srv, buffer *b)
int log_error_write (server *srv, const char *filename, unsigned int line, const char *fmt,...)
int log_error_write_multiline_buffer (server *srv, const char *filename, unsigned int line, buffer *multiline, const char *fmt,...)
Function Documentation
static void log_buffer_append_printf (buffer * out, const char * fmt, va_list ap) [static]
References buffer_append_int(), buffer_append_string_c_escaped(), buffer_append_string_len(), buffer_append_uint_hex(), CONST_BUF_LEN, and CONST_STR_LEN.
Referenced by log_error_write(), and log_error_write_multiline_buffer().
static int log_buffer_prepare (buffer * b, server * srv, const char * filename, unsigned int line) [static]
References buffer_append_int(), buffer_append_strftime(), buffer_append_string(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_string_prepare_copy(), CONST_STR_LEN, server::cur_ts, server::errorlog_fd, server::errorlog_mode, server::last_generated_debug_ts, and server::ts_debug_str.
Referenced by log_error_write(), and log_error_write_multiline_buffer().
int log_clock_gettime_realtime (struct timespec * ts)
Referenced by connection_handle_read_state(), connection_state_machine(), and REQUESTDONE_FUNC().
int log_error_close (server * srv)
References server::errorlog_fd, and server::errorlog_mode.
Referenced by main().
int log_error_cycle (server * srv)
open the errorlog
if the open failed, report to the user and die if no filename is given, use syslog instead
References server::errorlog_fd, server_config::errorlog_file, server::errorlog_mode, fd_close_on_exec(), log_error_write(), open_logfile_or_pipe(), buffer::ptr, and server::srvconf.
Referenced by main().
int log_error_open (server * srv)
open the errorlog
we have 4 possibilities:
stderr (default)
syslog
logfile
pipe
if the open failed, report to the user and die
References server_config::breakagelog_file, buffer_string_is_empty(), server_config::dont_daemonize, server::errorlog_fd, server_config::errorlog_file, server::errorlog_mode, server_config::errorlog_use_syslog, fd_close_on_exec(), log_error_write(), open_logfile_or_pipe(), openDevNull(), buffer::ptr, and server::srvconf.
Referenced by main().
int log_error_write (server * srv, const char * filename, unsigned int line, const char * fmt, ...)
References server::errorlog_buf, log_buffer_append_printf(), log_buffer_prepare(), and log_write().
Referenced by accesslog_parse_format(), accesslog_write_all(), build_doc_root(), cache_parse_lua(), cgi_connection_close(), cgi_create_env(), cgi_demux_response(), cgi_handle_fdevent(), cgi_handle_fdevent_send(), cgi_recv_response(), cgi_write_file_chunk_mmap(), cgi_write_request(), chunkqueue_append_mem_to_tempfile(), config_addrbuf_eq_remote_ip_mask(), config_addrstr_eq_remote_ip_mask(), config_check_cond(), config_check_cond_cached(), config_check_cond_nocache(), config_insert(), config_insert_values_internal(), config_parse(), config_parse_cmd(), config_parse_file(), config_parse_file_stream(), config_set_defaults(), config_tokenizer(), connection_accept(), connection_accepted(), connection_close(), CONNECTION_FUNC(), connection_handle_fdevent(), connection_handle_read(), connection_handle_read_post_chunked(), connection_handle_read_ssl(), connection_handle_read_state(), connection_handle_shutdown(), connection_handle_write(), connection_handle_write_prepare(), connection_state_machine(), deflate_compress_cleanup(), deflate_compress_response(), deflate_file_to_buffer(), deflate_file_to_file(), fastcgi_get_packet(), fcgi_backend_close(), fcgi_check_extension(), fcgi_demux_response(), fcgi_establish_connection(), fcgi_extension_host_get(), fcgi_handle_fdevent(), fcgi_host_disable(), fcgi_recv_response(), fcgi_response_parse(), fcgi_restart_dead_procs(), fcgi_stdin_append(), fcgi_write_request(), fdevent_freebsd_kqueue_init(), fdevent_init(), fdevent_libev_init(), fdevent_linux_sysepoll_init(), fdevent_poll_init(), fdevent_sched_run(), fdevent_solaris_devpoll_init(), fdevent_solaris_port_init(), http_list_directory(), http_request_parse(), http_response_prepare(), http_response_redirect_to_directory(), http_response_send_file(), http_response_write_header(), http_response_xsendfile(), log_error_cycle(), log_error_open(), magnet_atpanic(), magnet_attract(), magnet_print(), main(), mod_auth_check_basic(), mod_auth_check_digest(), mod_auth_require_parse(), mod_authn_file_htdigest_get(), mod_authn_file_htpasswd_get(), mod_authn_gssapi_basic(), mod_authn_gssapi_check_spnego(), mod_authn_gssapi_create_krb5_ccache(), mod_authn_gssapi_log_gss_error(), mod_authn_gssapi_log_krb5_error(), mod_authn_gssapi_verify_krb5_init_creds(), mod_authn_ldap_basic(), mod_authn_ldap_err(), mod_authn_ldap_get_dn(), mod_authn_ldap_host_init(), mod_authn_ldap_search(), mod_authn_mysql_query(), mod_authn_mysql_result(), mod_authn_mysql_sock_connect(), mod_deflate_file_chunk(), mod_evhost_uri_handler(), mod_expire_get_offset(), mod_mysql_vhost_connection_data(), mod_proxy_check_extension(), mod_proxy_extension_host_get(), mod_redirect_uri_handler(), mod_rrd_create_pipe(), mod_rrdtool_create_rrd(), mod_ssi_process_file(), mod_ssi_read_fd(), network_init(), network_open_file_chunk(), network_server_handle_fdevent(), network_server_init(), network_write_file_chunk_no_mmap(), network_write_mem_chunk(), open_logfile_or_pipe(), parse_config_entry(), pcre_keyvalue_buffer_append(), PHYSICALPATH_FUNC(), plugins_call_init(), plugins_load(), process_ssi_stmt(), proxy_create_env(), proxy_demux_response(), proxy_establish_connection(), proxy_handle_fdevent(), proxy_send_request(), proxy_write_request(), remove_pid_file(), scgi_backend_close(), scgi_check_extension(), scgi_demux_response(), scgi_establish_connection(), scgi_extension_host_get(), scgi_handle_fdevent(), scgi_proclist_sort_down(), scgi_proclist_sort_up(), scgi_recv_response(), scgi_restart_dead_procs(), scgi_send_request(), scgi_write_request(), secdl_verify_mac(), SERVER_FUNC(), server_oneshot_getsock(), server_oneshot_init(), SETDEFAULTS_FUNC(), SIGHUP_FUNC(), ssi_eval_expr(), ssi_expr_tokenizer(), stat_cache_get_entry(), SUBREQUEST_FUNC(), TRIGGER_FUNC(), URIHANDLER_FUNC(), and webdav_copy_file().
int log_error_write_multiline_buffer (server * srv, const char * filename, unsigned int line, buffer * multiline, const char * fmt, ...)
References buffer_append_string_len(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), server::errorlog_buf, log_buffer_append_printf(), log_buffer_prepare(), log_write(), and buffer::ptr.
Referenced by fcgi_demux_response().
static void log_write (server * srv, buffer * b) [static]
References buffer_append_string_len(), CONST_BUF_LEN, CONST_STR_LEN, server::errorlog_fd, server::errorlog_mode, buffer::ptr, and write_all().
Referenced by log_error_write(), and log_error_write_multiline_buffer().
int open_logfile_or_pipe (server * srv, const char * logfile)
References fd_close_on_exec(), log_error_write(), O_LARGEFILE, and openDevNull().
Referenced by log_error_cycle(), log_error_open(), and SETDEFAULTS_FUNC().
int openDevNull (int fd)
Referenced by log_error_open(), main(), and open_logfile_or_pipe().
ssize_t write_all (int fd, const void * buf, size_t count)
References force_assert.
Referenced by accesslog_write_all(), log_write(), main(), show_help(), and show_version().