md5.c File Reference
#include `first.h`
*
#include `md5.h`
*
#include <string.h>
*
Macros
#define S11 7
#define S12 12
#define S13 17
#define S14 22
#define S21 5
#define S22 9
#define S23 14
#define S24 20
#define S31 4
#define S32 11
#define S33 16
#define S34 23
#define S41 6
#define S42 10
#define S43 15
#define S44 21
#define F(x, y, z) (((x) & (y)) | ((~x) & (z)))
#define G(x, y, z) (((x) & (z)) | ((y) & (~z)))
#define H(x, y, z) ((x) ^ (y) ^ (z))
#define I(x, y, z) ((y) ^ ((x) | (~z)))
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32-(n))))
#define FF(a, b, c, d, x, s, ac)
#define GG(a, b, c, d, x, s, ac)
#define HH(a, b, c, d, x, s, ac)
#define II(a, b, c, d, x, s, ac)
Functions
static void li_MD5Transform (UINT4[4], const unsigned char[64])
static void Encode (unsigned char *, UINT4 *, unsigned int)
static void Decode (UINT4 *, const unsigned char *, unsigned int)
static void MD5_memcpy (POINTER, POINTER, unsigned int)
static void MD5_memset (POINTER, int, unsigned int)
void li_MD5_Init (li_MD5_CTX *context)
void li_MD5_Update (li_MD5_CTX *context, const void *_input, unsigned int inputLen)
void li_MD5_Final (unsigned char digest[16], li_MD5_CTX *context)
Variables
static unsigned char PADDING [64]
Macro Definition Documentation
#define F(x, y, z) (((x) & (y)) | ((~x) & (z)))
#define FF(a, b, c, d, x, s, ac)
Value:
{ \
 (a) += F ((b), (c), (d)) + (x) + (UINT4)(ac); \
 (a) = ROTATE_LEFT ((a), (s)); \
 (a) += (b); \
  }
Referenced by li_MD5Transform().
#define G(x, y, z) (((x) & (z)) | ((y) & (~z)))
#define GG(a, b, c, d, x, s, ac)
Value:
{ \
 (a) += G ((b), (c), (d)) + (x) + (UINT4)(ac); \
 (a) = ROTATE_LEFT ((a), (s)); \
 (a) += (b); \
  }
Referenced by li_MD5Transform().
#define H(x, y, z) ((x) ^ (y) ^ (z))
#define HH(a, b, c, d, x, s, ac)
Value:
{ \
 (a) += H ((b), (c), (d)) + (x) + (UINT4)(ac); \
 (a) = ROTATE_LEFT ((a), (s)); \
 (a) += (b); \
  }
Referenced by li_MD5Transform().
#define I(x, y, z) ((y) ^ ((x) | (~z)))
#define II(a, b, c, d, x, s, ac)
Value:
{ \
 (a) += I ((b), (c), (d)) + (x) + (UINT4)(ac); \
 (a) = ROTATE_LEFT ((a), (s)); \
 (a) += (b); \
  }
Referenced by li_MD5Transform().
#define ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32-(n))))
#define S11 7
Referenced by li_MD5Transform().
#define S12 12
Referenced by li_MD5Transform().
#define S13 17
Referenced by li_MD5Transform().
#define S14 22
Referenced by li_MD5Transform().
#define S21 5
Referenced by li_MD5Transform().
#define S22 9
Referenced by li_MD5Transform().
#define S23 14
Referenced by li_MD5Transform().
#define S24 20
Referenced by li_MD5Transform().
#define S31 4
Referenced by li_MD5Transform().
#define S32 11
Referenced by li_MD5Transform().
#define S33 16
Referenced by li_MD5Transform().
#define S34 23
Referenced by li_MD5Transform().
#define S41 6
Referenced by li_MD5Transform().
#define S42 10
Referenced by li_MD5Transform().
#define S43 15
Referenced by li_MD5Transform().
#define S44 21
Referenced by li_MD5Transform().
Function Documentation
static void Decode (UINT4 * output, const unsigned char * input, unsigned int len) [static]
References UINT4.
Referenced by li_MD5Transform().
static void Encode (unsigned char * output, UINT4 * input, unsigned int len) [static]
Referenced by li_MD5_Final().
void li_MD5_Final (unsigned char digest[16], li_MD5_CTX * context)
References li_MD5_CTX::count, Encode(), li_MD5_Update(), MD5_memset(), PADDING, POINTER, and li_MD5_CTX::state.
Referenced by apr_md5_encode(), f_crypto_md5(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_plain_digest(), mod_authn_mysql_password_cmp(), secdl_verify_mac(), and URIHANDLER_FUNC().
void li_MD5_Init (li_MD5_CTX * context)
References li_MD5_CTX::count, and li_MD5_CTX::state.
Referenced by apr_md5_encode(), f_crypto_md5(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_plain_digest(), mod_authn_mysql_password_cmp(), secdl_verify_mac(), and URIHANDLER_FUNC().
void li_MD5_Update (li_MD5_CTX * context, const void * _input, unsigned int inputLen)
References li_MD5_CTX::buffer, li_MD5_CTX::count, li_MD5Transform(), MD5_memcpy(), POINTER, li_MD5_CTX::state, and UINT4.
Referenced by apr_md5_encode(), f_crypto_md5(), li_MD5_Final(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_plain_digest(), mod_authn_mysql_password_cmp(), secdl_verify_mac(), and URIHANDLER_FUNC().
static void li_MD5Transform (UINT4 state[4], const unsigned char block[64]) [static]
References Decode(), FF, GG, HH, II, MD5_memset(), POINTER, S11, S12, S13, S14, S21, S22, S23, S24, S31, S32, S33, S34, S41, S42, S43, S44, and UINT4.
Referenced by li_MD5_Update().
static void MD5_memcpy (POINTER output, POINTER input, unsigned int len) [static]
Referenced by li_MD5_Update().
static void MD5_memset (POINTER output, int value, unsigned int len) [static]
Referenced by li_MD5_Final(), and li_MD5Transform().
Variable Documentation
unsigned char PADDING[64] [static]
Initial value:
= {
  0x80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
}
Referenced by li_MD5_Final().