md5.h File Reference
#include `first.h`
*
#include <limits.h>
*
Classes
struct li_MD5_CTX
Macros
#define UINT4 uint32_t
#define UINT2 uint16_t
#define POINTER unsigned char *
Functions
void li_MD5_Init (li_MD5_CTX *)
void li_MD5_Update (li_MD5_CTX *, const void *, unsigned int)
void li_MD5_Final (unsigned char[16], li_MD5_CTX *)
Macro Definition Documentation
#define POINTER unsigned char *
Referenced by li_MD5_Final(), li_MD5_Update(), and li_MD5Transform().
#define UINT2 uint16_t
#define UINT4 uint32_t
Referenced by Decode(), li_MD5_Update(), and li_MD5Transform().
Function Documentation
void li_MD5_Final (unsigned char[16], li_MD5_CTX *)
References li_MD5_CTX::count, Encode(), li_MD5_Update(), MD5_memset(), PADDING, POINTER, and li_MD5_CTX::state.
Referenced by apr_md5_encode(), f_crypto_md5(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_plain_digest(), mod_authn_mysql_password_cmp(), secdl_verify_mac(), and URIHANDLER_FUNC().
void li_MD5_Init (li_MD5_CTX *)
References li_MD5_CTX::count, and li_MD5_CTX::state.
Referenced by apr_md5_encode(), f_crypto_md5(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_plain_digest(), mod_authn_mysql_password_cmp(), secdl_verify_mac(), and URIHANDLER_FUNC().
void li_MD5_Update (li_MD5_CTX * , const void * , unsigned int)
References li_MD5_CTX::buffer, li_MD5_CTX::count, li_MD5Transform(), MD5_memcpy(), POINTER, li_MD5_CTX::state, and UINT4.
Referenced by apr_md5_encode(), f_crypto_md5(), li_MD5_Final(), mod_auth_check_digest(), mod_auth_send_401_unauthorized_digest(), mod_authn_file_htdigest_basic(), mod_authn_file_plain_digest(), mod_authn_mysql_password_cmp(), secdl_verify_mac(), and URIHANDLER_FUNC().