mod_accesslog.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <time.h>
*
#include <stdio.h>
*
Classes
struct format_mapping
struct format_field
struct format_fields
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Enumerations
enum e_optflags_time {
*
FORMAT_FLAG_TIME_END = 0x00,
FORMAT_FLAG_TIME_BEGIN = 0x01,
FORMAT_FLAG_TIME_SEC = 0x02,
FORMAT_FLAG_TIME_MSEC = 0x04,
*
FORMAT_FLAG_TIME_USEC = 0x08,
FORMAT_FLAG_TIME_NSEC = 0x10,
FORMAT_FLAG_TIME_MSEC_FRAC = 0x20,
FORMAT_FLAG_TIME_USEC_FRAC = 0x40,
*
FORMAT_FLAG_TIME_NSEC_FRAC = 0x80
 }
Functions
INIT_FUNC (mod_accesslog_init)
static void accesslog_write_all (server *srv, const buffer *filename, int fd, const void *buf, size_t count)
static void accesslog_append_escaped (buffer *dest, buffer *str)
static int accesslog_parse_format (server *srv, format_fields *fields, buffer *format)
FREE_FUNC (mod_accesslog_free)
SETDEFAULTS_FUNC (log_access_open)
SIGHUP_FUNC (log_access_cycle)
static int mod_accesslog_patch_connection (server *srv, connection *con, plugin_data *p)
REQUESTDONE_FUNC (log_access_write)
int mod_accesslog_plugin_init (plugin *p)
Variables
static const format_mapping fmap []
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_accesslog_patch_connection().
Enumeration Type Documentation
enum e_optflags_time
Enumerator
FORMAT_FLAG_TIME_END
FORMAT_FLAG_TIME_BEGIN
FORMAT_FLAG_TIME_SEC
FORMAT_FLAG_TIME_MSEC
FORMAT_FLAG_TIME_USEC
FORMAT_FLAG_TIME_NSEC
FORMAT_FLAG_TIME_MSEC_FRAC
FORMAT_FLAG_TIME_USEC_FRAC
FORMAT_FLAG_TIME_NSEC_FRAC
Function Documentation
static void accesslog_append_escaped (buffer * dest, buffer * str) [static]
References BUFFER_APPEND_STRING_CONST, buffer_append_string_len(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_append(), and buffer::ptr.
Referenced by REQUESTDONE_FUNC().
static int accesslog_parse_format (server * srv, format_fields * fields, buffer * format) [static]
References buffer_copy_string_len(), buffer_init(), buffer_is_empty(), buffer_string_length(), format_field::field, format_mapping::key, log_error_write(), format_field::opt, buffer::ptr, format_fields::ptr, format_fields::size, format_field::string, format_mapping::type, format_field::type, and format_fields::used.
Referenced by SETDEFAULTS_FUNC().
static void accesslog_write_all (server * srv, const buffer * filename, int fd, const void * buf, size_t count) [static]
References log_error_write(), and write_all().
Referenced by FREE_FUNC(), REQUESTDONE_FUNC(), and SIGHUP_FUNC().
FREE_FUNC (mod_accesslog_free)
References plugin_config::access_logbuffer, plugin_config::access_logfile, accesslog_write_all(), buffer_free(), buffer_string_is_empty(), plugin_data::config_storage, CONST_BUF_LEN, plugin_config::format, HANDLER_GO_ON, plugin_config::log_access_fd, plugin_config::parsed_format, format_fields::ptr, format_field::string, plugin_data::syslog_logbuffer, plugin_config::ts_accesslog_str, and format_fields::used.
INIT_FUNC (mod_accesslog_init)
References buffer_init(), and plugin_data::syslog_logbuffer.
static int mod_accesslog_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by REQUESTDONE_FUNC().
int mod_accesslog_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_request_done, plugin::handle_sighup, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
REQUESTDONE_FUNC (log_access_write)
References plugin_config::access_logbuffer, plugin_config::access_logfile, accesslog_append_escaped(), accesslog_write_all(), array_get_element(), buffer_append_int(), buffer_append_strftime(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), BUFFER_MAX_REUSE_SIZE, buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_copy(), buffer_string_set_length(), CON_STATE_RESPONSE_END, plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, format_field::field, FORMAT_FLAG_TIME_BEGIN, FORMAT_FLAG_TIME_END, FORMAT_FLAG_TIME_MSEC, FORMAT_FLAG_TIME_MSEC_FRAC, FORMAT_FLAG_TIME_NSEC, FORMAT_FLAG_TIME_SEC, FORMAT_FLAG_TIME_USEC, FORMAT_FLAG_TIME_USEC_FRAC, get_http_method_name(), HANDLER_GO_ON, HTTP_VERSION_1_1, plugin_config::last_generated_accesslog_ts_ptr, plugin_config::log_access_fd, log_clock_gettime_realtime(), mod_accesslog_patch_connection(), format_field::opt, plugin_config::parsed_format, buffer::ptr, format_fields::ptr, format_field::string, plugin_config::syslog_level, plugin_data::syslog_logbuffer, plugin_config::ts_accesslog_str, format_field::type, plugin_config::use_syslog, format_fields::used, and data_string::value.
SETDEFAULTS_FUNC (log_access_open)
References plugin_config::access_logfile, accesslog_parse_format(), buffer_copy_string_len(), buffer_init(), buffer_is_empty(), buffer_is_equal_string(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, CONST_STR_LEN, config_values_t::destination, format_field::field, FORMAT_FLAG_TIME_BEGIN, FORMAT_FLAG_TIME_END, FORMAT_FLAG_TIME_MSEC, FORMAT_FLAG_TIME_MSEC_FRAC, FORMAT_FLAG_TIME_NSEC, FORMAT_FLAG_TIME_NSEC_FRAC, FORMAT_FLAG_TIME_SEC, FORMAT_FLAG_TIME_USEC, FORMAT_FLAG_TIME_USEC_FRAC, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), open_logfile_or_pipe(), format_field::opt, buffer::ptr, format_field::string, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, format_field::type, and data_config::value.
SIGHUP_FUNC (log_access_cycle)
References plugin_config::access_logbuffer, plugin_config::access_logfile, accesslog_write_all(), buffer_reset(), buffer_string_is_empty(), plugin_data::config_storage, CONST_BUF_LEN, fdevent_open_cloexec(), HANDLER_ERROR, HANDLER_GO_ON, plugin_config::log_access_fd, log_error_write(), O_LARGEFILE, buffer::ptr, and plugin_config::use_syslog.
Variable Documentation
const format_mapping fmap[] [static]
`%h %l %u %t \`r" %>s b "%{Referer}i" "%{User-Agent}i""