mod_auth.c File Reference
#include `first.h`
*
#include `plugin.h`
*
#include `http_auth.h`
*
#include `log.h`
*
#include <stdlib.h>
*
#include <string.h>
*
#include `response.h`
*
#include `base64.h`
*
#include `md5.h`
*
#include `rand.h`
*
Classes
struct plugin_config
struct plugin_data
struct data_auth
struct digest_kv
Macros
#define PATCH(x) p->conf.x = s->x;
#define HASHLEN 16
#define HASHHEXLEN 32
#define S(x) x, sizeof(x)-1, NULL
Typedefs
typedef unsigned char HASH [HASHLEN]
typedef char HASHHEX [HASHHEXLEN+1]
Functions
static handler_t mod_auth_check_basic (server *srv, connection *con, void *p_d, const struct http_auth_require_t *require, const struct http_auth_backend_t *backend)
static handler_t mod_auth_check_digest (server *srv, connection *con, void *p_d, const struct http_auth_require_t *require, const struct http_auth_backend_t *backend)
static handler_t mod_auth_check_extern (server *srv, connection *con, void *p_d, const struct http_auth_require_t *require, const struct http_auth_backend_t *backend)
INIT_FUNC (mod_auth_init)
FREE_FUNC (mod_auth_free)
static void data_auth_free (data_unset *d)
static data_auth * data_auth_init (void)
static int mod_auth_require_parse (server *srv, http_auth_require_t *const require, const buffer *b)
SETDEFAULTS_FUNC (mod_auth_set_defaults)
static int mod_auth_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t mod_auth_uri_handler (server *srv, connection *con, void *p_d)
int mod_auth_plugin_init (plugin *p)
static handler_t mod_auth_send_400_bad_request (server *srv, connection *con)
static handler_t mod_auth_send_401_unauthorized_basic (server *srv, connection *con, buffer *realm)
static void CvtHex (const HASH Bin, char(*Hex)[33])
static handler_t mod_auth_send_401_unauthorized_digest (server *srv, connection *con, buffer *realm, int nonce_stale)
Macro Definition Documentation
#define HASHHEXLEN 32
Referenced by mod_auth_check_digest().
#define HASHLEN 16
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_auth_patch_connection().
#define S(x) x, sizeof(x)-1, NULL
Referenced by mod_auth_check_digest().
Typedef Documentation
typedef unsigned char HASH[HASHLEN]
typedef char HASHHEX[HASHHEXLEN+1]
Function Documentation
static void CvtHex (const HASH Bin, char(*) Hex[33]) [static]
References li_tohex().
Referenced by mod_auth_check_digest(), and mod_auth_send_401_unauthorized_digest().
static void data_auth_free (data_unset * d) [static]
References buffer_free(), http_auth_require_free(), and data_auth::require.
Referenced by data_auth_init().
static data_auth* data_auth_init (void) [static]
References buffer_init(), data_auth_free(), force_assert, http_auth_require_init(), data_auth::require, and TYPE_OTHER.
Referenced by SETDEFAULTS_FUNC().
FREE_FUNC (mod_auth_free)
References array_free(), plugin_config::auth_backend_conf, plugin_config::auth_require, buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_auth_init)
References http_auth_scheme_set(), mod_auth_check_basic(), mod_auth_check_digest(), and mod_auth_check_extern().
static handler_t mod_auth_check_basic (server * srv, connection * con, void * p_d, const struct http_auth_require_t * require, const struct http_auth_backend_t * backend) [static]
References array_get_element(), BASE64_STANDARD, http_auth_backend_t::basic, buffer_append_base64_decode(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_string_length(), buffer_string_set_length(), CONST_BUF_LEN, CONST_STR_LEN, DIRECT, connection::dst_addr_buf, connection::environment, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_UNSET, HANDLER_WAIT_FOR_EVENT, request::headers, http_auth_setenv(), connection::http_status, log_error_write(), mod_auth_send_400_bad_request(), mod_auth_send_401_unauthorized_basic(), connection::mode, http_auth_backend_t::p_d, request_uri::path, buffer::ptr, http_auth_require_t::realm, connection::request, UNUSED, connection::uri, and data_string::value.
Referenced by INIT_FUNC().
static handler_t mod_auth_check_digest (server * srv, connection * con, void * p_d, const struct http_auth_require_t * require, const struct http_auth_backend_t * backend) [static]
protect the md5-sess against missing cnonce and nonce
References array_get_element(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal_string(), buffer_string_length(), CONST_STR_LEN, server::cur_ts, CvtHex(), http_auth_backend_t::digest, DIRECT, connection::dst_addr_buf, connection::environment, force_assert, get_http_method_name(), HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, HASHHEXLEN, request::headers, hex2int(), http_auth_match_rules(), http_auth_setenv(), request::http_method, connection::http_status, digest_kv::key, li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), light_isxdigit(), log_error_write(), mod_auth_send_400_bad_request(), mod_auth_send_401_unauthorized_digest(), connection::mode, request::orig_uri, http_auth_backend_t::p_d, request_uri::path, buffer::ptr, digest_kv::ptr, http_auth_require_t::realm, connection::request, S, UNUSED, connection::uri, and data_string::value.
Referenced by INIT_FUNC().
static handler_t mod_auth_check_extern (server * srv, connection * con, void * p_d, const struct http_auth_require_t * require, const struct http_auth_backend_t * backend) [static]
References array_get_element(), DIRECT, connection::environment, HANDLER_FINISHED, HANDLER_GO_ON, http_auth_match_rules(), connection::http_status, connection::mode, buffer::ptr, UNUSED, and data_string::value.
Referenced by INIT_FUNC().
static int mod_auth_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_auth_uri_handler().
int mod_auth_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_uri_clean, plugin::init, mod_auth_uri_handler(), plugin::name, plugin::set_defaults, and plugin::version.
static int mod_auth_require_parse (server * srv, http_auth_require_t *const require, const buffer * b) [static]
References array_insert_unique(), buffer_copy_string_len(), buffer_is_equal_string(), CONST_STR_LEN, data_string_init(), http_auth_require_t::group, http_auth_require_t::host, log_error_write(), buffer::ptr, http_auth_require_t::user, and http_auth_require_t::valid_user.
Referenced by SETDEFAULTS_FUNC().
static handler_t mod_auth_send_400_bad_request (server * srv, connection * con) [static]
References DIRECT, HANDLER_FINISHED, connection::http_status, connection::mode, and UNUSED.
Referenced by mod_auth_check_basic(), and mod_auth_check_digest().
static handler_t mod_auth_send_401_unauthorized_basic (server * srv, connection * con, buffer * realm) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), CONST_BUF_LEN, CONST_STR_LEN, DIRECT, HANDLER_FINISHED, connection::http_status, connection::mode, response_header_insert(), and server::tmp_buf.
Referenced by mod_auth_check_basic().
static handler_t mod_auth_send_401_unauthorized_digest (server * srv, connection * con, buffer * realm, int nonce_stale) [static]
References buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_append_uint_hex(), buffer_copy_string_len(), CONST_BUF_LEN, CONST_STR_LEN, server::cur_ts, CvtHex(), DIRECT, force_assert, HANDLER_FINISHED, connection::http_status, LI_ITOSTRING_LENGTH, li_itostrn(), li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), li_rand_pseudo_bytes(), connection::mode, response_header_insert(), and server::tmp_buf.
Referenced by mod_auth_check_digest().
static handler_t mod_auth_uri_handler (server * srv, connection * con, void * p_d) [static]
References plugin_config::auth_backend, plugin_config::auth_require, buffer_string_length(), http_auth_scheme_t::checkfn, plugin_data::conf, connection::conf, array::data, specific_config::force_lowercase_filenames, HANDLER_GO_ON, mod_auth_patch_connection(), http_auth_scheme_t::p_d, request_uri::path, buffer::ptr, data_auth::require, http_auth_require_t::scheme, connection::uri, and array::used.
Referenced by mod_auth_plugin_init().
SETDEFAULTS_FUNC (mod_auth_set_defaults)
References array_get_element(), array_init(), array_insert_unique(), buffer_copy_buffer(), buffer_init(), buffer_is_empty(), buffer_is_equal_string(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, CONST_STR_LEN, array::data, data_auth_init(), config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, http_auth_backend_get(), http_auth_scheme_get(), log_error_write(), mod_auth_require_parse(), http_auth_require_t::realm, data_auth::require, http_auth_require_t::scheme, T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, TYPE_ARRAY, TYPE_STRING, array::used, data_string::value, data_array::value, and data_config::value.