mod_magnet_cache.c File Reference
#include `first.h`
*
#include `mod_magnet_cache.h`
*
#include `stat_cache.h`
*
#include <stdlib.h>
*
#include <time.h>
*
#include <assert.h>
*
#include <lualib.h>
*
#include <lauxlib.h>
*
Functions
static script * script_init ()
static void script_free (script *sc)
script_cache * script_cache_init ()
void script_cache_free (script_cache *p)
lua_State * script_cache_get_script (server *srv, connection *con, script_cache *cache, buffer *name)
Function Documentation
void script_cache_free (script_cache * p)
References script_cache::ptr, script_free(), and script_cache::used.
Referenced by FREE_FUNC().
lua_State* script_cache_get_script (server * srv, connection * con, script_cache * cache, buffer * name)
References buffer_copy_buffer(), buffer_is_equal(), script::etag, stat_cache_entry::etag, force_assert, HANDLER_ERROR, HANDLER_GO_ON, script::L, script::last_used, script::name, script_cache::ptr, buffer::ptr, script_init(), script_cache::size, stat_cache_get_entry(), and script_cache::used.
Referenced by magnet_attract().
script_cache* script_cache_init (void)
Referenced by INIT_FUNC().
static void script_free (script * sc) [static]
References buffer_free(), script::etag, script::L, and script::name.
Referenced by script_cache_free().
static script* script_init () [static]
References buffer_init(), script::etag, and script::name.
Referenced by script_cache_get_script().