mod_alias.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <stdio.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_alias_init)
FREE_FUNC (mod_alias_free)
SETDEFAULTS_FUNC (mod_alias_set_defaults)
static int mod_alias_patch_connection (server *srv, connection *con, plugin_data *p)
PHYSICALPATH_FUNC (mod_alias_physical_handler)
int mod_alias_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_alias_patch_connection().
Function Documentation
FREE_FUNC (mod_alias_free)
References plugin_config::alias, array_free(), plugin_data::config_storage, and HANDLER_GO_ON.
INIT_FUNC (mod_alias_init)
static int mod_alias_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by PHYSICALPATH_FUNC().
int mod_alias_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_physical, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
PHYSICALPATH_FUNC (mod_alias_physical_handler)
References plugin_config::alias, buffer_append_string(), buffer_copy_buffer(), buffer_is_empty(), buffer_string_length(), plugin_data::conf, array::data, HANDLER_GO_ON, mod_alias_patch_connection(), array::used, and data_string::value.
SETDEFAULTS_FUNC (mod_alias_set_defaults)
References plugin_config::alias, array_init(), buffer_string_length(), config_insert_values_global(), plugin_data::config_storage, array::data, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), buffer::ptr, array::sorted, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, array::used, and data_config::value.