mod_webdav.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `response.h`
*
#include `connections.h`
*
#include `plugin.h`
*
#include `stat_cache.h`
*
#include `sys-mmap.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <stdio.h>
*
#include <assert.h>
*
#include <unistd.h>
*
#include <dirent.h>
*
Classes
struct plugin_config
struct plugin_data
struct handler_ctx
struct webdav_property
struct webdav_properties
Macros
#define WEBDAV_FILE_MODE S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH
#define WEBDAV_DIR_MODE S_IRWXU | S_IRWXG | S_IRWXO
#define PATCH_OPTION(x) p->conf.x = s->x;
#define FIFO_NONBLOCK 0
Functions
INIT_FUNC (mod_webdav_init)
FREE_FUNC (mod_webdav_free)
SETDEFAULTS_FUNC (mod_webdav_set_defaults)
static int mod_webdav_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_webdav_uri_handler)
static int webdav_gen_prop_tag (server *srv, connection *con, char *prop_name, char *prop_ns, char *value, buffer *b)
static int webdav_gen_response_status_tag (server *srv, connection *con, physical *dst, int status, buffer *b)
static int webdav_delete_file (server *srv, connection *con, handler_ctx *hctx, physical *dst, buffer *b)
static int webdav_delete_dir (server *srv, connection *con, handler_ctx *hctx, physical *dst, buffer *b)
static int webdav_copy_file (server *srv, connection *con, handler_ctx *hctx, physical *src, physical *dst, int overwrite)
static int webdav_copy_dir (server *srv, connection *con, handler_ctx *hctx, physical *src, physical *dst, int overwrite)
static int webdav_get_live_property (server *srv, connection *con, handler_ctx *hctx, physical *dst, char *prop_name, buffer *b)
static int webdav_get_property (server *srv, connection *con, handler_ctx *hctx, physical *dst, char *prop_name, char *prop_ns, buffer *b)
static int webdav_get_props (server *srv, connection *con, handler_ctx *hctx, physical *dst, webdav_properties *props, buffer *b_200, buffer *b_404)
static int webdav_has_lock (server *srv, connection *con, handler_ctx *hctx, buffer *uri)
SUBREQUEST_FUNC (mod_webdav_subrequest_handler_huge)
SUBREQUEST_FUNC (mod_webdav_subrequest_handler)
PHYSICALPATH_FUNC (mod_webdav_physical_handler)
static handler_t mod_webdav_connection_reset (server *srv, connection *con, void *p_d)
int mod_webdav_plugin_init (plugin *p)
Variables
static webdav_property live_properties []
Macro Definition Documentation
#define FIFO_NONBLOCK 0
Referenced by SUBREQUEST_FUNC(), and webdav_copy_file().
#define PATCH_OPTION(x) p->conf.x = s->x;
Referenced by mod_webdav_patch_connection().
#define WEBDAV_DIR_MODE S_IRWXU | S_IRWXG | S_IRWXO
Referenced by SUBREQUEST_FUNC(), and webdav_copy_dir().
#define WEBDAV_FILE_MODE S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH
this is a webdav for a lighttpd plugin
at least a very basic one.
for now it is read-only and we only support PROPFIND
Referenced by SUBREQUEST_FUNC(), and webdav_copy_file().
Function Documentation
FREE_FUNC (mod_webdav_free)
References request_uri::authority, physical::basedir, buffer_free(), plugin_data::config_storage, physical::doc_root, HANDLER_GO_ON, request_uri::path, physical::path, request_uri::path_raw, plugin_data::physical, physical::rel_path, request_uri::scheme, plugin_config::sqlite_db_name, plugin_data::tmp_buf, UNUSED, and plugin_data::uri.
INIT_FUNC (mod_webdav_init)
References request_uri::authority, physical::basedir, buffer_init(), physical::doc_root, request_uri::path, physical::path, request_uri::path_raw, plugin_data::physical, physical::rel_path, request_uri::scheme, plugin_data::tmp_buf, and plugin_data::uri.
static handler_t mod_webdav_connection_reset (server * srv, connection * con, void * p_d) [static]
References HANDLER_GO_ON, connection::plugin_ctx, and UNUSED.
Referenced by mod_webdav_plugin_init().
static int mod_webdav_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH_OPTION, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_webdav_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_physical, plugin::handle_subrequest, plugin::handle_uri_clean, plugin::init, mod_webdav_connection_reset(), plugin::name, plugin::set_defaults, and plugin::version.
PHYSICALPATH_FUNC (mod_webdav_physical_handler)
References buffer_is_empty(), plugin_data::conf, handler_ctx::conf, connection::conf, plugin_config::enabled, HANDLER_GO_ON, request::http_method, HTTP_METHOD_COPY, HTTP_METHOD_DELETE, HTTP_METHOD_LOCK, HTTP_METHOD_MKCOL, HTTP_METHOD_MOVE, HTTP_METHOD_PROPFIND, HTTP_METHOD_PROPPATCH, HTTP_METHOD_PUT, HTTP_METHOD_UNLOCK, connection::mode, physical::path, connection::physical, connection::plugin_ctx, connection::request, specific_config::stream_request_body, and UNUSED.
SETDEFAULTS_FUNC (mod_webdav_set_defaults)
References buffer_init(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, CONST_STR_LEN, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), plugin_config::sqlite_db_name, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
SUBREQUEST_FUNC (mod_webdav_subrequest_handler_huge)
a mac wants to write
LOCK /dav/expire.txt HTTP/1.1
User-Agent: WebDAVFS/1.3 (01308000) Darwin/8.1.0 (Power Macintosh)
Accept: * / *
Depth: 0
Timeout: Second-600
Content-Type: text/xml; charset="utf-8"
Content-Length: 229
Connection: keep-alive
Host: 192.168.178.23:1025
<?xml version="1.0" encoding="utf-8"?>
<D:lockinfo xmlns:D="DAV:">
 <D:lockscope><D:exclusive/></D:lockscope>
 <D:locktype><D:write/></D:locktype>
 <D:owner>
 <D:href>http://www.apple.com/webdav_fs/</D:href>
 </D:owner>
</D:lockinfo>
References array_get_element(), request_uri::authority, physical::basedir, buffer_append_slash(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal(), buffer_is_equal_right_len(), buffer_path_simplify(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_to_lower(), buffer_urldecode_path(), chunkqueue::bytes_in, chunkqueue_append_buffer(), chunkqueue_mark_written(), CON_STATE_READ_POST, plugin_data::conf, handler_ctx::conf, connection::conf, connection_handle_read_post_state(), CONST_BUF_LEN, CONST_STR_LEN, request::content_length, physical::doc_root, plugin_config::enabled, ENCODING_REL_URI, chunk::fd, FIFO_NONBLOCK, chunk::file, connection::file_finished, chunkqueue::first, force_assert, specific_config::force_lowercase_filenames, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, request::headers, request::http_method, HTTP_METHOD_COPY, HTTP_METHOD_DELETE, HTTP_METHOD_LOCK, HTTP_METHOD_MKCOL, HTTP_METHOD_MOVE, HTTP_METHOD_PROPFIND, HTTP_METHOD_PROPPATCH, HTTP_METHOD_PUT, HTTP_METHOD_UNLOCK, http_response_redirect_to_directory(), connection::http_status, plugin_config::is_readonly, chunk::length, log_error_write(), plugin_config::log_xml, MAP_FAILED, chunk::mem, mmap, chunk::mmap, chunk::name, webdav_property::ns, O_BINARY, chunk::offset, request_uri::path, physical::path, request_uri::path_raw, plugin_data::physical, connection::physical, connection::plugin_ctx, webdav_property::prop, PROT_READ, buffer::ptr, webdav_properties::ptr, physical::rel_path, connection::request, connection::request_content_queue, response_header_overwrite(), request_uri::scheme, webdav_properties::size, stat_cache_entry::st, chunk::start, stat_cache_get_entry(), connection::state, plugin_data::tmp_buf, chunk::type, UNUSED, plugin_data::uri, connection::uri, webdav_properties::used, data_string::value, webdav_copy_dir(), webdav_copy_file(), webdav_delete_dir(), webdav_delete_file(), WEBDAV_DIR_MODE, WEBDAV_FILE_MODE, webdav_get_props(), webdav_has_lock(), and connection::write_queue.
SUBREQUEST_FUNC (mod_webdav_subrequest_handler)
References DIRECT, HANDLER_GO_ON, connection::http_status, and connection::mode.
URIHANDLER_FUNC (mod_webdav_uri_handler)
References buffer_is_empty(), plugin_data::conf, CONST_STR_LEN, plugin_config::enabled, HANDLER_GO_ON, HTTP_METHOD_OPTIONS, plugin_config::is_readonly, mod_webdav_patch_connection(), response_header_insert(), response_header_overwrite(), and UNUSED.
static int webdav_copy_dir (server * srv, connection * con, handler_ctx * hctx, physical * src, physical * dst, int overwrite) [static]
References buffer_append_slash(), buffer_append_string(), buffer_copy_buffer(), buffer_free(), buffer_init(), handler_ctx::conf, CONST_BUF_LEN, physical::path, buffer::ptr, physical::rel_path, webdav_copy_file(), and WEBDAV_DIR_MODE.
Referenced by SUBREQUEST_FUNC().
static int webdav_copy_file (server * srv, connection * con, handler_ctx * hctx, physical * src, physical * dst, int overwrite) [static]
References handler_ctx::conf, CONST_BUF_LEN, FIFO_NONBLOCK, force_assert, log_error_write(), O_BINARY, physical::path, buffer::ptr, physical::rel_path, UNUSED, and WEBDAV_FILE_MODE.
Referenced by SUBREQUEST_FUNC(), and webdav_copy_dir().
static int webdav_delete_dir (server * srv, connection * con, handler_ctx * hctx, physical * dst, buffer * b) [static]
References buffer_append_slash(), buffer_append_string(), buffer_copy_buffer(), buffer_free(), buffer_init(), handler_ctx::conf, CONST_BUF_LEN, physical::path, buffer::ptr, physical::rel_path, webdav_delete_file(), and webdav_gen_response_status_tag().
Referenced by SUBREQUEST_FUNC().
static int webdav_delete_file (server * srv, connection * con, handler_ctx * hctx, physical * dst, buffer * b) [static]
References handler_ctx::conf, CONST_BUF_LEN, physical::path, buffer::ptr, physical::rel_path, UNUSED, and webdav_gen_response_status_tag().
Referenced by SUBREQUEST_FUNC(), and webdav_delete_dir().
static int webdav_gen_prop_tag (server * srv, connection * con, char * prop_name, char * prop_ns, char * value, buffer * b) [static]
References buffer_append_string(), buffer_append_string_len(), CONST_STR_LEN, and UNUSED.
Referenced by webdav_get_property(), and webdav_get_props().
static int webdav_gen_response_status_tag (server * srv, connection * con, physical * dst, int status, buffer * b) [static]
References buffer_append_int(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), CONST_STR_LEN, get_http_status_name(), request::http_version, HTTP_VERSION_1_1, physical::rel_path, connection::request, and UNUSED.
Referenced by webdav_delete_dir(), and webdav_delete_file().
static int webdav_get_live_property (server * srv, connection * con, handler_ctx * hctx, physical * dst, char * prop_name, buffer * b) [static]
References buffer_append_int(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_is_empty(), buffer_is_equal_right_len(), buffer_reset(), buffer_string_length(), connection::conf, CONST_STR_LEN, array::data, physical::etag, etag_create(), connection::etag_flags, HANDLER_ERROR, specific_config::mimetypes, physical::path, connection::physical, stat_cache_entry::st, stat_cache_get_entry(), UNUSED, array::used, and data_string::value.
Referenced by webdav_get_property(), and webdav_get_props().
static int webdav_get_property (server * srv, connection * con, handler_ctx * hctx, physical * dst, char * prop_name, char * prop_ns, buffer * b) [static]
References handler_ctx::conf, CONST_BUF_LEN, physical::rel_path, webdav_gen_prop_tag(), and webdav_get_live_property().
Referenced by webdav_get_props().
static int webdav_get_props (server * srv, connection * con, handler_ctx * hctx, physical * dst, webdav_properties * props, buffer * b_200, buffer * b_404) [static]
References webdav_property::ns, webdav_property::prop, webdav_properties::ptr, webdav_properties::used, webdav_gen_prop_tag(), webdav_get_live_property(), and webdav_get_property().
Referenced by SUBREQUEST_FUNC().
static int webdav_has_lock (server * srv, connection * con, handler_ctx * hctx, buffer * uri) [static]
check if resource is having the right locks to access to resource
References array_get_element(), handler_ctx::conf, CONST_BUF_LEN, request::headers, connection::request, and UNUSED.
Referenced by SUBREQUEST_FUNC().
Variable Documentation
webdav_property live_properties[] [static]
Initial value:
= {
    { "DAV:", "creationdate" },
    
    { "DAV:", "getcontentlanguage" },
    { "DAV:", "getcontentlength" },
    { "DAV:", "getcontenttype" },
    { "DAV:", "getetag" },
    { "DAV:", "getlastmodified" },
    { "DAV:", "resourcetype" },
    
    { NULL, NULL }
}