mod_access.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_access_init)
FREE_FUNC (mod_access_free)
SETDEFAULTS_FUNC (mod_access_set_defaults)
static int mod_access_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_access_uri_handler)
int mod_access_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_access_patch_connection().
Function Documentation
FREE_FUNC (mod_access_free)
References plugin_config::access_allow, plugin_config::access_deny, array_free(), plugin_data::config_storage, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_access_init)
static int mod_access_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_access_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_subrequest_start, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_access_set_defaults)
References plugin_config::access_deny, array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_access_uri_handler)
URI handler
we will get called twice:
after the clean up of the URL and
after the pathinfo checks are done
this handles the issue of trailing slashes
References plugin_config::access_allow, plugin_config::access_deny, buffer_is_empty(), buffer_string_length(), plugin_data::conf, array::data, DIRECT, HANDLER_FINISHED, HANDLER_GO_ON, log_error_write(), mod_access_patch_connection(), buffer::ptr, array::used, and data_string::value.