mod_magnet.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `http_chunk.h`
*
#include `plugin.h`
*
#include `mod_magnet_cache.h`
*
#include `response.h`
*
#include `stat_cache.h`
*
#include `status_counter.h`
*
#include `etag.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <assert.h>
*
#include <setjmp.h>
*
#include <lua.h>
*
#include <lauxlib.h>
*
Classes
struct plugin_config
struct plugin_data
struct const_buffer
struct magnet_env_t
Macros
#define LUA_RIDX_LIGHTTPD_SERVER `lighty.srv`
#define LUA_RIDX_LIGHTTPD_CONNECTION `lighty.con`
#define MAGNET_CONFIG_RAW_URL `magnet.attract-raw-url-to`
#define MAGNET_CONFIG_PHYSICAL_PATH `magnet.attract-physical-path-to`
#define MAGNET_RESTART_REQUEST 99
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_magnet_init)
FREE_FUNC (mod_magnet_free)
SETDEFAULTS_FUNC (mod_magnet_set_defaults)
static int mod_magnet_patch_connection (server *srv, connection *con, plugin_data *p)
static void lua_pushglobaltable (lua_State *L)
static void magnet_setfenv_mainfn (lua_State *L, int funcIndex)
static int magnet_pairs (lua_State *L)
static int magnet_array_next (lua_State *L)
static int magnet_array_pairs (lua_State *L, array *a)
static server * magnet_get_server (lua_State *L)
static connection * magnet_get_connection (lua_State *L)
static const_buffer magnet_checkconstbuffer (lua_State *L, int index)
static buffer * magnet_checkbuffer (lua_State *L, int index)
static int magnet_print (lua_State *L)
static int magnet_stat (lua_State *L)
static int magnet_atpanic (lua_State *L)
static int magnet_reqhdr_get (lua_State *L)
static int magnet_reqhdr_pairs (lua_State *L)
static int magnet_status_get (lua_State *L)
static int magnet_status_set (lua_State *L)
static int magnet_status_pairs (lua_State *L)
static buffer * magnet_env_get_buffer_by_id (server *srv, connection *con, int id)
static buffer * magnet_env_get_buffer (server *srv, connection *con, const char *key)
static int magnet_env_get (lua_State *L)
static int magnet_env_set (lua_State *L)
static int magnet_env_next (lua_State *L)
static int magnet_env_pairs (lua_State *L)
static int magnet_cgi_get (lua_State *L)
static int magnet_cgi_set (lua_State *L)
static int magnet_cgi_pairs (lua_State *L)
static int magnet_copy_response_header (server *srv, connection *con, lua_State *L, int lighty_table_ndx)
static int magnet_attach_content (server *srv, connection *con, lua_State *L, int lighty_table_ndx)
static int traceback (lua_State *L)
static int push_traceback (lua_State *L, int narg)
static handler_t magnet_attract (server *srv, connection *con, plugin_data *p, buffer *name)
static handler_t magnet_attract_array (server *srv, connection *con, plugin_data *p, array *files)
URIHANDLER_FUNC (mod_magnet_uri_handler)
URIHANDLER_FUNC (mod_magnet_physical)
int mod_magnet_plugin_init (plugin *p)
Variables
static jmp_buf exceptionjmp
static const magnet_env_t magnet_env []
Macro Definition Documentation
#define LUA_RIDX_LIGHTTPD_CONNECTION `lighty.con`
Referenced by magnet_attract(), and magnet_get_connection().
#define LUA_RIDX_LIGHTTPD_SERVER `lighty.srv`
Referenced by magnet_attract(), and magnet_get_server().
#define MAGNET_CONFIG_PHYSICAL_PATH `magnet.attract-physical-path-to`
Referenced by mod_magnet_patch_connection(), and SETDEFAULTS_FUNC().
#define MAGNET_CONFIG_RAW_URL `magnet.attract-raw-url-to`
Referenced by mod_magnet_patch_connection(), and SETDEFAULTS_FUNC().
#define MAGNET_RESTART_REQUEST 99
Referenced by magnet_attract().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_magnet_patch_connection().
Function Documentation
FREE_FUNC (mod_magnet_free)
References array_free(), buffer_free(), plugin_data::cache, plugin_data::config_storage, plugin_data::encode_buf, HANDLER_GO_ON, plugin_config::physical_path, script_cache_free(), UNUSED, and plugin_config::url_raw.
INIT_FUNC (mod_magnet_init)
References buffer_init(), plugin_data::cache, plugin_data::encode_buf, and script_cache_init().
static void lua_pushglobaltable (lua_State * L) [static]
Referenced by magnet_attract().
static int magnet_array_next (lua_State * L) [static]
References buffer_is_empty(), CONST_BUF_LEN, array::data, TYPE_INTEGER, TYPE_STRING, array::used, data_string::value, and data_integer::value.
Referenced by magnet_array_pairs().
static int magnet_array_pairs (lua_State * L, array * a) [static]
References magnet_array_next().
Referenced by magnet_cgi_pairs(), magnet_reqhdr_pairs(), and magnet_status_pairs().
static int magnet_atpanic (lua_State * L) [static]
References buffer_free(), exceptionjmp, log_error_write(), magnet_checkbuffer(), and magnet_get_server().
Referenced by magnet_attract().
static int magnet_attach_content (server * srv, connection * con, lua_State * L, int lighty_table_ndx) [static]
walk through the content array
content = { `<pre>`, { file = `/content` } , `</pre>` }
header[`Content-Type`] = `text/html`
return 200
References buffer_free(), chunkqueue_append_mem(), force_assert, http_chunk_append_file_range(), const_buffer::len, magnet_checkbuffer(), magnet_checkconstbuffer(), const_buffer::ptr, and connection::write_queue.
Referenced by magnet_attract().
static handler_t magnet_attract (server * srv, connection * con, plugin_data * p, buffer * name) [static]
we want to create empty environment for our script
setmetatable({}, {__index = _G})
if a function symbol is not defined in our env, __index will lookup in the global env.
all variables created in the script-env will be thrown away at the end of the script run.
lighty.request[] (ro) has the HTTP-request headers lighty.env[] (rw) has various url/physical file paths and request meta data; might contain nil values lighty.req_env[] (ro) has the cgi environment lighty.status[] (ro) has the status counters lighty.content[] (rw) is a table of string/file lighty.header[] (rw) is a array to set response headers
References plugin_data::cache, chunkqueue_is_empty(), DIRECT, exceptionjmp, connection::file_finished, force_assert, HANDLER_COMEBACK, HANDLER_FINISHED, HANDLER_GO_ON, connection::http_status, log_error_write(), lua_pushglobaltable(), LUA_RIDX_LIGHTTPD_CONNECTION, LUA_RIDX_LIGHTTPD_SERVER, magnet_atpanic(), magnet_attach_content(), magnet_cgi_get(), magnet_cgi_pairs(), magnet_cgi_set(), magnet_copy_response_header(), magnet_env_get(), magnet_env_pairs(), magnet_env_set(), magnet_pairs(), magnet_print(), magnet_reqhdr_get(), magnet_reqhdr_pairs(), MAGNET_RESTART_REQUEST, magnet_setfenv_mainfn(), magnet_stat(), magnet_status_get(), magnet_status_pairs(), magnet_status_set(), connection::mode, push_traceback(), script_cache_get_script(), and connection::write_queue.
Referenced by magnet_attract_array().
static handler_t magnet_attract_array (server * srv, connection * con, plugin_data * p, array * files) [static]
execute all files and jump out on the first !HANDLER_GO_ON
References array_get_element(), buffer_string_is_empty(), array::data, connection::environment, connection::error_handler_saved_status, HANDLER_GO_ON, magnet_attract(), buffer::ptr, array::used, and data_string::value.
Referenced by URIHANDLER_FUNC().
static int magnet_cgi_get (lua_State * L) [static]
References array_get_element(), buffer_is_empty(), CONST_BUF_LEN, connection::environment, magnet_get_connection(), and data_string::value.
Referenced by magnet_attract().
static int magnet_cgi_pairs (lua_State * L) [static]
References connection::environment, magnet_array_pairs(), and magnet_get_connection().
Referenced by magnet_attract().
static int magnet_cgi_set (lua_State * L) [static]
References array_set_key_value(), connection::environment, const_buffer::len, magnet_checkconstbuffer(), magnet_get_connection(), and const_buffer::ptr.
Referenced by magnet_attract().
static buffer* magnet_checkbuffer (lua_State * L, int index) [static]
References buffer_copy_string_len(), buffer_init(), const_buffer::len, magnet_checkconstbuffer(), and const_buffer::ptr.
Referenced by magnet_atpanic(), magnet_attach_content(), magnet_print(), and magnet_stat().
static const_buffer magnet_checkconstbuffer (lua_State * L, int index) [static]
References const_buffer::len, and const_buffer::ptr.
Referenced by magnet_attach_content(), magnet_cgi_set(), magnet_checkbuffer(), magnet_copy_response_header(), magnet_env_set(), magnet_status_get(), and magnet_status_set().
static int magnet_copy_response_header (server * srv, connection * con, lua_State * L, int lighty_table_ndx) [static]
References force_assert, const_buffer::len, magnet_checkconstbuffer(), const_buffer::ptr, and response_header_overwrite().
Referenced by magnet_attract().
static int magnet_env_get (lua_State * L) [static]
References buffer_is_empty(), CONST_BUF_LEN, magnet_env_get_buffer(), magnet_get_connection(), and magnet_get_server().
Referenced by magnet_attract().
static buffer* magnet_env_get_buffer (server * srv, connection * con, const char * key) [static]
References magnet_env_get_buffer_by_id(), and magnet_env_t::name.
Referenced by magnet_env_get(), and magnet_env_set().
static buffer* magnet_env_get_buffer_by_id (server * srv, connection * con, int id) [static]
map all internal variables to lua
References request_uri::authority, physical::basedir, buffer_copy_string(), physical::doc_root, connection::dst_addr_buf, get_http_method_name(), get_http_version_name(), request::http_method, request::http_version, request::orig_uri, request_uri::path, physical::path, request_uri::path_raw, request::pathinfo, connection::physical, request_uri::query, physical::rel_path, connection::request, request_uri::scheme, server::tmp_buf, UNUSED, request::uri, and connection::uri.
Referenced by magnet_env_get_buffer(), and magnet_env_next().
static int magnet_env_next (lua_State * L) [static]
References buffer_is_empty(), CONST_BUF_LEN, magnet_env_get_buffer_by_id(), magnet_get_connection(), and magnet_get_server().
Referenced by magnet_env_pairs().
static int magnet_env_pairs (lua_State * L) [static]
References magnet_env_next().
Referenced by magnet_attract().
static int magnet_env_set (lua_State * L) [static]
References buffer_copy_string_len(), buffer_reset(), const_buffer::len, magnet_checkconstbuffer(), magnet_env_get_buffer(), magnet_get_connection(), magnet_get_server(), and const_buffer::ptr.
Referenced by magnet_attract().
static connection* magnet_get_connection (lua_State * L) [static]
References LUA_RIDX_LIGHTTPD_CONNECTION.
Referenced by magnet_cgi_get(), magnet_cgi_pairs(), magnet_cgi_set(), magnet_env_get(), magnet_env_next(), magnet_env_set(), magnet_reqhdr_get(), magnet_reqhdr_pairs(), and magnet_stat().
static server* magnet_get_server (lua_State * L) [static]
References LUA_RIDX_LIGHTTPD_SERVER.
Referenced by magnet_atpanic(), magnet_env_get(), magnet_env_next(), magnet_env_set(), magnet_print(), magnet_stat(), magnet_status_get(), magnet_status_pairs(), and magnet_status_set().
static int magnet_pairs (lua_State * L) [static]
Referenced by magnet_attract().
static int magnet_print (lua_State * L) [static]
References buffer_free(), log_error_write(), magnet_checkbuffer(), and magnet_get_server().
Referenced by magnet_attract().
static int magnet_reqhdr_get (lua_State * L) [static]
References array_get_element(), buffer_is_empty(), CONST_BUF_LEN, request::headers, magnet_get_connection(), connection::request, and data_string::value.
Referenced by magnet_attract().
static int magnet_reqhdr_pairs (lua_State * L) [static]
References request::headers, magnet_array_pairs(), magnet_get_connection(), and connection::request.
Referenced by magnet_attract().
static void magnet_setfenv_mainfn (lua_State * L, int funcIndex) [static]
Referenced by magnet_attract().
static int magnet_stat (lua_State * L) [static]
References buffer_free(), buffer_init(), buffer_string_is_empty(), CONST_BUF_LEN, stat_cache_entry::content_type, stat_cache_entry::etag, etag_mutate(), HANDLER_GO_ON, magnet_checkbuffer(), magnet_get_connection(), magnet_get_server(), stat_cache_entry::st, and stat_cache_get_entry().
Referenced by magnet_attract().
static int magnet_status_get (lua_State * L) [static]
References const_buffer::len, magnet_checkconstbuffer(), magnet_get_server(), const_buffer::ptr, status_counter_get_counter(), and data_integer::value.
Referenced by magnet_attract().
static int magnet_status_pairs (lua_State * L) [static]
References magnet_array_pairs(), magnet_get_server(), and server::status.
Referenced by magnet_attract().
static int magnet_status_set (lua_State * L) [static]
References const_buffer::len, magnet_checkconstbuffer(), magnet_get_server(), const_buffer::ptr, and status_counter_set().
Referenced by magnet_attract().
static int mod_magnet_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, MAGNET_CONFIG_PHYSICAL_PATH, MAGNET_CONFIG_RAW_URL, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_magnet_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_physical, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static int push_traceback (lua_State * L, int narg) [static]
References traceback().
Referenced by magnet_attract().
SETDEFAULTS_FUNC (mod_magnet_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, MAGNET_CONFIG_PHYSICAL_PATH, MAGNET_CONFIG_RAW_URL, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, plugin_config::url_raw, and data_config::value.
static int traceback (lua_State * L) [static]
Referenced by push_traceback().
URIHANDLER_FUNC (mod_magnet_uri_handler)
References plugin_data::conf, magnet_attract_array(), mod_magnet_patch_connection(), and plugin_config::url_raw.
URIHANDLER_FUNC (mod_magnet_physical)
References plugin_data::conf, magnet_attract_array(), mod_magnet_patch_connection(), and plugin_config::physical_path.
Variable Documentation
jmp_buf exceptionjmp [static]
Referenced by magnet_atpanic(), and magnet_attract().
const magnet_env_t magnet_env[] [static]
Initial value:
= {
    { "physical.path", MAGNET_ENV_PHYICAL_PATH },
    { "physical.rel-path", MAGNET_ENV_PHYICAL_REL_PATH },
    { "physical.doc-root", MAGNET_ENV_PHYICAL_DOC_ROOT },
    { "physical.basedir", MAGNET_ENV_PHYICAL_BASEDIR },
    { "uri.path", MAGNET_ENV_URI_PATH },
    { "uri.path-raw", MAGNET_ENV_URI_PATH_RAW },
    { "uri.scheme", MAGNET_ENV_URI_SCHEME },
    { "uri.authority", MAGNET_ENV_URI_AUTHORITY },
    { "uri.query", MAGNET_ENV_URI_QUERY },
    { "request.method", MAGNET_ENV_REQUEST_METHOD },
    { "request.uri", MAGNET_ENV_REQUEST_URI },
    { "request.orig-uri", MAGNET_ENV_REQUEST_ORIG_URI },
    { "request.path-info", MAGNET_ENV_REQUEST_PATH_INFO },
    { "request.remote-ip", MAGNET_ENV_REQUEST_REMOTE_IP },
    { "request.protocol", MAGNET_ENV_REQUEST_PROTOCOL },
    { NULL, MAGNET_ENV_UNSET }
}