mod_authn_mysql.c File Reference
#include `first.h`
*
#include <mysql.h>
*
#include `server.h`
*
#include `http_auth.h`
*
#include `log.h`
*
#include `md5.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <errno.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
static void mod_authn_mysql_sock_close (plugin_config *pconf)
static MYSQL * mod_authn_mysql_sock_connect (server *srv, plugin_config *pconf)
static MYSQL * mod_authn_mysql_sock_acquire (server *srv, plugin_config *pconf)
static void mod_authn_mysql_sock_release (server *srv, plugin_config *pconf)
static void mod_authn_mysql_sock_error (server *srv, plugin_config *pconf)
static handler_t mod_authn_mysql_basic (server *srv, connection *con, void *p_d, const http_auth_require_t *require, const buffer *username, const char *pw)
static handler_t mod_authn_mysql_digest (server *srv, connection *con, void *p_d, const char *username, const char *realm, unsigned char HA1[16])
INIT_FUNC (mod_authn_mysql_init)
FREE_FUNC (mod_authn_mysql_free)
SETDEFAULTS_FUNC (mod_authn_mysql_set_defaults)
static int mod_authn_mysql_patch_connection (server *srv, connection *con, plugin_data *p)
static int mod_authn_mysql_password_cmp (const char *userpw, unsigned long userpwlen, const char *reqpw)
static int mod_authn_mysql_result (server *srv, plugin_data *p, const char *pw, unsigned char HA1[16])
static handler_t mod_authn_mysql_query (server *srv, connection *con, void *p_d, const char *username, const char *realm, const char *pw, unsigned char HA1[16])
int mod_authn_mysql_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_authn_mysql_patch_connection().
Function Documentation
FREE_FUNC (mod_authn_mysql_free)
References plugin_config::auth_mysql_col_pass, plugin_config::auth_mysql_col_realm, plugin_config::auth_mysql_col_user, plugin_config::auth_mysql_db, plugin_config::auth_mysql_host, plugin_config::auth_mysql_pass, plugin_config::auth_mysql_socket, plugin_config::auth_mysql_user, plugin_config::auth_mysql_users_table, buffer_free(), plugin_data::conf, plugin_data::config_storage, HANDLER_GO_ON, mod_authn_mysql_sock_close(), plugin_config::mysql_conn, and UNUSED.
INIT_FUNC (mod_authn_mysql_init)
References http_auth_backend_set(), mod_authn_mysql_basic(), mod_authn_mysql_digest(), and http_auth_backend_t::p_d.
static handler_t mod_authn_mysql_basic (server * srv, connection * con, void * p_d, const http_auth_require_t * require, const buffer * username, const char * pw) [static]
References HANDLER_ERROR, HANDLER_GO_ON, http_auth_match_rules(), mod_authn_mysql_query(), buffer::ptr, and http_auth_require_t::realm.
Referenced by INIT_FUNC().
static handler_t mod_authn_mysql_digest (server * srv, connection * con, void * p_d, const char * username, const char * realm, unsigned char HA1[16]) [static]
References mod_authn_mysql_query().
Referenced by INIT_FUNC().
static int mod_authn_mysql_password_cmp (const char * userpw, unsigned long userpwlen, const char * reqpw) [static]
References http_auth_md5_hex2bin(), li_MD5_Final(), li_MD5_Init(), and li_MD5_Update().
Referenced by mod_authn_mysql_result().
static int mod_authn_mysql_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_authn_mysql_query().
int mod_authn_mysql_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static handler_t mod_authn_mysql_query (server * srv, connection * con, void * p_d, const char * username, const char * realm, const char * pw, unsigned char HA1[16]) [static]
References plugin_config::auth_mysql_col_pass, plugin_config::auth_mysql_col_realm, plugin_config::auth_mysql_col_user, plugin_config::auth_mysql_db, plugin_config::auth_mysql_host, plugin_config::auth_mysql_user, plugin_config::auth_mysql_users_table, buffer_string_is_empty(), plugin_data::conf, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), mod_authn_mysql_patch_connection(), mod_authn_mysql_result(), mod_authn_mysql_sock_acquire(), mod_authn_mysql_sock_error(), mod_authn_mysql_sock_release(), plugin_config::mysql_conn, buffer::ptr, connection::request, and request::uri.
Referenced by mod_authn_mysql_basic(), and mod_authn_mysql_digest().
static int mod_authn_mysql_result (server * srv, plugin_data * p, const char * pw, unsigned char HA1[16]) [static]
References plugin_data::conf, http_auth_md5_hex2bin(), log_error_write(), mod_authn_mysql_password_cmp(), mod_authn_mysql_sock_error(), and plugin_config::mysql_conn.
Referenced by mod_authn_mysql_query().
static MYSQL* mod_authn_mysql_sock_acquire (server * srv, plugin_config * pconf) [static]
References mod_authn_mysql_sock_connect().
Referenced by mod_authn_mysql_query().
static void mod_authn_mysql_sock_close (plugin_config * pconf) [static]
References plugin_config::mysql_conn.
Referenced by FREE_FUNC(), mod_authn_mysql_sock_connect(), and mod_authn_mysql_sock_error().
static MYSQL* mod_authn_mysql_sock_connect (server * srv, plugin_config * pconf) [static]
References plugin_config::auth_mysql_db, plugin_config::auth_mysql_host, plugin_config::auth_mysql_pass, plugin_config::auth_mysql_port, plugin_config::auth_mysql_socket, plugin_config::auth_mysql_user, buffer_string_is_empty(), log_error_write(), mod_authn_mysql_sock_close(), plugin_config::mysql_conn, plugin_config::mysql_conn_db, plugin_config::mysql_conn_host, plugin_config::mysql_conn_pass, plugin_config::mysql_conn_port, plugin_config::mysql_conn_user, and buffer::ptr.
Referenced by mod_authn_mysql_sock_acquire().
static void mod_authn_mysql_sock_error (server * srv, plugin_config * pconf) [static]
References mod_authn_mysql_sock_close(), and UNUSED.
Referenced by mod_authn_mysql_query(), and mod_authn_mysql_result().
static void mod_authn_mysql_sock_release (server * srv, plugin_config * pconf) [static]
References UNUSED.
Referenced by mod_authn_mysql_query().
SETDEFAULTS_FUNC (mod_authn_mysql_set_defaults)
References plugin_config::auth_mysql_col_pass, plugin_config::auth_mysql_col_realm, plugin_config::auth_mysql_col_user, buffer_init(), buffer_init_string(), buffer_is_empty(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), plugin_config::mysql_conn, T_CONFIG_INT, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.