mod_magnet_cache.h File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `base.h`
*
#include <lua.h>
*
Classes
struct script
struct script_cache
Functions
script_cache * script_cache_init (void)
void script_cache_free (script_cache *cache)
lua_State * script_cache_get_script (server *srv, connection *con, script_cache *cache, buffer *name)
Function Documentation
void script_cache_free (script_cache * cache)
References script_cache::ptr, script_free(), and script_cache::used.
Referenced by FREE_FUNC().
lua_State* script_cache_get_script (server * srv, connection * con, script_cache * cache, buffer * name)
References buffer_copy_buffer(), buffer_is_equal(), script::etag, stat_cache_entry::etag, force_assert, HANDLER_ERROR, HANDLER_GO_ON, script::L, script::last_used, script::name, script_cache::ptr, buffer::ptr, script_init(), script_cache::size, stat_cache_get_entry(), and script_cache::used.
Referenced by magnet_attract().
script_cache* script_cache_init (void)
Referenced by INIT_FUNC().