mod_redirect.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Functions
INIT_FUNC (mod_redirect_init)
FREE_FUNC (mod_redirect_free)
SETDEFAULTS_FUNC (mod_redirect_set_defaults)
static handler_t mod_redirect_uri_handler (server *srv, connection *con, void *p_data)
int mod_redirect_plugin_init (plugin *p)
Function Documentation
FREE_FUNC (mod_redirect_free)
References buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_data::location, plugin_data::match_buf, pcre_keyvalue_buffer_free(), and plugin_config::redirect.
INIT_FUNC (mod_redirect_init)
References buffer_init(), plugin_data::location, and plugin_data::match_buf.
int mod_redirect_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_uri_clean, plugin::init, mod_redirect_uri_handler(), plugin::name, plugin::set_defaults, and plugin::version.
static handler_t mod_redirect_uri_handler (server * srv, connection * con, void * p_data) [static]
References buffer_append_string(), buffer_append_string_len(), buffer_copy_buffer(), buffer_reset(), buffer_string_length(), plugin_data::conf, config_append_cond_match_buffer(), CONST_BUF_LEN, CONST_STR_LEN, plugin_config::context, DIRECT, connection::file_finished, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, connection::http_status, pcre_keyvalue_buffer::kv, plugin_data::location, log_error_write(), plugin_data::match_buf, connection::mode, buffer::ptr, plugin_config::redirect, plugin_config::redirect_code, connection::request, response_header_insert(), UNUSED, request::uri, pcre_keyvalue_buffer::used, and pcre_keyvalue::value.
Referenced by mod_redirect_plugin_init().
SETDEFAULTS_FUNC (mod_redirect_set_defaults)
References array_get_element(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), pcre_keyvalue_buffer_append(), pcre_keyvalue_buffer_init(), T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_UNSET, TYPE_ARRAY, TYPE_STRING, and data_config::value.