mod_scgi.c File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include `http_chunk.h`
*
#include `fdevent.h`
*
#include `connections.h`
*
#include `response.h`
*
#include `joblist.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include <sys/types.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <ctype.h>
*
#include <assert.h>
*
#include <signal.h>
*
#include <stdio.h>
*
#include `sys-socket.h`
*
#include `sys-endian.h`
*
Classes
struct scgi_proc
struct scgi_extension_host
struct scgi_extension
struct scgi_exts
struct plugin_config
struct char_array
struct plugin_data
struct handler_ctx
Macros
#define uwsgi_htole16(x) (x)
#define PATCH(x) p->conf.x = s->x;
Typedefs
typedef struct scgi_proc scgi_proc
Enumerations
enum { EOL_UNSET,
EOL_N,
EOL_RN
 }
enum { LI_PROTOCOL_SCGI,
LI_PROTOCOL_UWSGI
 }
enum scgi_connection_state_t {
*
FCGI_STATE_INIT,
FCGI_STATE_CONNECT,
FCGI_STATE_PREPARE_WRITE,
FCGI_STATE_WRITE,
*
FCGI_STATE_READ
 }
Functions
static handler_t scgi_handle_fdevent (server *srv, void *ctx, int revents)
int scgi_proclist_sort_down (server *srv, scgi_extension_host *host, scgi_proc *proc)
static void reset_signals (void)
static handler_ctx * handler_ctx_init (void)
static void handler_ctx_free (handler_ctx *hctx)
static scgi_proc * scgi_process_init (void)
static void scgi_process_free (scgi_proc *f)
static scgi_extension_host * scgi_host_init (void)
static void scgi_host_free (scgi_extension_host *h)
static scgi_exts * scgi_extensions_init (void)
static void scgi_extensions_free (scgi_exts *f)
static int scgi_extension_insert (scgi_exts *ext, buffer *key, scgi_extension_host *fh)
INIT_FUNC (mod_scgi_init)
FREE_FUNC (mod_scgi_free)
static int env_add (char_array *env, const char *key, size_t key_len, const char *val, size_t val_len)
static int scgi_spawn_connection (server *srv, plugin_data *p, scgi_extension_host *host, scgi_proc *proc)
static scgi_extension_host * unixsocket_is_dup (plugin_data *p, size_t used, buffer *unixsocket)
SETDEFAULTS_FUNC (mod_scgi_set_defaults)
static int scgi_set_state (server *srv, handler_ctx *hctx, scgi_connection_state_t state)
static void scgi_backend_close (server *srv, handler_ctx *hctx)
static scgi_extension_host * scgi_extension_host_get (server *srv, connection *con, plugin_data *p, scgi_extension *extension)
static void scgi_connection_close (server *srv, handler_ctx *hctx)
static handler_t scgi_reconnect (server *srv, handler_ctx *hctx)
static handler_t scgi_connection_reset (server *srv, connection *con, void *p_d)
static int scgi_env_add_scgi (void *venv, const char *key, size_t key_len, const char *val, size_t val_len)
static int scgi_env_add_uwsgi (void *venv, const char *key, size_t key_len, const char *val, size_t val_len)
static int scgi_establish_connection (server *srv, handler_ctx *hctx)
static int scgi_create_env (server *srv, handler_ctx *hctx)
static int scgi_response_parse (server *srv, connection *con, plugin_data *p, buffer *in, int eol)
static int scgi_demux_response (server *srv, handler_ctx *hctx)
static int scgi_proclist_sort_up (server *srv, scgi_extension_host *host, scgi_proc *proc)
static int scgi_restart_dead_procs (server *srv, plugin_data *p, scgi_extension_host *host)
static handler_t scgi_write_request (server *srv, handler_ctx *hctx)
static handler_t scgi_send_request (server *srv, handler_ctx *hctx)
static handler_t scgi_recv_response (server *srv, handler_ctx *hctx)
SUBREQUEST_FUNC (mod_scgi_handle_subrequest)
static int scgi_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t scgi_check_extension (server *srv, connection *con, void *p_d, int uri_path_handler)
static handler_t scgi_check_extension_1 (server *srv, connection *con, void *p_d)
static handler_t scgi_check_extension_2 (server *srv, connection *con, void *p_d)
TRIGGER_FUNC (mod_scgi_handle_trigger)
int mod_scgi_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by scgi_patch_connection().
#define uwsgi_htole16(x) (x)
Referenced by scgi_create_env(), and scgi_env_add_uwsgi().
Typedef Documentation
typedef struct scgi_proc scgi_proc
Enumeration Type Documentation
anonymous enum
Enumerator
EOL_UNSET
EOL_N
EOL_RN
anonymous enum
Enumerator
LI_PROTOCOL_SCGI
LI_PROTOCOL_UWSGI
enum scgi_connection_state_t
Enumerator
FCGI_STATE_INIT
FCGI_STATE_CONNECT
FCGI_STATE_PREPARE_WRITE
FCGI_STATE_WRITE
FCGI_STATE_READ
Function Documentation
static int env_add (char_array * env, const char * key, size_t key_len, const char * val, size_t val_len) [static]
References force_assert, char_array::ptr, char_array::size, and char_array::used.
FREE_FUNC (mod_scgi_free)
References buffer_free(), buffer_string_is_empty(), plugin_data::config_storage, scgi_exts::exts, plugin_config::exts, scgi_extension_host::first, HANDLER_GO_ON, scgi_extension::hosts, scgi_proc::is_local, scgi_proc::next, plugin_data::parse_response, scgi_proc::pid, buffer::ptr, plugin_data::scgi_env, scgi_extensions_free(), scgi_proc::socket, UNUSED, scgi_extension_host::unused_procs, scgi_extension::used, and scgi_exts::used.
static void handler_ctx_free (handler_ctx * hctx) [static]
References buffer_free(), chunkqueue_free(), handler_ctx::response, handler_ctx::response_header, and handler_ctx::wb.
Referenced by scgi_connection_close().
static handler_ctx* handler_ctx_init (void) [static]
References buffer_init(), chunkqueue_init(), FCGI_STATE_INIT, handler_ctx::fd, handler_ctx::fde_ndx, force_assert, handler_ctx::proc, handler_ctx::reconnects, handler_ctx::response, handler_ctx::response_header, handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by scgi_check_extension().
INIT_FUNC (mod_scgi_init)
References buffer_init(), force_assert, plugin_data::parse_response, and plugin_data::scgi_env.
int mod_scgi_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_connection_close, plugin::handle_subrequest, plugin::handle_subrequest_start, plugin::handle_trigger, plugin::handle_uri_clean, plugin::init, plugin::name, scgi_check_extension_1(), scgi_check_extension_2(), scgi_connection_reset(), plugin::set_defaults, and plugin::version.
static void reset_signals (void) [static]
static void scgi_backend_close (server * srv, handler_ctx * hctx) [static]
References handler_ctx::conf, plugin_config::debug, server::ev, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_del(), fdevent_sched_close(), fdevent_unregister(), handler_ctx::got_proc, handler_ctx::host, fcgi_proc::load, fcgi_extension_host::load, log_error_write(), fcgi_proc::pid, handler_ctx::proc, and scgi_proclist_sort_down().
Referenced by scgi_connection_close(), and scgi_reconnect().
static handler_t scgi_check_extension (server * srv, connection * con, void * p_d, int uri_path_handler) [static]
References buffer_copy_string(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), scgi_extension_host::check_local, plugin_data::conf, handler_ctx::conf, connection::conf, plugin_config::debug, DIRECT, handler_ctx::ext, fcgi_exts::exts, plugin_config::exts, connection::file_started, scgi_extension_host::fix_root_path_name, handler_ctx_init(), HANDLER_FINISHED, HANDLER_GO_ON, handler_ctx::host, scgi_extension::key, scgi_extension_host::load, log_error_write(), specific_config::log_request_handling, connection::mode, scgi_extension::note_is_sent, request_uri::path, physical::path, request::pathinfo, connection::physical, connection::plugin_ctx, handler_ctx::plugin_data, handler_ctx::proc, plugin_config::proto, buffer::ptr, handler_ctx::remote_conn, connection::request, scgi_extension_host_get(), scgi_patch_connection(), connection::uri, and fcgi_exts::used.
Referenced by scgi_check_extension_1(), and scgi_check_extension_2().
static handler_t scgi_check_extension_1 (server * srv, connection * con, void * p_d) [static]
References scgi_check_extension().
Referenced by mod_scgi_plugin_init().
static handler_t scgi_check_extension_2 (server * srv, connection * con, void * p_d) [static]
References scgi_check_extension().
Referenced by mod_scgi_plugin_init().
static void scgi_connection_close (server * srv, handler_ctx * hctx) [static]
References handler_ctx_free(), http_response_backend_done(), connection::mode, connection::plugin_ctx, handler_ctx::plugin_data, handler_ctx::remote_conn, and scgi_backend_close().
Referenced by scgi_connection_reset(), scgi_handle_fdevent(), scgi_recv_response(), and scgi_send_request().
static handler_t scgi_connection_reset (server * srv, connection * con, void * p_d) [static]
References HANDLER_GO_ON, connection::plugin_ctx, and scgi_connection_close().
Referenced by mod_scgi_plugin_init().
static int scgi_create_env (server * srv, handler_ctx * hctx) [static]
References buffer_append_int(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_commit(), buffer_free(), buffer_init(), buffer_string_length(), buffer_string_prepare_copy(), chunkqueue_append_buffer(), chunkqueue_append_chunkqueue(), handler_ctx::conf, CONST_STR_LEN, request::content_length, DIRECT, scgi_extension_host::docroot, handler_ctx::host, http_cgi_headers(), connection::http_status, LI_PROTOCOL_SCGI, connection::mode, handler_ctx::plugin_data, plugin_config::proto, buffer::ptr, handler_ctx::remote_conn, connection::request, connection::request_content_queue, plugin_data::scgi_env, scgi_env_add_scgi(), scgi_env_add_uwsgi(), uint32_t, uwsgi_htole16, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by scgi_write_request().
static int scgi_demux_response (server * srv, handler_ctx * hctx) [static]
References array_get_element(), buffer_append_string_buffer(), buffer_commit(), buffer_string_length(), buffer_string_prepare_copy(), buffer_string_set_length(), chunkqueue_length(), connection::conf, connection_get_state(), DIRECT, EOL_N, EOL_RN, EOL_UNSET, server::ev, handler_ctx::fd, connection::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), FDEVENT_IN, FDEVENT_STREAM_RESPONSE_BUFMIN, connection::file_started, response::headers, handler_ctx::host, http_chunk_append_buffer(), http_chunk_append_mem(), http_response_xsendfile(), connection::http_status, connection::is_writable, log_error_write(), MAX_HTTP_REQUEST_HEADER, connection::mode, request_uri::path, handler_ctx::plugin_data, buffer::ptr, handler_ctx::remote_conn, handler_ctx::response, connection::response, handler_ctx::response_header, scgi_response_parse(), buffer::size, connection::state, specific_config::stream_response_body, connection::uri, data_string::value, connection::write_queue, fcgi_extension_host::xsendfile_allow, and fcgi_extension_host::xsendfile_docroot.
Referenced by scgi_recv_response().
static int scgi_env_add_scgi (void * venv, const char * key, size_t key_len, const char * val, size_t val_len) [static]
References buffer_append_string_len(), and buffer_string_prepare_append().
Referenced by scgi_create_env().
static int scgi_env_add_uwsgi (void * venv, const char * key, size_t key_len, const char * val, size_t val_len) [static]
References buffer_append_string_len(), buffer_string_prepare_append(), and uwsgi_htole16.
Referenced by scgi_create_env().
static int scgi_establish_connection (server * srv, handler_ctx * hctx) [static]
returns -1 error 0 connected 1 not connected yet
References buffer_string_is_empty(), buffer_string_length(), handler_ctx::conf, plugin_config::debug, scgi_extension_host::family, handler_ctx::fd, scgi_extension_host::host, handler_ctx::host, log_error_write(), scgi_proc::port, handler_ctx::proc, buffer::ptr, and scgi_proc::socket.
Referenced by scgi_write_request().
static scgi_extension_host* scgi_extension_host_get (server * srv, connection * con, plugin_data * p, scgi_extension * extension) [static]
References scgi_extension_host::active_procs, DIRECT, scgi_extension::hosts, connection::http_status, scgi_extension::key, scgi_extension_host::load, log_error_write(), connection::mode, scgi_extension::note_is_sent, request_uri::path, UNUSED, connection::uri, and scgi_extension::used.
Referenced by scgi_check_extension(), and scgi_reconnect().
static int scgi_extension_insert (scgi_exts * ext, buffer * key, scgi_extension_host * fh) [static]
References buffer_copy_buffer(), buffer_init(), buffer_is_equal(), scgi_exts::exts, force_assert, scgi_extension::hosts, scgi_extension::key, scgi_extension::size, scgi_exts::size, scgi_extension::used, and scgi_exts::used.
Referenced by SETDEFAULTS_FUNC().
static void scgi_extensions_free (scgi_exts * f) [static]
References buffer_free(), scgi_exts::exts, scgi_extension::hosts, scgi_extension::key, scgi_host_free(), scgi_extension::used, and scgi_exts::used.
Referenced by FREE_FUNC().
static scgi_exts* scgi_extensions_init (void) [static]
References force_assert.
Referenced by SETDEFAULTS_FUNC().
static handler_t scgi_handle_fdevent (server * srv, void * ctx, int revents) [static]
References FCGI_STATE_CONNECT, FDEVENT_ERR, FDEVENT_HUP, FDEVENT_IN, FDEVENT_OUT, connection::file_started, HANDLER_FINISHED, HANDLER_GO_ON, scgi_extension_host::host, handler_ctx::host, http_response_backend_error(), joblist_append(), log_error_write(), request_uri::path, scgi_extension_host::port, handler_ctx::remote_conn, scgi_connection_close(), scgi_recv_response(), scgi_send_request(), handler_ctx::state, and connection::uri.
Referenced by scgi_write_request().
static void scgi_host_free (scgi_extension_host * h) [static]
References array_free(), scgi_extension_host::bin_env, scgi_extension_host::bin_env_copy, scgi_extension_host::bin_path, buffer_free(), scgi_extension_host::docroot, scgi_extension_host::first, scgi_extension_host::host, scgi_extension_host::refcount, scgi_process_free(), scgi_extension_host::unixsocket, scgi_extension_host::unused_procs, and scgi_extension_host::xsendfile_docroot.
Referenced by scgi_extensions_free(), and SETDEFAULTS_FUNC().
static scgi_extension_host* scgi_host_init (void) [static]
References array_init(), scgi_extension_host::bin_env, scgi_extension_host::bin_env_copy, scgi_extension_host::bin_path, buffer_init(), scgi_extension_host::docroot, scgi_extension_host::host, scgi_extension_host::unixsocket, and scgi_extension_host::xsendfile_docroot.
Referenced by SETDEFAULTS_FUNC().
static int scgi_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by scgi_check_extension().
static void scgi_process_free (scgi_proc * f) [static]
References buffer_free(), scgi_proc::next, and scgi_proc::socket.
Referenced by scgi_host_free(), SETDEFAULTS_FUNC(), and TRIGGER_FUNC().
static scgi_proc* scgi_process_init (void) [static]
References buffer_init(), force_assert, scgi_proc::next, scgi_proc::prev, and scgi_proc::socket.
Referenced by SETDEFAULTS_FUNC(), and TRIGGER_FUNC().
int scgi_proclist_sort_down (server * srv, scgi_extension_host * host, scgi_proc * proc)
References scgi_extension_host::first, scgi_proc::load, log_error_write(), scgi_proc::next, scgi_proc::pid, scgi_proc::prev, and UNUSED.
Referenced by scgi_backend_close(), scgi_recv_response(), and scgi_restart_dead_procs().
static int scgi_proclist_sort_up (server * srv, scgi_extension_host * host, scgi_proc * proc) [static]
References scgi_extension_host::first, scgi_proc::load, log_error_write(), scgi_proc::next, scgi_proc::pid, scgi_proc::prev, and UNUSED.
Referenced by scgi_write_request().
static handler_t scgi_reconnect (server * srv, handler_ctx * hctx) [static]
References handler_ctx::ext, FCGI_STATE_INIT, HANDLER_COMEBACK, HANDLER_FINISHED, handler_ctx::host, fcgi_extension_host::load, handler_ctx::plugin_data, handler_ctx::remote_conn, scgi_backend_close(), scgi_extension_host_get(), and scgi_set_state().
Referenced by scgi_recv_response(), scgi_send_request(), and scgi_write_request().
static handler_t scgi_recv_response (server * srv, handler_ctx * hctx) [static]
References chunkqueue::bytes_out, handler_ctx::conf, plugin_config::debug, handler_ctx::fd, connection::fd, connection::file_started, HANDLER_FINISHED, HANDLER_GO_ON, handler_ctx::host, http_response_backend_error(), log_error_write(), scgi_extension_host::min_procs, scgi_proc::pid, handler_ctx::plugin_data, scgi_extension_host::port, handler_ctx::proc, handler_ctx::reconnects, handler_ctx::remote_conn, scgi_connection_close(), scgi_demux_response(), scgi_proclist_sort_down(), scgi_reconnect(), scgi_spawn_connection(), scgi_proc::state, scgi_extension_host::unixsocket, and handler_ctx::wb.
Referenced by scgi_handle_fdevent(), and SUBREQUEST_FUNC().
static int scgi_response_parse (server * srv, connection * con, plugin_data * p, buffer * in, int eol) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), response::content_length, data_response_init(), EOL_RN, response::headers, HTTP_CONNECTION, HTTP_CONTENT_LENGTH, HTTP_DATE, HTTP_LOCATION, HTTP_STATUS, connection::http_status, response::keep_alive, plugin_data::parse_response, connection::parsed_response, buffer::ptr, connection::response, TYPE_STRING, UNUSED, and data_string::value.
Referenced by scgi_demux_response().
static int scgi_restart_dead_procs (server * srv, plugin_data * p, scgi_extension_host * host) [static]
References scgi_extension_host::active_procs, plugin_data::conf, server::cur_ts, plugin_config::debug, scgi_extension_host::disable_time, scgi_proc::disable_ts, scgi_extension_host::first, HANDLER_ERROR, scgi_extension_host::host, scgi_proc::is_local, scgi_proc::load, log_error_write(), scgi_extension_host::min_procs, scgi_proc::next, scgi_proc::pid, scgi_proc::port, scgi_extension_host::port, scgi_proclist_sort_down(), scgi_spawn_connection(), scgi_proc::socket, scgi_proc::state, and scgi_extension_host::unixsocket.
Referenced by scgi_send_request(), and TRIGGER_FUNC().
static handler_t scgi_send_request (server * srv, handler_ctx * hctx) [static]
References scgi_extension_host::active_procs, handler_ctx::conf, server::cur_ts, plugin_config::debug, scgi_proc::disable_ts, FCGI_STATE_CONNECT, FCGI_STATE_INIT, HANDLER_ERROR, HANDLER_FINISHED, scgi_extension_host::host, handler_ctx::host, connection::http_status, scgi_proc::is_local, log_error_write(), scgi_proc::pid, handler_ctx::pid, handler_ctx::plugin_data, scgi_proc::port, handler_ctx::proc, handler_ctx::remote_conn, scgi_connection_close(), scgi_reconnect(), scgi_restart_dead_procs(), scgi_write_request(), scgi_proc::socket, scgi_proc::state, and handler_ctx::state.
Referenced by scgi_handle_fdevent(), and SUBREQUEST_FUNC().
static int scgi_set_state (server * srv, handler_ctx * hctx, scgi_connection_state_t state) [static]
References server::cur_ts, handler_ctx::state, and handler_ctx::state_timestamp.
Referenced by scgi_reconnect(), and scgi_write_request().
static int scgi_spawn_connection (server * srv, plugin_data * p, scgi_extension_host * host, scgi_proc * proc) [static]
References UNUSED.
Referenced by scgi_recv_response(), scgi_restart_dead_procs(), SETDEFAULTS_FUNC(), and TRIGGER_FUNC().
static handler_t scgi_write_request (server * srv, handler_ctx * hctx) [static]
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_remove_finished_chunks(), handler_ctx::conf, connection::conf, server::cur_fds, server::cur_ts, plugin_config::debug, server::ev, scgi_extension_host::family, FCGI_STATE_CONNECT, FCGI_STATE_INIT, FCGI_STATE_PREPARE_WRITE, FCGI_STATE_READ, FCGI_STATE_WRITE, handler_ctx::fd, connection::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), fdevent_event_set(), fdevent_fcntl_set(), FDEVENT_IN, FDEVENT_OUT, fdevent_register(), fdevent_socket_nb_cloexec(), FDEVENT_STREAM_REQUEST_POLLIN, fcgi_extension_host::first, handler_ctx::got_proc, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_WAIT_FOR_EVENT, HANDLER_WAIT_FOR_FD, handler_ctx::host, fcgi_proc::is_local, connection::is_readable, fcgi_proc::load, log_error_write(), server::max_fds, MAX_WRITE_LIMIT, server::network_backend_write, fcgi_proc::next, fcgi_proc::pid, handler_ctx::pid, fcgi_proc::port, handler_ctx::proc, handler_ctx::reconnects, handler_ctx::remote_conn, scgi_create_env(), scgi_establish_connection(), scgi_handle_fdevent(), scgi_proclist_sort_up(), scgi_reconnect(), scgi_set_state(), fcgi_proc::state, handler_ctx::state, specific_config::stream_request_body, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by scgi_send_request().
SETDEFAULTS_FUNC (mod_scgi_set_defaults)
References scgi_extension_host::active_procs, array_get_element(), scgi_extension_host::bin_env, scgi_extension_host::bin_env_copy, scgi_extension_host::bin_path, buffer_append_int(), buffer_append_slash(), buffer_append_string_len(), buffer_copy_buffer(), buffer_is_equal(), buffer_is_equal_string(), buffer_path_simplify(), buffer_string_is_empty(), buffer_string_length(), scgi_extension_host::check_local, server::config_context, config_insert_values_global(), config_insert_values_internal(), plugin_data::config_storage, CONST_STR_LEN, array::data, config_values_t::destination, scgi_extension_host::disable_time, scgi_extension_host::docroot, scgi_extension_host::family, scgi_extension_host::first, scgi_extension_host::fix_root_path_name, force_assert, scgi_extension_host::host, scgi_proc::id, scgi_extension_host::idle_timeout, LI_PROTOCOL_SCGI, LI_PROTOCOL_UWSGI, scgi_extension_host::listen_backlog, log_error_write(), scgi_extension_host::max_id, scgi_extension_host::max_load_per_proc, scgi_extension_host::max_procs, scgi_extension_host::min_procs, scgi_proc::next, scgi_extension_host::num_procs, scgi_proc::port, scgi_extension_host::port, server_config::preflight_check, scgi_proc::prev, buffer::ptr, scgi_extension_host::refcount, scgi_extension_insert(), scgi_extensions_init(), scgi_host_free(), scgi_host_init(), scgi_process_free(), scgi_process_init(), scgi_spawn_connection(), scgi_proc::socket, server::srvconf, scgi_proc::state, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_INT, T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, TYPE_ARRAY, TYPE_STRING, scgi_extension_host::unixsocket, unixsocket_is_dup(), array::used, data_string::value, data_array::value, data_config::value, scgi_extension_host::xsendfile_allow, and scgi_extension_host::xsendfile_docroot.
SUBREQUEST_FUNC (mod_scgi_handle_subrequest)
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_append_chunkqueue(), chunkqueue_is_empty(), chunkqueue_length(), CON_STATE_READ_POST, connection_handle_read_post_error(), connection_handle_read_post_state(), server::ev, FCGI_STATE_CONNECT, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_clr(), fdevent_event_get_interest, FDEVENT_IN, FDEVENT_OUT, FDEVENT_STREAM_REQUEST_BUFMIN, FDEVENT_STREAM_REQUEST_POLLIN, FDEVENT_STREAM_RESPONSE_BUFMIN, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, scgi_recv_response(), scgi_send_request(), handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
TRIGGER_FUNC (mod_scgi_handle_trigger)
References scgi_extension_host::active_procs, buffer_append_int(), buffer_append_string_len(), buffer_copy_buffer(), buffer_string_is_empty(), plugin_data::conf, server::config_context, plugin_data::config_storage, CONST_STR_LEN, server::cur_ts, plugin_config::debug, scgi_exts::exts, plugin_config::exts, scgi_extension_host::first, HANDLER_ERROR, HANDLER_GO_ON, scgi_extension::hosts, scgi_proc::id, scgi_extension_host::idle_timeout, scgi_proc::last_used, scgi_proc::load, log_error_write(), scgi_extension_host::max_id, scgi_extension_host::max_load_per_proc, scgi_extension_host::max_procs, scgi_extension_host::min_procs, scgi_proc::next, scgi_extension_host::num_procs, scgi_proc::pid, scgi_proc::port, scgi_extension_host::port, scgi_proc::prev, scgi_process_free(), scgi_process_init(), scgi_restart_dead_procs(), scgi_spawn_connection(), scgi_proc::socket, scgi_proc::state, scgi_extension_host::unixsocket, scgi_extension_host::unused_procs, array::used, scgi_extension::used, and scgi_exts::used.
static scgi_extension_host* unixsocket_is_dup (plugin_data * p, size_t used, buffer * unixsocket) [static]
References scgi_extension_host::bin_path, buffer_is_equal(), buffer_string_is_empty(), plugin_data::config_storage, scgi_exts::exts, plugin_config::exts, scgi_extension::hosts, scgi_extension_host::unixsocket, scgi_extension::used, and scgi_exts::used.
Referenced by SETDEFAULTS_FUNC().