mod_authn_file.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `safe_memclear.h`
*
#include `plugin.h`
*
#include `http_auth.h`
*
#include `log.h`
*
#include `response.h`
*
#include `inet_ntop_cache.h`
*
#include `base64.h`
*
#include `md5.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
#define APR_MD5_DIGESTSIZE 16
#define APR1_ID `$apr1$`
#define apr_cpystrn strncpy
Functions
static handler_t mod_authn_file_htdigest_digest (server *srv, connection *con, void *p_d, const char *username, const char *realm, unsigned char HA1[16])
static handler_t mod_authn_file_htdigest_basic (server *srv, connection *con, void *p_d, const http_auth_require_t *require, const buffer *username, const char *pw)
static handler_t mod_authn_file_plain_digest (server *srv, connection *con, void *p_d, const char *username, const char *realm, unsigned char HA1[16])
static handler_t mod_authn_file_plain_basic (server *srv, connection *con, void *p_d, const http_auth_require_t *require, const buffer *username, const char *pw)
static handler_t mod_authn_file_htpasswd_basic (server *srv, connection *con, void *p_d, const http_auth_require_t *require, const buffer *username, const char *pw)
INIT_FUNC (mod_authn_file_init)
FREE_FUNC (mod_authn_file_free)
SETDEFAULTS_FUNC (mod_authn_file_set_defaults)
static int mod_authn_file_patch_connection (server *srv, connection *con, plugin_data *p)
static int mod_authn_file_htdigest_get (server *srv, const buffer *auth_fn, const buffer *username, const buffer *realm, unsigned char HA1[16])
static int mod_authn_file_htpasswd_get (server *srv, const buffer *auth_fn, const buffer *username, buffer *password)
static void to64 (char *s, unsigned long v, int n)
static void apr_md5_encode (const char *pw, const char *salt, char *result, size_t nbytes)
int mod_authn_file_plugin_init (plugin *p)
Macro Definition Documentation
#define APR1_ID `$apr1$`
Referenced by apr_md5_encode(), and mod_authn_file_htpasswd_basic().
#define apr_cpystrn strncpy
Referenced by apr_md5_encode().
#define APR_MD5_DIGESTSIZE 16
the $apr1$ handling is taken from apache 1.3.x
Referenced by apr_md5_encode().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_authn_file_patch_connection().
Function Documentation
static void apr_md5_encode (const char * pw, const char * salt, char * result, size_t nbytes) [static]
References APR1_ID, apr_cpystrn, APR_MD5_DIGESTSIZE, li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), safe_memclear(), and to64().
Referenced by mod_authn_file_htpasswd_basic().
FREE_FUNC (mod_authn_file_free)
References plugin_config::auth_htdigest_userfile, plugin_config::auth_htpasswd_userfile, plugin_config::auth_plain_groupfile, plugin_config::auth_plain_userfile, buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_authn_file_init)
References http_auth_backend_set(), mod_authn_file_htdigest_basic(), mod_authn_file_htdigest_digest(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), mod_authn_file_plain_digest(), and http_auth_backend_t::p_d.
static handler_t mod_authn_file_htdigest_basic (server * srv, connection * con, void * p_d, const http_auth_require_t * require, const buffer * username, const char * pw) [static]
References plugin_config::auth_htdigest_userfile, plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, HANDLER_ERROR, HANDLER_GO_ON, http_auth_match_rules(), li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), mod_authn_file_htdigest_get(), mod_authn_file_patch_connection(), buffer::ptr, http_auth_require_t::realm, and UNUSED.
Referenced by INIT_FUNC().
static handler_t mod_authn_file_htdigest_digest (server * srv, connection * con, void * p_d, const char * username, const char * realm, unsigned char HA1[16]) [static]
References plugin_config::auth_htdigest_userfile, buffer_free(), buffer_init_string(), plugin_data::conf, HANDLER_ERROR, HANDLER_GO_ON, mod_authn_file_htdigest_get(), mod_authn_file_patch_connection(), and UNUSED.
Referenced by INIT_FUNC().
static int mod_authn_file_htdigest_get (server * srv, const buffer * auth_fn, const buffer * username, const buffer * realm, unsigned char HA1[16]) [static]
References buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), http_auth_md5_hex2bin(), log_error_write(), and buffer::ptr.
Referenced by mod_authn_file_htdigest_basic(), and mod_authn_file_htdigest_digest().
static handler_t mod_authn_file_htpasswd_basic (server * srv, connection * con, void * p_d, const http_auth_require_t * require, const buffer * username, const char * pw) [static]
References APR1_ID, apr_md5_encode(), plugin_config::auth_htpasswd_userfile, buffer_free(), buffer_init(), buffer_string_length(), plugin_data::conf, CONST_STR_LEN, HANDLER_ERROR, HANDLER_GO_ON, http_auth_match_rules(), li_tohex(), mod_authn_file_htpasswd_get(), mod_authn_file_patch_connection(), buffer::ptr, and UNUSED.
Referenced by INIT_FUNC().
static int mod_authn_file_htpasswd_get (server * srv, const buffer * auth_fn, const buffer * username, buffer * password) [static]
References buffer_copy_string_len(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), log_error_write(), and buffer::ptr.
Referenced by mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), and mod_authn_file_plain_digest().
static int mod_authn_file_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_authn_file_htdigest_basic(), mod_authn_file_htdigest_digest(), mod_authn_file_htpasswd_basic(), mod_authn_file_plain_basic(), and mod_authn_file_plain_digest().
static handler_t mod_authn_file_plain_basic (server * srv, connection * con, void * p_d, const http_auth_require_t * require, const buffer * username, const char * pw) [static]
References plugin_config::auth_plain_userfile, buffer_free(), buffer_init(), buffer_is_equal_string(), plugin_data::conf, HANDLER_ERROR, HANDLER_GO_ON, http_auth_match_rules(), mod_authn_file_htpasswd_get(), mod_authn_file_patch_connection(), buffer::ptr, and UNUSED.
Referenced by INIT_FUNC().
static handler_t mod_authn_file_plain_digest (server * srv, connection * con, void * p_d, const char * username, const char * realm, unsigned char HA1[16]) [static]
References plugin_config::auth_plain_userfile, buffer_free(), buffer_init(), buffer_init_string(), buffer_string_length(), plugin_data::conf, CONST_STR_LEN, HANDLER_ERROR, HANDLER_GO_ON, li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), mod_authn_file_htpasswd_get(), mod_authn_file_patch_connection(), buffer::ptr, and UNUSED.
Referenced by INIT_FUNC().
int mod_authn_file_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_authn_file_set_defaults)
References plugin_config::auth_plain_groupfile, buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
static void to64 (char * s, unsigned long v, int n) [static]
Referenced by apr_md5_encode().