mod_flv_streaming.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `response.h`
*
#include `http_chunk.h`
*
#include `stat_cache.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_flv_streaming_init)
FREE_FUNC (mod_flv_streaming_free)
SETDEFAULTS_FUNC (mod_flv_streaming_set_defaults)
static int mod_flv_streaming_patch_connection (server *srv, connection *con, plugin_data *p)
static int split_get_params (array *get_params, buffer *qrystr)
URIHANDLER_FUNC (mod_flv_streaming_path_handler)
int mod_flv_streaming_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_flv_streaming_patch_connection().
Function Documentation
FREE_FUNC (mod_flv_streaming_free)
References array_free(), buffer_free(), plugin_data::config_storage, plugin_config::extensions, plugin_data::get_params, HANDLER_GO_ON, plugin_data::query_str, and UNUSED.
INIT_FUNC (mod_flv_streaming_init)
References array_init(), buffer_init(), plugin_data::get_params, and plugin_data::query_str.
static int mod_flv_streaming_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_flv_streaming_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_physical, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_flv_streaming_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, plugin_config::extensions, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
static int split_get_params (array * get_params, buffer * qrystr) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), buffer_string_length(), data_string_init(), buffer::ptr, TYPE_STRING, and data_string::value.
Referenced by URIHANDLER_FUNC().
URIHANDLER_FUNC (mod_flv_streaming_path_handler)
References array_get_element(), array_reset(), buffer_copy_buffer(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), chunkqueue_reset(), plugin_data::conf, CONST_STR_LEN, array::data, DIRECT, plugin_config::extensions, plugin_data::get_params, HANDLER_FINISHED, HANDLER_GO_ON, http_chunk_append_file_range(), http_chunk_append_mem(), mod_flv_streaming_patch_connection(), buffer::ptr, plugin_data::query_str, response_header_overwrite(), split_get_params(), UNUSED, array::used, and data_string::value.