mod_cml.c File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `log.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include `mod_cml.h`
*
#include <sys/stat.h>
*
#include <time.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <stdio.h>
*
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_cml_init)
FREE_FUNC (mod_cml_free)
SETDEFAULTS_FUNC (mod_cml_set_defaults)
static int mod_cml_patch_connection (server *srv, connection *con, plugin_data *p)
static int cache_call_lua (server *srv, connection *con, plugin_data *p, buffer *cml_file)
URIHANDLER_FUNC (mod_cml_power_magnet)
URIHANDLER_FUNC (mod_cml_is_handled)
int mod_cml_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_cml_patch_connection().
Function Documentation
static int cache_call_lua (server * srv, connection * con, plugin_data * p, buffer * cml_file) [static]
References plugin_data::basedir, plugin_data::baseurl, buffer_copy_buffer(), buffer_string_length(), buffer_string_set_length(), cache_parse_lua(), request_uri::path, physical::path, connection::physical, buffer::ptr, and connection::uri.
Referenced by URIHANDLER_FUNC().
FREE_FUNC (mod_cml_free)
References array_free(), plugin_data::basedir, plugin_data::baseurl, buffer_free(), plugin_data::config_storage, plugin_config::ext, HANDLER_GO_ON, plugin_config::mc_hosts, plugin_config::mc_namespace, plugin_config::power_magnet, plugin_data::trigger_handler, and UNUSED.
INIT_FUNC (mod_cml_init)
References plugin_data::basedir, plugin_data::baseurl, buffer_init(), and plugin_data::trigger_handler.
static int mod_cml_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_cml_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_physical, plugin::handle_subrequest_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_cml_set_defaults)
References array_init(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_free(), buffer_init(), config_insert_values_global(), plugin_data::config_storage, CONST_BUF_LEN, CONST_STR_LEN, config_values_t::destination, plugin_config::ext, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, data_string::value, and data_config::value.
URIHANDLER_FUNC (mod_cml_power_magnet)
References plugin_data::basedir, plugin_data::baseurl, buffer_reset(), buffer_string_is_empty(), cache_call_lua(), plugin_data::conf, HANDLER_COMEBACK, HANDLER_FINISHED, HANDLER_GO_ON, log_error_write(), mod_cml_patch_connection(), plugin_config::power_magnet, and plugin_data::trigger_handler.
URIHANDLER_FUNC (mod_cml_is_handled)
References plugin_data::basedir, plugin_data::baseurl, buffer_is_equal_right_len(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), cache_call_lua(), plugin_data::conf, plugin_config::ext, HANDLER_COMEBACK, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, log_error_write(), mod_cml_patch_connection(), physical::path, plugin_data::physical, and plugin_data::trigger_handler.