mod_indexfile.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `stat_cache.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_indexfile_init)
FREE_FUNC (mod_indexfile_free)
SETDEFAULTS_FUNC (mod_indexfile_set_defaults)
static int mod_indexfile_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_indexfile_subrequest)
int mod_indexfile_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_indexfile_patch_connection().
Function Documentation
FREE_FUNC (mod_indexfile_free)
References array_free(), buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_config::indexfiles, plugin_data::tmp_buf, and UNUSED.
INIT_FUNC (mod_indexfile_init)
References buffer_init(), and plugin_data::tmp_buf.
static int mod_indexfile_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_indexfile_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_subrequest_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_indexfile_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::indexfiles, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_indexfile_subrequest)
References array_get_unused_element(), array_insert_unique(), buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_is_empty(), buffer_reset(), buffer_string_length(), plugin_data::conf, CONST_STR_LEN, array::data, data_string_init(), DIRECT, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, plugin_config::indexfiles, log_error_write(), mod_indexfile_patch_connection(), buffer::ptr, stat_cache_get_entry(), plugin_data::tmp_buf, TYPE_STRING, array::used, and data_string::value.