mod_mysql_vhost.c File Reference
#include `first.h`
*
#include <unistd.h>
*
#include <stdio.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <string.h>
*
#include <mysql.h>
*
#include `plugin.h`
*
#include `log.h`
*
#include `stat_cache.h`
*
Classes
struct plugin_config
struct plugin_data
struct plugin_connection_data
Macros
#define FOO(x) (buffer_string_is_empty(s->x) ? NULL : s->x->ptr)
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_mysql_vhost_init)
SERVER_FUNC (mod_mysql_vhost_cleanup)
static void * mod_mysql_vhost_connection_data (server *srv, connection *con, void *p_d)
CONNECTION_FUNC (mod_mysql_vhost_handle_connection_close)
SERVER_FUNC (mod_mysql_vhost_set_defaults)
static int mod_mysql_vhost_patch_connection (server *srv, connection *con, plugin_data *p)
CONNECTION_FUNC (mod_mysql_vhost_handle_docroot)
int mod_mysql_vhost_plugin_init (plugin *p)
Macro Definition Documentation
#define FOO(x) (buffer_string_is_empty(s->x) ? NULL : s->x->ptr)
Referenced by SERVER_FUNC().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_mysql_vhost_patch_connection().
Function Documentation
CONNECTION_FUNC (mod_mysql_vhost_handle_connection_close)
References buffer_free(), plugin_connection_data::document_root, HANDLER_GO_ON, log_error_write(), plugin_connection_data::server_name, and UNUSED.
CONNECTION_FUNC (mod_mysql_vhost_handle_docroot)
References buffer_append_slash(), buffer_append_string_len(), buffer_commit(), buffer_copy_buffer(), buffer_copy_string(), buffer_is_equal(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_append(), buffer_string_set_length(), plugin_data::conf, CONST_BUF_LEN, DIRECT, plugin_connection_data::document_root, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, log_error_write(), mod_mysql_vhost_connection_data(), mod_mysql_vhost_patch_connection(), plugin_config::mysql, plugin_config::mysql_query, buffer::ptr, plugin_connection_data::server_name, stat_cache_entry::st, stat_cache_get_entry(), and plugin_data::tmp_buf.
INIT_FUNC (mod_mysql_vhost_init)
References buffer_init(), and plugin_data::tmp_buf.
static void* mod_mysql_vhost_connection_data (server * srv, connection * con, void * p_d) [static]
References buffer_init(), plugin_connection_data::document_root, log_error_write(), connection::plugin_ctx, plugin_connection_data::server_name, and UNUSED.
Referenced by CONNECTION_FUNC().
static int mod_mysql_vhost_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, plugin_config::mysql, PATCH, array::used, and data_config::value.
Referenced by CONNECTION_FUNC().
int mod_mysql_vhost_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::handle_docroot, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SERVER_FUNC (mod_mysql_vhost_cleanup)
References buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_config::hostname, log_error_write(), plugin_config::mydb, plugin_config::mypass, plugin_config::mysock, plugin_config::mysql, plugin_config::mysql_query, plugin_config::myuser, plugin_data::tmp_buf, and UNUSED.
SERVER_FUNC (mod_mysql_vhost_set_defaults)
References buffer_init(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, fd_close_on_exec(), FOO, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), plugin_config::mysql_query, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.