mod_usertrack.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `rand.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `md5.h`
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_usertrack_init)
FREE_FUNC (mod_usertrack_free)
SETDEFAULTS_FUNC (mod_usertrack_set_defaults)
static int mod_usertrack_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_usertrack_uri_handler)
int mod_usertrack_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_usertrack_patch_connection().
Function Documentation
FREE_FUNC (mod_usertrack_free)
References buffer_free(), plugin_data::config_storage, plugin_config::cookie_domain, plugin_config::cookie_name, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_usertrack_init)
static int mod_usertrack_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_usertrack_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_usertrack_set_defaults)
References buffer_copy_string_len(), buffer_init(), buffer_string_is_empty(), buffer_string_length(), config_insert_values_global(), plugin_data::config_storage, CONST_STR_LEN, plugin_config::cookie_name, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), T_CONFIG_INT, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_usertrack_uri_handler)
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_append_int(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, plugin_config::cookie_domain, plugin_config::cookie_max_age, plugin_config::cookie_name, data_response_init(), ENCODING_HEX, ENCODING_REL_URI, HANDLER_GO_ON, LI_ITOSTRING_LENGTH, li_itostrn(), li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), li_rand_pseudo_bytes(), mod_usertrack_patch_connection(), buffer::ptr, TYPE_STRING, and data_string::value.