mod_secdownload.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `base64.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `md5.h`
*
Classes
struct plugin_config
struct plugin_data
Macros
#define HASHLEN 16
#define HASHHEXLEN 32
#define PATCH(x) p->conf.x = s->x;
Typedefs
typedef unsigned char HASH [HASHLEN]
typedef char HASHHEX [HASHHEXLEN+1]
Enumerations
enum secdl_algorithm { SECDL_INVALID = 0,
SECDL_MD5 = 1,
SECDL_HMAC_SHA1 = 2,
SECDL_HMAC_SHA256 = 3
 }
Functions
static int const_time_memeq (const char *a, const char *b, size_t len)
static secdl_algorithm algorithm_from_string (buffer *name)
static size_t secdl_algorithm_mac_length (secdl_algorithm alg)
static int secdl_verify_mac (server *srv, plugin_config *config, const char *protected_path, const char *mac, size_t maclen)
INIT_FUNC (mod_secdownload_init)
FREE_FUNC (mod_secdownload_free)
SETDEFAULTS_FUNC (mod_secdownload_set_defaults)
static int is_hex_len (const char *str, size_t len)
static int is_base64_len (const char *str, size_t len)
static int mod_secdownload_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_secdownload_uri_handler)
int mod_secdownload_plugin_init (plugin *p)
Variables
static const char * secdl_algorithm_names []
Macro Definition Documentation
#define HASHHEXLEN 32
#define HASHLEN 16
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_secdownload_patch_connection().
Typedef Documentation
typedef unsigned char HASH[HASHLEN]
typedef char HASHHEX[HASHHEXLEN+1]
Enumeration Type Documentation
enum secdl_algorithm
Enumerator
SECDL_INVALID
SECDL_MD5
SECDL_HMAC_SHA1
SECDL_HMAC_SHA256
Function Documentation
static secdl_algorithm algorithm_from_string (buffer * name) [static]
References buffer_string_is_empty(), buffer::ptr, secdl_algorithm_names, and SECDL_INVALID.
Referenced by SETDEFAULTS_FUNC().
static int const_time_memeq (const char * a, const char * b, size_t len) [static]
Referenced by secdl_verify_mac().
FREE_FUNC (mod_secdownload_free)
References buffer_free(), plugin_data::config_storage, plugin_config::doc_root, HANDLER_GO_ON, plugin_config::secret, UNUSED, and plugin_config::uri_prefix.
INIT_FUNC (mod_secdownload_init)
static int is_base64_len (const char * str, size_t len) [static]
checks if the supplied string is a base64 (modified URL) string
Parameters
str a possible base64 (modified URL) string
Returns
if the supplied string is a valid base64 (modified URL) string 1 is returned otherwise 0
Referenced by URIHANDLER_FUNC().
static int is_hex_len (const char * str, size_t len) [static]
checks if the supplied string is a hex string
Parameters
str a possible hex string
Returns
if the supplied string is a valid hex string 1 is returned otherwise 0
Referenced by URIHANDLER_FUNC().
static int mod_secdownload_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_secdownload_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_physical, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static size_t secdl_algorithm_mac_length (secdl_algorithm alg) [static]
References SECDL_HMAC_SHA1, SECDL_HMAC_SHA256, SECDL_INVALID, and SECDL_MD5.
Referenced by secdl_verify_mac(), and URIHANDLER_FUNC().
static int secdl_verify_mac (server * srv, plugin_config * config, const char * protected_path, const char * mac, size_t maclen) [static]
References plugin_config::algorithm, BASE64_URL, CONST_BUF_LEN, const_time_memeq(), li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), li_to_base64_no_padding(), li_tohex(), log_error_write(), secdl_algorithm_mac_length(), SECDL_HMAC_SHA1, SECDL_HMAC_SHA256, SECDL_INVALID, SECDL_MD5, plugin_config::secret, and UNUSED.
Referenced by URIHANDLER_FUNC().
SETDEFAULTS_FUNC (mod_secdownload_set_defaults)
References algorithm_from_string(), buffer_free(), buffer_init(), buffer_is_empty(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), SECDL_HMAC_SHA1, SECDL_HMAC_SHA256, SECDL_INVALID, T_CONFIG_INT, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_secdownload_uri_handler)
References plugin_config::algorithm, buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), plugin_data::conf, DIRECT, plugin_config::doc_root, HANDLER_FINISHED, HANDLER_GO_ON, hex2int(), is_base64_len(), is_hex_len(), log_error_write(), mod_secdownload_patch_connection(), buffer::ptr, secdl_algorithm_mac_length(), SECDL_INVALID, secdl_verify_mac(), plugin_config::secret, plugin_config::timeout, and plugin_config::uri_prefix.
Variable Documentation
const char* secdl_algorithm_names[] [static]
Initial value:
= {
    "invalid",
    "md5",
    "hmac-sha1",
    "hmac-sha256",
}
Referenced by algorithm_from_string().