mod_cml_funcs.c File Reference
#include `first.h`
*
#include <sys/stat.h>
*
#include <time.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <dirent.h>
*
#include <stdio.h>
*
#include <lauxlib.h>
*
#include `mod_cml_funcs.h`
*
#include `mod_cml.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `log.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include `md5.h`
*
Macros
#define HASHLEN 16
#define HASHHEXLEN 32
Typedefs
typedef unsigned char HASH [HASHLEN]
typedef char HASHHEX [HASHHEXLEN+1]
Functions
int f_crypto_md5 (lua_State *L)
int f_file_mtime (lua_State *L)
static int f_dir_files_iter (lua_State *L)
int f_dir_files (lua_State *L)
int f_file_isreg (lua_State *L)
int f_file_isdir (lua_State *L)
Macro Definition Documentation
#define HASHHEXLEN 32
#define HASHLEN 16
Typedef Documentation
typedef unsigned char HASH[HASHLEN]
typedef char HASHHEX[HASHHEXLEN+1]
Function Documentation
int f_crypto_md5 (lua_State * L)
References li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), and li_tohex().
Referenced by cache_parse_lua().
int f_dir_files (lua_State * L)
References f_dir_files_iter().
Referenced by cache_parse_lua().
static int f_dir_files_iter (lua_State * L) [static]
Referenced by f_dir_files().
int f_file_isdir (lua_State * L)
int f_file_isreg (lua_State * L)
Referenced by cache_parse_lua().
int f_file_mtime (lua_State * L)
Referenced by cache_parse_lua().