mod_trigger_b4_dl.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include `inet_ntop_cache.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <fcntl.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_trigger_b4_dl_init)
FREE_FUNC (mod_trigger_b4_dl_free)
SETDEFAULTS_FUNC (mod_trigger_b4_dl_set_defaults)
static int mod_trigger_b4_dl_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_trigger_b4_dl_uri_handler)
int mod_trigger_b4_dl_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_trigger_b4_dl_patch_connection().
Function Documentation
FREE_FUNC (mod_trigger_b4_dl_free)
References array_free(), buffer_free(), plugin_data::config_storage, plugin_config::db_filename, plugin_config::deny_url, plugin_config::download_url, HANDLER_GO_ON, plugin_config::mc_hosts, plugin_config::mc_namespace, plugin_data::tmp_buf, plugin_config::trigger_url, and UNUSED.
INIT_FUNC (mod_trigger_b4_dl_init)
References buffer_init(), and plugin_data::tmp_buf.
static int mod_trigger_b4_dl_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_trigger_b4_dl_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_trigger, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_trigger_b4_dl_set_defaults)
References array_init(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_free(), buffer_init(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, CONST_BUF_LEN, CONST_STR_LEN, config_values_t::destination, fd_close_on_exec(), HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, data_string::value, and data_config::value.
URIHANDLER_FUNC (mod_trigger_b4_dl_uri_handler)
References array_get_element(), buffer_append_string(), buffer_copy_buffer(), buffer_is_empty(), buffer_string_length(), plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, plugin_config::debug, plugin_config::deny_url, DIRECT, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, inet_ntop_cache_get_ip(), log_error_write(), plugin_config::mc_namespace, mod_trigger_b4_dl_patch_connection(), buffer::ptr, response_header_insert(), plugin_data::tmp_buf, plugin_config::trigger_timeout, UNUSED, and data_string::value.