mod_ssi.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include `mod_ssi.h`
*
#include `inet_ntop_cache.h`
*
#include `sys-socket.h`
*
#include <sys/types.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include <strings.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <time.h>
*
#include <unistd.h>
*
#include `etag.h`
*
Macros
#define FIFO_NONBLOCK 0
#define PATCH(x) p->conf.x = s->x;
Functions
static handler_ctx * handler_ctx_init (plugin_data *p)
static void handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_ssi_init)
FREE_FUNC (mod_ssi_free)
SETDEFAULTS_FUNC (mod_ssi_set_defaults)
static int ssi_env_add (void *venv, const char *key, size_t klen, const char *val, size_t vlen)
static int build_ssi_cgi_vars (server *srv, connection *con, handler_ctx *p)
static int mod_ssi_process_file (server *srv, connection *con, handler_ctx *p, struct stat *st)
static int process_ssi_stmt (server *srv, connection *con, handler_ctx *p, const char **l, size_t n, struct stat *st)
static int mod_ssi_parse_ssi_stmt_value (const char *const s, const int len)
static int mod_ssi_parse_ssi_stmt_offlen (int o[10], const char *const s, const int len)
static void mod_ssi_parse_ssi_stmt (server *srv, connection *con, handler_ctx *p, char *s, int len, struct stat *st)
static int mod_ssi_stmt_len (const char *s, const int len)
static void mod_ssi_read_fd (server *srv, connection *con, handler_ctx *p, struct stat *st, int fd)
static int mod_ssi_handle_request (server *srv, connection *con, handler_ctx *p)
static int mod_ssi_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_ssi_physical_path)
SUBREQUEST_FUNC (mod_ssi_handle_subrequest)
static handler_t mod_ssi_connection_reset (server *srv, connection *con, void *p_d)
int mod_ssi_plugin_init (plugin *p)
Variables
static volatile time_t include_file_last_mtime = 0
Macro Definition Documentation
#define FIFO_NONBLOCK 0
Referenced by mod_ssi_process_file().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_ssi_patch_connection().
Function Documentation
static int build_ssi_cgi_vars (server * srv, connection * con, handler_ctx * p) [static]
References array_get_element(), array_reset(), request::headers, http_cgi_headers(), connection::http_status, connection::request, handler_ctx::ssi_cgi_env, ssi_env_add(), and data_string::value.
Referenced by mod_ssi_handle_request().
FREE_FUNC (mod_ssi_free)
References array_free(), buffer_free(), plugin_data::config_storage, plugin_config::content_type, HANDLER_GO_ON, plugin_data::ssi_cgi_env, plugin_config::ssi_extension, plugin_data::ssi_vars, plugin_data::stat_fn, plugin_data::timefmt, and UNUSED.
static void handler_ctx_free (handler_ctx * hctx) [static]
Referenced by mod_ssi_connection_reset().
static handler_ctx* handler_ctx_init (plugin_data * p) [static]
References plugin_data::conf, handler_ctx::conf, force_assert, plugin_data::ssi_cgi_env, handler_ctx::ssi_cgi_env, plugin_data::ssi_vars, handler_ctx::ssi_vars, plugin_data::stat_fn, handler_ctx::stat_fn, plugin_data::timefmt, and handler_ctx::timefmt.
Referenced by URIHANDLER_FUNC().
INIT_FUNC (mod_ssi_init)
References array_init(), buffer_init(), plugin_data::ssi_cgi_env, plugin_data::ssi_vars, plugin_data::stat_fn, and plugin_data::timefmt.
static handler_t mod_ssi_connection_reset (server * srv, connection * con, void * p_d) [static]
References handler_ctx_free(), HANDLER_GO_ON, connection::plugin_ctx, and UNUSED.
Referenced by mod_ssi_plugin_init().
static int mod_ssi_handle_request (server * srv, connection * con, handler_ctx * p) [static]
References array_reset(), buffer_copy_string_len(), buffer_reset(), buffer_string_is_empty(), build_ssi_cgi_vars(), chunkqueue_reset(), plugin_config::conditional_requests, handler_ctx::conf, CONST_BUF_LEN, CONST_STR_LEN, plugin_config::content_type, physical::etag, etag_create(), connection::etag_flags, connection::file_finished, connection::file_started, HANDLER_FINISHED, http_response_handle_cachable(), include_file_last_mtime, mod_ssi_process_file(), physical::path, connection::physical, response_header_overwrite(), handler_ctx::ssi_cgi_env, handler_ctx::ssi_vars, strftime_cache_get(), handler_ctx::timefmt, and connection::write_queue.
Referenced by SUBREQUEST_FUNC().
static void mod_ssi_parse_ssi_stmt (server * srv, connection * con, handler_ctx * p, char * s, int len, struct stat * st) [static]
References chunkqueue_append_mem(), mod_ssi_parse_ssi_stmt_offlen(), process_ssi_stmt(), and connection::write_queue.
Referenced by mod_ssi_read_fd().
static int mod_ssi_parse_ssi_stmt_offlen (int o[10], const char *const s, const int len) [static]
References light_isalpha(), and mod_ssi_parse_ssi_stmt_value().
Referenced by mod_ssi_parse_ssi_stmt().
static int mod_ssi_parse_ssi_stmt_value (const char *const s, const int len) [static]
Referenced by mod_ssi_parse_ssi_stmt_offlen().
static int mod_ssi_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_ssi_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_subrequest, plugin::handle_subrequest_start, plugin::init, mod_ssi_connection_reset(), plugin::name, plugin::set_defaults, and plugin::version.
static int mod_ssi_process_file (server * srv, connection * con, handler_ctx * p, struct stat * st) [static]
References FIFO_NONBLOCK, log_error_write(), mod_ssi_read_fd(), physical::path, connection::physical, and buffer::ptr.
Referenced by mod_ssi_handle_request(), and process_ssi_stmt().
static void mod_ssi_read_fd (server * srv, connection * con, handler_ctx * p, struct stat * st, int fd) [static]
References chunkqueue_append_mem(), CONST_STR_LEN, force_assert, handler_ctx::if_is_false, log_error_write(), mod_ssi_parse_ssi_stmt(), mod_ssi_stmt_len(), physical::path, connection::physical, and connection::write_queue.
Referenced by mod_ssi_process_file().
static int mod_ssi_stmt_len (const char * s, const int len) [static]
Referenced by mod_ssi_read_fd().
static int process_ssi_stmt (server * srv, connection * con, handler_ctx * p, const char ** l, size_t n, struct stat * st) [static]
config DONE errmsg -- missing sizefmt DONE timefmt DONE echo DONE var DONE encoding -- missing exec DONE cgi -- never cmd DONE fsize DONE file DONE virtual DONE flastmod DONE file DONE virtual DONE include DONE file DONE virtual DONE printenv DONE set DONE var DONE value DONE
if DONE elif DONE else DONE endif DONE
expressions AND, OR DONE comp DONE ${...} -- missing $... DONE '...' DONE (...) DONE
** all DONE ** DATE_GMT The current date in Greenwich Mean Time. DATE_LOCAL The current date in the local time zone. DOCUMENT_NAME The filename (excluding directories) of the document requested by the user. DOCUMENT_URI The (%-decoded) URL path of the document requested by the user. Note that in the case of nested include files, this is not then URL for the current document. LAST_MODIFIED The last modification date of the document requested by the user. USER_NAME Contains the owner of the file which included it.
References array_get_element(), array_get_unused_element(), array_insert_unique(), request_uri::authority, buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_int(), buffer_copy_string(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_init_buffer(), buffer_is_equal(), buffer_is_equal_right_len(), buffer_path_simplify(), buffer_string_is_empty(), buffer_string_length(), buffer_to_lower(), buffer_urldecode_path(), chunkqueue_append_buffer(), chunkqueue_append_file(), chunkqueue_append_mem(), chunkqueue_get_memory(), chunkqueue_use_memory(), handler_ctx::conf, connection::conf, CONST_BUF_LEN, CONST_STR_LEN, array::data, data_string_init(), physical::doc_root, ENCODING_MINIMAL_XML, specific_config::force_lowercase_filenames, handler_ctx::if_is_false, handler_ctx::if_is_false_endif, handler_ctx::if_is_false_level, handler_ctx::if_level, include_file_last_mtime, log_error_write(), mod_ssi_process_file(), request_uri::path, physical::path, connection::physical, pid, buffer::ptr, request_uri::query, physical::rel_path, connection::request, request_uri::scheme, SEGFAULT, handler_ctx::sizefmt, array::sorted, handler_ctx::ssi_cgi_env, ssi_eval_expr(), plugin_config::ssi_exec, handler_ctx::ssi_recursion_depth, plugin_config::ssi_recursion_max, handler_ctx::ssi_vars, handler_ctx::stat_fn, handler_ctx::timefmt, server::tmp_buf, TYPE_STRING, request::uri, connection::uri, array::used, data_string::value, and connection::write_queue.
Referenced by mod_ssi_parse_ssi_stmt().
SETDEFAULTS_FUNC (mod_ssi_set_defaults)
References array_init(), buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::ssi_extension, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
static int ssi_env_add (void * venv, const char * key, size_t klen, const char * val, size_t vlen) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), data_string_init(), TYPE_STRING, and data_string::value.
Referenced by build_ssi_cgi_vars().
SUBREQUEST_FUNC (mod_ssi_handle_subrequest)
References DIRECT, HANDLER_FINISHED, HANDLER_GO_ON, and mod_ssi_handle_request().
URIHANDLER_FUNC (mod_ssi_physical_path)
References buffer_is_empty(), buffer_is_equal_right_len(), buffer_string_length(), plugin_data::conf, array::data, DIRECT, handler_ctx_init(), HANDLER_GO_ON, mod_ssi_patch_connection(), plugin_config::ssi_extension, array::used, and data_string::value.
Variable Documentation
volatile time_t include_file_last_mtime = 0 [static]
Referenced by mod_ssi_handle_request(), and process_ssi_stmt().