mod_extforward.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include `configfile.h`
*
#include <assert.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <stdio.h>
*
#include <netinet/in.h>
*
#include <errno.h>
*
Classes
struct plugin_config
struct plugin_data
struct handler_ctx
Macros
#define PATCH(x) p->conf.x = s->x;
#define IP_TRUSTED 1
#define IP_UNTRUSTED 0
Functions
static handler_ctx * handler_ctx_init (sock_addr oldaddr, buffer *oldaddr_buf)
static void handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_extforward_init)
FREE_FUNC (mod_extforward_free)
SETDEFAULTS_FUNC (mod_extforward_set_defaults)
static int mod_extforward_patch_connection (server *srv, connection *con, plugin_data *p)
static void put_string_into_array_len (array *ary, const char *str, int len)
static array * extract_forward_array (buffer *pbuffer)
static int is_proxy_trusted (const char *ipstr, plugin_data *p)
static const char * last_not_in_array (array *a, plugin_data *p)
static void clean_cond_cache (server *srv, connection *con)
URIHANDLER_FUNC (mod_extforward_uri_handler)
CONNECTION_FUNC (mod_extforward_restore)
int mod_extforward_plugin_init (plugin *p)
Macro Definition Documentation
#define IP_TRUSTED 1
Referenced by is_proxy_trusted().
#define IP_UNTRUSTED 0
Referenced by is_proxy_trusted(), and URIHANDLER_FUNC().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_extforward_patch_connection().
Function Documentation
static void clean_cond_cache (server * srv, connection * con) [static]
References COMP_HTTP_REMOTE_IP, COMP_HTTP_SCHEME, and config_cond_cache_reset_item().
Referenced by CONNECTION_FUNC(), and URIHANDLER_FUNC().
CONNECTION_FUNC (mod_extforward_restore)
References buffer_free(), clean_cond_cache(), handler_ctx_free(), HANDLER_GO_ON, handler_ctx::saved_remote_addr, and handler_ctx::saved_remote_addr_buf.
static array* extract_forward_array (buffer * pbuffer) [static]
References array_init(), buffer_string_is_empty(), buffer::ptr, and put_string_into_array_len().
Referenced by URIHANDLER_FUNC().
FREE_FUNC (mod_extforward_free)
References array_free(), plugin_data::config_storage, plugin_config::forwarder, HANDLER_GO_ON, plugin_config::headers, and UNUSED.
static void handler_ctx_free (handler_ctx * hctx) [static]
Referenced by CONNECTION_FUNC(), and URIHANDLER_FUNC().
static handler_ctx* handler_ctx_init (sock_addr oldaddr, buffer * oldaddr_buf) [static]
References handler_ctx::saved_remote_addr, and handler_ctx::saved_remote_addr_buf.
Referenced by URIHANDLER_FUNC().
INIT_FUNC (mod_extforward_init)
static int is_proxy_trusted (const char * ipstr, plugin_data * p) [static]
References array_get_element(), plugin_data::conf, plugin_config::forwarder, IP_TRUSTED, IP_UNTRUSTED, buffer::ptr, and data_string::value.
Referenced by URIHANDLER_FUNC().
static const char* last_not_in_array (array * a, plugin_data * p) [static]
References array_get_element(), plugin_data::conf, array::data, plugin_config::forwarder, buffer::ptr, array::used, and data_string::value.
Referenced by URIHANDLER_FUNC().
static int mod_extforward_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_extforward_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_request_done, plugin::handle_uri_raw, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static void put_string_into_array_len (array * ary, const char * str, int len) [static]
References array_insert_unique(), buffer_copy_string_len(), data_string_init(), and data_string::value.
Referenced by extract_forward_array().
SETDEFAULTS_FUNC (mod_extforward_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, plugin_config::forwarder, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_extforward_uri_handler)
References array_free(), array_get_element(), buffer_copy_string(), buffer_copy_string_len(), buffer_init(), buffer_is_equal_caseless_string(), clean_cond_cache(), plugin_data::conf, CONST_STR_LEN, array::data, extract_forward_array(), handler_ctx_free(), handler_ctx_init(), HANDLER_GO_ON, plugin_config::headers, IP_UNTRUSTED, sock_addr::ipv4, is_proxy_trusted(), last_not_in_array(), log_error_write(), mod_extforward_patch_connection(), sock_addr::plain, buffer::ptr, array::used, and data_string::value.