mod_cml_funcs.h File Reference
#include `first.h`
*
#include <lua.h>
*
Functions
int f_crypto_md5 (lua_State *L)
int f_file_mtime (lua_State *L)
int f_file_isreg (lua_State *L)
int f_file_isdir (lua_State *L)
int f_dir_files (lua_State *L)
int f_memcache_exists (lua_State *L)
int f_memcache_get_string (lua_State *L)
int f_memcache_get_long (lua_State *L)
Function Documentation
int f_crypto_md5 (lua_State * L)
References li_MD5_Final(), li_MD5_Init(), li_MD5_Update(), and li_tohex().
Referenced by cache_parse_lua().
int f_dir_files (lua_State * L)
References f_dir_files_iter().
Referenced by cache_parse_lua().
int f_file_isdir (lua_State * L)
int f_file_isreg (lua_State * L)
Referenced by cache_parse_lua().
int f_file_mtime (lua_State * L)
Referenced by cache_parse_lua().
int f_memcache_exists (lua_State * L)
Referenced by cache_parse_lua().
int f_memcache_get_long (lua_State * L)
Referenced by cache_parse_lua().
int f_memcache_get_string (lua_State * L)
Referenced by cache_parse_lua().