mod_cml_lua.c File Reference
#include `first.h`
*
#include <lua.h>
*
#include <lualib.h>
*
#include <lauxlib.h>
*
#include <assert.h>
*
#include <stdio.h>
*
#include <errno.h>
*
#include <time.h>
*
#include <string.h>
*
#include `mod_cml_funcs.h`
*
#include `mod_cml.h`
*
#include `log.h`
*
#include `stat_cache.h`
*
Macros
#define HASHLEN 16
#define HASHHEXLEN 32
Typedefs
typedef unsigned char HASH [HASHLEN]
typedef char HASHHEX [HASHHEXLEN+1]
Functions
static int lua_to_c_get_string (lua_State *L, const char *varname, buffer *b)
static int lua_to_c_is_table (lua_State *L, const char *varname)
static int c_to_lua_push (lua_State *L, int tbl, const char *key, size_t key_len, const char *val, size_t val_len)
static int cache_export_get_params (lua_State *L, int tbl, buffer *qrystr)
int cache_parse_lua (server *srv, connection *con, plugin_data *p, buffer *fn)
Macro Definition Documentation
#define HASHHEXLEN 32
#define HASHLEN 16
Typedef Documentation
typedef unsigned char HASH[HASHLEN]
typedef char HASHHEX[HASHHEXLEN+1]
Function Documentation
static int c_to_lua_push (lua_State * L, int tbl, const char * key, size_t key_len, const char * val, size_t val_len) [static]
Referenced by cache_export_get_params(), and cache_parse_lua().
static int cache_export_get_params (lua_State * L, int tbl, buffer * qrystr) [static]
References buffer_string_length(), c_to_lua_push(), and buffer::ptr.
Referenced by cache_parse_lua().
int cache_parse_lua (server * srv, connection * con, plugin_data * p, buffer * fn)
References array_get_element(), plugin_data::basedir, physical::basedir, plugin_data::baseurl, buffer_append_string(), buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string(), buffer_free(), buffer_init(), buffer_reset(), buffer_string_is_empty(), c_to_lua_push(), cache_export_get_params(), chunkqueue_append_file_fd(), chunkqueue_reset(), plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, f_crypto_md5(), f_dir_files(), f_file_isreg(), f_file_mtime(), f_memcache_exists(), f_memcache_get_long(), f_memcache_get_string(), connection::file_finished, force_assert, HANDLER_FINISHED, response::headers, http_response_handle_cachable(), log_error_write(), lua_to_c_get_string(), lua_to_c_is_table(), request::orig_uri, request_uri::path, physical::path, request::pathinfo, connection::physical, buffer::ptr, request_uri::query, connection::request, connection::response, response_header_overwrite(), stat_cache_open_rdonly_fstat(), plugin_data::trigger_handler, connection::uri, data_string::value, and connection::write_queue.
Referenced by cache_call_lua().
static int lua_to_c_get_string (lua_State * L, const char * varname, buffer * b) [static]
References buffer_copy_string(), and force_assert.
Referenced by cache_parse_lua().
static int lua_to_c_is_table (lua_State * L, const char * varname) [static]
References force_assert.
Referenced by cache_parse_lua().