mod_evasive.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `response.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_evasive_init)
FREE_FUNC (mod_evasive_free)
SETDEFAULTS_FUNC (mod_evasive_set_defaults)
static int mod_evasive_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_evasive_uri_handler)
int mod_evasive_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_evasive_patch_connection().
Function Documentation
FREE_FUNC (mod_evasive_free)
References buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_config::location, and UNUSED.
INIT_FUNC (mod_evasive_init)
static int mod_evasive_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_evasive_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_evasive_set_defaults)
References buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::max_conns, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_evasive_uri_handler)
References buffer_is_empty(), CON_STATE_REQUEST_END, plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, DIRECT, connection::dst_addr, HANDLER_FINISHED, HANDLER_GO_ON, inet_ntop_cache_get_ip(), sock_addr::ipv4, plugin_config::location, log_error_write(), plugin_config::max_conns, mod_evasive_patch_connection(), sock_addr::plain, response_header_overwrite(), plugin_config::silent, and connection::state.