mod_proxy.c File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include `http_chunk.h`
*
#include `fdevent.h`
*
#include `connections.h`
*
#include `response.h`
*
#include `joblist.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include `crc32.h`
*
#include <sys/types.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <ctype.h>
*
#include <assert.h>
*
#include <stdio.h>
*
#include `sys-socket.h`
*
Classes
struct plugin_config
struct plugin_data
struct handler_ctx
Macros
#define data_proxy data_fastcgi
#define data_proxy_init data_fastcgi_init
#define PROXY_RETRY_TIMEOUT 60
#define PATCH(x) p->conf.x = s->x;
Enumerations
enum proxy_balance_t {
*
PROXY_BALANCE_UNSET,
PROXY_BALANCE_FAIR,
PROXY_BALANCE_HASH,
PROXY_BALANCE_RR,
*
PROXY_BALANCE_STICKY
 }
enum proxy_connection_state_t {
*
PROXY_STATE_INIT,
PROXY_STATE_CONNECT,
PROXY_STATE_PREPARE_WRITE,
PROXY_STATE_WRITE,
*
PROXY_STATE_READ
 }
enum { PROXY_STDOUT,
PROXY_END_REQUEST
 }
Functions
static handler_t proxy_handle_fdevent (server *srv, void *ctx, int revents)
static handler_ctx * handler_ctx_init (void)
static void handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_proxy_init)
FREE_FUNC (mod_proxy_free)
SETDEFAULTS_FUNC (mod_proxy_set_defaults)
static void proxy_backend_close (server *srv, handler_ctx *hctx)
static data_proxy * mod_proxy_extension_host_get (server *srv, connection *con, data_array *extension, proxy_balance_t balance, int debug)
static void proxy_connection_close (server *srv, handler_ctx *hctx)
static handler_t proxy_reconnect (server *srv, handler_ctx *hctx)
static int proxy_establish_connection (server *srv, handler_ctx *hctx)
static void proxy_set_header (connection *con, const char *key, const char *value)
static void proxy_append_header (connection *con, const char *key, const char *value)
static int proxy_create_env (server *srv, handler_ctx *hctx)
static int proxy_set_state (server *srv, handler_ctx *hctx, proxy_connection_state_t state)
static int proxy_response_parse (server *srv, connection *con, plugin_data *p, buffer *in)
static int proxy_demux_response (server *srv, handler_ctx *hctx)
static handler_t proxy_write_request (server *srv, handler_ctx *hctx)
static int mod_proxy_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t proxy_send_request (server *srv, handler_ctx *hctx)
static handler_t proxy_recv_response (server *srv, handler_ctx *hctx)
SUBREQUEST_FUNC (mod_proxy_handle_subrequest)
static handler_t mod_proxy_check_extension (server *srv, connection *con, void *p_d)
static handler_t mod_proxy_connection_reset (server *srv, connection *con, void *p_d)
TRIGGER_FUNC (mod_proxy_trigger)
int mod_proxy_plugin_init (plugin *p)
Macro Definition Documentation
#define data_proxy data_fastcgi
Referenced by mod_proxy_check_extension(), mod_proxy_extension_host_get(), proxy_establish_connection(), proxy_send_request(), proxy_write_request(), SETDEFAULTS_FUNC(), and TRIGGER_FUNC().
#define data_proxy_init data_fastcgi_init
Referenced by SETDEFAULTS_FUNC().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_proxy_patch_connection().
#define PROXY_RETRY_TIMEOUT 60
Enumeration Type Documentation
anonymous enum
Enumerator
PROXY_STDOUT
PROXY_END_REQUEST
enum proxy_balance_t
the proxy module is based on the fastcgi module
28.06.2004 Jan Kneschke The first release 01.07.2004 Evgeny Rodichev Several bugfixes and cleanups
co-ordinate up- and downstream flows correctly (proxy_demux_response and proxy_handle_fdevent)
correctly transfer upstream http_response_status;
some unused structures removed.
TODO: - delay upstream read if write_queue is too large (to prevent memory eating, like in apache). Shoud be configurable).
persistent connection with upstream servers
HTTP/1.1
Enumerator
PROXY_BALANCE_UNSET
PROXY_BALANCE_FAIR
PROXY_BALANCE_HASH
PROXY_BALANCE_RR
PROXY_BALANCE_STICKY
enum proxy_connection_state_t
Enumerator
PROXY_STATE_INIT
PROXY_STATE_CONNECT
PROXY_STATE_PREPARE_WRITE
PROXY_STATE_WRITE
PROXY_STATE_READ
Function Documentation
FREE_FUNC (mod_proxy_free)
References array_free(), plugin_data::balance_buf, buffer_free(), plugin_data::config_storage, plugin_config::extensions, HANDLER_GO_ON, plugin_data::parse_response, and UNUSED.
static void handler_ctx_free (handler_ctx * hctx) [static]
References buffer_free(), chunkqueue_free(), handler_ctx::response, handler_ctx::response_header, and handler_ctx::wb.
Referenced by proxy_connection_close().
static handler_ctx* handler_ctx_init (void) [static]
References buffer_init(), chunkqueue_init(), handler_ctx::fd, handler_ctx::fde_ndx, handler_ctx::host, PROXY_STATE_INIT, handler_ctx::response, handler_ctx::response_header, handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by mod_proxy_check_extension().
INIT_FUNC (mod_proxy_init)
References plugin_data::balance_buf, buffer_init(), and plugin_data::parse_response.
static handler_t mod_proxy_check_extension (server * srv, connection * con, void * p_d) [static]
References plugin_config::balance, buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), plugin_data::conf, handler_ctx::conf, array::data, data_proxy, plugin_config::debug, DIRECT, handler_ctx::ext, plugin_config::extensions, connection::file_started, handler_ctx_init(), HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, handler_ctx::host, log_error_write(), mod_proxy_extension_host_get(), mod_proxy_patch_connection(), connection::mode, request_uri::path, connection::plugin_ctx, handler_ctx::plugin_data, buffer::ptr, handler_ctx::remote_conn, plugin_config::replace_http_host, connection::uri, and array::used.
Referenced by mod_proxy_plugin_init().
static handler_t mod_proxy_connection_reset (server * srv, connection * con, void * p_d) [static]
References HANDLER_GO_ON, connection::plugin_ctx, and proxy_connection_close().
Referenced by mod_proxy_plugin_init().
static data_proxy* mod_proxy_extension_host_get (server * srv, connection * con, data_array * extension, proxy_balance_t balance, int debug) [static]
References request_uri::authority, CONST_BUF_LEN, array::data, data_proxy, DIRECT, connection::dst_addr_buf, force_assert, generate_crc32c(), connection::http_status, log_error_write(), connection::mode, request_uri::path, PROXY_BALANCE_FAIR, PROXY_BALANCE_HASH, PROXY_BALANCE_RR, PROXY_BALANCE_STICKY, connection::uri, array::used, and data_array::value.
Referenced by mod_proxy_check_extension(), and proxy_reconnect().
static int mod_proxy_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_proxy_check_extension().
int mod_proxy_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_connection_close, plugin::handle_subrequest, plugin::handle_trigger, plugin::handle_uri_clean, plugin::init, mod_proxy_check_extension(), mod_proxy_connection_reset(), plugin::name, plugin::set_defaults, and plugin::version.
static void proxy_append_header (connection * con, const char * key, const char * value) [static]
References array_get_unused_element(), array_insert_unique(), buffer_append_string(), buffer_copy_string(), data_string_init(), request::headers, connection::request, TYPE_STRING, and data_string::value.
Referenced by proxy_create_env().
static void proxy_backend_close (server * srv, handler_ctx * hctx) [static]
References server::ev, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_del(), fdevent_sched_close(), fdevent_unregister(), and handler_ctx::host.
Referenced by proxy_connection_close(), and proxy_reconnect().
static void proxy_connection_close (server * srv, handler_ctx * hctx) [static]
References handler_ctx_free(), http_response_backend_done(), connection::mode, connection::plugin_ctx, handler_ctx::plugin_data, proxy_backend_close(), and handler_ctx::remote_conn.
Referenced by mod_proxy_connection_reset(), proxy_handle_fdevent(), and proxy_recv_response().
static int proxy_create_env (server * srv, handler_ctx * hctx) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal_caseless_string(), buffer_string_is_empty(), buffer_string_length(), chunkqueue_append_buffer(), chunkqueue_append_chunkqueue(), handler_ctx::conf, CONST_STR_LEN, request::content_length, array::data, plugin_config::debug, connection::dst_addr, get_http_method_name(), request::headers, handler_ctx::host, request::http_host, request::http_method, inet_ntop_cache_get_ip(), log_error_write(), proxy_append_header(), proxy_set_header(), buffer::ptr, handler_ctx::remote_conn, plugin_config::replace_http_host, connection::request, connection::request_content_queue, request_uri::scheme, request::uri, connection::uri, array::used, data_string::value, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by proxy_write_request().
static int proxy_demux_response (server * srv, handler_ctx * hctx) [static]
References buffer_append_string_len(), buffer_commit(), buffer_reset(), buffer_search_string_len(), buffer_string_length(), buffer_string_prepare_append(), buffer_string_prepare_copy(), buffer_string_space(), chunkqueue_length(), handler_ctx::conf, connection::conf, CONST_STR_LEN, plugin_config::debug, DIRECT, server::ev, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), FDEVENT_IN, FDEVENT_STREAM_RESPONSE_BUFMIN, connection::file_started, force_assert, connection::got_response, http_chunk_append_buffer(), http_chunk_append_mem(), connection::http_status, connection::is_writable, log_error_write(), MAX_HTTP_REQUEST_HEADER, connection::mode, request_uri::path, handler_ctx::plugin_data, proxy_response_parse(), buffer::ptr, handler_ctx::remote_conn, handler_ctx::response, handler_ctx::response_header, specific_config::stream_response_body, connection::uri, buffer::used, and connection::write_queue.
Referenced by proxy_recv_response().
static int proxy_establish_connection (server * srv, handler_ctx * hctx) [static]
References buffer_string_length(), handler_ctx::conf, data_proxy, plugin_config::debug, handler_ctx::fd, handler_ctx::host, and log_error_write().
Referenced by proxy_write_request().
static handler_t proxy_handle_fdevent (server * srv, void * ctx, int revents) [static]
References FDEVENT_ERR, FDEVENT_HUP, FDEVENT_IN, FDEVENT_OUT, connection::file_started, HANDLER_FINISHED, HANDLER_GO_ON, http_response_backend_error(), joblist_append(), log_error_write(), proxy_connection_close(), proxy_recv_response(), proxy_send_request(), PROXY_STATE_CONNECT, handler_ctx::remote_conn, and handler_ctx::state.
Referenced by proxy_write_request().
static handler_t proxy_reconnect (server * srv, handler_ctx * hctx) [static]
References plugin_config::balance, handler_ctx::conf, plugin_config::debug, handler_ctx::ext, HANDLER_COMEBACK, HANDLER_FINISHED, handler_ctx::host, mod_proxy_extension_host_get(), proxy_backend_close(), PROXY_STATE_INIT, handler_ctx::remote_conn, and handler_ctx::state.
Referenced by proxy_send_request().
static handler_t proxy_recv_response (server * srv, handler_ctx * hctx) [static]
References HANDLER_FINISHED, HANDLER_GO_ON, http_response_backend_error(), proxy_connection_close(), proxy_demux_response(), and handler_ctx::remote_conn.
Referenced by proxy_handle_fdevent(), and SUBREQUEST_FUNC().
static int proxy_response_parse (server * srv, connection * con, plugin_data * p, buffer * in) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), response::content_length, data_response_init(), response::headers, HTTP_CONTENT_LENGTH, HTTP_DATE, HTTP_LOCATION, HTTP_STATUS, connection::http_status, plugin_data::parse_response, connection::parsed_response, buffer::ptr, connection::response, TYPE_STRING, UNUSED, and data_string::value.
Referenced by proxy_demux_response().
static handler_t proxy_send_request (server * srv, handler_ctx * hctx) [static]
References server::cur_ts, data_proxy, handler_ctx::fd, HANDLER_ERROR, handler_ctx::host, log_error_write(), proxy_reconnect(), and proxy_write_request().
Referenced by proxy_handle_fdevent(), and SUBREQUEST_FUNC().
static void proxy_set_header (connection * con, const char * key, const char * value) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_string(), data_string_init(), request::headers, connection::request, TYPE_STRING, and data_string::value.
Referenced by proxy_create_env().
static int proxy_set_state (server * srv, handler_ctx * hctx, proxy_connection_state_t state) [static]
References server::cur_ts, handler_ctx::state, and handler_ctx::state_timestamp.
Referenced by proxy_write_request().
static handler_t proxy_write_request (server * srv, handler_ctx * hctx) [static]
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_remove_finished_chunks(), handler_ctx::conf, connection::conf, server::cur_fds, data_proxy, plugin_config::debug, server::ev, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), fdevent_event_set(), fdevent_fcntl_set(), FDEVENT_IN, FDEVENT_OUT, fdevent_register(), fdevent_socket_nb_cloexec(), FDEVENT_STREAM_REQUEST_POLLIN, HANDLER_ERROR, HANDLER_WAIT_FOR_EVENT, handler_ctx::host, connection::is_readable, log_error_write(), MAX_WRITE_LIMIT, server::network_backend_write, fcgi_extension_host::port, proxy_create_env(), proxy_establish_connection(), proxy_handle_fdevent(), proxy_set_state(), PROXY_STATE_CONNECT, PROXY_STATE_INIT, PROXY_STATE_PREPARE_WRITE, PROXY_STATE_READ, PROXY_STATE_WRITE, handler_ctx::remote_conn, handler_ctx::state, specific_config::stream_request_body, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by proxy_send_request().
SETDEFAULTS_FUNC (mod_proxy_set_defaults)
References array_get_element(), array_init(), array_insert_unique(), plugin_data::balance_buf, buffer_copy_buffer(), buffer_is_equal_string(), buffer_reset(), buffer_string_is_empty(), config_insert_values_global(), config_insert_values_internal(), plugin_data::config_storage, CONST_STR_LEN, array::data, data_array_init(), data_proxy, data_proxy_init, config_values_t::destination, plugin_config::extensions, HANDLER_ERROR, log_error_write(), PROXY_BALANCE_FAIR, PROXY_BALANCE_HASH, PROXY_BALANCE_RR, PROXY_BALANCE_STICKY, T_CONFIG_BOOLEAN, T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, TYPE_ARRAY, array::used, data_array::value, and data_config::value.
SUBREQUEST_FUNC (mod_proxy_handle_subrequest)
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_append_chunkqueue(), chunkqueue_is_empty(), chunkqueue_length(), CON_STATE_READ_POST, connection_handle_read_post_error(), connection_handle_read_post_state(), handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_clr(), fdevent_event_get_interest, FDEVENT_IN, FDEVENT_OUT, FDEVENT_STREAM_REQUEST_BUFMIN, FDEVENT_STREAM_REQUEST_POLLIN, FDEVENT_STREAM_RESPONSE_BUFMIN, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, proxy_recv_response(), proxy_send_request(), PROXY_STATE_CONNECT, handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
TRIGGER_FUNC (mod_proxy_trigger)
the trigger re-enables the disabled connections after the timeout is over
References plugin_data::config_storage, array::data, data_proxy, plugin_config::extensions, HANDLER_GO_ON, log_error_write(), array::used, and data_array::value.