mod_fastcgi.c File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include `http_chunk.h`
*
#include `fdevent.h`
*
#include `connections.h`
*
#include `response.h`
*
#include `joblist.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include `stat_cache.h`
*
#include `status_counter.h`
*
#include <sys/types.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <ctype.h>
*
#include <assert.h>
*
#include <signal.h>
*
#include `fastcgi.h`
*
#include <stdio.h>
*
#include `sys-socket.h`
*
Classes
struct fcgi_proc
struct fcgi_extension_host
struct fcgi_extension
struct fcgi_exts
struct plugin_config
struct char_array
struct plugin_data
struct handler_ctx
struct fastcgi_response_packet
Macros
#define CLEAN(x)
#define CLEAN(x)
#define PATCH(x) p->conf.x = s->x;
Typedefs
typedef struct fcgi_proc fcgi_proc
Enumerations
enum fcgi_connection_state_t {
*
FCGI_STATE_INIT,
FCGI_STATE_CONNECT_DELAYED,
FCGI_STATE_PREPARE_WRITE,
FCGI_STATE_WRITE,
*
FCGI_STATE_READ
 }
enum connection_result_t { CONNECTION_OK,
CONNECTION_DELAYED,
CONNECTION_OVERLOADED,
CONNECTION_DEAD
 }
Functions
static handler_t fcgi_handle_fdevent (server *srv, void *ctx, int revents)
static void reset_signals (void)
static void fastcgi_status_copy_procname (buffer *b, fcgi_extension_host *host, fcgi_proc *proc)
static void fcgi_proc_load_inc (server *srv, handler_ctx *hctx)
static void fcgi_proc_load_dec (server *srv, handler_ctx *hctx)
static void fcgi_host_assign (server *srv, handler_ctx *hctx, fcgi_extension_host *host)
static void fcgi_host_reset (server *srv, handler_ctx *hctx)
static void fcgi_host_disable (server *srv, handler_ctx *hctx)
static int fastcgi_status_init (server *srv, buffer *b, fcgi_extension_host *host, fcgi_proc *proc)
static handler_ctx * handler_ctx_init (void)
static void handler_ctx_free (handler_ctx *hctx)
static void handler_ctx_clear (handler_ctx *hctx)
static fcgi_proc * fastcgi_process_init (void)
static void fastcgi_process_free (fcgi_proc *f)
static fcgi_extension_host * fastcgi_host_init (void)
static void fastcgi_host_free (fcgi_extension_host *h)
static fcgi_exts * fastcgi_extensions_init (void)
static void fastcgi_extensions_free (fcgi_exts *f)
static int fastcgi_extension_insert (fcgi_exts *ext, buffer *key, fcgi_extension_host *fh)
INIT_FUNC (mod_fastcgi_init)
FREE_FUNC (mod_fastcgi_free)
static int env_add (char_array *env, const char *key, size_t key_len, const char *val, size_t val_len)
static int parse_binpath (char_array *env, buffer *b)
static int fcgi_spawn_connection (server *srv, plugin_data *p, fcgi_extension_host *host, fcgi_proc *proc)
static fcgi_extension_host * unixsocket_is_dup (plugin_data *p, size_t used, buffer *unixsocket)
SETDEFAULTS_FUNC (mod_fastcgi_set_defaults)
static int fcgi_set_state (server *srv, handler_ctx *hctx, fcgi_connection_state_t state)
static void fcgi_backend_close (server *srv, handler_ctx *hctx)
static fcgi_extension_host * fcgi_extension_host_get (server *srv, connection *con, plugin_data *p, fcgi_extension *extension)
static void fcgi_connection_close (server *srv, handler_ctx *hctx)
static handler_t fcgi_reconnect (server *srv, handler_ctx *hctx)
static handler_t fcgi_connection_reset (server *srv, connection *con, void *p_d)
static int fcgi_env_add (void *venv, const char *key, size_t key_len, const char *val, size_t val_len)
static int fcgi_header (FCGI_Header *header, unsigned char type, int request_id, int contentLength, unsigned char paddingLength)
static connection_result_t fcgi_establish_connection (server *srv, handler_ctx *hctx)
static void fcgi_stdin_append (server *srv, connection *con, handler_ctx *hctx, int request_id)
static int fcgi_create_env (server *srv, handler_ctx *hctx, int request_id)
static int fcgi_response_parse (server *srv, connection *con, plugin_data *p, buffer *in)
static int fastcgi_get_packet (server *srv, handler_ctx *hctx, fastcgi_response_packet *packet)
static int fcgi_demux_response (server *srv, handler_ctx *hctx)
static int fcgi_restart_dead_procs (server *srv, plugin_data *p, fcgi_extension_host *host)
static handler_t fcgi_write_request (server *srv, handler_ctx *hctx)
static handler_t fcgi_send_request (server *srv, handler_ctx *hctx)
static handler_t fcgi_recv_response (server *srv, handler_ctx *hctx)
SUBREQUEST_FUNC (mod_fastcgi_handle_subrequest)
static int fcgi_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t fcgi_check_extension (server *srv, connection *con, void *p_d, int uri_path_handler)
static handler_t fcgi_check_extension_1 (server *srv, connection *con, void *p_d)
static handler_t fcgi_check_extension_2 (server *srv, connection *con, void *p_d)
TRIGGER_FUNC (mod_fastcgi_handle_trigger)
int mod_fastcgi_plugin_init (plugin *p)
Macro Definition Documentation
#define CLEAN(x)
Value:
fastcgi_status_copy_procname(b, host, proc); \
    buffer_append_string_len(b, CONST_STR_LEN(x));
      \
    status_counter_set(srv, CONST_BUF_LEN(b), 0);
Referenced by fastcgi_status_init().
#define CLEAN(x)
Value:
fastcgi_status_copy_procname(b, host, NULL); \
    buffer_append_string_len(b, CONST_STR_LEN(x));
      \
    status_counter_set(srv, CONST_BUF_LEN(b), 0);
#define PATCH(x) p->conf.x = s->x;
Referenced by fcgi_patch_connection().
Typedef Documentation
typedef struct fcgi_proc fcgi_proc
Enumeration Type Documentation
enum connection_result_t
Enumerator
CONNECTION_OK
CONNECTION_DELAYED
CONNECTION_OVERLOADED
CONNECTION_DEAD
enum fcgi_connection_state_t
Enumerator
FCGI_STATE_INIT
FCGI_STATE_CONNECT_DELAYED
FCGI_STATE_PREPARE_WRITE
FCGI_STATE_WRITE
FCGI_STATE_READ
Function Documentation
static int env_add (char_array * env, const char * key, size_t key_len, const char * val, size_t val_len) [static]
References char_array::ptr, char_array::size, and char_array::used.
static int fastcgi_extension_insert (fcgi_exts * ext, buffer * key, fcgi_extension_host * fh) [static]
References buffer_copy_buffer(), buffer_init(), buffer_is_equal(), fcgi_exts::exts, force_assert, fcgi_extension::hosts, fcgi_extension::key, fcgi_extension::last_used_ndx, fcgi_extension::size, fcgi_exts::size, fcgi_extension::used, and fcgi_exts::used.
Referenced by SETDEFAULTS_FUNC().
static void fastcgi_extensions_free (fcgi_exts * f) [static]
References buffer_free(), fcgi_exts::exts, fastcgi_host_free(), fcgi_extension::hosts, fcgi_extension::key, fcgi_extension::used, and fcgi_exts::used.
Referenced by FREE_FUNC().
static fcgi_exts* fastcgi_extensions_init (void) [static]
Referenced by SETDEFAULTS_FUNC().
static int fastcgi_get_packet (server * srv, handler_ctx * hctx, fastcgi_response_packet * packet) [static]
References fastcgi_response_packet::b, buffer_append_string_len(), buffer_free(), buffer_init(), buffer_string_length(), buffer_string_set_length(), chunkqueue_mark_written(), handler_ctx::conf, FCGI_Header::contentLengthB0, FCGI_Header::contentLengthB1, plugin_config::debug, chunkqueue::first, fastcgi_response_packet::len, log_error_write(), chunk::mem, chunk::next, chunk::offset, fastcgi_response_packet::padding, FCGI_Header::paddingLength, buffer::ptr, handler_ctx::rb, fastcgi_response_packet::request_id, FCGI_Header::requestIdB0, FCGI_Header::requestIdB1, FCGI_Header::type, and fastcgi_response_packet::type.
Referenced by fcgi_demux_response().
static void fastcgi_host_free (fcgi_extension_host * h) [static]
References array_free(), fcgi_extension_host::bin_env, fcgi_extension_host::bin_env_copy, fcgi_extension_host::bin_path, buffer_free(), fcgi_extension_host::docroot, fastcgi_process_free(), fcgi_extension_host::first, fcgi_extension_host::host, fcgi_extension_host::id, fcgi_extension_host::refcount, fcgi_extension_host::strip_request_uri, fcgi_extension_host::unixsocket, fcgi_extension_host::unused_procs, and fcgi_extension_host::xsendfile_docroot.
Referenced by fastcgi_extensions_free(), and SETDEFAULTS_FUNC().
static fcgi_extension_host* fastcgi_host_init (void) [static]
References array_init(), fcgi_extension_host::bin_env, fcgi_extension_host::bin_env_copy, fcgi_extension_host::bin_path, buffer_init(), fcgi_extension_host::docroot, fcgi_extension_host::host, fcgi_extension_host::id, fcgi_extension_host::strip_request_uri, fcgi_extension_host::unixsocket, and fcgi_extension_host::xsendfile_docroot.
Referenced by SETDEFAULTS_FUNC().
static void fastcgi_process_free (fcgi_proc * f) [static]
References buffer_free(), fcgi_proc::connection_name, fcgi_proc::next, and fcgi_proc::unixsocket.
Referenced by fastcgi_host_free(), and SETDEFAULTS_FUNC().
static fcgi_proc* fastcgi_process_init (void) [static]
References buffer_init(), fcgi_proc::connection_name, fcgi_proc::next, fcgi_proc::prev, and fcgi_proc::unixsocket.
Referenced by SETDEFAULTS_FUNC().
static void fastcgi_status_copy_procname (buffer * b, fcgi_extension_host * host, fcgi_proc * proc) [static]
References buffer_append_int(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), CONST_STR_LEN, fcgi_proc::id, and fcgi_extension_host::id.
Referenced by fcgi_host_assign(), fcgi_host_reset(), fcgi_proc_load_dec(), fcgi_proc_load_inc(), and fcgi_write_request().
static int fastcgi_status_init (server * srv, buffer * b, fcgi_extension_host * host, fcgi_proc * proc) [static]
References CLEAN.
Referenced by SETDEFAULTS_FUNC().
static void fcgi_backend_close (server * srv, handler_ctx * hctx) [static]
References handler_ctx::conf, fcgi_proc::connection_name, plugin_config::debug, server::ev, fcgi_host_reset(), fcgi_proc_load_dec(), handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_del(), fdevent_sched_close(), fdevent_unregister(), handler_ctx::got_proc, handler_ctx::host, fcgi_proc::load, log_error_write(), fcgi_proc::pid, and handler_ctx::proc.
Referenced by fcgi_connection_close(), fcgi_reconnect(), and fcgi_recv_response().
static handler_t fcgi_check_extension (server * srv, connection * con, void * p_d, int uri_path_handler) [static]
References buffer_copy_string(), buffer_is_empty(), buffer_is_equal(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), fcgi_extension_host::check_local, plugin_data::conf, handler_ctx::conf, connection::conf, array::data, plugin_config::debug, DIRECT, handler_ctx::ext, handler_ctx::ext_auth, plugin_config::ext_mapping, fcgi_exts::exts, plugin_config::exts, plugin_config::exts_auth, plugin_config::exts_resp, FCGI_AUTHORIZER, fcgi_extension_host_get(), fcgi_host_assign(), handler_ctx::fcgi_mode, fcgi_patch_connection(), FCGI_RESPONDER, fcgi_extension_host::fix_root_path_name, handler_ctx_init(), HANDLER_FINISHED, HANDLER_GO_ON, fcgi_extension::key, log_error_write(), specific_config::log_request_handling, connection::mode, fcgi_extension::note_is_sent, request_uri::path, physical::path, request::pathinfo, connection::physical, connection::plugin_ctx, handler_ctx::plugin_data, handler_ctx::proc, buffer::ptr, handler_ctx::remote_conn, connection::request, connection::uri, array::used, fcgi_exts::used, and data_string::value.
Referenced by fcgi_check_extension_1(), and fcgi_check_extension_2().
static handler_t fcgi_check_extension_1 (server * srv, connection * con, void * p_d) [static]
References fcgi_check_extension().
Referenced by mod_fastcgi_plugin_init().
static handler_t fcgi_check_extension_2 (server * srv, connection * con, void * p_d) [static]
References fcgi_check_extension().
Referenced by mod_fastcgi_plugin_init().
static void fcgi_connection_close (server * srv, handler_ctx * hctx) [static]
References fcgi_backend_close(), handler_ctx_free(), http_response_backend_done(), connection::mode, connection::plugin_ctx, handler_ctx::plugin_data, and handler_ctx::remote_conn.
Referenced by fcgi_connection_reset(), fcgi_handle_fdevent(), fcgi_recv_response(), and fcgi_send_request().
static handler_t fcgi_connection_reset (server * srv, connection * con, void * p_d) [static]
References fcgi_connection_close(), HANDLER_GO_ON, and connection::plugin_ctx.
Referenced by mod_fastcgi_plugin_init().
static int fcgi_create_env (server * srv, handler_ctx * hctx, int request_id) [static]
References FCGI_BeginRequestRecord::body, fcgi_extension_host::break_scriptfilename_for_php, buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_string_length(), buffer_string_prepare_copy(), chunkqueue_append_buffer(), request::content_length, fcgi_extension_host::docroot, FCGI_AUTHORIZER, FCGI_BEGIN_REQUEST, plugin_data::fcgi_env, fcgi_env_add(), fcgi_header(), handler_ctx::fcgi_mode, FCGI_PARAMS, fcgi_stdin_append(), FCGI_BeginRequestBody::flags, FCGI_BeginRequestRecord::header, handler_ctx::host, http_cgi_headers(), connection::http_status, handler_ctx::plugin_data, handler_ctx::remote_conn, connection::request, FCGI_BeginRequestBody::reserved, FCGI_BeginRequestBody::roleB0, FCGI_BeginRequestBody::roleB1, fcgi_extension_host::strip_request_uri, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by fcgi_write_request().
static int fcgi_demux_response (server * srv, handler_ctx * hctx) [static]
References array_get_element(), fastcgi_response_packet::b, buffer_append_string_buffer(), buffer_copy_string_len(), buffer_free(), buffer_search_string_len(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), chunkqueue_get_memory(), chunkqueue_length(), chunkqueue_use_memory(), connection::conf, fcgi_proc::connection_name, CONST_STR_LEN, DIRECT, server::ev, fastcgi_get_packet(), FCGI_AUTHORIZER, FCGI_END_REQUEST, handler_ctx::fcgi_mode, fcgi_response_parse(), FCGI_STDERR, FCGI_STDOUT, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), FDEVENT_IN, FDEVENT_STREAM_RESPONSE_BUFMIN, connection::file_started, response::headers, handler_ctx::host, http_chunk_append_buffer(), http_response_xsendfile(), connection::http_status, connection::is_writable, fastcgi_response_packet::len, log_error_write(), log_error_write_multiline_buffer(), MAX_HTTP_REQUEST_HEADER, connection::mode, request_uri::path, fcgi_proc::pid, handler_ctx::plugin_data, handler_ctx::proc, buffer::ptr, handler_ctx::rb, handler_ctx::remote_conn, connection::response, handler_ctx::response_header, handler_ctx::send_content_body, specific_config::stream_response_body, fastcgi_response_packet::type, connection::uri, data_string::value, connection::write_queue, fcgi_extension_host::xsendfile_allow, and fcgi_extension_host::xsendfile_docroot.
Referenced by fcgi_recv_response().
static int fcgi_env_add (void * venv, const char * key, size_t key_len, const char * val, size_t val_len) [static]
we can't append more headers, ignore it
field length can be 31bit max
HINT: this can't happen as FCGI_MAX_LENGTH is only 16bit
References buffer_append_string_len(), buffer_string_length(), buffer_string_prepare_append(), FCGI_MAX_LENGTH, and force_assert.
Referenced by fcgi_create_env().
static connection_result_t fcgi_establish_connection (server * srv, handler_ctx * hctx) [static]
References buffer_append_int(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string_len(), buffer_string_is_empty(), buffer_string_length(), handler_ctx::conf, CONNECTION_DEAD, CONNECTION_DELAYED, fcgi_proc::connection_name, CONNECTION_OK, CONNECTION_OVERLOADED, CONST_STR_LEN, plugin_config::debug, fcgi_extension_host::family, handler_ctx::fd, fcgi_extension_host::host, handler_ctx::host, fcgi_proc::load, log_error_write(), fcgi_proc::port, handler_ctx::proc, buffer::ptr, handler_ctx::reconnects, and fcgi_proc::unixsocket.
Referenced by fcgi_write_request().
static fcgi_extension_host* fcgi_extension_host_get (server * srv, connection * con, plugin_data * p, fcgi_extension * extension) [static]
References fcgi_extension_host::active_procs, DIRECT, fcgi_extension::hosts, connection::http_status, fcgi_extension::key, fcgi_extension::last_used_ndx, fcgi_extension_host::load, log_error_write(), connection::mode, fcgi_extension::note_is_sent, request_uri::path, request_uri::query, UNUSED, connection::uri, and fcgi_extension::used.
Referenced by fcgi_check_extension(), and fcgi_reconnect().
static handler_t fcgi_handle_fdevent (server * srv, void * ctx, int revents) [static]
References fcgi_proc::connection_name, fcgi_connection_close(), fcgi_recv_response(), fcgi_send_request(), FCGI_STATE_CONNECT_DELAYED, FDEVENT_ERR, FDEVENT_HUP, FDEVENT_IN, FDEVENT_OUT, connection::file_started, HANDLER_FINISHED, HANDLER_GO_ON, http_response_backend_error(), joblist_append(), log_error_write(), request_uri::path, handler_ctx::proc, request_uri::query, handler_ctx::remote_conn, handler_ctx::state, and connection::uri.
Referenced by fcgi_write_request().
static int fcgi_header (FCGI_Header * header, unsigned char type, int request_id, int contentLength, unsigned char paddingLength) [static]
References FCGI_Header::contentLengthB0, FCGI_Header::contentLengthB1, FCGI_MAX_LENGTH, FCGI_VERSION_1, force_assert, FCGI_Header::paddingLength, FCGI_Header::requestIdB0, FCGI_Header::requestIdB1, FCGI_Header::reserved, FCGI_Header::type, and FCGI_Header::version.
Referenced by fcgi_create_env(), and fcgi_stdin_append().
static void fcgi_host_assign (server * srv, handler_ctx * hctx, fcgi_extension_host * host) [static]
References buffer_append_string_len(), CONST_BUF_LEN, CONST_STR_LEN, fastcgi_status_copy_procname(), handler_ctx::host, fcgi_extension_host::load, handler_ctx::plugin_data, status_counter_set(), and plugin_data::statuskey.
Referenced by fcgi_check_extension(), and fcgi_reconnect().
static void fcgi_host_disable (server * srv, handler_ctx * hctx) [static]
References fcgi_extension_host::active_procs, handler_ctx::conf, server::cur_ts, plugin_config::debug, fcgi_extension_host::disable_time, fcgi_proc::disabled_until, handler_ctx::host, fcgi_proc::is_local, log_error_write(), handler_ctx::proc, and fcgi_proc::state.
Referenced by fcgi_write_request().
static void fcgi_host_reset (server * srv, handler_ctx * hctx) [static]
References buffer_append_string_len(), CONST_BUF_LEN, CONST_STR_LEN, fastcgi_status_copy_procname(), handler_ctx::host, fcgi_extension_host::load, handler_ctx::plugin_data, status_counter_set(), and plugin_data::statuskey.
Referenced by fcgi_backend_close().
static int fcgi_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by fcgi_check_extension().
static void fcgi_proc_load_dec (server * srv, handler_ctx * hctx) [static]
References buffer_append_string_len(), CONST_BUF_LEN, CONST_STR_LEN, fastcgi_status_copy_procname(), handler_ctx::host, fcgi_proc::load, handler_ctx::plugin_data, handler_ctx::proc, status_counter_dec(), status_counter_set(), and plugin_data::statuskey.
Referenced by fcgi_backend_close().
static void fcgi_proc_load_inc (server * srv, handler_ctx * hctx) [static]
References buffer_append_string_len(), CONST_BUF_LEN, CONST_STR_LEN, fastcgi_status_copy_procname(), handler_ctx::host, fcgi_proc::load, handler_ctx::plugin_data, handler_ctx::proc, status_counter_inc(), status_counter_set(), and plugin_data::statuskey.
Referenced by fcgi_write_request().
static handler_t fcgi_reconnect (server * srv, handler_ctx * hctx) [static]
References handler_ctx::ext, fcgi_backend_close(), fcgi_extension_host_get(), fcgi_host_assign(), fcgi_set_state(), FCGI_STATE_INIT, HANDLER_COMEBACK, HANDLER_FINISHED, handler_ctx::host, handler_ctx::plugin_data, handler_ctx::remote_conn, and handler_ctx::request_id.
Referenced by fcgi_recv_response(), and fcgi_send_request().
static handler_t fcgi_recv_response (server * srv, handler_ctx * hctx) [static]
References physical::basedir, buffer_append_string_buffer(), buffer_copy_buffer(), buffer_string_is_empty(), chunkqueue::bytes_out, handler_ctx::conf, fcgi_proc::connection_name, connection_response_reset(), plugin_config::debug, DIRECT, physical::doc_root, fcgi_extension_host::docroot, FCGI_AUTHORIZER, fcgi_backend_close(), fcgi_connection_close(), fcgi_demux_response(), handler_ctx::fcgi_mode, fcgi_reconnect(), fcgi_spawn_connection(), connection::file_started, HANDLER_COMEBACK, handler_ctx_clear(), HANDLER_FINISHED, HANDLER_GO_ON, handler_ctx::host, http_response_backend_error(), connection::http_status, log_error_write(), connection::loops_per_request, fcgi_extension_host::max_procs, connection::mode, request::orig_uri, request_uri::path, physical::path, connection::physical, fcgi_proc::pid, handler_ctx::plugin_data, handler_ctx::proc, request_uri::query, handler_ctx::reconnects, handler_ctx::remote_conn, connection::request, fcgi_proc::state, connection::uri, and handler_ctx::wb.
Referenced by fcgi_handle_fdevent(), and SUBREQUEST_FUNC().
static int fcgi_response_parse (server * srv, connection * con, plugin_data * p, buffer * in) [static]
References array_get_unused_element(), array_insert_unique(), array_replace(), buffer_copy_int(), buffer_copy_string(), buffer_copy_string_len(), buffer_path_simplify(), buffer_string_length(), buffer_to_lower(), buffer_urldecode_path(), handler_ctx::conf, connection::conf, CONST_STR_LEN, response::content_length, array::data, data_response_init(), plugin_config::debug, connection::environment, FCGI_AUTHORIZER, handler_ctx::fcgi_mode, specific_config::force_lowercase_filenames, HANDLER_ERROR, response::headers, handler_ctx::host, http_chunk_append_file_range(), HTTP_CONNECTION, HTTP_CONTENT_LENGTH, HTTP_DATE, HTTP_LOCATION, HTTP_STATUS, connection::http_status, response::keep_alive, log_error_write(), connection::parsed_response, connection::plugin_ctx, buffer::ptr, connection::response, handler_ctx::send_content_body, stat_cache_entry::st, stat_cache_get_entry(), server::tmp_buf, TYPE_STRING, UNUSED, array::used, data_string::value, fcgi_extension_host::xsendfile_allow, and fcgi_extension_host::xsendfile_docroot.
Referenced by fcgi_demux_response().
static int fcgi_restart_dead_procs (server * srv, plugin_data * p, fcgi_extension_host * host) [static]
References fcgi_extension_host::active_procs, fcgi_extension_host::bin_path, buffer_string_is_empty(), plugin_data::conf, fcgi_proc::connection_name, server::cur_ts, plugin_config::debug, fcgi_proc::disabled_until, fcgi_spawn_connection(), fcgi_extension_host::first, force_assert, HANDLER_ERROR, fcgi_extension_host::host, fcgi_proc::is_local, fcgi_proc::load, log_error_write(), fcgi_extension_host::max_procs, fcgi_proc::next, fcgi_proc::pid, fcgi_extension_host::port, fcgi_proc::state, and fcgi_extension_host::unixsocket.
Referenced by fcgi_send_request(), and TRIGGER_FUNC().
static handler_t fcgi_send_request (server * srv, handler_ctx * hctx) [static]
References fcgi_connection_close(), fcgi_reconnect(), fcgi_restart_dead_procs(), FCGI_STATE_CONNECT_DELAYED, FCGI_STATE_INIT, fcgi_write_request(), HANDLER_ERROR, HANDLER_FINISHED, handler_ctx::host, connection::http_status, handler_ctx::plugin_data, handler_ctx::reconnects, handler_ctx::remote_conn, and handler_ctx::state.
Referenced by fcgi_handle_fdevent(), and SUBREQUEST_FUNC().
static int fcgi_set_state (server * srv, handler_ctx * hctx, fcgi_connection_state_t state) [static]
References server::cur_ts, handler_ctx::state, and handler_ctx::state_timestamp.
Referenced by fcgi_reconnect(), and fcgi_write_request().
static int fcgi_spawn_connection (server * srv, plugin_data * p, fcgi_extension_host * host, fcgi_proc * proc) [static]
References UNUSED.
Referenced by fcgi_recv_response(), fcgi_restart_dead_procs(), and SETDEFAULTS_FUNC().
static void fcgi_stdin_append (server * srv, connection * con, handler_ctx * hctx, int request_id) [static]
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_append_mem(), chunkqueue_steal(), handler_ctx::conf, plugin_config::debug, fcgi_header(), FCGI_MAX_LENGTH, FCGI_STDIN, log_error_write(), connection::request_content_queue, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by fcgi_create_env(), and SUBREQUEST_FUNC().
static handler_t fcgi_write_request (server * srv, handler_ctx * hctx) [static]
References fcgi_extension_host::active_procs, buffer_append_string_len(), chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_remove_finished_chunks(), handler_ctx::conf, connection::conf, CONNECTION_DEAD, CONNECTION_DELAYED, fcgi_proc::connection_name, CONNECTION_OK, CONNECTION_OVERLOADED, CONST_BUF_LEN, CONST_STR_LEN, server::cur_fds, server::cur_ts, plugin_config::debug, fcgi_extension_host::disable_time, fcgi_proc::disabled_until, server::ev, fcgi_extension_host::family, fastcgi_status_copy_procname(), fcgi_create_env(), fcgi_establish_connection(), fcgi_handle_fdevent(), fcgi_host_disable(), fcgi_proc_load_inc(), fcgi_set_state(), FCGI_STATE_CONNECT_DELAYED, FCGI_STATE_INIT, FCGI_STATE_PREPARE_WRITE, FCGI_STATE_READ, FCGI_STATE_WRITE, handler_ctx::fd, connection::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), fdevent_event_set(), fdevent_fcntl_set(), FDEVENT_IN, FDEVENT_OUT, fdevent_register(), fdevent_socket_nb_cloexec(), FDEVENT_STREAM_REQUEST_POLLIN, fcgi_extension_host::first, handler_ctx::got_proc, HANDLER_ERROR, HANDLER_WAIT_FOR_EVENT, HANDLER_WAIT_FOR_FD, handler_ctx::host, fcgi_proc::is_local, connection::is_readable, fcgi_proc::load, fcgi_extension_host::load, log_error_write(), server::max_fds, MAX_WRITE_LIMIT, server::network_backend_write, fcgi_proc::next, fcgi_proc::pid, handler_ctx::pid, handler_ctx::plugin_data, handler_ctx::proc, handler_ctx::reconnects, handler_ctx::remote_conn, handler_ctx::request_id, fcgi_proc::state, handler_ctx::state, status_counter_inc(), plugin_data::statuskey, specific_config::stream_request_body, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by fcgi_send_request().
FREE_FUNC (mod_fastcgi_free)
References array_free(), buffer_free(), buffer_string_is_empty(), plugin_data::config_storage, plugin_config::ext_mapping, fcgi_exts::exts, plugin_config::exts, plugin_config::exts_auth, plugin_config::exts_resp, fastcgi_extensions_free(), plugin_data::fcgi_env, fcgi_extension_host::first, HANDLER_GO_ON, fcgi_extension::hosts, fcgi_proc::is_local, fcgi_extension_host::kill_signal, fcgi_proc::next, fcgi_proc::pid, buffer::ptr, plugin_data::statuskey, fcgi_proc::unixsocket, UNUSED, fcgi_extension_host::unused_procs, fcgi_extension::used, and fcgi_exts::used.
static void handler_ctx_clear (handler_ctx * hctx) [static]
References buffer_reset(), chunkqueue_reset(), handler_ctx::ext, handler_ctx::fcgi_mode, FCGI_RESPONDER, FCGI_STATE_INIT, handler_ctx::fd, handler_ctx::fde_ndx, handler_ctx::got_proc, handler_ctx::host, handler_ctx::proc, handler_ctx::rb, handler_ctx::reconnects, handler_ctx::request_id, handler_ctx::response_header, handler_ctx::send_content_body, handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by fcgi_recv_response().
static void handler_ctx_free (handler_ctx * hctx) [static]
References buffer_free(), chunkqueue_free(), handler_ctx::rb, handler_ctx::response_header, and handler_ctx::wb.
Referenced by fcgi_connection_close().
static handler_ctx* handler_ctx_init (void) [static]
References buffer_init(), chunkqueue_init(), handler_ctx::fcgi_mode, FCGI_RESPONDER, FCGI_STATE_INIT, handler_ctx::fd, handler_ctx::fde_ndx, force_assert, handler_ctx::proc, handler_ctx::rb, handler_ctx::reconnects, handler_ctx::request_id, handler_ctx::response_header, handler_ctx::send_content_body, handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
Referenced by fcgi_check_extension().
INIT_FUNC (mod_fastcgi_init)
References buffer_init(), plugin_data::fcgi_env, and plugin_data::statuskey.
int mod_fastcgi_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, fcgi_check_extension_1(), fcgi_check_extension_2(), fcgi_connection_reset(), plugin::handle_connection_close, plugin::handle_subrequest, plugin::handle_subrequest_start, plugin::handle_trigger, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static int parse_binpath (char_array * env, buffer * b) [static]
References buffer_string_length(), buffer::ptr, char_array::ptr, char_array::size, and char_array::used.
static void reset_signals (void) [static]
SETDEFAULTS_FUNC (mod_fastcgi_set_defaults)
References fcgi_extension_host::active_procs, array_get_element(), array_init(), fcgi_extension_host::bin_env, fcgi_extension_host::bin_env_copy, fcgi_extension_host::bin_path, fcgi_extension_host::break_scriptfilename_for_php, buffer_append_int(), buffer_append_slash(), buffer_append_string_len(), buffer_copy_buffer(), buffer_init(), buffer_is_equal(), buffer_path_simplify(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), fcgi_extension_host::check_local, server::config_context, config_insert_values_global(), config_insert_values_internal(), plugin_data::config_storage, CONST_STR_LEN, array::data, config_values_t::destination, fcgi_extension_host::disable_time, fcgi_extension_host::docroot, plugin_config::exts, fcgi_extension_host::family, fastcgi_extension_insert(), fastcgi_extensions_init(), fastcgi_host_free(), fastcgi_host_init(), fastcgi_process_free(), fastcgi_process_init(), fastcgi_status_init(), FCGI_AUTHORIZER, FCGI_RESPONDER, fcgi_spawn_connection(), fcgi_extension_host::first, fcgi_extension_host::fix_root_path_name, fcgi_extension_host::host, fcgi_proc::id, fcgi_extension_host::id, fcgi_extension_host::kill_signal, fcgi_extension_host::listen_backlog, log_error_write(), fcgi_extension_host::max_id, fcgi_extension_host::max_procs, fcgi_proc::next, fcgi_extension_host::num_procs, fcgi_proc::port, fcgi_extension_host::port, server_config::preflight_check, fcgi_proc::prev, buffer::ptr, fcgi_extension_host::refcount, server::srvconf, fcgi_proc::state, plugin_data::statuskey, fcgi_extension_host::strip_request_uri, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_INT, T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, TYPE_ARRAY, TYPE_STRING, fcgi_proc::unixsocket, fcgi_extension_host::unixsocket, unixsocket_is_dup(), array::used, data_string::value, data_array::value, data_config::value, fcgi_extension_host::xsendfile_allow, and fcgi_extension_host::xsendfile_docroot.
SUBREQUEST_FUNC (mod_fastcgi_handle_subrequest)
References chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_is_empty(), chunkqueue_length(), CON_STATE_READ_POST, connection_handle_read_post_error(), connection_handle_read_post_state(), server::ev, FCGI_AUTHORIZER, handler_ctx::fcgi_mode, fcgi_recv_response(), fcgi_send_request(), FCGI_STATE_CONNECT_DELAYED, fcgi_stdin_append(), handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_clr(), fdevent_event_get_interest, FDEVENT_IN, FDEVENT_OUT, FDEVENT_STREAM_REQUEST_BUFMIN, FDEVENT_STREAM_REQUEST_POLLIN, FDEVENT_STREAM_RESPONSE_BUFMIN, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, handler_ctx::request_id, handler_ctx::state, handler_ctx::wb, and handler_ctx::wb_reqlen.
TRIGGER_FUNC (mod_fastcgi_handle_trigger)
References fcgi_extension_host::active_procs, server::config_context, plugin_data::config_storage, fcgi_proc::connection_name, fcgi_exts::exts, plugin_config::exts, fcgi_restart_dead_procs(), fcgi_extension_host::first, HANDLER_GO_ON, fcgi_extension::hosts, log_error_write(), fcgi_extension_host::max_id, fcgi_proc::next, fcgi_proc::pid, fcgi_proc::state, fcgi_extension_host::unused_procs, array::used, fcgi_extension::used, and fcgi_exts::used.
static fcgi_extension_host* unixsocket_is_dup (plugin_data * p, size_t used, buffer * unixsocket) [static]
References fcgi_extension_host::bin_path, buffer_is_equal(), buffer_string_is_empty(), plugin_data::config_storage, fcgi_exts::exts, plugin_config::exts, fcgi_extension::hosts, fcgi_extension_host::unixsocket, fcgi_extension::used, and fcgi_exts::used.
Referenced by SETDEFAULTS_FUNC().