mod_ssi.h File Reference
#include `first.h`
*
#include `base.h`
*
#include `buffer.h`
*
#include `array.h`
*
#include `plugin.h`
*
Classes
struct plugin_config
struct plugin_data
struct handler_ctx
Functions
int ssi_eval_expr (server *srv, connection *con, handler_ctx *p, const char *expr)
Function Documentation
int ssi_eval_expr (server * srv, connection * con, handler_ctx * p, const char * expr)
References ssi_val_t::bo, buffer_free(), buffer_init(), force_assert, ssi_tokenizer_t::in_brace, ssi_tokenizer_t::in_cond, ssi_tokenizer_t::in_key, ssi_tokenizer_t::input, ssi_tokenizer_t::line_pos, log_error_write(), ssi_tokenizer_t::offset, ssi_ctx_t::ok, ssi_tokenizer_t::size, ssi_ctx_t::srv, ssi_expr_tokenizer(), ssiexprparser(), ssiexprparserAlloc(), ssiexprparserFree(), and ssi_ctx_t::val.
Referenced by process_ssi_stmt().