mod_rewrite.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `stat_cache.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Macros
#define parse_config_entry(srv, ca, x, option, y) parse_config_entry(srv, ca, option)
Functions
static int parse_config_entry (server *srv, array *ca, const char *option)
SETDEFAULTS_FUNC (mod_rewrite_set_defaults)
int mod_rewrite_plugin_init (plugin *p)
Macro Definition Documentation
#define parse_config_entry(srv, ca, x, option, y) parse_config_entry(srv, ca, option)
Referenced by SETDEFAULTS_FUNC().
Function Documentation
int mod_rewrite_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_physical, plugin::handle_uri_raw, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static int parse_config_entry (server * srv, array * ca, const char * option) [static]
References array_get_element(), and log_error_write().
SETDEFAULTS_FUNC (mod_rewrite_set_defaults)
References server::config_context, config_insert_values_global(), plugin_data::config_storage, array::data, HANDLER_ERROR, HANDLER_GO_ON, parse_config_entry, T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, UNUSED, array::used, and data_config::value.