mod_ssi_expr.c File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `log.h`
*
#include `mod_ssi.h`
*
#include `mod_ssi_expr.h`
*
#include `mod_ssi_exprparser.h`
*
#include <ctype.h>
*
#include <string.h>
*
Classes
struct ssi_tokenizer_t
Functions
ssi_val_t * ssi_val_init (void)
void ssi_val_free (ssi_val_t *s)
int ssi_val_tobool (ssi_val_t *B)
static int ssi_expr_tokenizer (server *srv, connection *con, handler_ctx *p, ssi_tokenizer_t *t, int *token_id, buffer *token)
int ssi_eval_expr (server *srv, connection *con, handler_ctx *p, const char *expr)
Function Documentation
int ssi_eval_expr (server * srv, connection * con, handler_ctx * p, const char * expr)
References ssi_val_t::bo, buffer_free(), buffer_init(), force_assert, ssi_tokenizer_t::in_brace, ssi_tokenizer_t::in_cond, ssi_tokenizer_t::in_key, ssi_tokenizer_t::input, ssi_tokenizer_t::line_pos, log_error_write(), ssi_tokenizer_t::offset, ssi_ctx_t::ok, ssi_tokenizer_t::size, ssi_ctx_t::srv, ssi_expr_tokenizer(), ssiexprparser(), ssiexprparserAlloc(), ssiexprparserFree(), and ssi_ctx_t::val.
Referenced by process_ssi_stmt().
static int ssi_expr_tokenizer (server * srv, connection * con, handler_ctx * p, ssi_tokenizer_t * t, int * token_id, buffer * token) [static]
References array_get_element(), buffer_copy_buffer(), buffer_copy_string_len(), CONST_STR_LEN, ssi_tokenizer_t::in_brace, ssi_tokenizer_t::input, ssi_tokenizer_t::line_pos, log_error_write(), ssi_tokenizer_t::offset, buffer::ptr, ssi_tokenizer_t::size, handler_ctx::ssi_cgi_env, handler_ctx::ssi_vars, TK_AND, TK_EQ, TK_GE, TK_GT, TK_LE, TK_LPARAN, TK_LT, TK_NE, TK_NOT, TK_OR, TK_RPARAN, TK_VALUE, UNUSED, and data_string::value.
Referenced by ssi_eval_expr().
void ssi_val_free (ssi_val_t * s)
References buffer_free(), and ssi_val_t::str.
Referenced by yy_reduce().
ssi_val_t* ssi_val_init (void)
Referenced by yy_reduce().
int ssi_val_tobool (ssi_val_t * B)
References ssi_val_t::bo, buffer_string_is_empty(), ssi_val_t::str, and ssi_val_t::type.
Referenced by yy_reduce().