mod_authn_gssapi.c File Reference
#include `first.h`
*
#include `plugin.h`
*
#include <krb5.h>
*
#include <gssapi.h>
*
#include <gssapi/gssapi_krb5.h>
*
#include `http_auth.h`
*
#include `base.h`
*
#include `log.h`
*
#include `md5.h`
*
#include `base64.h`
*
#include `response.h`
*
#include <errno.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
#define GSS_KRB5_NT_PRINCIPAL_NAME gss_nt_krb5_name
Functions
static handler_t mod_authn_gssapi_check (server *srv, connection *con, void *p_d, const struct http_auth_require_t *require, const struct http_auth_backend_t *backend)
static handler_t mod_authn_gssapi_basic (server *srv, connection *con, void *p_d, const http_auth_require_t *require, const buffer *username, const char *pw)
INIT_FUNC (mod_authn_gssapi_init)
FREE_FUNC (mod_authn_gssapi_free)
SETDEFAULTS_FUNC (mod_authn_gssapi_set_defaults)
static int mod_authn_gssapi_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t mod_authn_gssapi_send_400_bad_request (server *srv, connection *con)
static void mod_authn_gssapi_log_gss_error (server *srv, const char *file, unsigned int line, const char *func, const char *extra, OM_uint32 err_maj, OM_uint32 err_min)
static void mod_authn_gssapi_log_krb5_error (server *srv, const char *file, unsigned int line, const char *func, const char *extra, krb5_context context, int code)
static int mod_authn_gssapi_create_krb5_ccache (server *srv, connection *con, plugin_data *p, krb5_context kcontext, krb5_principal princ, krb5_ccache *ccache)
static handler_t mod_authn_gssapi_send_401_unauthorized_negotiate (server *srv, connection *con)
static int mod_authn_gssapi_store_gss_creds (server *srv, connection *con, plugin_data *p, char *princ_name, gss_cred_id_t delegated_cred)
static handler_t mod_authn_gssapi_check_spnego (server *srv, connection *con, plugin_data *p, const http_auth_require_t *require, const char *realm_str)
static krb5_error_code mod_authn_gssapi_verify_krb5_init_creds (server *srv, krb5_context context, krb5_creds *creds, krb5_principal ap_req_server, krb5_keytab ap_req_keytab)
static int mod_authn_gssapi_store_krb5_creds (server *srv, connection *con, plugin_data *p, krb5_context kcontext, krb5_ccache delegated_cred)
static handler_t mod_authn_gssapi_send_401_unauthorized_basic (server *srv, connection *con)
CONNECTION_FUNC (mod_authn_gssapi_handle_reset)
int mod_authn_gssapi_plugin_init (plugin *p)
Macro Definition Documentation
#define GSS_KRB5_NT_PRINCIPAL_NAME gss_nt_krb5_name
Referenced by mod_authn_gssapi_check_spnego().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_authn_gssapi_patch_connection().
Function Documentation
CONNECTION_FUNC (mod_authn_gssapi_handle_reset)
References buffer_free(), HANDLER_GO_ON, buffer::ptr, and UNUSED.
FREE_FUNC (mod_authn_gssapi_free)
References plugin_config::auth_gssapi_keytab, plugin_config::auth_gssapi_principal, buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_authn_gssapi_init)
References http_auth_backend_set(), http_auth_scheme_set(), mod_authn_gssapi_basic(), mod_authn_gssapi_check(), http_auth_backend_t::p_d, and http_auth_scheme_t::p_d.
static handler_t mod_authn_gssapi_basic (server * srv, connection * con, void * p_d, const http_auth_require_t * require, const buffer * username, const char * pw) [static]
References plugin_config::auth_gssapi_keytab, plugin_config::auth_gssapi_principal, buffer_append_string(), buffer_append_string_buffer(), BUFFER_APPEND_STRING_CONST, buffer_append_string_len(), buffer_free(), buffer_init_buffer(), buffer_is_empty(), plugin_data::conf, connection::dst_addr_buf, HANDLER_GO_ON, http_auth_match_rules(), request::http_host, log_error_write(), mod_authn_gssapi_log_krb5_error(), mod_authn_gssapi_patch_connection(), mod_authn_gssapi_send_401_unauthorized_basic(), mod_authn_gssapi_store_krb5_creds(), mod_authn_gssapi_verify_krb5_init_creds(), request_uri::path, buffer::ptr, http_auth_require_t::realm, connection::request, and connection::uri.
Referenced by INIT_FUNC().
static handler_t mod_authn_gssapi_check (server * srv, connection * con, void * p_d, const struct http_auth_require_t * require, const struct http_auth_backend_t * backend) [static]
References array_get_element(), buffer_is_empty(), request::headers, mod_authn_gssapi_check_spnego(), mod_authn_gssapi_send_400_bad_request(), mod_authn_gssapi_send_401_unauthorized_negotiate(), buffer::ptr, connection::request, UNUSED, and data_string::value.
Referenced by INIT_FUNC().
static handler_t mod_authn_gssapi_check_spnego (server * srv, connection * con, plugin_data * p, const http_auth_require_t * require, const char * realm_str) [static]
References plugin_config::auth_gssapi_keytab, plugin_config::auth_gssapi_principal, BASE64_STANDARD, buffer_append_base64_decode(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_string(), buffer_free(), buffer_init(), buffer_init_buffer(), buffer_is_empty(), buffer_string_length(), plugin_data::conf, CONST_STR_LEN, connection::environment, GSS_KRB5_NT_PRINCIPAL_NAME, HANDLER_GO_ON, http_auth_match_rules(), http_auth_setenv(), request::http_host, log_error_write(), mod_authn_gssapi_log_gss_error(), mod_authn_gssapi_patch_connection(), mod_authn_gssapi_send_400_bad_request(), mod_authn_gssapi_send_401_unauthorized_negotiate(), mod_authn_gssapi_store_gss_creds(), buffer::ptr, http_auth_require_t::realm, and connection::request.
Referenced by mod_authn_gssapi_check().
static int mod_authn_gssapi_create_krb5_ccache (server * srv, connection * con, plugin_data * p, krb5_context kcontext, krb5_principal princ, krb5_ccache * ccache) [static]
References array_set_key_value(), buffer_free(), buffer_init_string(), buffer_string_length(), CONST_STR_LEN, connection::environment, request::headers, log_error_write(), mod_authn_gssapi_log_krb5_error(), connection::plugin_ctx, buffer::ptr, and connection::request.
Referenced by mod_authn_gssapi_store_gss_creds(), and mod_authn_gssapi_store_krb5_creds().
static void mod_authn_gssapi_log_gss_error (server * srv, const char * file, unsigned int line, const char * func, const char * extra, OM_uint32 err_maj, OM_uint32 err_min) [static]
References buffer_append_string(), buffer_append_string_len(), buffer_free(), buffer_init_string(), CONST_STR_LEN, and log_error_write().
Referenced by mod_authn_gssapi_check_spnego(), and mod_authn_gssapi_store_gss_creds().
static void mod_authn_gssapi_log_krb5_error (server * srv, const char * file, unsigned int line, const char * func, const char * extra, krb5_context context, int code) [static]
References log_error_write(), and UNUSED.
Referenced by mod_authn_gssapi_basic(), mod_authn_gssapi_create_krb5_ccache(), mod_authn_gssapi_store_gss_creds(), and mod_authn_gssapi_store_krb5_creds().
static int mod_authn_gssapi_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_authn_gssapi_basic(), and mod_authn_gssapi_check_spnego().
int mod_authn_gssapi_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static handler_t mod_authn_gssapi_send_400_bad_request (server * srv, connection * con) [static]
References DIRECT, HANDLER_FINISHED, connection::http_status, connection::mode, and UNUSED.
Referenced by mod_authn_gssapi_check(), and mod_authn_gssapi_check_spnego().
static handler_t mod_authn_gssapi_send_401_unauthorized_basic (server * srv, connection * con) [static]
References CONST_STR_LEN, DIRECT, HANDLER_FINISHED, connection::http_status, connection::mode, and response_header_insert().
Referenced by mod_authn_gssapi_basic().
static handler_t mod_authn_gssapi_send_401_unauthorized_negotiate (server * srv, connection * con) [static]
References CONST_STR_LEN, DIRECT, HANDLER_FINISHED, connection::http_status, connection::mode, and response_header_insert().
Referenced by mod_authn_gssapi_check(), and mod_authn_gssapi_check_spnego().
static int mod_authn_gssapi_store_gss_creds (server * srv, connection * con, plugin_data * p, char * princ_name, gss_cred_id_t delegated_cred) [static]
References mod_authn_gssapi_create_krb5_ccache(), mod_authn_gssapi_log_gss_error(), and mod_authn_gssapi_log_krb5_error().
Referenced by mod_authn_gssapi_check_spnego().
static int mod_authn_gssapi_store_krb5_creds (server * srv, connection * con, plugin_data * p, krb5_context kcontext, krb5_ccache delegated_cred) [static]
References mod_authn_gssapi_create_krb5_ccache(), and mod_authn_gssapi_log_krb5_error().
Referenced by mod_authn_gssapi_basic().
static krb5_error_code mod_authn_gssapi_verify_krb5_init_creds (server * srv, krb5_context context, krb5_creds * creds, krb5_principal ap_req_server, krb5_keytab ap_req_keytab) [static]
References log_error_write().
Referenced by mod_authn_gssapi_basic().
SETDEFAULTS_FUNC (mod_authn_gssapi_set_defaults)
References plugin_config::auth_gssapi_keytab, buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.