mod_cgi.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `stat_cache.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include `connections.h`
*
#include `joblist.h`
*
#include `response.h`
*
#include `http_chunk.h`
*
#include `plugin.h`
*
#include <sys/types.h>
*
#include `sys-mmap.h`
*
#include <sys/socket.h>
*
#include <sys/wait.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <fdevent.h>
*
#include <signal.h>
*
#include <ctype.h>
*
#include <assert.h>
*
#include <stdio.h>
*
#include <fcntl.h>
*
Classes
struct char_array
struct buffer_pid_t
struct plugin_config
struct plugin_data
struct handler_ctx
Macros
#define PATCH(x) p->conf.x = s->x;
Enumerations
enum { EOL_UNSET,
EOL_N,
EOL_RN
 }
enum {
*
FDEVENT_HANDLED_UNSET,
FDEVENT_HANDLED_FINISHED,
FDEVENT_HANDLED_NOT_FINISHED,
FDEVENT_HANDLED_COMEBACK,
*
FDEVENT_HANDLED_ERROR
 }
Functions
static int pipe_cloexec (int pipefd[2])
static handler_ctx * cgi_handler_ctx_init (void)
static void cgi_handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_cgi_init)
FREE_FUNC (mod_cgi_free)
SETDEFAULTS_FUNC (mod_fastcgi_set_defaults)
static int cgi_pid_add (server *srv, plugin_data *p, pid_t pid)
static int cgi_pid_del (server *srv, plugin_data *p, pid_t pid)
static int cgi_response_parse (server *srv, connection *con, plugin_data *p, buffer *in)
static int cgi_demux_response (server *srv, handler_ctx *hctx)
static void cgi_connection_close_fdtocgi (server *srv, handler_ctx *hctx)
static void cgi_connection_close (server *srv, handler_ctx *hctx)
static handler_t cgi_connection_close_callback (server *srv, connection *con, void *p_d)
static int cgi_write_request (server *srv, handler_ctx *hctx, int fd)
static handler_t cgi_handle_fdevent_send (server *srv, void *ctx, int revents)
static int cgi_recv_response (server *srv, handler_ctx *hctx)
static handler_t cgi_handle_fdevent (server *srv, void *ctx, int revents)
static int cgi_env_add (void *venv, const char *key, size_t key_len, const char *val, size_t val_len)
static off_t mmap_align_offset (off_t start)
static ssize_t cgi_write_file_chunk_mmap (server *srv, connection *con, int fd, chunkqueue *cq)
static int cgi_create_env (server *srv, connection *con, plugin_data *p, handler_ctx *hctx, buffer *cgi_handler)
static buffer * cgi_get_handler (array *a, buffer *fn)
static int mod_cgi_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (cgi_is_handled)
TRIGGER_FUNC (cgi_trigger)
SUBREQUEST_FUNC (mod_cgi_handle_subrequest)
int mod_cgi_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_cgi_patch_connection().
Enumeration Type Documentation
anonymous enum
Enumerator
EOL_UNSET
EOL_N
EOL_RN
anonymous enum
Enumerator
FDEVENT_HANDLED_UNSET
FDEVENT_HANDLED_FINISHED
FDEVENT_HANDLED_NOT_FINISHED
FDEVENT_HANDLED_COMEBACK
FDEVENT_HANDLED_ERROR
Function Documentation
static void cgi_connection_close (server * srv, handler_ctx * hctx) [static]
References cgi_connection_close_fdtocgi(), cgi_handler_ctx_free(), cgi_pid_add(), server::ev, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_del(), fdevent_sched_close(), fdevent_unregister(), handler_ctx::fdtocgi, http_response_backend_done(), log_error_write(), connection::mode, pid, handler_ctx::pid, connection::plugin_ctx, handler_ctx::plugin_data, and handler_ctx::remote_conn.
Referenced by cgi_connection_close_callback(), cgi_create_env(), cgi_handle_fdevent(), cgi_handle_fdevent_send(), cgi_recv_response(), and SUBREQUEST_FUNC().
static handler_t cgi_connection_close_callback (server * srv, connection * con, void * p_d) [static]
References cgi_connection_close(), HANDLER_GO_ON, and connection::plugin_ctx.
Referenced by mod_cgi_plugin_init().
static void cgi_connection_close_fdtocgi (server * srv, handler_ctx * hctx) [static]
References server::ev, handler_ctx::fde_ndx_tocgi, fdevent_event_del(), fdevent_sched_close(), fdevent_unregister(), and handler_ctx::fdtocgi.
Referenced by cgi_connection_close(), cgi_handle_fdevent_send(), and cgi_write_request().
static int cgi_create_env (server * srv, connection * con, plugin_data * p, handler_ctx * hctx, buffer * cgi_handler) [static]
References buffer_string_is_empty(), cgi_connection_close(), cgi_env_add(), cgi_handle_fdevent(), cgi_write_request(), CONST_STR_LEN, request::content_length, server::cur_fds, server::errorlog_fd, server::ev, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_set(), fdevent_fcntl_set_nb(), FDEVENT_IN, fdevent_register(), force_assert, http_cgi_headers(), log_error_write(), physical::path, connection::physical, pid, handler_ctx::pid, pipe_cloexec(), buffer::ptr, char_array::ptr, connection::request, char_array::size, UNUSED, and char_array::used.
Referenced by SUBREQUEST_FUNC().
static int cgi_demux_response (server * srv, handler_ctx * hctx) [static]
we have to handle a few cases:
nph:
HTTP/1.0 200 Ok
 Header: Value
 CGI: Header: Value
 Status: 200
 and different mixes of
 and
 combinations
Some users also forget about CGI and just send a response and hope we handle it. No headers, no header-content seperator
check if we saw a
()?
 sequence
i still points to the char after the terminating EOL EOL
put it on the last
 again
References array_get_element(), buffer_append_string_buffer(), buffer_commit(), buffer_copy_buffer(), buffer_string_length(), buffer_string_prepare_copy(), buffer_string_set_length(), chunkqueue::bytes_in, cgi_response_parse(), chunkqueue_length(), chunkqueue_reset(), handler_ctx::conf, connection::conf, connection_get_state(), connection_response_reset(), request::content_length, DIRECT, server::ev, handler_ctx::fd, connection::fd, handler_ctx::fde_ndx, fdevent_event_add(), fdevent_event_clr(), FDEVENT_HANDLED_COMEBACK, FDEVENT_HANDLED_ERROR, FDEVENT_HANDLED_FINISHED, FDEVENT_HANDLED_NOT_FINISHED, FDEVENT_IN, FDEVENT_STREAM_RESPONSE_BUFMIN, connection::file_started, response::headers, http_chunk_append_buffer(), http_chunk_append_mem(), request::http_method, HTTP_METHOD_GET, http_response_xsendfile(), connection::http_status, connection::is_writable, connection::keep_alive, log_error_write(), connection::loops_per_request, MAX_HTTP_REQUEST_HEADER, MAX_READ_LIMIT, connection::mode, request::orig_uri, request_uri::path, handler_ctx::plugin_data, buffer::ptr, handler_ctx::remote_conn, connection::request, connection::request_content_queue, handler_ctx::response, connection::response, handler_ctx::response_header, buffer::size, connection::state, specific_config::stream_response_body, request::uri, connection::uri, data_string::value, connection::write_queue, plugin_config::xsendfile_allow, and plugin_config::xsendfile_docroot.
Referenced by cgi_recv_response().
static int cgi_env_add (void * venv, const char * key, size_t key_len, const char * val, size_t val_len) [static]
References force_assert, char_array::ptr, char_array::size, and char_array::used.
Referenced by cgi_create_env().
static buffer* cgi_get_handler (array * a, buffer * fn) [static]
References buffer_is_empty(), buffer_string_length(), array::data, buffer::ptr, array::used, and data_string::value.
Referenced by URIHANDLER_FUNC().
static handler_t cgi_handle_fdevent (server * srv, void * ctx, int revents) [static]
References buffer_string_is_empty(), cgi_connection_close(), cgi_recv_response(), handler_ctx::fd, connection::fd, FDEVENT_ERR, FDEVENT_HUP, FDEVENT_IN, connection::file_started, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, http_chunk_append_buffer(), joblist_append(), log_error_write(), handler_ctx::remote_conn, and handler_ctx::response_header.
Referenced by cgi_create_env().
static handler_t cgi_handle_fdevent_send (server * srv, void * ctx, int revents) [static]
References chunkqueue::bytes_in, cgi_connection_close(), cgi_connection_close_fdtocgi(), cgi_write_request(), chunkqueue_length(), chunkqueue_mark_written(), request::content_length, FDEVENT_ERR, FDEVENT_HUP, FDEVENT_OUT, handler_ctx::fdtocgi, HANDLER_ERROR, HANDLER_FINISHED, joblist_append(), connection::keep_alive, log_error_write(), handler_ctx::remote_conn, connection::request, and connection::request_content_queue.
Referenced by cgi_write_request().
static void cgi_handler_ctx_free (handler_ctx * hctx) [static]
References buffer_free(), handler_ctx::response, and handler_ctx::response_header.
Referenced by cgi_connection_close().
static handler_ctx* cgi_handler_ctx_init (void) [static]
References buffer_init(), handler_ctx::fd, handler_ctx::fdtocgi, force_assert, handler_ctx::response, and handler_ctx::response_header.
Referenced by URIHANDLER_FUNC().
static int cgi_pid_add (server * srv, plugin_data * p, pid_t pid) [static]
References plugin_data::cgi_pid, force_assert, pid, buffer_pid_t::ptr, buffer_pid_t::size, UNUSED, and buffer_pid_t::used.
Referenced by cgi_connection_close().
static int cgi_pid_del (server * srv, plugin_data * p, pid_t pid) [static]
References plugin_data::cgi_pid, buffer_pid_t::ptr, UNUSED, and buffer_pid_t::used.
Referenced by TRIGGER_FUNC().
static int cgi_recv_response (server * srv, handler_ctx * hctx) [static]
References cgi_connection_close(), cgi_demux_response(), connection_get_state(), handler_ctx::fd, FDEVENT_HANDLED_COMEBACK, FDEVENT_HANDLED_ERROR, FDEVENT_HANDLED_FINISHED, FDEVENT_HANDLED_NOT_FINISHED, HANDLER_COMEBACK, HANDLER_FINISHED, HANDLER_GO_ON, and log_error_write().
Referenced by cgi_handle_fdevent(), and SUBREQUEST_FUNC().
static int cgi_response_parse (server * srv, connection * con, plugin_data * p, buffer * in) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), response::content_length, data_response_init(), response::headers, HTTP_CONNECTION, HTTP_CONTENT_LENGTH, HTTP_DATE, HTTP_LOCATION, HTTP_STATUS, connection::http_status, response::keep_alive, plugin_data::parse_response, connection::parsed_response, buffer::ptr, connection::response, TYPE_STRING, UNUSED, and data_string::value.
Referenced by cgi_demux_response().
static ssize_t cgi_write_file_chunk_mmap (server * srv, connection * con, int fd, chunkqueue * cq) [static]
References chunkqueue_mark_written(), chunkqueue_remove_finished_chunks(), chunk::fd, fdevent_open_cloexec(), chunk::file, chunkqueue::first, force_assert, chunk::length, log_error_write(), MAP_FAILED, mmap, chunk::mmap, mmap_align_offset(), munmap, chunk::name, chunk::offset, PROT_READ, buffer::ptr, chunk::start, chunk::type, and UNUSED.
Referenced by cgi_write_request().
static int cgi_write_request (server * srv, handler_ctx * hctx, int fd) [static]
References buffer_string_length(), chunkqueue::bytes_in, chunkqueue::bytes_out, cgi_connection_close_fdtocgi(), cgi_handle_fdevent_send(), cgi_write_file_chunk_mmap(), chunkqueue_length(), chunkqueue_mark_written(), connection::conf, request::content_length, server::cur_fds, server::ev, handler_ctx::fde_ndx_tocgi, fdevent_event_get_interest, fdevent_event_set(), FDEVENT_OUT, fdevent_register(), FDEVENT_STREAM_REQUEST_POLLIN, handler_ctx::fdtocgi, chunkqueue::first, connection::is_readable, log_error_write(), chunk::mem, chunk::offset, buffer::ptr, handler_ctx::remote_conn, connection::request, connection::request_content_queue, specific_config::stream_request_body, and chunk::type.
Referenced by cgi_create_env(), cgi_handle_fdevent_send(), and SUBREQUEST_FUNC().
FREE_FUNC (mod_cgi_free)
References array_free(), buffer_free(), plugin_config::cgi, plugin_data::cgi_pid, plugin_data::config_storage, HANDLER_GO_ON, plugin_data::parse_response, buffer_pid_t::ptr, UNUSED, and plugin_config::xsendfile_docroot.
INIT_FUNC (mod_cgi_init)
References buffer_init(), force_assert, and plugin_data::parse_response.
static off_t mmap_align_offset (off_t start) [static]
Referenced by cgi_write_file_chunk_mmap().
static int mod_cgi_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_cgi_plugin_init (plugin * p)
References buffer_init_string(), cgi_connection_close_callback(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_subrequest, plugin::handle_subrequest_start, plugin::handle_trigger, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static int pipe_cloexec (int pipefd[2]) [static]
Referenced by cgi_create_env().
SETDEFAULTS_FUNC (mod_fastcgi_set_defaults)
References array_init(), buffer_append_slash(), buffer_path_simplify(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, force_assert, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), buffer::ptr, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, TYPE_STRING, data_string::value, and data_config::value.
SUBREQUEST_FUNC (mod_cgi_handle_subrequest)
References chunkqueue::bytes_in, chunkqueue::bytes_out, cgi_connection_close(), cgi_create_env(), handler_ctx::cgi_handler, cgi_recv_response(), cgi_write_request(), chunkqueue_is_empty(), chunkqueue_length(), connection_handle_read_post_error(), connection_handle_read_post_state(), DIRECT, handler_ctx::fd, handler_ctx::fde_ndx, fdevent_event_clr(), fdevent_event_get_interest, FDEVENT_IN, FDEVENT_OUT, FDEVENT_STREAM_REQUEST_BUFMIN, FDEVENT_STREAM_REQUEST_POLLIN, FDEVENT_STREAM_RESPONSE_BUFMIN, handler_ctx::fdtocgi, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, log_error_write(), and handler_ctx::pid.
TRIGGER_FUNC (cgi_trigger)
References plugin_data::cgi_pid, cgi_pid_del(), HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), buffer_pid_t::ptr, and buffer_pid_t::used.
URIHANDLER_FUNC (cgi_is_handled)
References buffer_is_empty(), plugin_config::cgi, cgi_get_handler(), handler_ctx::cgi_handler, cgi_handler_ctx_init(), plugin_data::conf, handler_ctx::conf, DIRECT, plugin_config::execute_x_only, HANDLER_ERROR, HANDLER_GO_ON, mod_cgi_patch_connection(), handler_ctx::plugin_data, handler_ctx::remote_conn, stat_cache_entry::st, and stat_cache_get_entry().