mod_status.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `connections.h`
*
#include `response.h`
*
#include `log.h`
*
#include `plugin.h`
*
#include `inet_ntop_cache.h`
*
#include <sys/types.h>
*
#include <fcntl.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <time.h>
*
#include <stdio.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_status_init)
FREE_FUNC (mod_status_free)
SETDEFAULTS_FUNC (mod_status_set_defaults)
static int mod_status_row_append (buffer *b, const char *key, const char *value)
static int mod_status_header_append (buffer *b, const char *key)
static int mod_status_header_append_sort (buffer *b, void *p_d, const char *key)
static int mod_status_get_multiplier (double *avg, char *multiplier, int size)
static handler_t mod_status_handle_server_status_html (server *srv, connection *con, void *p_d)
static handler_t mod_status_handle_server_status_text (server *srv, connection *con, void *p_d)
static handler_t mod_status_handle_server_status_json (server *srv, connection *con, void *p_d)
static handler_t mod_status_handle_server_statistics (server *srv, connection *con, void *p_d)
static handler_t mod_status_handle_server_status (server *srv, connection *con, void *p_d)
static handler_t mod_status_handle_server_config (server *srv, connection *con, void *p_d)
static int mod_status_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t mod_status_handler (server *srv, connection *con, void *p_d)
TRIGGER_FUNC (mod_status_trigger)
REQUESTDONE_FUNC (mod_status_account)
int mod_status_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_status_patch_connection().
Function Documentation
FREE_FUNC (mod_status_free)
References buffer_free(), plugin_data::config_storage, plugin_config::config_url, HANDLER_GO_ON, plugin_data::module_list, plugin_config::statistics_url, plugin_config::status_url, and UNUSED.
INIT_FUNC (mod_status_init)
References plugin_data::abs_requests, plugin_data::abs_traffic_out, buffer_init(), plugin_data::bytes_written, plugin_data::mod_5s_requests, plugin_data::mod_5s_traffic_out, plugin_data::module_list, plugin_data::rel_requests, plugin_data::rel_traffic_out, plugin_data::requests, and plugin_data::traffic_out.
static int mod_status_get_multiplier (double * avg, char * multiplier, int size) [static]
Referenced by mod_status_handle_server_status_html().
static handler_t mod_status_handle_server_config (server * srv, connection * con, void * p_d) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_free(), buffer_init(), chunkqueue_append_buffer(), connection::conf, CONST_STR_LEN, server::event_handler, FDEVENT_HANDLER_FREEBSD_KQUEUE, FDEVENT_HANDLER_LIBEV, FDEVENT_HANDLER_LINUX_SYSEPOLL, FDEVENT_HANDLER_POLL, FDEVENT_HANDLER_SELECT, FDEVENT_HANDLER_SOLARIS_DEVPOLL, FDEVENT_HANDLER_SOLARIS_PORT, FDEVENT_HANDLER_UNSET, connection::file_finished, HANDLER_FINISHED, connection::http_status, mod_status_header_append(), mod_status_row_append(), plugin_data::module_list, plugin::name, server::plugins, ps, buffer::ptr, buffer_plugin::ptr, response_header_overwrite(), specific_config::server_tag, buffer_plugin::used, and connection::write_queue.
Referenced by mod_status_handler().
static handler_t mod_status_handle_server_statistics (server * srv, connection * con, void * p_d) [static]
References buffer_append_int(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_free(), buffer_init(), chunkqueue_append_buffer(), CONST_STR_LEN, array::data, connection::file_finished, HANDLER_FINISHED, connection::http_status, response_header_overwrite(), array::sorted, server::status, UNUSED, array::used, and connection::write_queue.
Referenced by mod_status_handler().
static handler_t mod_status_handle_server_status (server * srv, connection * con, void * p_d) [static]
References buffer_is_equal_string(), buffer_string_length(), CONST_STR_LEN, connection::file_finished, HANDLER_FINISHED, connection::http_status, mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), buffer::ptr, request_uri::query, and connection::uri.
Referenced by mod_status_handler().
static handler_t mod_status_handle_server_status_html (server * srv, connection * con, void * p_d) [static]
References plugin_data::abs_requests, plugin_data::abs_traffic_out, request_uri::authority, buffer_append_int(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_string_is_empty(), chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_append_buffer(), chunkqueue_length(), CON_STATE_CLOSE, CON_STATE_READ, plugin_data::conf, connection::conf, connection_get_short_state(), connection_get_state(), server::conns, CONST_BUF_LEN, CONST_STR_LEN, request::content_length, server::cur_ts, connection::dst_addr, ENCODING_HTML, inet_ntop_cache_get_ip(), plugin_data::mod_5s_requests, plugin_data::mod_5s_traffic_out, mod_status_get_multiplier(), mod_status_header_append_sort(), request::orig_uri, request_uri::path, physical::path, connection::physical, buffer::ptr, connections::ptr, request_uri::query, connection::request, connection::request_content_queue, connection::request_start, response_header_overwrite(), connection::server_name, specific_config::server_tag, plugin_config::sort, server::startup_ts, connection::state, connection::uri, connections::used, and connection::write_queue.
Referenced by mod_status_handle_server_status().
static handler_t mod_status_handle_server_status_json (server * srv, connection * con, void * p_d) [static]
References plugin_data::abs_requests, plugin_data::abs_traffic_out, buffer_append_int(), buffer_append_string(), buffer_append_string_len(), buffer_free(), buffer_init(), buffer_string_length(), chunkqueue_append_buffer(), server::conns, CONST_STR_LEN, server::cur_ts, light_isalnum(), light_isalpha(), plugin_data::mod_5s_requests, plugin_data::mod_5s_traffic_out, buffer::ptr, request_uri::query, response_header_overwrite(), connections::size, server::startup_ts, connection::uri, connections::used, and connection::write_queue.
Referenced by mod_status_handle_server_status().
static handler_t mod_status_handle_server_status_text (server * srv, connection * con, void * p_d) [static]
References plugin_data::abs_requests, plugin_data::abs_traffic_out, buffer_append_int(), buffer_append_string(), buffer_append_string_len(), buffer_free(), buffer_init(), buffer_string_is_empty(), chunkqueue_append_buffer(), CON_STATE_READ, connection_get_short_state(), server::conns, CONST_STR_LEN, server::cur_ts, request::orig_uri, connections::ptr, connection::request, response_header_overwrite(), connections::size, server::startup_ts, connection::state, connections::used, and connection::write_queue.
Referenced by mod_status_handle_server_status().
static handler_t mod_status_handler (server * srv, connection * con, void * p_d) [static]
References buffer_is_equal(), buffer_string_is_empty(), plugin_data::conf, plugin_config::config_url, DIRECT, HANDLER_GO_ON, mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status(), mod_status_patch_connection(), connection::mode, request_uri::path, plugin_config::statistics_url, plugin_config::status_url, and connection::uri.
Referenced by mod_status_plugin_init().
static int mod_status_header_append (buffer * b, const char * key) [static]
References buffer_append_string(), buffer_append_string_len(), and CONST_STR_LEN.
Referenced by mod_status_handle_server_config().
static int mod_status_header_append_sort (buffer * b, void * p_d, const char * key) [static]
References buffer_append_string(), buffer_append_string_len(), plugin_data::conf, CONST_STR_LEN, and plugin_config::sort.
Referenced by mod_status_handle_server_status_html().
static int mod_status_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_status_handler().
int mod_status_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_request_done, plugin::handle_trigger, plugin::handle_uri_clean, plugin::init, mod_status_handler(), plugin::name, plugin::set_defaults, and plugin::version.
static int mod_status_row_append (buffer * b, const char * key, const char * value) [static]
References buffer_append_string(), buffer_append_string_len(), and CONST_STR_LEN.
Referenced by mod_status_handle_server_config().
REQUESTDONE_FUNC (mod_status_account)
References plugin_data::abs_requests, plugin_data::bytes_written, HANDLER_GO_ON, plugin_data::rel_requests, plugin_data::requests, and UNUSED.
SETDEFAULTS_FUNC (mod_status_set_defaults)
References buffer_init(), config_insert_values_global(), plugin_data::config_storage, plugin_config::config_url, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
TRIGGER_FUNC (mod_status_trigger)
References plugin_data::abs_traffic_out, plugin_data::bytes_written, connection::bytes_written_cur_second, HANDLER_GO_ON, plugin_data::mod_5s_ndx, plugin_data::mod_5s_requests, plugin_data::mod_5s_traffic_out, plugin_data::rel_traffic_out, plugin_data::requests, and plugin_data::traffic_out.