mod_rrdtool.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `connections.h`
*
#include `response.h`
*
#include `log.h`
*
#include `plugin.h`
*
#include <sys/types.h>
*
#include <assert.h>
*
#include <fcntl.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <time.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_rrd_init)
FREE_FUNC (mod_rrd_free)
static int mod_rrd_create_pipe (server *srv, plugin_data *p)
static ssize_t safe_write (int fd, const void *buf, size_t count)
static ssize_t safe_read (int fd, void *buf, size_t count)
static int mod_rrdtool_create_rrd (server *srv, plugin_data *p, plugin_config *s)
static int mod_rrd_patch_connection (server *srv, connection *con, plugin_data *p)
SETDEFAULTS_FUNC (mod_rrd_set_defaults)
TRIGGER_FUNC (mod_rrd_trigger)
REQUESTDONE_FUNC (mod_rrd_account)
int mod_rrdtool_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_rrd_patch_connection().
Function Documentation
FREE_FUNC (mod_rrd_free)
References buffer_free(), plugin_data::cmd, plugin_data::config_storage, HANDLER_GO_ON, plugin_config::path_rrd, plugin_config::path_rrdtool_bin, plugin_data::read_fd, plugin_data::resp, plugin_data::rrdtool_pid, and plugin_data::write_fd.
INIT_FUNC (mod_rrd_init)
References buffer_init(), plugin_data::cmd, and plugin_data::resp.
static int mod_rrd_create_pipe (server * srv, plugin_data * p) [static]
References plugin_data::conf, fd_close_on_exec(), log_error_write(), plugin_config::path_rrdtool_bin, pid, buffer::ptr, plugin_data::read_fd, plugin_data::rrdtool_pid, SEGFAULT, and plugin_data::write_fd.
Referenced by SETDEFAULTS_FUNC().
static int mod_rrd_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), plugin_config::bytes_read, plugin_config::bytes_read_ptr, plugin_config::bytes_written, plugin_config::bytes_written_ptr, plugin_data::conf, config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, plugin_config::requests, plugin_config::requests_ptr, array::used, and data_config::value.
Referenced by REQUESTDONE_FUNC().
static int mod_rrdtool_create_rrd (server * srv, plugin_data * p, plugin_config * s) [static]
References buffer_append_string_buffer(), buffer_append_string_len(), buffer_commit(), buffer_copy_string_len(), buffer_string_prepare_copy(), plugin_data::cmd, CONST_BUF_LEN, CONST_STR_LEN, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), plugin_config::path_rrd, buffer::ptr, plugin_data::read_fd, plugin_data::resp, safe_read(), safe_write(), buffer::size, and plugin_data::write_fd.
Referenced by TRIGGER_FUNC().
int mod_rrdtool_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_request_done, plugin::handle_trigger, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
REQUESTDONE_FUNC (mod_rrd_account)
References plugin_config::bytes_read_ptr, plugin_config::bytes_written_ptr, plugin_data::conf, HANDLER_GO_ON, mod_rrd_patch_connection(), and plugin_config::requests_ptr.
static ssize_t safe_read (int fd, void * buf, size_t count) [static]
Referenced by mod_rrdtool_create_rrd(), and TRIGGER_FUNC().
static ssize_t safe_write (int fd, const void * buf, size_t count) [static]
Referenced by mod_rrdtool_create_rrd(), and TRIGGER_FUNC().
SETDEFAULTS_FUNC (mod_rrd_set_defaults)
References buffer_init(), buffer_string_is_empty(), plugin_data::conf, config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, force_assert, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), mod_rrd_create_pipe(), plugin_config::path_rrdtool_bin, plugin_data::rrdtool_running, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
TRIGGER_FUNC (mod_rrd_trigger)
References buffer_append_int(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_commit(), buffer_copy_string_len(), buffer_string_is_empty(), buffer_string_prepare_copy(), plugin_config::bytes_read, plugin_config::bytes_written, plugin_data::cmd, plugin_data::config_storage, CONST_BUF_LEN, CONST_STR_LEN, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), mod_rrdtool_create_rrd(), plugin_config::path_rrd, buffer::ptr, plugin_data::read_fd, plugin_config::requests, plugin_data::resp, plugin_data::rrdtool_running, safe_read(), safe_write(), buffer::size, and plugin_data::write_fd.