mod_cml.h File Reference
#include `first.h`
*
#include `buffer.h`
*
#include `server.h`
*
#include `response.h`
*
#include `plugin.h`
*
Classes
struct plugin_config
struct plugin_data
Macros
#define plugin_data mod_cache_plugin_data
Functions
int cache_parse_lua (server *srv, connection *con, plugin_data *p, buffer *fn)
Macro Definition Documentation
#define plugin_data mod_cache_plugin_data
Function Documentation
int cache_parse_lua (server * srv, connection * con, plugin_data * p, buffer * fn)
References array_get_element(), plugin_data::basedir, physical::basedir, plugin_data::baseurl, buffer_append_string(), buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string(), buffer_free(), buffer_init(), buffer_reset(), buffer_string_is_empty(), c_to_lua_push(), cache_export_get_params(), chunkqueue_append_file_fd(), chunkqueue_reset(), plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, f_crypto_md5(), f_dir_files(), f_file_isreg(), f_file_mtime(), f_memcache_exists(), f_memcache_get_long(), f_memcache_get_string(), connection::file_finished, force_assert, HANDLER_FINISHED, response::headers, http_response_handle_cachable(), log_error_write(), lua_to_c_get_string(), lua_to_c_is_table(), request::orig_uri, request_uri::path, physical::path, request::pathinfo, connection::physical, buffer::ptr, request_uri::query, connection::request, connection::response, response_header_overwrite(), stat_cache_open_rdonly_fstat(), plugin_data::trigger_handler, connection::uri, data_string::value, and connection::write_queue.
Referenced by cache_call_lua().