mod_expire.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `response.h`
*
#include `plugin.h`
*
#include `stat_cache.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <time.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_expire_init)
FREE_FUNC (mod_expire_free)
static int mod_expire_get_offset (server *srv, plugin_data *p, buffer *expire, time_t *offset)
SETDEFAULTS_FUNC (mod_expire_set_defaults)
static int mod_expire_patch_connection (server *srv, connection *con, plugin_data *p)
CONNECTION_FUNC (mod_expire_handler)
int mod_expire_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_expire_patch_connection().
Function Documentation
CONNECTION_FUNC (mod_expire_handler)
References array_get_element(), buffer_append_int(), buffer_append_strftime(), buffer_copy_string_len(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_copy(), plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, array::data, plugin_config::expire_mimetypes, plugin_data::expire_tstmp, plugin_config::expire_url, HANDLER_ERROR, HANDLER_GO_ON, HTTP_METHOD_GET, HTTP_METHOD_HEAD, mod_expire_get_offset(), mod_expire_patch_connection(), buffer::ptr, response_header_append(), response_header_overwrite(), stat_cache_entry::st, stat_cache_get_entry(), array::used, and data_string::value.
FREE_FUNC (mod_expire_free)
References array_free(), buffer_free(), plugin_data::config_storage, plugin_config::expire_mimetypes, plugin_data::expire_tstmp, plugin_config::expire_url, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_expire_init)
References buffer_init(), buffer_string_prepare_copy(), and plugin_data::expire_tstmp.
static int mod_expire_get_offset (server * srv, plugin_data * p, buffer * expire, time_t * offset) [static]
References buffer_string_is_empty(), log_error_write(), buffer::ptr, and UNUSED.
Referenced by CONNECTION_FUNC(), and SETDEFAULTS_FUNC().
static int mod_expire_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by CONNECTION_FUNC().
int mod_expire_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_response_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_expire_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, plugin_config::expire_url, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), mod_expire_get_offset(), T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, data_string::value, and data_config::value.