mod_evhost.c File Reference
#include `first.h`
*
#include `plugin.h`
*
#include `log.h`
*
#include `response.h`
*
#include `stat_cache.h`
*
#include <string.h>
*
#include <errno.h>
*
#include <ctype.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_evhost_init)
FREE_FUNC (mod_evhost_free)
static int mod_evhost_parse_pattern (plugin_config *s)
SETDEFAULTS_FUNC (mod_evhost_set_defaults)
static int mod_evhost_parse_host (connection *con, array *host)
static int mod_evhost_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t mod_evhost_uri_handler (server *srv, connection *con, void *p_d)
int mod_evhost_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_evhost_patch_connection().
Function Documentation
FREE_FUNC (mod_evhost_free)
References buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_config::len, plugin_config::path_pieces, plugin_config::path_pieces_raw, plugin_data::tmp_buf, and UNUSED.
INIT_FUNC (mod_evhost_init)
References buffer_init(), and plugin_data::tmp_buf.
static int mod_evhost_parse_host (connection * con, array * host) [static]
assign the different parts of the domain to array-indezes (sub2.sub1.domain.tld)
%0 - domain.tld
%1 - tld
%2 - domain
%3 - sub1
...
References array_insert_unique(), request_uri::authority, buffer_append_int(), buffer_copy_string_len(), buffer_string_length(), CONST_STR_LEN, data_string_init(), buffer::ptr, connection::uri, and data_string::value.
Referenced by mod_evhost_uri_handler().
static int mod_evhost_parse_pattern (plugin_config * s) [static]
References buffer_copy_string_len(), buffer_init(), plugin_config::len, light_isdigit(), plugin_config::path_pieces, plugin_config::path_pieces_raw, and buffer::ptr.
Referenced by SETDEFAULTS_FUNC().
static int mod_evhost_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_evhost_uri_handler().
int mod_evhost_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_docroot, plugin::init, mod_evhost_uri_handler(), plugin::name, plugin::set_defaults, and plugin::version.
static handler_t mod_evhost_uri_handler (server * srv, connection * con, void * p_d) [static]
References array_free(), array_get_element(), array_init(), request_uri::authority, buffer_append_slash(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), plugin_data::conf, CONST_STR_LEN, physical::doc_root, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::len, log_error_write(), mod_evhost_parse_host(), mod_evhost_patch_connection(), plugin_config::path_pieces, connection::physical, buffer::ptr, stat_cache_entry::st, stat_cache_get_entry(), plugin_data::tmp_buf, connection::uri, and data_string::value.
Referenced by mod_evhost_plugin_init().
SETDEFAULTS_FUNC (mod_evhost_set_defaults)
#
define a pattern for the host url finding
%% => % sign
%0 => domain name + tld
%1 => tld
%2 => domain name without tld
%3 => subdomain 1 name
%4 => subdomain 2 name
_ => fqdn (without port info)
# evhost.path-pattern = `/home/ckruse/dev/www/%3/htdocs/`
References buffer_init(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), mod_evhost_parse_pattern(), plugin_config::path_pieces_raw, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.