mod_staticfile.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `stat_cache.h`
*
#include `etag.h`
*
#include `http_chunk.h`
*
#include `response.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_staticfile_init)
FREE_FUNC (mod_staticfile_free)
SETDEFAULTS_FUNC (mod_staticfile_set_defaults)
static int mod_staticfile_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_staticfile_subrequest)
int mod_staticfile_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_staticfile_patch_connection().
Function Documentation
FREE_FUNC (mod_staticfile_free)
References array_free(), plugin_data::config_storage, plugin_config::exclude_ext, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_staticfile_init)
static int mod_staticfile_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_staticfile_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_subrequest_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_staticfile_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, plugin_config::exclude_ext, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_staticfile_subrequest)
References buffer_is_empty(), buffer_is_equal_right_len(), buffer_string_is_empty(), buffer_string_length(), plugin_data::conf, array::data, DIRECT, plugin_config::disable_pathinfo, plugin_config::etags_used, plugin_config::exclude_ext, HANDLER_FINISHED, HANDLER_GO_ON, HTTP_METHOD_GET, HTTP_METHOD_HEAD, HTTP_METHOD_POST, http_response_send_file(), log_error_write(), mod_staticfile_patch_connection(), array::used, and data_string::value.