mod_authn_ldap.c File Reference
#include `first.h`
*
#include <ldap.h>
*
#include `server.h`
*
#include `http_auth.h`
*
#include `log.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <errno.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define USE_LDAP
#define PATCH(x) p->conf.x = s->x;
Functions
static handler_t mod_authn_ldap_basic (server *srv, connection *con, void *p_d, const http_auth_require_t *require, const buffer *username, const char *pw)
INIT_FUNC (mod_authn_ldap_init)
FREE_FUNC (mod_authn_ldap_free)
SETDEFAULTS_FUNC (mod_authn_ldap_set_defaults)
static int mod_authn_ldap_patch_connection (server *srv, connection *con, plugin_data *p)
static void mod_authn_ldap_err (server *srv, const char *file, unsigned long line, const char *fn, int err)
static void mod_authn_ldap_opt_err (server *srv, const char *file, unsigned long line, const char *fn, LDAP *ld)
static LDAP * mod_authn_ldap_host_init (server *srv, plugin_config *s)
static int mod_authn_ldap_bind (server *srv, LDAP *ld, const char *dn, const char *pw)
static LDAPMessage * mod_authn_ldap_search (server *srv, plugin_config *s, char *base, char *filter)
static char * mod_authn_ldap_get_dn (server *srv, plugin_config *s, char *base, char *filter)
int mod_authn_ldap_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_authn_ldap_patch_connection().
#define USE_LDAP
Function Documentation
FREE_FUNC (mod_authn_ldap_free)
References plugin_config::auth_ldap_basedn, plugin_config::auth_ldap_binddn, plugin_config::auth_ldap_bindpw, plugin_config::auth_ldap_cafile, plugin_config::auth_ldap_filter, plugin_config::auth_ldap_hostname, buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_config::ldap, plugin_data::ldap_filter, and UNUSED.
INIT_FUNC (mod_authn_ldap_init)
References buffer_init(), http_auth_backend_set(), plugin_data::ldap_filter, mod_authn_ldap_basic(), and http_auth_backend_t::p_d.
static handler_t mod_authn_ldap_basic (server * srv, connection * con, void * p_d, const http_auth_require_t * require, const buffer * username, const char * pw) [static]
References plugin_data::anon_conf, plugin_config::auth_ldap_allow_empty_pw, plugin_config::auth_ldap_basedn, plugin_config::auth_ldap_filter, buffer_append_string_buffer(), buffer_append_string_len(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), plugin_data::conf, CONST_STR_LEN, DIRECT, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, http_auth_match_rules(), connection::http_status, plugin_data::ldap_filter, log_error_write(), mod_authn_ldap_bind(), mod_authn_ldap_get_dn(), mod_authn_ldap_host_init(), mod_authn_ldap_patch_connection(), connection::mode, and buffer::ptr.
Referenced by INIT_FUNC().
static int mod_authn_ldap_bind (server * srv, LDAP * ld, const char * dn, const char * pw) [static]
References mod_authn_ldap_err().
Referenced by mod_authn_ldap_basic(), and mod_authn_ldap_search().
static void mod_authn_ldap_err (server * srv, const char * file, unsigned long line, const char * fn, int err) [static]
References log_error_write().
Referenced by mod_authn_ldap_bind(), mod_authn_ldap_host_init(), and mod_authn_ldap_opt_err().
static char* mod_authn_ldap_get_dn (server * srv, plugin_config * s, char * base, char * filter) [static]
References plugin_config::ldap, log_error_write(), mod_authn_ldap_opt_err(), and mod_authn_ldap_search().
Referenced by mod_authn_ldap_basic().
static LDAP* mod_authn_ldap_host_init (server * srv, plugin_config * s) [static]
References plugin_config::auth_ldap_cafile, plugin_config::auth_ldap_hostname, plugin_config::auth_ldap_starttls, buffer_string_is_empty(), log_error_write(), mod_authn_ldap_err(), and buffer::ptr.
Referenced by mod_authn_ldap_basic(), and mod_authn_ldap_search().
static void mod_authn_ldap_opt_err (server * srv, const char * file, unsigned long line, const char * fn, LDAP * ld) [static]
References mod_authn_ldap_err().
Referenced by mod_authn_ldap_get_dn().
static int mod_authn_ldap_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References plugin_data::anon_conf, buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_authn_ldap_basic().
int mod_authn_ldap_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
static LDAPMessage* mod_authn_ldap_search (server * srv, plugin_config * s, char * base, char * filter) [static]
References plugin_config::auth_ldap_binddn, plugin_config::auth_ldap_bindpw, buffer_string_is_empty(), plugin_config::ldap, log_error_write(), mod_authn_ldap_bind(), mod_authn_ldap_host_init(), and buffer::ptr.
Referenced by mod_authn_ldap_get_dn().
SETDEFAULTS_FUNC (mod_authn_ldap_set_defaults)
References plugin_config::auth_ldap_hostname, buffer_init(), buffer_string_is_empty(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.