mod_skeleton.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
struct handler_ctx
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
static handler_ctx * handler_ctx_init ()
static void handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_skeleton_init)
FREE_FUNC (mod_skeleton_free)
SETDEFAULTS_FUNC (mod_skeleton_set_defaults)
static int mod_skeleton_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_skeleton_uri_handler)
int mod_skeleton_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_skeleton_patch_connection().
Function Documentation
FREE_FUNC (mod_skeleton_free)
References array_free(), buffer_free(), plugin_data::config_storage, HANDLER_GO_ON, plugin_config::match, plugin_data::match_buf, and UNUSED.
static void handler_ctx_free (handler_ctx * hctx) [static]
static handler_ctx* handler_ctx_init (void) [static]
INIT_FUNC (mod_skeleton_init)
References buffer_init(), and plugin_data::match_buf.
static int mod_skeleton_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_skeleton_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_skeleton_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::match, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_skeleton_uri_handler)
References buffer_string_length(), plugin_data::conf, array::data, DIRECT, HANDLER_FINISHED, HANDLER_GO_ON, plugin_config::match, mod_skeleton_patch_connection(), buffer::ptr, UNUSED, array::used, and data_string::value.