mod_userdir.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `response.h`
*
#include `plugin.h`
*
#include <sys/types.h>
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_userdir_init)
FREE_FUNC (mod_userdir_free)
SETDEFAULTS_FUNC (mod_userdir_set_defaults)
static int mod_userdir_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_userdir_docroot_handler)
int mod_userdir_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_userdir_patch_connection().
Function Documentation
FREE_FUNC (mod_userdir_free)
References array_free(), plugin_config::basepath, buffer_free(), plugin_data::config_storage, plugin_config::exclude_user, HANDLER_GO_ON, plugin_config::include_user, plugin_config::path, plugin_data::temp_path, and plugin_data::username.
INIT_FUNC (mod_userdir_init)
References buffer_init(), plugin_data::temp_path, and plugin_data::username.
static int mod_userdir_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_userdir_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_physical, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_userdir_set_defaults)
References array_init(), buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, plugin_config::exclude_user, HANDLER_ERROR, HANDLER_GO_ON, T_CONFIG_ARRAY, T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_userdir_docroot_handler)
References plugin_config::active, plugin_config::basepath, buffer_append_slash(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), buffer_is_empty(), buffer_is_equal(), buffer_reset(), buffer_string_is_empty(), buffer_to_lower(), plugin_data::conf, array::data, plugin_config::exclude_user, HANDLER_FINISHED, HANDLER_GO_ON, http_response_redirect_to_directory(), plugin_config::include_user, plugin_config::letterhomes, mod_userdir_patch_connection(), plugin_config::path, buffer::ptr, plugin_data::temp_path, array::used, plugin_data::username, and data_string::value.