mod_dirlisting.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include `stat_cache.h`
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <dirent.h>
*
#include <assert.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <stdio.h>
*
#include <unistd.h>
*
#include <time.h>
*
Classes
struct excludes
struct excludes_buffer
struct plugin_config
struct plugin_data
struct dirls_entry_t
struct dirls_list_t
Macros
#define CONFIG_EXCLUDE `dir-listing.exclude`
#define CONFIG_ACTIVATE `dir-listing.activate`
#define CONFIG_HIDE_DOTFILES `dir-listing.hide-dotfiles`
#define CONFIG_EXTERNAL_CSS `dir-listing.external-css`
#define CONFIG_EXTERNAL_JS `dir-listing.external-js`
#define CONFIG_ENCODING `dir-listing.encoding`
#define CONFIG_SHOW_README `dir-listing.show-readme`
#define CONFIG_HIDE_README_FILE `dir-listing.hide-readme-file`
#define CONFIG_SHOW_HEADER `dir-listing.show-header`
#define CONFIG_HIDE_HEADER_FILE `dir-listing.hide-header-file`
#define CONFIG_DIR_LISTING `server.dir-listing`
#define CONFIG_SET_FOOTER `dir-listing.set-footer`
#define CONFIG_ENCODE_README `dir-listing.encode-readme`
#define CONFIG_ENCODE_HEADER `dir-listing.encode-header`
#define CONFIG_AUTO_LAYOUT `dir-listing.auto-layout`
#define PATCH(x) p->conf.x = s->x;
#define DIRLIST_ENT_NAME(ent) ((char*)(ent) + sizeof(dirls_entry_t))
#define DIRLIST_BLOB_SIZE 16
#define FIFO_NONBLOCK 0
Functions
static excludes_buffer * excludes_buffer_init (void)
static int excludes_buffer_append (excludes_buffer *exb, buffer *string)
static void excludes_buffer_free (excludes_buffer *exb)
INIT_FUNC (mod_dirlisting_init)
FREE_FUNC (mod_dirlisting_free)
SETDEFAULTS_FUNC (mod_dirlisting_set_defaults)
static int mod_dirlisting_patch_connection (server *srv, connection *con, plugin_data *p)
static void http_dirls_sort (dirls_entry_t **ent, int num)
static int http_list_directory_sizefmt (char *buf, size_t bufsz, off_t size)
static void http_list_directory_include_file (buffer *out, buffer *path, const char *classname, int encode)
static void http_dirlist_append_js_table_resort (buffer *b, connection *con)
static void http_list_directory_header (server *srv, connection *con, plugin_data *p, buffer *out)
static void http_list_directory_footer (server *srv, connection *con, plugin_data *p, buffer *out)
static int http_list_directory (server *srv, connection *con, plugin_data *p, buffer *dir)
URIHANDLER_FUNC (mod_dirlisting_subrequest)
int mod_dirlisting_plugin_init (plugin *p)
Variables
static const char js_simple_table_resort []
static const char js_simple_table_init_sort []
Macro Definition Documentation
#define CONFIG_ACTIVATE `dir-listing.activate`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_AUTO_LAYOUT `dir-listing.auto-layout`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_DIR_LISTING `server.dir-listing`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_ENCODE_HEADER `dir-listing.encode-header`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_ENCODE_README `dir-listing.encode-readme`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_ENCODING `dir-listing.encoding`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_EXCLUDE `dir-listing.exclude`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_EXTERNAL_CSS `dir-listing.external-css`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_EXTERNAL_JS `dir-listing.external-js`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_HIDE_DOTFILES `dir-listing.hide-dotfiles`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_HIDE_HEADER_FILE `dir-listing.hide-header-file`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_HIDE_README_FILE `dir-listing.hide-readme-file`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_SET_FOOTER `dir-listing.set-footer`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_SHOW_HEADER `dir-listing.show-header`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define CONFIG_SHOW_README `dir-listing.show-readme`
Referenced by mod_dirlisting_patch_connection(), and SETDEFAULTS_FUNC().
#define DIRLIST_BLOB_SIZE 16
Referenced by http_list_directory().
#define DIRLIST_ENT_NAME(ent) ((char*)(ent) + sizeof(dirls_entry_t))
Referenced by http_dirls_sort(), and http_list_directory().
#define FIFO_NONBLOCK 0
Referenced by http_list_directory_include_file().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_dirlisting_patch_connection().
Function Documentation
static int excludes_buffer_append (excludes_buffer * exb, buffer * string) [static]
References buffer_copy_buffer(), buffer_init(), buffer::ptr, excludes_buffer::ptr, excludes_buffer::size, excludes::string, UNUSED, and excludes_buffer::used.
Referenced by SETDEFAULTS_FUNC().
static void excludes_buffer_free (excludes_buffer * exb) [static]
References buffer_free(), excludes_buffer::ptr, excludes_buffer::size, and excludes::string.
Referenced by FREE_FUNC().
static excludes_buffer* excludes_buffer_init (void) [static]
Referenced by SETDEFAULTS_FUNC().
FREE_FUNC (mod_dirlisting_free)
References buffer_free(), plugin_data::config_storage, plugin_data::content_charset, plugin_config::encoding, plugin_config::excludes, excludes_buffer_free(), plugin_config::external_css, plugin_config::external_js, HANDLER_GO_ON, plugin_config::set_footer, plugin_config::show_header, plugin_config::show_readme, plugin_data::tmp_buf, and UNUSED.
static void http_dirlist_append_js_table_resort (buffer * b, connection * con) [static]
References buffer_append_string_len(), buffer_string_is_empty(), CONST_STR_LEN, js_simple_table_init_sort, js_simple_table_resort, buffer::ptr, request_uri::query, and connection::uri.
Referenced by http_list_directory_footer().
static void http_dirls_sort (dirls_entry_t ** ent, int num) [static]
References DIRLIST_ENT_NAME.
Referenced by http_list_directory().
static int http_list_directory (server * srv, connection * con, plugin_data * p, buffer * dir) [static]
References buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), chunkqueue_append_buffer(), plugin_data::conf, connection::conf, CONST_BUF_LEN, CONST_STR_LEN, plugin_data::content_charset, array::data, DIRLIST_BLOB_SIZE, DIRLIST_ENT_NAME, plugin_config::encoding, ENCODING_MINIMAL_XML, ENCODING_REL_URI_PART, dirls_list_t::ent, plugin_config::excludes, connection::file_finished, force_assert, plugin_config::hide_dot_files, plugin_config::hide_header_file, plugin_config::hide_readme_file, http_dirls_sort(), http_list_directory_footer(), http_list_directory_header(), http_list_directory_sizefmt(), log_error_write(), specific_config::mimetypes, dirls_entry_t::mtime, dirls_entry_t::namelen, buffer::ptr, excludes_buffer::ptr, response_header_overwrite(), plugin_config::show_header, plugin_config::show_readme, dirls_entry_t::size, dirls_list_t::size, server::srvconf, specific_config::use_xattr, array::used, excludes_buffer::used, dirls_list_t::used, data_string::value, connection::write_queue, and server_config::xattr_name.
Referenced by URIHANDLER_FUNC().
static void http_list_directory_footer (server * srv, connection * con, plugin_data * p, buffer * out) [static]
References plugin_config::auto_layout, buffer_append_slash(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_is_empty(), buffer_string_is_empty(), plugin_data::conf, connection::conf, CONST_STR_LEN, plugin_config::encode_readme, plugin_config::external_js, http_dirlist_append_js_table_resort(), http_list_directory_include_file(), physical::path, connection::physical, specific_config::server_tag, plugin_config::set_footer, plugin_config::show_readme, plugin_data::tmp_buf, and UNUSED.
Referenced by http_list_directory().
static void http_list_directory_header (server * srv, connection * con, plugin_data * p, buffer * out) [static]
References plugin_config::auto_layout, buffer_append_slash(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_buffer(), buffer_string_is_empty(), plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, plugin_config::encode_header, plugin_config::encoding, ENCODING_MINIMAL_XML, plugin_config::external_css, http_list_directory_include_file(), request_uri::path, physical::path, connection::physical, plugin_config::show_header, plugin_data::tmp_buf, UNUSED, and connection::uri.
Referenced by http_list_directory().
static void http_list_directory_include_file (buffer * out, buffer * path, const char * classname, int encode) [static]
References buffer_append_string(), buffer_append_string_encoded(), buffer_append_string_len(), CONST_STR_LEN, ENCODING_MINIMAL_XML, FIFO_NONBLOCK, and buffer::ptr.
Referenced by http_list_directory_footer(), and http_list_directory_header().
static int http_list_directory_sizefmt (char * buf, size_t bufsz, off_t size) [static]
References li_itostrn().
Referenced by http_list_directory().
INIT_FUNC (mod_dirlisting_init)
References buffer_init(), plugin_data::content_charset, and plugin_data::tmp_buf.
static int mod_dirlisting_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), CONFIG_ACTIVATE, CONFIG_AUTO_LAYOUT, config_check_cond(), server::config_context, CONFIG_DIR_LISTING, CONFIG_ENCODE_HEADER, CONFIG_ENCODE_README, CONFIG_ENCODING, CONFIG_EXCLUDE, CONFIG_EXTERNAL_CSS, CONFIG_EXTERNAL_JS, CONFIG_HIDE_DOTFILES, CONFIG_HIDE_HEADER_FILE, CONFIG_HIDE_README_FILE, CONFIG_SET_FOOTER, CONFIG_SHOW_HEADER, CONFIG_SHOW_README, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_dirlisting_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_subrequest_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_dirlisting_set_defaults)
References array_get_element(), buffer_copy_string_len(), buffer_init(), buffer_is_equal_string(), buffer_string_is_empty(), buffer_string_set_length(), CONFIG_ACTIVATE, CONFIG_AUTO_LAYOUT, CONFIG_DIR_LISTING, CONFIG_ENCODE_HEADER, CONFIG_ENCODE_README, CONFIG_ENCODING, CONFIG_EXCLUDE, CONFIG_EXTERNAL_CSS, CONFIG_EXTERNAL_JS, CONFIG_HIDE_DOTFILES, CONFIG_HIDE_HEADER_FILE, CONFIG_HIDE_README_FILE, config_insert_values_global(), CONFIG_SET_FOOTER, CONFIG_SHOW_HEADER, CONFIG_SHOW_README, plugin_data::config_storage, CONST_STR_LEN, array::data, config_values_t::destination, excludes_buffer_append(), excludes_buffer_init(), HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), T_CONFIG_BOOLEAN, T_CONFIG_LOCAL, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, TYPE_ARRAY, TYPE_STRING, array::used, and data_config::value.
URIHANDLER_FUNC (mod_dirlisting_subrequest)
References buffer_is_empty(), buffer_reset(), buffer_string_length(), plugin_data::conf, plugin_config::dir_listing, DIRECT, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, http_list_directory(), HTTP_METHOD_GET, HTTP_METHOD_HEAD, log_error_write(), mod_dirlisting_patch_connection(), physical::path, plugin_data::physical, SEGFAULT, stat_cache_entry::st, stat_cache_get_entry(), and UNUSED.
Variable Documentation
const char js_simple_table_init_sort[] [static]
Referenced by http_dirlist_append_js_table_resort().
const char js_simple_table_resort[] [static]
Referenced by http_dirlist_append_js_table_resort().