mod_compress.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `response.h`
*
#include `stat_cache.h`
*
#include `plugin.h`
*
#include `crc32.h`
*
#include `etag.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <assert.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <strings.h>
*
#include <errno.h>
*
#include <time.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define HTTP_ACCEPT_ENCODING_IDENTITY BV(0)
#define HTTP_ACCEPT_ENCODING_GZIP BV(1)
#define HTTP_ACCEPT_ENCODING_DEFLATE BV(2)
#define HTTP_ACCEPT_ENCODING_COMPRESS BV(3)
#define HTTP_ACCEPT_ENCODING_BZIP2 BV(4)
#define HTTP_ACCEPT_ENCODING_X_GZIP BV(5)
#define HTTP_ACCEPT_ENCODING_X_BZIP2 BV(6)
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_compress_init)
FREE_FUNC (mod_compress_free)
static int mkdir_recursive (char *dir)
static int mkdir_for_file (char *filename)
SETDEFAULTS_FUNC (mod_compress_setdefaults)
static void mod_compress_note_ratio (server *srv, connection *con, off_t in, off_t out)
static int deflate_file_to_file (server *srv, connection *con, plugin_data *p, buffer *fn, stat_cache_entry *sce, int type)
static int deflate_file_to_buffer (server *srv, connection *con, plugin_data *p, buffer *fn, stat_cache_entry *sce, int type)
static int mod_compress_patch_connection (server *srv, connection *con, plugin_data *p)
static int mod_compress_contains_encoding (const char *headervalue, const char *encoding, size_t len)
PHYSICALPATH_FUNC (mod_compress_physical)
int mod_compress_plugin_init (plugin *p)
Macro Definition Documentation
#define HTTP_ACCEPT_ENCODING_BZIP2 BV(4)
Referenced by deflate_file_to_buffer(), deflate_file_to_file(), PHYSICALPATH_FUNC(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_COMPRESS BV(3)
Referenced by PHYSICALPATH_FUNC().
#define HTTP_ACCEPT_ENCODING_DEFLATE BV(2)
Referenced by deflate_file_to_buffer(), deflate_file_to_file(), PHYSICALPATH_FUNC(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_GZIP BV(1)
Referenced by deflate_file_to_buffer(), deflate_file_to_file(), PHYSICALPATH_FUNC(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_IDENTITY BV(0)
Referenced by PHYSICALPATH_FUNC().
#define HTTP_ACCEPT_ENCODING_X_BZIP2 BV(6)
Referenced by deflate_file_to_buffer(), deflate_file_to_file(), PHYSICALPATH_FUNC(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_X_GZIP BV(5)
Referenced by deflate_file_to_buffer(), deflate_file_to_file(), PHYSICALPATH_FUNC(), and SETDEFAULTS_FUNC().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_compress_patch_connection().
Function Documentation
static int deflate_file_to_buffer (server * srv, connection * con, plugin_data * p, buffer * fn, stat_cache_entry * sce, int type) [static]
References plugin_data::b, buffer_reset(), buffer_string_length(), chunkqueue_append_buffer(), chunkqueue_reset(), plugin_data::conf, connection::file_finished, connection::file_started, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, HTTP_ACCEPT_ENCODING_X_BZIP2, HTTP_ACCEPT_ENCODING_X_GZIP, server_config::loadavg, log_error_write(), MAP_FAILED, MAP_SHARED, plugin_config::max_loadavg, mmap, mod_compress_note_ratio(), munmap, O_BINARY, physical::path, connection::physical, PROT_READ, buffer::ptr, server::srvconf, stat_cache_entry::st, and connection::write_queue.
Referenced by PHYSICALPATH_FUNC().
static int deflate_file_to_file (server * srv, connection * con, plugin_data * p, buffer * fn, stat_cache_entry * sce, int type) [static]
References plugin_data::b, buffer_append_slash(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_reset(), buffer_string_length(), plugin_config::compress_cache_dir, plugin_data::conf, CONST_BUF_LEN, CONST_STR_LEN, physical::doc_root, stat_cache_entry::etag, HANDLER_ERROR, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, HTTP_ACCEPT_ENCODING_X_BZIP2, HTTP_ACCEPT_ENCODING_X_GZIP, server_config::loadavg, log_error_write(), MAP_FAILED, MAP_SHARED, plugin_config::max_loadavg, mkdir_for_file(), mmap, mod_compress_note_ratio(), munmap, O_BINARY, plugin_data::ofn, request_uri::path, physical::path, connection::physical, PROT_READ, buffer::ptr, server::srvconf, stat_cache_entry::st, stat_cache_get_entry(), and connection::uri.
Referenced by PHYSICALPATH_FUNC().
FREE_FUNC (mod_compress_free)
References array_free(), plugin_data::b, buffer_free(), plugin_config::compress, plugin_config::compress_cache_dir, plugin_data::config_storage, HANDLER_GO_ON, plugin_data::ofn, and UNUSED.
INIT_FUNC (mod_compress_init)
References plugin_data::b, buffer_init(), and plugin_data::ofn.
static int mkdir_for_file (char * filename) [static]
Referenced by deflate_file_to_file().
static int mkdir_recursive (char * dir) [static]
Referenced by SETDEFAULTS_FUNC().
static int mod_compress_contains_encoding (const char * headervalue, const char * encoding, size_t len) [static]
Referenced by PHYSICALPATH_FUNC().
static void mod_compress_note_ratio (server * srv, connection * con, off_t in, off_t out) [static]
References array_set_key_value(), CONST_STR_LEN, connection::environment, LI_ITOSTRING_LENGTH, li_itostrn(), and UNUSED.
Referenced by deflate_file_to_buffer(), and deflate_file_to_file().
static int mod_compress_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by PHYSICALPATH_FUNC().
int mod_compress_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_subrequest_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
PHYSICALPATH_FUNC (mod_compress_physical)
References plugin_config::allowed_encodings, array_get_element(), buffer_append_string(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_is_equal(), buffer_string_is_empty(), plugin_config::compress, plugin_config::compress_cache_dir, plugin_config::compress_max_filesize, plugin_data::conf, connection::conf, CONST_BUF_LEN, CONST_STR_LEN, stat_cache_entry::content_type, array::data, deflate_file_to_buffer(), deflate_file_to_file(), DIRECT, physical::etag, stat_cache_entry::etag, etag_mutate(), specific_config::follow_symlink, force_assert, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, request::headers, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_COMPRESS, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, HTTP_ACCEPT_ENCODING_IDENTITY, HTTP_ACCEPT_ENCODING_X_BZIP2, HTTP_ACCEPT_ENCODING_X_GZIP, request::http_method, HTTP_METHOD_GET, HTTP_METHOD_POST, http_response_handle_cachable(), connection::http_status, log_error_write(), specific_config::log_request_handling, mod_compress_contains_encoding(), mod_compress_patch_connection(), connection::mode, request_uri::path, physical::path, connection::physical, buffer::ptr, connection::request, response_header_insert(), response_header_overwrite(), stat_cache_entry::st, stat_cache_get_entry(), strftime_cache_get(), server::tmp_buf, connection::uri, array::used, and data_string::value.
SETDEFAULTS_FUNC (mod_compress_setdefaults)
References array_free(), array_init(), buffer_init(), buffer_string_is_empty(), buffer_string_set_length(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, HTTP_ACCEPT_ENCODING_X_BZIP2, HTTP_ACCEPT_ENCODING_X_GZIP, log_error_write(), mkdir_recursive(), buffer::ptr, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, data_string::value, and data_config::value.