mod_simple_vhost.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `stat_cache.h`
*
#include `plugin.h`
*
#include <assert.h>
*
#include <ctype.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_simple_vhost_init)
FREE_FUNC (mod_simple_vhost_free)
SETDEFAULTS_FUNC (mod_simple_vhost_set_defaults)
static int build_doc_root (server *srv, connection *con, plugin_data *p, buffer *out, buffer *host)
static int mod_simple_vhost_patch_connection (server *srv, connection *con, plugin_data *p)
static handler_t mod_simple_vhost_docroot (server *srv, connection *con, void *p_data)
int mod_simple_vhost_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_simple_vhost_patch_connection().
Function Documentation
static int build_doc_root (server * srv, connection * con, plugin_data * p, buffer * out, buffer * host) [static]
References buffer_append_slash(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_copy(), plugin_data::conf, plugin_config::debug, plugin_config::document_root, force_assert, HANDLER_ERROR, log_error_write(), buffer::ptr, plugin_config::server_root, stat_cache_entry::st, and stat_cache_get_entry().
Referenced by mod_simple_vhost_docroot().
FREE_FUNC (mod_simple_vhost_free)
References buffer_free(), plugin_data::config_storage, plugin_config::default_host, plugin_data::doc_root, plugin_config::docroot_cache_key, plugin_config::docroot_cache_servername, plugin_config::docroot_cache_value, plugin_config::document_root, HANDLER_GO_ON, plugin_config::server_root, and UNUSED.
INIT_FUNC (mod_simple_vhost_init)
References buffer_init(), and plugin_data::doc_root.
static handler_t mod_simple_vhost_docroot (server * srv, connection * con, void * p_data) [static]
References request_uri::authority, buffer_copy_buffer(), buffer_is_equal(), buffer_string_is_empty(), build_doc_root(), plugin_data::conf, plugin_config::default_host, plugin_data::doc_root, physical::doc_root, plugin_config::docroot_cache_key, plugin_config::docroot_cache_servername, plugin_config::docroot_cache_value, HANDLER_GO_ON, mod_simple_vhost_patch_connection(), connection::physical, connection::server_name, plugin_config::server_root, and connection::uri.
Referenced by mod_simple_vhost_plugin_init().
static int mod_simple_vhost_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by mod_simple_vhost_docroot().
int mod_simple_vhost_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_docroot, plugin::init, mod_simple_vhost_docroot(), plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_simple_vhost_set_defaults)
References buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::server_root, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.