mod_uploadprogress.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include `stat_cache.h`
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct connection_map_entry
struct connection_map
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
static connection_map * connection_map_init ()
static void connection_map_free (connection_map *cm)
static int connection_map_insert (connection_map *cm, connection *con, buffer *con_id)
static connection * connection_map_get_connection (connection_map *cm, buffer *con_id)
static int connection_map_remove_connection (connection_map *cm, connection *con)
INIT_FUNC (mod_uploadprogress_init)
FREE_FUNC (mod_uploadprogress_free)
SETDEFAULTS_FUNC (mod_uploadprogress_set_defaults)
static int mod_uploadprogress_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_uploadprogress_uri_handler)
REQUESTDONE_FUNC (mod_uploadprogress_request_done)
int mod_uploadprogress_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_uploadprogress_patch_connection().
Function Documentation
static void connection_map_free (connection_map * cm) [static]
References buffer_free(), connection_map_entry::con_id, connection_map::ptr, and connection_map::size.
Referenced by FREE_FUNC().
static connection* connection_map_get_connection (connection_map * cm, buffer * con_id) [static]
References buffer_is_equal(), connection_map_entry::con, connection_map_entry::con_id, connection_map::ptr, and connection_map::used.
Referenced by URIHANDLER_FUNC().
static connection_map* connection_map_init () [static]
connection maps
Referenced by INIT_FUNC().
static int connection_map_insert (connection_map * cm, connection * con, buffer * con_id) [static]
References buffer_copy_buffer(), buffer_init(), connection_map_entry::con, connection_map_entry::con_id, connection_map::ptr, connection_map::size, and connection_map::used.
Referenced by URIHANDLER_FUNC().
static int connection_map_remove_connection (connection_map * cm, connection * con) [static]
References buffer_reset(), connection_map_entry::con, connection_map_entry::con_id, connection_map::ptr, and connection_map::used.
Referenced by REQUESTDONE_FUNC().
FREE_FUNC (mod_uploadprogress_free)
References buffer_free(), plugin_data::con_map, plugin_data::config_storage, connection_map_free(), HANDLER_GO_ON, plugin_config::progress_url, and UNUSED.
INIT_FUNC (mod_uploadprogress_init)
References plugin_data::con_map, and connection_map_init().
static int mod_uploadprogress_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_uploadprogress_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_connection_close, plugin::handle_request_done, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
REQUESTDONE_FUNC (mod_uploadprogress_request_done)
References buffer_string_is_empty(), plugin_data::con_map, connection_map_remove_connection(), HANDLER_GO_ON, HTTP_METHOD_POST, and UNUSED.
SETDEFAULTS_FUNC (mod_uploadprogress_set_defaults)
References buffer_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::progress_url, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_uploadprogress_uri_handler)
the idea:
for the first request we check if it is a post-request
if no, move out, don't care about them
if yes, take the connection structure and register it locally in the progress-struct together with an session-id (md5 ...)
if the connections closes, cleanup the entry in the progress-struct
a second request can now get the info about the size of the upload, the received bytes
References array_get_element(), buffer_append_int(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_equal(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), chunkqueue::bytes_in, chunkqueue_append_buffer(), chunkqueue_append_mem(), plugin_data::con_map, plugin_data::conf, connection_map_get_connection(), connection_map_insert(), CONST_STR_LEN, request::content_length, DIRECT, HANDLER_FINISHED, HANDLER_GO_ON, HTTP_METHOD_GET, HTTP_METHOD_POST, light_isxdigit(), log_error_write(), mod_uploadprogress_patch_connection(), plugin_config::progress_url, buffer::ptr, connection::request, connection::request_content_queue, response_header_overwrite(), UNUSED, and data_string::value.