mod_deflate.c File Reference
#include `first.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include `sys-mmap.h`
*
#include <fcntl.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <time.h>
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `etag.h`
*
#include `http_chunk.h`
*
#include `response.h`
*
#include `plugin.h`
*
Classes
struct plugin_config
struct plugin_data
struct handler_ctx
Macros
#define Z_DEFAULT_COMPRESSION -1
#define MAX_WBITS 15
#define HTTP_ACCEPT_ENCODING_IDENTITY BV(0)
#define HTTP_ACCEPT_ENCODING_GZIP BV(1)
#define HTTP_ACCEPT_ENCODING_DEFLATE BV(2)
#define HTTP_ACCEPT_ENCODING_COMPRESS BV(3)
#define HTTP_ACCEPT_ENCODING_BZIP2 BV(4)
#define HTTP_ACCEPT_ENCODING_X_GZIP BV(5)
#define HTTP_ACCEPT_ENCODING_X_BZIP2 BV(6)
#define KByte * 1024
#define MByte * 1024 KByte
#define GByte * 1024 MByte
#define PATCH(x) p->conf.x = s->x;
Functions
static handler_ctx * handler_ctx_init ()
static void handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_deflate_init)
FREE_FUNC (mod_deflate_free)
SETDEFAULTS_FUNC (mod_deflate_setdefaults)
static int mod_deflate_stream_init (handler_ctx *hctx)
static int mod_deflate_compress (server *srv, connection *con, handler_ctx *hctx, unsigned char *start, off_t st_size)
static int mod_deflate_stream_flush (server *srv, connection *con, handler_ctx *hctx, int end)
static void mod_deflate_note_ratio (server *srv, connection *con, handler_ctx *hctx)
static int mod_deflate_stream_end (server *srv, handler_ctx *hctx)
static void deflate_compress_cleanup (server *srv, connection *con, handler_ctx *hctx)
static int mod_deflate_file_chunk (server *srv, connection *con, handler_ctx *hctx, chunk *c, off_t st_size)
static handler_t deflate_compress_response (server *srv, connection *con, handler_ctx *hctx)
static int mod_deflate_patch_connection (server *srv, connection *con, plugin_data *p)
static int mod_deflate_choose_encoding (const char *value, plugin_data *p, const char **label)
CONNECTION_FUNC (mod_deflate_handle_response_start)
static handler_t mod_deflate_cleanup (server *srv, connection *con, void *p_d)
int mod_deflate_plugin_init (plugin *p)
Macro Definition Documentation
#define GByte * 1024 MByte
#define HTTP_ACCEPT_ENCODING_BZIP2 BV(4)
Referenced by mod_deflate_choose_encoding(), mod_deflate_compress(), mod_deflate_stream_end(), mod_deflate_stream_flush(), mod_deflate_stream_init(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_COMPRESS BV(3)
#define HTTP_ACCEPT_ENCODING_DEFLATE BV(2)
Referenced by CONNECTION_FUNC(), mod_deflate_choose_encoding(), mod_deflate_compress(), mod_deflate_stream_end(), mod_deflate_stream_flush(), mod_deflate_stream_init(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_GZIP BV(1)
Referenced by mod_deflate_choose_encoding(), mod_deflate_compress(), mod_deflate_stream_end(), mod_deflate_stream_flush(), mod_deflate_stream_init(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_IDENTITY BV(0)
#define HTTP_ACCEPT_ENCODING_X_BZIP2 BV(6)
Referenced by mod_deflate_choose_encoding(), and SETDEFAULTS_FUNC().
#define HTTP_ACCEPT_ENCODING_X_GZIP BV(5)
Referenced by mod_deflate_choose_encoding(), and SETDEFAULTS_FUNC().
#define KByte * 1024
Referenced by INIT_FUNC(), and mod_deflate_file_chunk().
#define MAX_WBITS 15
#define MByte * 1024 KByte
Referenced by mod_deflate_file_chunk().
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_deflate_patch_connection().
#define Z_DEFAULT_COMPRESSION -1
Function Documentation
CONNECTION_FUNC (mod_deflate_handle_response_start)
References array_get_element(), buffer_append_string(), buffer_append_string_len(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), chunkqueue_length(), chunkqueue_reset(), handler_ctx::compression_type, plugin_data::conf, connection::conf, CONST_STR_LEN, array::data, deflate_compress_cleanup(), deflate_compress_response(), DIRECT, connection::file_finished, handler_ctx_free(), handler_ctx_init(), HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, request::headers, response::headers, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_CONTENT_LENGTH, request::http_if_none_match, request::http_method, HTTP_METHOD_GET, HTTP_METHOD_HEAD, connection::http_status, server_config::loadavg, log_error_write(), plugin_config::max_compress_size, plugin_config::max_loadavg, plugin_config::mimetypes, plugin_config::min_compress_size, mod_deflate_choose_encoding(), mod_deflate_note_ratio(), mod_deflate_patch_connection(), mod_deflate_stream_init(), connection::mode, handler_ctx::output, plugin_config::output_buffer_size, connection::parsed_response, connection::plugin_ctx, handler_ctx::plugin_data, buffer::ptr, connection::request, connection::response, response_header_insert(), response_header_overwrite(), server::srvconf, specific_config::stream_response_body, plugin_config::sync_flush, plugin_data::tmp_buf, response::transfer_encoding, array::used, data_string::value, and connection::write_queue.
static void deflate_compress_cleanup (server * srv, connection * con, handler_ctx * hctx) [static]
References handler_ctx::bytes_in, handler_ctx::bytes_out, handler_ctx_free(), log_error_write(), mod_deflate_stream_end(), request_uri::path_raw, connection::plugin_ctx, handler_ctx::plugin_data, and connection::uri.
Referenced by CONNECTION_FUNC(), and mod_deflate_cleanup().
static handler_t deflate_compress_response (server * srv, connection * con, handler_ctx * hctx) [static]
References buffer_string_length(), chunkqueue::bytes_in, chunkqueue::bytes_out, chunkqueue_append_chunkqueue(), chunkqueue_is_empty(), chunkqueue_length(), chunkqueue_mark_written(), chunkqueue_remove_finished_chunks(), plugin_data::conf, chunk::file, connection::file_finished, chunkqueue::first, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, handler_ctx::in_queue, chunk::length, log_error_write(), chunk::mem, mod_deflate_compress(), mod_deflate_file_chunk(), mod_deflate_stream_flush(), chunk::offset, buffer::ptr, plugin_config::sync_flush, chunk::type, plugin_config::work_block_size, and connection::write_queue.
Referenced by CONNECTION_FUNC().
FREE_FUNC (mod_deflate_free)
References array_free(), buffer_free(), plugin_data::config_storage, plugin_data::encodings, HANDLER_GO_ON, plugin_config::mimetypes, plugin_data::tmp_buf, and UNUSED.
static void handler_ctx_free (handler_ctx * hctx) [static]
References buffer_free(), chunkqueue_free(), handler_ctx::in_queue, and handler_ctx::output.
Referenced by CONNECTION_FUNC(), and deflate_compress_cleanup().
static handler_ctx* handler_ctx_init (void) [static]
References chunkqueue_init(), and handler_ctx::in_queue.
Referenced by CONNECTION_FUNC().
INIT_FUNC (mod_deflate_init)
References array_init(), buffer_init(), buffer_string_prepare_copy(), plugin_data::encodings, KByte, and plugin_data::tmp_buf.
static int mod_deflate_choose_encoding (const char * value, plugin_data * p, const char ** label) [static]
References plugin_config::allowed_encodings, plugin_data::conf, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, HTTP_ACCEPT_ENCODING_X_BZIP2, HTTP_ACCEPT_ENCODING_X_GZIP, and UNUSED.
Referenced by CONNECTION_FUNC().
static handler_t mod_deflate_cleanup (server * srv, connection * con, void * p_d) [static]
References deflate_compress_cleanup(), HANDLER_GO_ON, and connection::plugin_ctx.
Referenced by mod_deflate_plugin_init().
static int mod_deflate_compress (server * srv, connection * con, handler_ctx * hctx, unsigned char * start, off_t st_size) [static]
References handler_ctx::compression_type, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, and UNUSED.
Referenced by deflate_compress_response(), and mod_deflate_file_chunk().
static int mod_deflate_file_chunk (server * srv, connection * con, handler_ctx * hctx, chunk * c, off_t st_size) [static]
References chunk::fd, fdevent_open_cloexec(), chunk::file, force_assert, KByte, chunk::length, log_error_write(), MAP_FAILED, MAP_SHARED, MByte, mmap, chunk::mmap, mod_deflate_compress(), munmap, chunk::name, chunk::offset, PROT_READ, buffer::ptr, and chunk::start.
Referenced by deflate_compress_response().
static void mod_deflate_note_ratio (server * srv, connection * con, handler_ctx * hctx) [static]
References array_set_key_value(), handler_ctx::bytes_in, handler_ctx::bytes_out, CONST_STR_LEN, connection::environment, LI_ITOSTRING_LENGTH, li_itostrn(), and UNUSED.
Referenced by CONNECTION_FUNC().
static int mod_deflate_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by CONNECTION_FUNC().
int mod_deflate_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_connection_close, plugin::handle_response_start, plugin::init, mod_deflate_cleanup(), plugin::name, plugin::set_defaults, and plugin::version.
static int mod_deflate_stream_end (server * srv, handler_ctx * hctx) [static]
References handler_ctx::compression_type, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, and UNUSED.
Referenced by deflate_compress_cleanup().
static int mod_deflate_stream_flush (server * srv, connection * con, handler_ctx * hctx, int end) [static]
References handler_ctx::bytes_in, handler_ctx::compression_type, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, and UNUSED.
Referenced by deflate_compress_response().
static int mod_deflate_stream_init (handler_ctx * hctx) [static]
References handler_ctx::compression_type, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, and HTTP_ACCEPT_ENCODING_GZIP.
Referenced by CONNECTION_FUNC().
SETDEFAULTS_FUNC (mod_deflate_setdefaults)
References plugin_config::allowed_encodings, array_init(), array_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), plugin_config::compression_level, config_insert_values_global(), plugin_data::config_storage, array::data, config_values_t::destination, plugin_data::encodings, HANDLER_ERROR, HANDLER_GO_ON, HTTP_ACCEPT_ENCODING_BZIP2, HTTP_ACCEPT_ENCODING_DEFLATE, HTTP_ACCEPT_ENCODING_GZIP, HTTP_ACCEPT_ENCODING_X_BZIP2, HTTP_ACCEPT_ENCODING_X_GZIP, log_error_write(), plugin_config::max_compress_size, plugin_config::max_loadavg, plugin_config::mimetypes, plugin_config::min_compress_size, plugin_config::output_buffer_size, buffer::ptr, plugin_config::sync_flush, T_CONFIG_ARRAY, T_CONFIG_INT, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_SHORT, T_CONFIG_STRING, T_CONFIG_UNSET, plugin_data::tmp_buf, array::used, data_string::value, and plugin_config::work_block_size.