mod_geoip.c File Reference
#include `first.h`
*
#include <GeoIP.h>
*
#include <GeoIPCity.h>
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
INIT_FUNC (mod_geoip_init)
FREE_FUNC (mod_geoip_free)
SETDEFAULTS_FUNC (mod_geoip_set_defaults)
static int mod_geoip_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_geoip_subrequest)
int mod_geoip_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_geoip_patch_connection().
Function Documentation
FREE_FUNC (mod_geoip_free)
References buffer_free(), plugin_data::config_storage, plugin_config::db_name, plugin_config::gi, HANDLER_GO_ON, and UNUSED.
INIT_FUNC (mod_geoip_init)
static int mod_geoip_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_geoip_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::data, plugin::handle_subrequest_start, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_geoip_set_defaults)
References buffer_init(), buffer_is_empty(), config_insert_values_global(), plugin_data::config_storage, plugin_config::db_name, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), T_CONFIG_BOOLEAN, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_STRING, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_geoip_subrequest)
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_copy_string(), buffer_is_empty(), plugin_data::conf, data_string_init(), plugin_config::db_name, plugin_config::gi, HANDLER_GO_ON, mod_geoip_patch_connection(), TYPE_STRING, and data_string::value.