mod_setenv.c File Reference
#include `first.h`
*
#include `base.h`
*
#include `log.h`
*
#include `buffer.h`
*
#include `plugin.h`
*
#include `response.h`
*
#include <stdlib.h>
*
#include <string.h>
*
Classes
struct handler_ctx
struct plugin_config
struct plugin_data
Macros
#define PATCH(x) p->conf.x = s->x;
Functions
static handler_ctx * handler_ctx_init (void)
static void handler_ctx_free (handler_ctx *hctx)
INIT_FUNC (mod_setenv_init)
FREE_FUNC (mod_setenv_free)
SETDEFAULTS_FUNC (mod_setenv_set_defaults)
static int mod_setenv_patch_connection (server *srv, connection *con, plugin_data *p)
URIHANDLER_FUNC (mod_setenv_uri_handler)
CONNECTION_FUNC (mod_setenv_reset)
int mod_setenv_plugin_init (plugin *p)
Macro Definition Documentation
#define PATCH(x) p->conf.x = s->x;
Referenced by mod_setenv_patch_connection().
Function Documentation
CONNECTION_FUNC (mod_setenv_reset)
References handler_ctx_free(), HANDLER_GO_ON, and UNUSED.
FREE_FUNC (mod_setenv_free)
References array_free(), plugin_data::config_storage, plugin_config::environment, HANDLER_GO_ON, plugin_config::request_header, plugin_config::response_header, and UNUSED.
static void handler_ctx_free (handler_ctx * hctx) [static]
Referenced by CONNECTION_FUNC().
static handler_ctx* handler_ctx_init (void) [static]
References handler_ctx::handled.
Referenced by URIHANDLER_FUNC().
INIT_FUNC (mod_setenv_init)
static int mod_setenv_patch_connection (server * srv, connection * con, plugin_data * p) [static]
References buffer_is_equal_string(), config_check_cond(), server::config_context, plugin_data::config_storage, CONST_STR_LEN, array::data, PATCH, array::used, and data_config::value.
Referenced by URIHANDLER_FUNC().
int mod_setenv_plugin_init (plugin * p)
References buffer_init_string(), plugin::cleanup, plugin::connection_reset, plugin::data, plugin::handle_uri_clean, plugin::init, plugin::name, plugin::set_defaults, and plugin::version.
SETDEFAULTS_FUNC (mod_setenv_set_defaults)
References array_init(), config_insert_values_global(), plugin_data::config_storage, config_values_t::destination, HANDLER_ERROR, HANDLER_GO_ON, plugin_config::request_header, T_CONFIG_ARRAY, T_CONFIG_SCOPE_CONNECTION, T_CONFIG_SCOPE_SERVER, T_CONFIG_SCOPE_UNSET, T_CONFIG_UNSET, and data_config::value.
URIHANDLER_FUNC (mod_setenv_uri_handler)
References array_get_unused_element(), array_insert_unique(), buffer_copy_buffer(), plugin_data::conf, CONST_BUF_LEN, array::data, data_string_init(), plugin_config::environment, handler_ctx::handled, handler_ctx_init(), HANDLER_GO_ON, mod_setenv_patch_connection(), plugin_config::request_header, plugin_config::response_header, response_header_insert(), TYPE_STRING, array::used, and data_string::value.