mod_ssi_exprparser.c File Reference
#include `first.h`
*
#include <stdio.h>
*
#include `mod_ssi_expr.h`
*
#include `buffer.h`
*
#include <assert.h>
*
#include <string.h>
*
Classes
union YYMINORTYPE
struct yyStackEntry
struct yyParser
Macros
#define INTERFACE 1
#define YYCODETYPE unsigned char
#define YYNOCODE 20
#define YYACTIONTYPE unsigned char
#define ssiexprparserTOKENTYPE buffer *
#define YYSTACKDEPTH 100
#define ssiexprparserARG_SDECL ssi_ctx_t *ctx;
#define ssiexprparserARG_PDECL ,ssi_ctx_t *ctx
#define ssiexprparserARG_FETCH ssi_ctx_t *ctx = yypParser->ctx
#define ssiexprparserARG_STORE yypParser->ctx = ctx
#define YYNSTATE 23
#define YYNRULE 16
#define YYERRORSYMBOL 13
#define YYERRSYMDT yy39
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
#define YY_SHIFT_USE_DFLT (-2)
#define YY_REDUCE_USE_DFLT (-7)
#define YY_SZ_ACTTAB (sizeof(yy_action)/sizeof(yy_action[0]))
#define TOKEN (yyminor.yy0)
Typedefs
typedef struct yyStackEntry yyStackEntry
typedef struct yyParser yyParser
Functions
void * ssiexprparserAlloc (void *(*mallocProc)(size_t))
static void yy_destructor (YYCODETYPE yymajor, YYMINORTYPE *yypminor)
static int yy_pop_parser_stack (yyParser *pParser)
void ssiexprparserFree (void *p, void(*freeProc)(void *))
static int yy_find_shift_action (yyParser *pParser, int iLookAhead)
static int yy_find_reduce_action (yyParser *pParser, int iLookAhead)
static void yy_shift (yyParser *yypParser, int yyNewState, int yyMajor, YYMINORTYPE *yypMinor)
static void yy_accept (yyParser *)
static void yy_reduce (yyParser *yypParser, int yyruleno)
static void yy_parse_failed (yyParser *yypParser)
static void yy_syntax_error (yyParser *yypParser, int yymajor, YYMINORTYPE yyminor)
void ssiexprparser (void *yyp, int yymajor, ssiexprparserTOKENTYPE yyminorssiexprparserARG_PDECL)
Variables
static YYACTIONTYPE yy_action []
static YYCODETYPE yy_lookahead []
static signed char yy_shift_ofst []
static signed char yy_reduce_ofst []
static YYACTIONTYPE yy_default []
static FILE * yyTraceFILE = NULL
static char * yyTracePrompt = NULL
static const char * yyTokenName []
static const char * yyRuleName []
xx xx xx xx xx xx xx xx xx
struct {
 YYCODETYPE lhs
 unsigned char nrhs
} yyRuleInfo []
Macro Definition Documentation
#define INTERFACE 1
#define ssiexprparserARG_FETCH ssi_ctx_t *ctx = yypParser->ctx
Referenced by yy_accept(), yy_parse_failed(), yy_reduce(), yy_shift(), and yy_syntax_error().
#define ssiexprparserARG_PDECL ,ssi_ctx_t *ctx
#define ssiexprparserARG_SDECL ssi_ctx_t *ctx;
#define ssiexprparserARG_STORE yypParser->ctx = ctx
Referenced by ssiexprparser(), yy_accept(), yy_parse_failed(), yy_shift(), and yy_syntax_error().
#define ssiexprparserTOKENTYPE buffer *
#define TOKEN (yyminor.yy0)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
Referenced by ssiexprparser().
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YY_REDUCE_USE_DFLT (-7)
Referenced by yy_find_reduce_action().
#define YY_SHIFT_USE_DFLT (-2)
Referenced by yy_find_shift_action().
#define YY_SZ_ACTTAB (sizeof(yy_action)/sizeof(yy_action[0]))
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YYACTIONTYPE unsigned char
#define YYCODETYPE unsigned char
Referenced by yy_pop_parser_stack().
#define YYERRORSYMBOL 13
Referenced by ssiexprparser().
#define YYERRSYMDT yy39
#define YYNOCODE 20
Referenced by ssiexprparser(), yy_find_reduce_action(), and yy_find_shift_action().
#define YYNRULE 16
Referenced by ssiexprparser(), and yy_reduce().
#define YYNSTATE 23
Referenced by ssiexprparser(), and yy_reduce().
#define YYSTACKDEPTH 100
Referenced by yy_shift().
Typedef Documentation
typedef struct yyParser yyParser
typedef struct yyStackEntry yyStackEntry
Function Documentation
void ssiexprparser (void * yyp, int yymajor, ssiexprparserTOKENTYPE yyminor ssiexprparserARG_PDECL)
References yyStackEntry::major, ssiexprparserARG_STORE, yyStackEntry::stateno, YYMINORTYPE::yy0, yy_accept(), yy_destructor(), YY_ERROR_ACTION, yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), yy_syntax_error(), yyParser::yyerrcnt, YYERRORSYMBOL, yyParser::yyidx, YYNOCODE, YYNRULE, YYNSTATE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
void* ssiexprparserAlloc (void *(*)(size_t) mallocProc)
References yyParser::yyidx.
Referenced by ssi_eval_expr().
void ssiexprparserFree (void * p, void(*)(void *) freeProc)
References yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by ssi_eval_expr().
static void yy_accept (yyParser * yypParser) [static]
References ssiexprparserARG_FETCH, ssiexprparserARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by ssiexprparser(), and yy_reduce().
static void yy_destructor (YYCODETYPE yymajor, YYMINORTYPE * yypminor) [static]
References buffer_free(), and YYMINORTYPE::yy0.
Referenced by ssiexprparser(), yy_pop_parser_stack(), and yy_reduce().
static int yy_find_reduce_action (yyParser * pParser, int iLookAhead) [static]
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_NO_ACTION, yy_reduce_ofst, YY_REDUCE_USE_DFLT, YY_SZ_ACTTAB, yyParser::yyidx, YYNOCODE, and yyParser::yystack.
Referenced by yy_reduce().
static int yy_find_shift_action (yyParser * pParser, int iLookAhead) [static]
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_NO_ACTION, yy_shift_ofst, YY_SHIFT_USE_DFLT, YY_SZ_ACTTAB, yyParser::yyidx, YYNOCODE, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by ssiexprparser().
static void yy_parse_failed (yyParser * yypParser) [static]
References ssiexprparserARG_FETCH, ssiexprparserARG_STORE, yy_pop_parser_stack(), yyParser::yyidx, yyTraceFILE, and yyTracePrompt.
Referenced by ssiexprparser().
static int yy_pop_parser_stack (yyParser * pParser) [static]
References yyStackEntry::major, yyStackEntry::minor, yy_destructor(), YYCODETYPE, yyParser::yyidx, yyParser::yystack, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by ssiexprparser(), ssiexprparserFree(), yy_accept(), yy_parse_failed(), and yy_shift().
static void yy_reduce (yyParser * yypParser, int yyruleno) [static]
References ssi_val_t::bo, buffer_append_string_buffer(), buffer_free(), yyStackEntry::minor, buffer::ptr, SSI_COND_EQ, SSI_COND_GE, SSI_COND_GT, SSI_COND_LE, SSI_COND_LT, SSI_COND_NE, ssi_val_free(), ssi_val_init(), ssi_val_tobool(), ssiexprparserARG_FETCH, ssi_val_t::str, ssi_val_t::type, YYMINORTYPE::yy0, YYMINORTYPE::yy19, YYMINORTYPE::yy29, YYMINORTYPE::yy8, yy_accept(), yy_destructor(), yy_find_reduce_action(), yy_shift(), yyParser::yyidx, YYNRULE, YYNSTATE, yyRuleInfo, yyRuleName, yyParser::yystack, yyTraceFILE, and yyTracePrompt.
Referenced by ssiexprparser().
static void yy_shift (yyParser * yypParser, int yyNewState, int yyMajor, YYMINORTYPE * yypMinor) [static]
References yyStackEntry::major, yyStackEntry::minor, ssiexprparserARG_FETCH, ssiexprparserARG_STORE, yyStackEntry::stateno, yy_pop_parser_stack(), yyParser::yyidx, yyParser::yystack, YYSTACKDEPTH, yyTokenName, yyTraceFILE, and yyTracePrompt.
Referenced by ssiexprparser(), and yy_reduce().
static void yy_syntax_error (yyParser * yypParser, int yymajor, YYMINORTYPE yyminor) [static]
References ssiexprparserARG_FETCH, ssiexprparserARG_STORE, and UNUSED.
Referenced by ssiexprparser().
Variable Documentation
YYCODETYPE lhs
unsigned char nrhs
YYACTIONTYPE yy_action[] [static]
Initial value:
= {
      5, 7, 17, 18, 22, 20, 21, 19, 2, 14,
      1, 23, 40, 9, 11, 3, 16, 2, 14, 12,
      4, 14, 5, 7, 6, 14, 7, 8, 14, 10,
     14, 13, 37, 37, 15,
}
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
YYACTIONTYPE yy_default[] [static]
Initial value:
= {
     39, 39, 25, 39, 24, 39, 26, 39, 27, 39,
     28, 39, 39, 29, 30, 32, 31, 33, 34, 35,
     36, 37, 38,
}
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
YYCODETYPE yy_lookahead[] [static]
Initial value:
= {
      1, 2, 3, 4, 5, 6, 7, 8, 14, 15,
     16, 0, 18, 9, 10, 17, 12, 14, 15, 16,
     14, 15, 1, 2, 14, 15, 2, 14, 15, 14,
     15, 11, 19, 19, 12,
}
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
signed char yy_reduce_ofst[] [static]
Initial value:
= {
     -6, -7, -2, 6, -7, 10, -7, 13, -7, 15,
     -7, 3, -7, -7, -7, -7, -7, -7, -7, -7,
     -7, -7, -7,
}
Referenced by yy_find_reduce_action().
signed char yy_shift_ofst[] [static]
Initial value:
= {
      4, 11, -1, 4, 21, 4, 24, 4, -2, 4,
     -2, 4, 20, -2, 22, -2, -2, -2, -2, -2,
     -2, -2, -2,
}
Referenced by yy_find_shift_action().
struct { ... } yyRuleInfo[] [static]
Initial value:
= {
  { 18, 1 },
  { 16, 3 },
  { 16, 1 },
  { 14, 3 },
  { 14, 3 },
  { 14, 2 },
  { 14, 3 },
  { 14, 1 },
  { 15, 1 },
  { 15, 2 },
  { 17, 1 },
  { 17, 1 },
  { 17, 1 },
  { 17, 1 },
  { 17, 1 },
  { 17, 1 },
}
Referenced by yy_reduce().
const char* yyRuleName[] [static]
Initial value:
= {
  "input ::= exprline",
  "exprline ::= expr cond expr",
  "exprline ::= expr",
  "expr ::= expr AND expr",
  "expr ::= expr OR expr",
  "expr ::= NOT expr",
  "expr ::= LPARAN exprline RPARAN",
  "expr ::= value",
  "value ::= VALUE",
  "value ::= value VALUE",
  "cond ::= EQ",
  "cond ::= NE",
  "cond ::= LE",
  "cond ::= GE",
  "cond ::= LT",
  "cond ::= GT",
}
Referenced by yy_reduce().
const char* yyTokenName[] [static]
Initial value:
= {
  "$", "AND", "OR", "EQ",
  "NE", "GT", "GE", "LT",
  "LE", "NOT", "LPARAN", "RPARAN",
  "VALUE", "error", "expr", "value",
  "exprline", "cond", "input",
}
Referenced by ssiexprparser(), yy_find_shift_action(), yy_pop_parser_stack(), and yy_shift().
FILE* yyTraceFILE = NULL [static]
Referenced by ssiexprparser(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), and yy_shift().
char* yyTracePrompt = NULL [static]
Referenced by ssiexprparser(), yy_accept(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), and yy_shift().