mod_ssi_expr.h File Reference
#include `first.h`
*
#include `buffer.h`
*
Classes
struct ssi_val_t
struct ssi_ctx_t
Enumerations
enum ssi_expr_cond {
*
SSI_COND_UNSET,
SSI_COND_LE,
SSI_COND_GE,
SSI_COND_EQ,
*
SSI_COND_NE,
SSI_COND_LT,
SSI_COND_GT
 }
Functions
void * ssiexprparserAlloc (void *(*mallocProc)(size_t))
void ssiexprparserFree (void *p, void(*freeProc)(void *))
void ssiexprparser (void *yyp, int yymajor, buffer *yyminor, ssi_ctx_t *ctx)
int ssi_val_tobool (ssi_val_t *B)
ssi_val_t * ssi_val_init (void)
void ssi_val_free (ssi_val_t *s)
Enumeration Type Documentation
enum ssi_expr_cond
Enumerator
SSI_COND_UNSET
SSI_COND_LE
SSI_COND_GE
SSI_COND_EQ
SSI_COND_NE
SSI_COND_LT
SSI_COND_GT
Function Documentation
void ssi_val_free (ssi_val_t * s)
References buffer_free(), and ssi_val_t::str.
Referenced by yy_reduce().
ssi_val_t* ssi_val_init (void)
Referenced by yy_reduce().
int ssi_val_tobool (ssi_val_t * B)
References ssi_val_t::bo, buffer_string_is_empty(), ssi_val_t::str, and ssi_val_t::type.
Referenced by yy_reduce().
void ssiexprparser (void * yyp, int yymajor, buffer * yyminor, ssi_ctx_t * ctx)
Referenced by ssi_eval_expr().
void* ssiexprparserAlloc (void *(*)(size_t) mallocProc)
References yyParser::yyidx.
Referenced by ssi_eval_expr().
void ssiexprparserFree (void * p, void(*)(void *) freeProc)
References yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by ssi_eval_expr().