network.c File Reference
#include `first.h`
*
#include `network.h`
*
#include `fdevent.h`
*
#include `log.h`
*
#include `connections.h`
*
#include `plugin.h`
*
#include `joblist.h`
*
#include `configfile.h`
*
#include `network_backends.h`
*
#include `sys-mmap.h`
*
#include `sys-socket.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <sys/time.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <assert.h>
*
Enumerations
enum network_backend_t { NETWORK_BACKEND_UNSET,
NETWORK_BACKEND_WRITE,
NETWORK_BACKEND_WRITEV,
NETWORK_BACKEND_SENDFILE
 }
Functions
void network_accept_tcp_nagle_disable (const int fd)
static handler_t network_server_handle_fdevent (server *srv, void *context, int revents)
static int network_server_init (server *srv, buffer *host_token, specific_config *s)
int network_close (server *srv)
int network_init (server *srv)
int network_register_fdevents (server *srv)
int network_write_chunkqueue (server *srv, connection *con, chunkqueue *cq, off_t max_bytes)
Enumeration Type Documentation
enum network_backend_t
Enumerator
NETWORK_BACKEND_UNSET
NETWORK_BACKEND_WRITE
NETWORK_BACKEND_WRITEV
NETWORK_BACKEND_SENDFILE
Function Documentation
void network_accept_tcp_nagle_disable (const int fd)
Referenced by connection_accept(), and server_oneshot_init().
int network_close (server * srv)
References buffer_free(), server::ev, server_socket::fd, server_socket::fde_ndx, fdevent_event_del(), fdevent_unregister(), server_socket_array::ptr, server::srv_sockets, server_socket::srv_token, and server_socket_array::used.
Referenced by main().
int network_init (server * srv)
References server_config::bindhost, buffer_append_int(), buffer_append_string_len(), buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_is_equal(), buffer_is_equal_string(), buffer_string_is_empty(), data_config::comp, COMP_HTTP_HOST, COMP_SERVER_SOCKET, data_config::cond, CONFIG_COND_EQ, server::config_context, server::config_storage, CONST_STR_LEN, array::data, log_error_write(), server_config::network_backend, NETWORK_BACKEND_SENDFILE, NETWORK_BACKEND_UNSET, NETWORK_BACKEND_WRITE, server::network_backend_write, NETWORK_BACKEND_WRITEV, network_server_init(), network_write_chunkqueue_write(), network_write_chunkqueue_writev(), server_config::port, buffer::ptr, server_socket_array::ptr, server::srv_sockets, server_socket::srv_token, server::srvconf, specific_config::ssl_ca_file, specific_config::ssl_cipher_list, specific_config::ssl_dh_file, specific_config::ssl_ec_curve, specific_config::ssl_empty_fragments, specific_config::ssl_enabled, specific_config::ssl_honor_cipher_order, server::ssl_is_init, specific_config::ssl_pemfile, specific_config::ssl_read_ahead, specific_config::ssl_use_sslv2, specific_config::ssl_use_sslv3, specific_config::ssl_verifyclient, specific_config::ssl_verifyclient_depth, specific_config::ssl_verifyclient_enforce, data_config::string, array::used, and server_socket_array::used.
Referenced by main().
int network_register_fdevents (server * srv)
References server::ev, server_socket::fd, server_socket::fde_ndx, fdevent_event_set(), FDEVENT_IN, fdevent_register(), fdevent_reset(), network_server_handle_fdevent(), server_socket_array::ptr, server::sockets_disabled, server::srv_sockets, and server_socket_array::used.
Referenced by main().
static handler_t network_server_handle_fdevent (server * srv, void * context, int revents) [static]
References connection_accept(), connection_state_machine(), server_socket::fd, FDEVENT_IN, HANDLER_ERROR, HANDLER_GO_ON, log_error_write(), and UNUSED.
Referenced by network_register_fdevents().
static int network_server_init (server * srv, buffer * host_token, specific_config * s) [static]
References server_socket::addr, buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal_string(), buffer_string_length(), CONST_STR_LEN, server::cur_fds, specific_config::defer_accept, server::ev, server_socket::fd, server_socket::fde_ndx, fdevent_event_del(), fdevent_fcntl_set_nb(), fdevent_socket_cloexec(), fdevent_socket_nb_cloexec(), fdevent_unregister(), force_assert, sock_addr::ipv4, server_socket::is_ssl, specific_config::listen_backlog, log_error_write(), sock_addr::plain, server_config::port, server_config::preflight_check, buffer::ptr, server_socket_array::ptr, specific_config::set_v6only, server_socket_array::size, server::sockets_disabled, server::srv_sockets, server_socket::srv_token, server::srvconf, specific_config::ssl_enabled, specific_config::use_ipv6, and server_socket_array::used.
Referenced by network_init().
int network_write_chunkqueue (server * srv, connection * con, chunkqueue * cq, off_t max_bytes)
References chunkqueue::bytes_out, connection::bytes_written, connection::bytes_written_cur_second, chunkqueue_is_empty(), chunkqueue_remove_finished_chunks(), connection::conf, connection::fd, chunkqueue::first, specific_config::global_bytes_per_second_cnt_ptr, specific_config::global_kbytes_per_second, server_socket::is_ssl, specific_config::kbytes_per_second, server::network_backend_write, chunk::next, connection::srv_socket, and connection::traffic_limit_reached.
Referenced by connection_handle_write().