network_write_no_mmap.c File Reference
#include `first.h`
*
#include `network_backends.h`
*
#include `network.h`
*
#include `fdevent.h`
*
#include `log.h`
*
#include `stat_cache.h`
*
#include `sys-socket.h`
*
#include <sys/time.h>
*
#include <stdlib.h>
*
#include <fcntl.h>
*
#include <sys/stat.h>
*
#include <unistd.h>
*
#include <errno.h>
*
#include <string.h>
*
Functions
int network_open_file_chunk (server *srv, connection *con, chunkqueue *cq)
int network_write_file_chunk_no_mmap (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
Function Documentation
int network_open_file_chunk (server * srv, connection * con, chunkqueue * cq)
References chunk::fd, fdevent_open_cloexec(), chunk::file, chunkqueue::first, force_assert, chunk::is_temp, chunk::length, log_error_write(), chunk::name, chunk::offset, buffer::ptr, chunk::start, chunk::type, and UNUSED.
Referenced by network_write_file_chunk_no_mmap().
int network_write_file_chunk_no_mmap (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes)
References buffer_string_prepare_copy(), chunkqueue_mark_written(), chunkqueue_remove_finished_chunks(), chunk::fd, chunk::file, chunkqueue::first, force_assert, chunk::length, log_error_write(), network_open_file_chunk(), chunk::offset, buffer::ptr, chunk::start, server::tmp_buf, and chunk::type.
Referenced by network_write_file_chunk_mmap().