network_backends.h File Reference
#include `first.h`
*
#include `settings.h`
*
#include <sys/types.h>
*
#include `base.h`
*
Functions
int network_write_chunkqueue_write (server *srv, connection *con, int fd, chunkqueue *cq, off_t max_bytes)
int network_write_mem_chunk (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
static int network_writev_mem_chunks (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
int network_write_file_chunk_no_mmap (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
off_t mmap_align_offset (off_t start)
static int network_write_file_chunk_mmap (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
static int network_write_file_chunk_sendfile (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
int network_open_file_chunk (server *srv, connection *con, chunkqueue *cq)
Function Documentation
off_t mmap_align_offset (off_t start)
References force_assert, and MMAP_CHUNK_SIZE.
int network_open_file_chunk (server * srv, connection * con, chunkqueue * cq)
References chunk::fd, fdevent_open_cloexec(), chunk::file, chunkqueue::first, force_assert, chunk::is_temp, chunk::length, log_error_write(), chunk::name, chunk::offset, buffer::ptr, chunk::start, chunk::type, and UNUSED.
Referenced by network_write_file_chunk_no_mmap().
int network_write_chunkqueue_write (server * srv, connection * con, int fd, chunkqueue * cq, off_t max_bytes)
References chunkqueue::first, network_write_file_chunk_mmap(), network_write_mem_chunk(), and chunk::type.
Referenced by network_init().
static int network_write_file_chunk_mmap (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes) [inline], [static]
References network_write_file_chunk_no_mmap().
Referenced by network_write_chunkqueue_write(), network_write_chunkqueue_writev(), and network_write_file_chunk_sendfile().
int network_write_file_chunk_no_mmap (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes)
References buffer_string_prepare_copy(), chunkqueue_mark_written(), chunkqueue_remove_finished_chunks(), chunk::fd, chunk::file, chunkqueue::first, force_assert, chunk::length, log_error_write(), network_open_file_chunk(), chunk::offset, buffer::ptr, chunk::start, server::tmp_buf, and chunk::type.
Referenced by network_write_file_chunk_mmap().
static int network_write_file_chunk_sendfile (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes) [inline], [static]
References network_write_file_chunk_mmap().
int network_write_mem_chunk (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes)
References buffer_string_length(), chunkqueue_mark_written(), chunkqueue_remove_finished_chunks(), chunkqueue::first, force_assert, log_error_write(), chunk::mem, chunk::offset, buffer::ptr, chunk::type, and UNUSED.
Referenced by network_write_chunkqueue_write(), and network_writev_mem_chunks().
static int network_writev_mem_chunks (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes) [inline], [static]
References network_write_mem_chunk().
Referenced by network_write_chunkqueue_writev().