network_writev.c File Reference
#include `first.h`
*
#include `network_backends.h`
*
Functions
int network_write_chunkqueue_writev (server *srv, connection *con, int fd, chunkqueue *cq, off_t max_bytes)
Function Documentation
int network_write_chunkqueue_writev (server * srv, connection * con, int fd, chunkqueue * cq, off_t max_bytes)
References chunkqueue::first, network_write_file_chunk_mmap(), network_writev_mem_chunks(), and chunk::type.
Referenced by network_init().