network_write.c File Reference
#include `first.h`
*
#include `network_backends.h`
*
#include `network.h`
*
#include `log.h`
*
#include `sys-socket.h`
*
#include <unistd.h>
*
#include <errno.h>
*
#include <string.h>
*
Functions
int network_write_mem_chunk (server *srv, connection *con, int fd, chunkqueue *cq, off_t *p_max_bytes)
int network_write_chunkqueue_write (server *srv, connection *con, int fd, chunkqueue *cq, off_t max_bytes)
Function Documentation
int network_write_chunkqueue_write (server * srv, connection * con, int fd, chunkqueue * cq, off_t max_bytes)
References chunkqueue::first, network_write_file_chunk_mmap(), network_write_mem_chunk(), and chunk::type.
Referenced by network_init().
int network_write_mem_chunk (server * srv, connection * con, int fd, chunkqueue * cq, off_t * p_max_bytes)
References buffer_string_length(), chunkqueue_mark_written(), chunkqueue_remove_finished_chunks(), chunkqueue::first, force_assert, log_error_write(), chunk::mem, chunk::offset, buffer::ptr, chunk::type, and UNUSED.
Referenced by network_write_chunkqueue_write(), and network_writev_mem_chunks().