network.h File Reference
#include `first.h`
*
#include `server.h`
*
Functions
void network_accept_tcp_nagle_disable (int fd)
int network_write_chunkqueue (server *srv, connection *con, chunkqueue *c, off_t max_bytes)
int network_init (server *srv)
int network_close (server *srv)
int network_register_fdevents (server *srv)
Function Documentation
void network_accept_tcp_nagle_disable (int fd)
Referenced by connection_accept(), and server_oneshot_init().
int network_close (server * srv)
References buffer_free(), server::ev, server_socket::fd, server_socket::fde_ndx, fdevent_event_del(), fdevent_unregister(), server_socket_array::ptr, server::srv_sockets, server_socket::srv_token, and server_socket_array::used.
Referenced by main().
int network_init (server * srv)
References server_config::bindhost, buffer_append_int(), buffer_append_string_len(), buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_is_equal(), buffer_is_equal_string(), buffer_string_is_empty(), data_config::comp, COMP_HTTP_HOST, COMP_SERVER_SOCKET, data_config::cond, CONFIG_COND_EQ, server::config_context, server::config_storage, CONST_STR_LEN, array::data, log_error_write(), server_config::network_backend, NETWORK_BACKEND_SENDFILE, NETWORK_BACKEND_UNSET, NETWORK_BACKEND_WRITE, server::network_backend_write, NETWORK_BACKEND_WRITEV, network_server_init(), network_write_chunkqueue_write(), network_write_chunkqueue_writev(), server_config::port, buffer::ptr, server_socket_array::ptr, server::srv_sockets, server_socket::srv_token, server::srvconf, specific_config::ssl_ca_file, specific_config::ssl_cipher_list, specific_config::ssl_dh_file, specific_config::ssl_ec_curve, specific_config::ssl_empty_fragments, specific_config::ssl_enabled, specific_config::ssl_honor_cipher_order, server::ssl_is_init, specific_config::ssl_pemfile, specific_config::ssl_read_ahead, specific_config::ssl_use_sslv2, specific_config::ssl_use_sslv3, specific_config::ssl_verifyclient, specific_config::ssl_verifyclient_depth, specific_config::ssl_verifyclient_enforce, data_config::string, array::used, and server_socket_array::used.
Referenced by main().
int network_register_fdevents (server * srv)
References server::ev, server_socket::fd, server_socket::fde_ndx, fdevent_event_set(), FDEVENT_IN, fdevent_register(), fdevent_reset(), network_server_handle_fdevent(), server_socket_array::ptr, server::sockets_disabled, server::srv_sockets, and server_socket_array::used.
Referenced by main().
int network_write_chunkqueue (server * srv, connection * con, chunkqueue * c, off_t max_bytes)
References chunkqueue::bytes_out, connection::bytes_written, connection::bytes_written_cur_second, chunkqueue_is_empty(), chunkqueue_remove_finished_chunks(), connection::conf, connection::fd, chunkqueue::first, specific_config::global_bytes_per_second_cnt_ptr, specific_config::global_kbytes_per_second, server_socket::is_ssl, specific_config::kbytes_per_second, server::network_backend_write, chunk::next, connection::srv_socket, and connection::traffic_limit_reached.
Referenced by connection_handle_write().