plugin.c File Reference
#include `first.h`
*
#include `plugin.h`
*
#include `log.h`
*
#include <string.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <dlfcn.h>
*
Classes
struct plugin_data
Macros
#define PLUGIN_TO_SLOT(x, y)
#define PLUGIN_TO_SLOT(x, y)
#define PLUGIN_TO_SLOT(x, y)
Enumerations
enum plugin_t {
*
PLUGIN_FUNC_UNSET,
PLUGIN_FUNC_HANDLE_URI_CLEAN,
PLUGIN_FUNC_HANDLE_URI_RAW,
PLUGIN_FUNC_HANDLE_REQUEST_DONE,
*
PLUGIN_FUNC_HANDLE_CONNECTION_CLOSE,
PLUGIN_FUNC_HANDLE_TRIGGER,
PLUGIN_FUNC_HANDLE_SIGHUP,
PLUGIN_FUNC_HANDLE_SUBREQUEST,
*
PLUGIN_FUNC_HANDLE_SUBREQUEST_START,
PLUGIN_FUNC_HANDLE_RESPONSE_START,
PLUGIN_FUNC_HANDLE_DOCROOT,
PLUGIN_FUNC_HANDLE_PHYSICAL,
*
PLUGIN_FUNC_CONNECTION_RESET,
PLUGIN_FUNC_INIT,
PLUGIN_FUNC_CLEANUP,
PLUGIN_FUNC_SET_DEFAULTS,
*
PLUGIN_FUNC_SIZEOF
 }
Functions
static plugin * plugin_init (void)
static void plugin_free (plugin *p)
static int plugins_register (server *srv, plugin *p)
int plugins_load (server *srv)
handler_t plugins_call_init (server *srv)
void plugins_free (server *srv)
Macro Definition Documentation
#define PLUGIN_TO_SLOT(x, y)
Value:
handler_t plugins_call_##y(server *srv, connection *con) {\
        plugin **slot;\
        size_t j;\
        if (!srv->plugin_slots) return HANDLER_GO_ON;\
        slot = ((plugin ***)(srv->plugin_slots))[x];\
        if (!slot) return HANDLER_GO_ON;\
        for (j = 0; j < srv->plugins.used && slot[j]; j++) { \
            plugin *p = slot[j];\
            handler_t r;\
            switch(r = p->y(srv, con, p->data)) {\
            case HANDLER_GO_ON:\
                break;\
            case HANDLER_FINISHED:\
            case HANDLER_COMEBACK:\
            case HANDLER_WAIT_FOR_EVENT:\
            case HANDLER_WAIT_FOR_FD:\
            case HANDLER_ERROR:\
                return r;\
            default:\
                log_error_write(srv, __FILE__, __LINE__, "sbs", #x, p->name, "unknown
       state");\
                return HANDLER_ERROR;\
            }\
        }\
        return HANDLER_GO_ON;\
    }
plugins that use
server *srv
connection *con
void *p_d (plugin_data *)
Referenced by plugins_call_init().
#define PLUGIN_TO_SLOT(x, y)
Value:
handler_t plugins_call_##y(server *srv) {\
        plugin **slot;\
        size_t j;\
        if (!srv->plugin_slots) return HANDLER_GO_ON;\
        slot = ((plugin ***)(srv->plugin_slots))[x];\
        if (!slot) return HANDLER_GO_ON;\
        for (j = 0; j < srv->plugins.used && slot[j]; j++) { \
            plugin *p = slot[j];\
            handler_t r;\
            switch(r = p->y(srv, p->data)) {\
            case HANDLER_GO_ON:\
                break;\
            case HANDLER_FINISHED:\
            case HANDLER_COMEBACK:\
            case HANDLER_WAIT_FOR_EVENT:\
            case HANDLER_WAIT_FOR_FD:\
            case HANDLER_ERROR:\
                return r;\
            default:\
                log_error_write(srv, __FILE__, __LINE__, "sbsd", #x, p->name, "unknown
       state:", r);\
                return HANDLER_ERROR;\
            }\
        }\
        return HANDLER_GO_ON;\
    }
plugins that use
server *srv
connection *con
void *p_d (plugin_data *)
#define PLUGIN_TO_SLOT(x, y)
Value:
if (p->y) { \
        plugin **slot = ((plugin ***)(srv->plugin_slots))[x]; \
        if (!slot) { \
            slot = calloc(srv->plugins.used, sizeof(*slot));\
            force_assert(NULL != slot); \
            ((plugin ***)(srv->plugin_slots))[x] = slot; \
        } \
        for (j = 0; j < srv->plugins.used; j++) { \
            if (slot[j]) continue;\
            slot[j] = p;\
            break;\
        }\
    }
plugins that use
server *srv
connection *con
void *p_d (plugin_data *)
Enumeration Type Documentation
enum plugin_t
Enumerator
PLUGIN_FUNC_UNSET
PLUGIN_FUNC_HANDLE_URI_CLEAN
PLUGIN_FUNC_HANDLE_URI_RAW
PLUGIN_FUNC_HANDLE_REQUEST_DONE
PLUGIN_FUNC_HANDLE_CONNECTION_CLOSE
PLUGIN_FUNC_HANDLE_TRIGGER
PLUGIN_FUNC_HANDLE_SIGHUP
PLUGIN_FUNC_HANDLE_SUBREQUEST
PLUGIN_FUNC_HANDLE_SUBREQUEST_START
PLUGIN_FUNC_HANDLE_RESPONSE_START
PLUGIN_FUNC_HANDLE_DOCROOT
PLUGIN_FUNC_HANDLE_PHYSICAL
PLUGIN_FUNC_CONNECTION_RESET
PLUGIN_FUNC_INIT
PLUGIN_FUNC_CLEANUP
PLUGIN_FUNC_SET_DEFAULTS
PLUGIN_FUNC_SIZEOF
Function Documentation
static void plugin_free (plugin * p) [static]
References buffer_free(), plugin::lib, and plugin::name.
Referenced by plugins_free(), and plugins_load().
static plugin* plugin_init (void) [static]
References force_assert.
Referenced by plugins_load().
handler_t plugins_call_init (server * srv)
plugins that use
server *srv
void *p_d (plugin_data *)
call init function of all plugins to init the plugin-internals
added each plugin that supports has callback to the corresponding slot
is only called once.
References connection_reset(), plugin::data, force_assert, HANDLER_ERROR, HANDLER_GO_ON, plugin::init, log_error_write(), plugin::name, PLUGIN_FUNC_HANDLE_TRIGGER, PLUGIN_FUNC_HANDLE_URI_CLEAN, PLUGIN_FUNC_SIZEOF, server::plugin_slots, PLUGIN_TO_SLOT, server::plugins, ps, buffer_plugin::ptr, buffer_plugin::used, and plugin::version.
Referenced by main().
void plugins_free (server * srv)
References plugin_free(), PLUGIN_FUNC_SIZEOF, server::plugin_slots, server::plugins, plugins_call_cleanup(), buffer_plugin::ptr, and buffer_plugin::used.
Referenced by main().
int plugins_load (server * srv)
References buffer_append_string(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_is_equal(), buffer_reset(), CONST_STR_LEN, array::data, plugin::lib, log_error_write(), server_config::modules, server_config::modules_dir, plugin_free(), plugin_init(), plugins_register(), buffer::ptr, server::srvconf, server::tmp_buf, array::used, and data_string::value.
static int plugins_register (server * srv, plugin * p) [static]
References force_assert, server::plugins, ps, buffer_plugin::ptr, buffer_plugin::size, and buffer_plugin::used.
Referenced by plugins_load().