plugin.h File Reference
#include `first.h`
*
#include `base.h`
*
#include `buffer.h`
*
Classes
struct plugin
Macros
#define SERVER_FUNC(x) static handler_t x(server *srv, void *p_d)
#define CONNECTION_FUNC(x) static handler_t x(server *srv, connection *con, void *p_d)
#define INIT_FUNC(x) static void *x(void)
#define FREE_FUNC SERVER_FUNC
#define TRIGGER_FUNC SERVER_FUNC
#define SETDEFAULTS_FUNC SERVER_FUNC
#define SIGHUP_FUNC SERVER_FUNC
#define SUBREQUEST_FUNC CONNECTION_FUNC
#define PHYSICALPATH_FUNC CONNECTION_FUNC
#define REQUESTDONE_FUNC CONNECTION_FUNC
#define URIHANDLER_FUNC CONNECTION_FUNC
#define PLUGIN_DATA size_t id
Functions
int plugins_load (server *srv)
void plugins_free (server *srv)
handler_t plugins_call_handle_uri_raw (server *srv, connection *con)
handler_t plugins_call_handle_uri_clean (server *srv, connection *con)
handler_t plugins_call_handle_subrequest_start (server *srv, connection *con)
handler_t plugins_call_handle_subrequest (server *srv, connection *con)
handler_t plugins_call_handle_response_start (server *srv, connection *con)
handler_t plugins_call_handle_request_done (server *srv, connection *con)
handler_t plugins_call_handle_docroot (server *srv, connection *con)
handler_t plugins_call_handle_physical (server *srv, connection *con)
handler_t plugins_call_handle_connection_close (server *srv, connection *con)
handler_t plugins_call_connection_reset (server *srv, connection *con)
handler_t plugins_call_handle_trigger (server *srv)
handler_t plugins_call_handle_sighup (server *srv)
handler_t plugins_call_init (server *srv)
handler_t plugins_call_set_defaults (server *srv)
handler_t plugins_call_cleanup (server *srv)
int config_insert_values_global (server *srv, array *ca, const config_values_t *cv, config_scope_type_t scope)
int config_insert_values_internal (server *srv, array *ca, const config_values_t *cv, config_scope_type_t scope)
int config_check_cond (server *srv, connection *con, data_config *dc)
int config_append_cond_match_buffer (connection *con, data_config *dc, buffer *buf, int n)
Macro Definition Documentation
#define CONNECTION_FUNC(x) static handler_t x(server *srv, connection *con, void *p_d)
#define FREE_FUNC SERVER_FUNC
#define INIT_FUNC(x) static void *x(void)
#define PHYSICALPATH_FUNC CONNECTION_FUNC
#define PLUGIN_DATA size_t id
#define REQUESTDONE_FUNC CONNECTION_FUNC
#define SERVER_FUNC(x) static handler_t x(server *srv, void *p_d)
#define SETDEFAULTS_FUNC SERVER_FUNC
#define SIGHUP_FUNC SERVER_FUNC
#define SUBREQUEST_FUNC CONNECTION_FUNC
#define TRIGGER_FUNC SERVER_FUNC
#define URIHANDLER_FUNC CONNECTION_FUNC
Function Documentation
int config_append_cond_match_buffer (connection * con, data_config * dc, buffer * buf, int n)
References buffer_append_string_len(), cond_cache_t::comp_value, connection::cond_cache, data_config::context_ndx, cond_cache_t::matches, cond_cache_t::patterncount, and buffer::ptr.
Referenced by mod_redirect_uri_handler().
int config_check_cond (server * srv, connection * con, data_config * dc)
References COND_RESULT_TRUE, connection::conf, config_check_cond_cached(), specific_config::log_condition_handling, and log_error_write().
Referenced by config_patch_connection(), fcgi_patch_connection(), mod_access_patch_connection(), mod_accesslog_patch_connection(), mod_alias_patch_connection(), mod_auth_patch_connection(), mod_authn_file_patch_connection(), mod_authn_gssapi_patch_connection(), mod_authn_ldap_patch_connection(), mod_authn_mysql_patch_connection(), mod_cgi_patch_connection(), mod_cml_patch_connection(), mod_compress_patch_connection(), mod_deflate_patch_connection(), mod_dirlisting_patch_connection(), mod_evasive_patch_connection(), mod_evhost_patch_connection(), mod_expire_patch_connection(), mod_extforward_patch_connection(), mod_flv_streaming_patch_connection(), mod_geoip_patch_connection(), mod_indexfile_patch_connection(), mod_magnet_patch_connection(), mod_mysql_vhost_patch_connection(), mod_proxy_patch_connection(), mod_rrd_patch_connection(), mod_secdownload_patch_connection(), mod_setenv_patch_connection(), mod_simple_vhost_patch_connection(), mod_skeleton_patch_connection(), mod_ssi_patch_connection(), mod_staticfile_patch_connection(), mod_status_patch_connection(), mod_trigger_b4_dl_patch_connection(), mod_uploadprogress_patch_connection(), mod_userdir_patch_connection(), mod_usertrack_patch_connection(), mod_webdav_patch_connection(), and scgi_patch_connection().
int config_insert_values_global (server * srv, array * ca, const config_values_t * cv, config_scope_type_t scope)
int config_insert_values_internal (server * srv, array * ca, const config_values_t * cv, config_scope_type_t scope)
handler_t plugins_call_cleanup (server * srv)
Referenced by plugins_free().
handler_t plugins_call_connection_reset (server * srv, connection * con)
Referenced by connection_reset(), and connection_state_machine().
handler_t plugins_call_handle_connection_close (server * srv, connection * con)
Referenced by connection_handle_shutdown().
handler_t plugins_call_handle_docroot (server * srv, connection * con)
Referenced by http_response_prepare().
handler_t plugins_call_handle_physical (server * srv, connection * con)
Referenced by http_response_prepare().
handler_t plugins_call_handle_request_done (server * srv, connection * con)
Referenced by connection_handle_response_end_state().
handler_t plugins_call_handle_response_start (server * srv, connection * con)
Referenced by connection_handle_write_prepare().
handler_t plugins_call_handle_sighup (server * srv)
Referenced by main().
handler_t plugins_call_handle_subrequest (server * srv, connection * con)
Referenced by connection_state_machine(), and http_response_prepare().
handler_t plugins_call_handle_subrequest_start (server * srv, connection * con)
Referenced by http_response_prepare().
handler_t plugins_call_handle_trigger (server * srv)
Referenced by main().
handler_t plugins_call_handle_uri_clean (server * srv, connection * con)
Referenced by http_response_prepare().
handler_t plugins_call_handle_uri_raw (server * srv, connection * con)
Referenced by http_response_prepare().
handler_t plugins_call_init (server * srv)
plugins that use
server *srv
void *p_d (plugin_data *)
call init function of all plugins to init the plugin-internals
added each plugin that supports has callback to the corresponding slot
is only called once.
References connection_reset(), plugin::data, force_assert, HANDLER_ERROR, HANDLER_GO_ON, plugin::init, log_error_write(), plugin::name, PLUGIN_FUNC_HANDLE_TRIGGER, PLUGIN_FUNC_HANDLE_URI_CLEAN, PLUGIN_FUNC_SIZEOF, server::plugin_slots, PLUGIN_TO_SLOT, server::plugins, ps, buffer_plugin::ptr, buffer_plugin::used, and plugin::version.
Referenced by main().
handler_t plugins_call_set_defaults (server * srv)
Referenced by main().
void plugins_free (server * srv)
References plugin_free(), PLUGIN_FUNC_SIZEOF, server::plugin_slots, server::plugins, plugins_call_cleanup(), buffer_plugin::ptr, and buffer_plugin::used.
Referenced by main().
int plugins_load (server * srv)
References buffer_append_string(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_is_equal(), buffer_reset(), CONST_STR_LEN, array::data, plugin::lib, log_error_write(), server_config::modules, server_config::modules_dir, plugin_free(), plugin_init(), plugins_register(), buffer::ptr, server::srvconf, server::tmp_buf, array::used, and data_string::value.