proc_open.h File Reference
#include `first.h`
*
#include `buffer.h`
*
Classes
struct pipe_t
struct proc_handler_t
Typedefs
typedef int descriptor_t
typedef pid_t proc_pid_t
Functions
int proc_close (proc_handler_t *ht)
int proc_open (proc_handler_t *ht, const char *command)
int proc_open_buffer (const char *command, buffer *in, buffer *out, buffer *err)
Typedef Documentation
typedef int descriptor_t
typedef pid_t proc_pid_t
Function Documentation
int proc_close (proc_handler_t * ht)
References proc_handler_t::child, and proc_close_pipes().
Referenced by proc_open(), and proc_open_buffer().
int proc_open (proc_handler_t * ht, const char * command)
References proc_handler_t::child, proc_close(), proc_close_childs(), proc_close_parents(), proc_open_pipes(), and SHELLENV.
Referenced by proc_open_buffer().
int proc_open_buffer (const char * command, buffer * in, buffer * out, buffer * err)
References buffer_free(), buffer_init(), buffer_string_is_empty(), CONST_BUF_LEN, proc_handler_t::err, pipe_t::fd, proc_handler_t::in, proc_handler_t::out, pipe_close(), proc_close(), proc_open(), and proc_read_fd_to_buffer().
Referenced by config_parse_cmd().