proc_open.c File Reference
#include `first.h`
*
#include `proc_open.h`
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <ctype.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <sys/wait.h>
*
#include <unistd.h>
*
Macros
#define SHELLENV `SHELL`
#define SECURITY_DC
#define SECURITY_CC
#define close_descriptor(fd) close(fd)
Functions
static void pipe_close_parent (pipe_t *p)
static void pipe_close_child (pipe_t *p)
static void pipe_close (pipe_t *p)
static int pipe_open (pipe_t *p, int fd SECURITY_DC)
static int proc_open_pipes (proc_handler_t *proc SECURITY_DC)
static void proc_close_pipes (proc_handler_t *proc)
static void proc_close_parents (proc_handler_t *proc)
static void proc_close_childs (proc_handler_t *proc)
int proc_close (proc_handler_t *proc)
int proc_open (proc_handler_t *proc, const char *command)
static void proc_read_fd_to_buffer (int fd, buffer *b)
int proc_open_buffer (const char *command, buffer *in, buffer *out, buffer *err)
Macro Definition Documentation
#define close_descriptor(fd) close(fd)
Referenced by pipe_close(), pipe_close_child(), and pipe_close_parent().
#define SECURITY_CC
Referenced by proc_open_pipes().
#define SECURITY_DC
#define SHELLENV `SHELL`
Referenced by proc_open().
Function Documentation
static void pipe_close (pipe_t * p) [static]
References pipe_t::child, close_descriptor, pipe_t::fd, and pipe_t::parent.
Referenced by proc_close_pipes(), and proc_open_buffer().
static void pipe_close_child (pipe_t * p) [static]
References pipe_t::child, close_descriptor, pipe_t::fd, and pipe_t::parent.
Referenced by proc_close_childs().
static void pipe_close_parent (pipe_t * p) [static]
References pipe_t::child, close_descriptor, pipe_t::fd, and pipe_t::parent.
Referenced by proc_close_parents().
static int pipe_open (pipe_t * p, int fd SECURITY_DC) [static]
References pipe_t::child, pipe_t::fd, and pipe_t::parent.
Referenced by proc_open_pipes().
int proc_close (proc_handler_t * proc)
References proc_handler_t::child, and proc_close_pipes().
Referenced by proc_open(), and proc_open_buffer().
static void proc_close_childs (proc_handler_t * proc) [static]
References proc_handler_t::err, proc_handler_t::in, proc_handler_t::out, and pipe_close_child().
Referenced by proc_open().
static void proc_close_parents (proc_handler_t * proc) [static]
References proc_handler_t::err, proc_handler_t::in, proc_handler_t::out, and pipe_close_parent().
Referenced by proc_open().
static void proc_close_pipes (proc_handler_t * proc) [static]
References proc_handler_t::err, proc_handler_t::in, proc_handler_t::out, and pipe_close().
Referenced by proc_close().
int proc_open (proc_handler_t * proc, const char * command)
References proc_handler_t::child, proc_close(), proc_close_childs(), proc_close_parents(), proc_open_pipes(), and SHELLENV.
Referenced by proc_open_buffer().
int proc_open_buffer (const char * command, buffer * in, buffer * out, buffer * err)
References buffer_free(), buffer_init(), buffer_string_is_empty(), CONST_BUF_LEN, proc_handler_t::err, pipe_t::fd, proc_handler_t::in, proc_handler_t::out, pipe_close(), proc_close(), proc_open(), and proc_read_fd_to_buffer().
Referenced by config_parse_cmd().
static int proc_open_pipes (proc_handler_t *proc SECURITY_DC) [static]
References pipe_open(), and SECURITY_CC.
Referenced by proc_open().
static void proc_read_fd_to_buffer (int fd, buffer * b) [static]
References buffer_commit(), buffer_string_length(), buffer_string_prepare_append(), buffer_string_space(), and buffer::ptr.
Referenced by proc_open_buffer().