rand.h File Reference
#include `first.h`
*
Functions
int li_rand_pseudo_bytes (void)
void li_rand_reseed (void)
int li_rand_bytes (unsigned char *buf, int num)
void li_rand_cleanup (void)
Function Documentation
int li_rand_bytes (unsigned char * buf, int num)
References li_rand_device_bytes(), and li_rand_pseudo_bytes().
void li_rand_cleanup (void)
References safe_memclear(), and xsubi.
Referenced by server_free().
int li_rand_pseudo_bytes (void)
References li_rand_init(), li_rand_inited, and xsubi.
Referenced by li_rand_bytes(), mod_auth_send_401_unauthorized_digest(), and URIHANDLER_FUNC().
void li_rand_reseed (void)
References li_rand_init(), and li_rand_inited.
Referenced by main(), and server_init().