rand.c File Reference
#include `first.h`
*
#include `rand.h`
*
#include `base.h`
*
#include `fdevent.h`
*
#include `safe_memclear.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <time.h>
*
#include <unistd.h>
*
Functions
static int li_getentropy (void *buf, size_t buflen)
static int li_rand_device_bytes (unsigned char *buf, int num)
static void li_rand_init (void)
void li_rand_reseed (void)
int li_rand_pseudo_bytes (void)
int li_rand_bytes (unsigned char *buf, int num)
void li_rand_cleanup (void)
Variables
static int li_rand_inited
static unsigned short xsubi [3]
Function Documentation
static int li_getentropy (void * buf, size_t buflen) [static]
References UNUSED.
Referenced by li_rand_device_bytes().
int li_rand_bytes (unsigned char * buf, int num)
References li_rand_device_bytes(), and li_rand_pseudo_bytes().
void li_rand_cleanup (void)
References safe_memclear(), and xsubi.
Referenced by server_free().
static int li_rand_device_bytes (unsigned char * buf, int num) [static]
References fdevent_open_cloexec(), and li_getentropy().
Referenced by li_rand_bytes(), and li_rand_init().
static void li_rand_init (void) [static]
References li_rand_device_bytes(), li_rand_inited, and xsubi.
Referenced by li_rand_pseudo_bytes(), and li_rand_reseed().
int li_rand_pseudo_bytes (void)
References li_rand_init(), li_rand_inited, and xsubi.
Referenced by li_rand_bytes(), mod_auth_send_401_unauthorized_digest(), and URIHANDLER_FUNC().
void li_rand_reseed (void)
References li_rand_init(), and li_rand_inited.
Referenced by main(), and server_init().
Variable Documentation
int li_rand_inited [static]
Referenced by li_rand_init(), li_rand_pseudo_bytes(), and li_rand_reseed().
unsigned short xsubi[3] [static]
Referenced by li_rand_cleanup(), li_rand_init(), and li_rand_pseudo_bytes().