request.c File Reference
#include `first.h`
*
#include `request.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include <sys/stat.h>
*
#include <limits.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <stdio.h>
*
#include <ctype.h>
*
Functions
static int request_check_hostname (buffer *host)
int http_request_host_normalize (buffer *b)
static int http_request_split_value (array *vals, buffer *b)
static int request_uri_is_valid_char (unsigned char c)
int http_request_parse (server *srv, connection *con)
int http_request_header_finished (server *srv, connection *con)
Function Documentation
int http_request_header_finished (server * srv, connection * con)
References buffer_string_length(), CONST_STR_LEN, buffer::ptr, request::request, connection::request, and UNUSED.
int http_request_host_normalize (buffer * b)
References buffer_append_int(), buffer_append_string_len(), buffer_copy_string(), buffer_string_length(), buffer_string_set_length(), CONST_STR_LEN, light_isdigit(), and buffer::ptr.
Referenced by configparser_remoteip_normalize_compat(), http_request_parse(), and yy_reduce().
int http_request_parse (server * srv, connection * con)
1*<any char=`` except=`` ctls=`` or=`` separators>=``> CTLs == 0-31 + 127, CHAR = 7-bit ascii (0..127)
we use a evil hack to handle the line-folding
As array_insert_unique() deletes 'ds' in the case of a duplicate ds points somewhere and we get a evil crash. As a solution we keep the old `key` and get the current value from the hash and append us
References specific_config::allow_http11, array_get_element(), array_get_unused_element(), array_insert_unique(), array_reset(), buffer_append_string(), buffer_caseless_compare(), buffer_copy_buffer(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), connection::conf, CONST_BUF_LEN, CONST_STR_LEN, request::content_length, array::data, data_string_init(), connection::fd, get_http_method_key(), connection::header_len, request::headers, request::http_content_type, request::http_host, request::http_if_modified_since, request::http_if_none_match, request::http_method, HTTP_METHOD_GET, HTTP_METHOD_HEAD, HTTP_METHOD_POST, HTTP_METHOD_UNSET, HTTP_PARSEOPT_HEADER_STRICT, HTTP_PARSEOPT_HOST_NORMALIZE, HTTP_PARSEOPT_HOST_STRICT, specific_config::http_parseopts, request::http_range, http_request_host_normalize(), http_request_split_value(), connection::http_status, request::http_version, HTTP_VERSION_1_0, HTTP_VERSION_1_1, response::keep_alive, connection::keep_alive, log_error_write(), specific_config::log_request_header, server_config::log_request_header_on_error, request::orig_uri, connection::parse_request, buffer::ptr, server_config::reject_expect_100_with_417, request::request, connection::request, request_check_hostname(), connection::request_count, request::request_line, request_uri_is_valid_char(), connection::response, server::split_vals, server::srvconf, TYPE_STRING, request::uri, array::used, and data_string::value.
Referenced by connection_state_machine().
static int http_request_split_value (array * vals, buffer * b) [static]
References array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), buffer_string_is_empty(), buffer_string_length(), current, data_string_init(), buffer::ptr, TYPE_STRING, and data_string::value.
Referenced by http_request_parse().
static int request_check_hostname (buffer * host) [static]
References buffer_string_length(), buffer_string_set_length(), light_isalnum(), light_isdigit(), light_isxdigit(), and buffer::ptr.
Referenced by http_request_parse().
static int request_uri_is_valid_char (unsigned char c) [static]
Referenced by http_request_parse().