response.h File Reference
#include `first.h`
*
#include `server.h`
*
#include <time.h>
*
Classes
struct http_cgi_opts_t
Typedefs
typedef struct http_cgi_opts_t http_cgi_opts
typedef int(* http_cgi_header_append_cb)(void *vdata, const char *k, size_t klen, const char *v, size_t vlen)
Functions
int http_response_parse (server *srv, connection *con)
int http_response_write_header (server *srv, connection *con)
int response_header_insert (server *srv, connection *con, const char *key, size_t keylen, const char *value, size_t vallen)
int response_header_overwrite (server *srv, connection *con, const char *key, size_t keylen, const char *value, size_t vallen)
int response_header_append (server *srv, connection *con, const char *key, size_t keylen, const char *value, size_t vallen)
int http_cgi_headers (server *srv, connection *con, http_cgi_opts *opts, http_cgi_header_append_cb cb, void *vdata)
handler_t http_response_prepare (server *srv, connection *con)
int http_response_redirect_to_directory (server *srv, connection *con)
int http_response_handle_cachable (server *srv, connection *con, buffer *mtime)
void http_response_send_file (server *srv, connection *con, buffer *path)
void http_response_xsendfile (server *srv, connection *con, buffer *path, const array *xdocroot)
void http_response_backend_done (server *srv, connection *con)
void http_response_backend_error (server *srv, connection *con)
buffer * strftime_cache_get (server *srv, time_t last_mod)
Typedef Documentation
typedef int(* http_cgi_header_append_cb)(void *vdata, const char *k, size_t klen, const char *v, size_t vlen)
typedef struct http_cgi_opts_t http_cgi_opts
Function Documentation
int http_cgi_headers (server * srv, connection * con, http_cgi_opts * opts, http_cgi_header_append_cb cb, void * vdata)
/app1/index/list
stripping /app1 or /app1/ should lead to
/index/list
References server_socket::addr, http_cgi_opts_t::authorizer, physical::basedir, http_cgi_opts_t::break_scriptfilename_for_php, buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string_encoded_cgi_varnames(), buffer_is_empty(), buffer_is_equal(), buffer_is_equal_caseless_string(), buffer_string_is_empty(), buffer_string_length(), connection::conf, CONST_BUF_LEN, CONST_STR_LEN, request::content_length, array::data, http_cgi_opts_t::docroot, connection::dst_addr, connection::dst_addr_buf, connection::environment, connection::error_handler_saved_status, connection::fd, force_assert, get_http_method_name(), get_http_version_name(), request::headers, request::http_method, request::http_version, sock_addr::ipv4, LI_ITOSTRING_LENGTH, li_itostrn(), li_utostrn(), request::orig_uri, request_uri::path, physical::path, request::pathinfo, connection::physical, sock_addr::plain, buffer::ptr, request_uri::query, connection::request, request_uri::scheme, connection::server_name, specific_config::server_tag, connection::srv_socket, http_cgi_opts_t::strip_request_uri, server::tmp_buf, request::uri, connection::uri, array::used, and data_string::value.
Referenced by build_ssi_cgi_vars(), cgi_create_env(), fcgi_create_env(), and scgi_create_env().
void http_response_backend_done (server * srv, connection * con)
References CON_STATE_HANDLE_REQUEST, CON_STATE_READ_POST, CON_STATE_WRITE, DIRECT, connection::file_finished, connection::file_started, http_chunk_close(), connection::http_status, connection::mode, and connection::state.
Referenced by cgi_connection_close(), fcgi_connection_close(), proxy_connection_close(), and scgi_connection_close().
void http_response_backend_error (server * srv, connection * con)
References DIRECT, connection::file_finished, connection::file_started, connection::keep_alive, connection::mode, and UNUSED.
Referenced by fcgi_handle_fdevent(), fcgi_recv_response(), proxy_handle_fdevent(), proxy_recv_response(), scgi_handle_fdevent(), and scgi_recv_response().
int http_response_handle_cachable (server * srv, connection * con, buffer * mtime)
parsing failed, let's get out of here
References DIRECT, physical::etag, etag_is_equal(), HANDLER_FINISHED, HANDLER_GO_ON, request::http_if_modified_since, request::http_if_none_match, request::http_method, HTTP_METHOD_GET, HTTP_METHOD_HEAD, connection::http_status, connection::mode, connection::physical, buffer::ptr, connection::request, and UNUSED.
Referenced by cache_parse_lua(), http_response_send_file(), mod_ssi_handle_request(), and PHYSICALPATH_FUNC().
int http_response_parse (server * srv, connection * con)
handler_t http_response_prepare (server * srv, connection * con)
prepare strings
uri.path_raw
uri.path (secure)
uri.query
Name according to RFC 2396
scheme
authority
path
query
(scheme)://(authority)(path)?(query)#fragment
their might be a fragment which has to be cut away
extract query string from request.uri
call plugins
based on the raw URL
call plugins
based on the clean URL
create physical filename -> physical.path = docroot + rel_path
References specific_config::allow_http11, request_uri::authority, physical::basedir, buffer_append_slash(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), buffer_is_empty(), buffer_path_simplify(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), buffer_to_lower(), buffer_urldecode_path(), chunkqueue_reset(), COMP_HTTP_COOKIE, COMP_HTTP_HOST, COMP_HTTP_LANGUAGE, COMP_HTTP_QUERY_STRING, COMP_HTTP_REFERER, COMP_HTTP_REMOTE_IP, COMP_HTTP_REQUEST_METHOD, COMP_HTTP_SCHEME, COMP_HTTP_URL, COMP_HTTP_USER_AGENT, COMP_SERVER_SOCKET, connection::conditional_is_valid, connection::conf, config_cond_cache_reset(), config_patch_connection(), config_setup_connection(), CONST_STR_LEN, request::content_length, DIRECT, physical::doc_root, specific_config::document_root, connection::file_finished, specific_config::follow_symlink, specific_config::force_lowercase_filenames, HANDLER_COMEBACK, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, request::http_host, request::http_method, HTTP_METHOD_OPTIONS, http_response_redirect_to_directory(), connection::http_status, request::http_version, HTTP_VERSION_1_0, server_socket::is_ssl, connection::keep_alive, specific_config::log_condition_handling, log_error_write(), specific_config::log_file_not_found, specific_config::log_request_handling, specific_config::max_request_size, connection::mode, request_uri::path, physical::path, request_uri::path_raw, request::pathinfo, connection::physical, plugins_call_handle_docroot(), plugins_call_handle_physical(), plugins_call_handle_subrequest(), plugins_call_handle_subrequest_start(), plugins_call_handle_uri_clean(), plugins_call_handle_uri_raw(), buffer::ptr, request_uri::query, physical::rel_path, connection::request, response_header_insert(), request_uri::scheme, connection::server_name, connection::srv_socket, specific_config::ssl_verifyclient, stat_cache_entry::st, stat_cache_get_entry(), server::tmp_buf, request::uri, connection::uri, buffer::used, and connection::write_queue.
Referenced by connection_state_machine().
int http_response_redirect_to_directory (server * srv, connection * con)
References request_uri::authority, buffer_append_int(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal_caseless_string(), buffer_string_is_empty(), CONST_BUF_LEN, CONST_STR_LEN, ENCODING_REL_URI, connection::fd, connection::file_finished, connection::http_status, sock_addr::ipv4, log_error_write(), request_uri::path, sock_addr::plain, server_config::port, request_uri::query, response_header_insert(), request_uri::scheme, server::srvconf, and connection::uri.
Referenced by http_response_prepare(), SUBREQUEST_FUNC(), and URIHANDLER_FUNC().
void http_response_send_file (server * srv, connection * con, buffer * path)
client wants a ETag
we don't have a Last-Modified and can match the If-Range:
sending all
References array_get_element(), buffer_is_equal(), buffer_string_is_empty(), connection::conf, CONST_BUF_LEN, CONST_STR_LEN, stat_cache_entry::content_type, physical::etag, stat_cache_entry::etag, connection::etag_flags, etag_mutate(), connection::file_finished, specific_config::follow_symlink, HANDLER_ERROR, HANDLER_FINISHED, request::headers, response::headers, http_chunk_append_file(), request::http_range, http_response_handle_cachable(), http_response_parse_range(), connection::http_status, log_error_write(), specific_config::log_file_not_found, specific_config::log_request_handling, stat_cache_entry::name, request_uri::path, connection::physical, buffer::ptr, specific_config::range_requests, connection::request, connection::response, response_header_overwrite(), stat_cache_entry::st, stat_cache_get_entry(), strftime_cache_get(), connection::uri, and data_string::value.
Referenced by http_response_xsendfile(), and URIHANDLER_FUNC().
int http_response_write_header (server * srv, connection * con)
References buffer_append_int(), buffer_append_strftime(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_copy(), connection::bytes_header, chunkqueue_prepend_buffer(), connection::conf, CONST_BUF_LEN, CONST_STR_LEN, server::cur_ts, array::data, ENCODING_HTTP_HEADER, get_http_status_name(), response::headers, connection::http_status, request::http_version, HTTP_VERSION_1_1, connection::keep_alive, connection::keep_alive_idle, server::last_generated_date_ts, log_error_write(), specific_config::log_response_header, specific_config::max_keep_alive_idle, specific_config::max_keep_alive_requests, connection::request, connection::request_count, connection::response, response_header_overwrite(), specific_config::server_tag, response::transfer_encoding, server::ts_date_str, array::used, data_string::value, and connection::write_queue.
Referenced by connection_handle_write_prepare().
void http_response_xsendfile (server * srv, connection * con, buffer * path, const array * xdocroot)
References array_get_element(), buffer_path_simplify(), buffer_reset(), buffer_string_length(), buffer_to_lower(), buffer_urldecode_path(), connection::conf, response::content_length, array::data, DIRECT, connection::file_started, specific_config::force_lowercase_filenames, response::headers, HTTP_CONTENT_LENGTH, http_response_send_file(), connection::http_status, log_error_write(), connection::mode, connection::parsed_response, buffer::ptr, connection::response, array::used, and data_string::value.
Referenced by cgi_demux_response(), fcgi_demux_response(), and scgi_demux_response().
int response_header_append (server * srv, connection * con, const char * key, size_t keylen, const char * value, size_t vallen)
References array_get_element(), buffer_append_string_len(), CONST_STR_LEN, response::headers, connection::response, response_header_insert(), UNUSED, and data_string::value.
Referenced by CONNECTION_FUNC().
int response_header_insert (server * srv, connection * con, const char * key, size_t keylen, const char * value, size_t vallen)
References array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), data_response_init(), response::headers, connection::response, TYPE_STRING, UNUSED, and data_string::value.
Referenced by CONNECTION_FUNC(), connection_handle_errdoc_init(), connection_handle_write_prepare(), http_response_parse_range(), http_response_prepare(), http_response_redirect_to_directory(), mod_auth_send_401_unauthorized_basic(), mod_auth_send_401_unauthorized_digest(), mod_authn_gssapi_send_401_unauthorized_basic(), mod_authn_gssapi_send_401_unauthorized_negotiate(), mod_redirect_uri_handler(), PHYSICALPATH_FUNC(), response_header_append(), response_header_overwrite(), and URIHANDLER_FUNC().
int response_header_overwrite (server * srv, connection * con, const char * key, size_t keylen, const char * value, size_t vallen)
References array_get_element(), buffer_copy_string(), response::headers, connection::response, response_header_insert(), UNUSED, and data_string::value.
Referenced by cache_parse_lua(), CONNECTION_FUNC(), connection_handle_write_prepare(), http_list_directory(), http_response_parse_range(), http_response_send_file(), http_response_write_header(), magnet_copy_response_header(), mod_ssi_handle_request(), mod_status_handle_server_config(), mod_status_handle_server_statistics(), mod_status_handle_server_status_html(), mod_status_handle_server_status_json(), mod_status_handle_server_status_text(), PHYSICALPATH_FUNC(), SUBREQUEST_FUNC(), and URIHANDLER_FUNC().
buffer* strftime_cache_get (server * srv, time_t last_mod)
References buffer_append_strftime(), buffer_string_prepare_copy(), FILE_CACHE_MAX, mtime_cache_type::mtime, server::mtime_cache, and mtime_cache_type::str.
Referenced by http_response_send_file(), mod_ssi_handle_request(), and PHYSICALPATH_FUNC().