response.c File Reference
#include `first.h`
*
#include `response.h`
*
#include `keyvalue.h`
*
#include `log.h`
*
#include `stat_cache.h`
*
#include `chunk.h`
*
#include `configfile.h`
*
#include `plugin.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <limits.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <time.h>
*
#include <unistd.h>
*
#include <ctype.h>
*
#include <assert.h>
*
#include <stdio.h>
*
#include `sys-socket.h`
*
Functions
int http_response_write_header (server *srv, connection *con)
handler_t http_response_prepare (server *srv, connection *con)
Function Documentation
handler_t http_response_prepare (server * srv, connection * con)
prepare strings
uri.path_raw
uri.path (secure)
uri.query
Name according to RFC 2396
scheme
authority
path
query
(scheme)://(authority)(path)?(query)#fragment
their might be a fragment which has to be cut away
extract query string from request.uri
call plugins
based on the raw URL
call plugins
based on the clean URL
create physical filename -> physical.path = docroot + rel_path
References specific_config::allow_http11, request_uri::authority, physical::basedir, buffer_append_slash(), buffer_append_string_buffer(), buffer_append_string_len(), buffer_copy_buffer(), buffer_copy_string(), buffer_copy_string_len(), buffer_is_empty(), buffer_path_simplify(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), buffer_to_lower(), buffer_urldecode_path(), chunkqueue_reset(), COMP_HTTP_COOKIE, COMP_HTTP_HOST, COMP_HTTP_LANGUAGE, COMP_HTTP_QUERY_STRING, COMP_HTTP_REFERER, COMP_HTTP_REMOTE_IP, COMP_HTTP_REQUEST_METHOD, COMP_HTTP_SCHEME, COMP_HTTP_URL, COMP_HTTP_USER_AGENT, COMP_SERVER_SOCKET, connection::conditional_is_valid, connection::conf, config_cond_cache_reset(), config_patch_connection(), config_setup_connection(), CONST_STR_LEN, request::content_length, DIRECT, physical::doc_root, specific_config::document_root, connection::file_finished, specific_config::follow_symlink, specific_config::force_lowercase_filenames, HANDLER_COMEBACK, HANDLER_ERROR, HANDLER_FINISHED, HANDLER_GO_ON, HANDLER_WAIT_FOR_EVENT, request::http_host, request::http_method, HTTP_METHOD_OPTIONS, http_response_redirect_to_directory(), connection::http_status, request::http_version, HTTP_VERSION_1_0, server_socket::is_ssl, connection::keep_alive, specific_config::log_condition_handling, log_error_write(), specific_config::log_file_not_found, specific_config::log_request_handling, specific_config::max_request_size, connection::mode, request_uri::path, physical::path, request_uri::path_raw, request::pathinfo, connection::physical, plugins_call_handle_docroot(), plugins_call_handle_physical(), plugins_call_handle_subrequest(), plugins_call_handle_subrequest_start(), plugins_call_handle_uri_clean(), plugins_call_handle_uri_raw(), buffer::ptr, request_uri::query, physical::rel_path, connection::request, response_header_insert(), request_uri::scheme, connection::server_name, connection::srv_socket, specific_config::ssl_verifyclient, stat_cache_entry::st, stat_cache_get_entry(), server::tmp_buf, request::uri, connection::uri, buffer::used, and connection::write_queue.
Referenced by connection_state_machine().
int http_response_write_header (server * srv, connection * con)
References buffer_append_int(), buffer_append_strftime(), buffer_append_string(), buffer_append_string_buffer(), buffer_append_string_encoded(), buffer_append_string_len(), buffer_copy_string_len(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_string_is_empty(), buffer_string_length(), buffer_string_prepare_copy(), connection::bytes_header, chunkqueue_prepend_buffer(), connection::conf, CONST_BUF_LEN, CONST_STR_LEN, server::cur_ts, array::data, ENCODING_HTTP_HEADER, get_http_status_name(), response::headers, connection::http_status, request::http_version, HTTP_VERSION_1_1, connection::keep_alive, connection::keep_alive_idle, server::last_generated_date_ts, log_error_write(), specific_config::log_response_header, specific_config::max_keep_alive_idle, specific_config::max_keep_alive_requests, connection::request, connection::request_count, connection::response, response_header_overwrite(), specific_config::server_tag, response::transfer_encoding, server::ts_date_str, array::used, data_string::value, and connection::write_queue.
Referenced by connection_handle_write_prepare().