safe_memclear.h File Reference
#include `first.h`
*
#include <sys/types.h>
*
Functions
void safe_memclear (void *s, size_t n)
Function Documentation
void safe_memclear (void * s, size_t n)
References safe_memset().
Referenced by apr_md5_encode(), and li_rand_cleanup().