safe_memclear.c File Reference
#include `first.h`
*
#include `settings.h`
*
#include `safe_memclear.h`
*
#include <string.h>
*
Functions
static void * safe_memset (void *s, int c, size_t n)
void safe_memclear (void *s, size_t n)
Function Documentation
void safe_memclear (void * s, size_t n)
References safe_memset().
Referenced by apr_md5_encode(), and li_rand_cleanup().
static void* safe_memset (void * s, int c, size_t n) [static]
Referenced by safe_memclear().