server.h File Reference
#include `first.h`
*
#include `base.h`
*
Functions
int config_read (server *srv, const char *fn)
int config_set_defaults (server *srv)
Function Documentation
int config_read (server * srv, const char * fn)
References config_t::all_configs, array_insert_unique(), config_t::basedir, buffer_commit(), buffer_copy_string_len(), buffer_free(), buffer_init_string(), buffer_string_prepare_copy(), server::config_context, config_insert(), config_parse_file_stream(), config_t::configs_stack, CONST_STR_LEN, context_free(), context_init(), data_config::context_ndx, config_t::current, data_config_init(), data_integer_init(), data_string_init(), force_assert, config_t::ok, buffer::ptr, buffer::size, array::used, data_string::value, data_config::value, and data_integer::value.
Referenced by main().
int config_set_defaults (server * srv)
References array_insert_unique(), buffer_append_slash(), buffer_append_string_buffer(), buffer_copy_buffer(), buffer_copy_string(), buffer_is_equal(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), buffer_to_lower(), buffer_to_upper(), server_config::changeroot, chunkqueue_set_tempdirs_default(), server::config_storage, array::data, data_string_init(), specific_config::document_root, server_config::event_handler, server::event_handler, FDEVENT_HANDLER_FREEBSD_KQUEUE, FDEVENT_HANDLER_LIBEV, FDEVENT_HANDLER_LINUX_SYSEPOLL, FDEVENT_HANDLER_POLL, FDEVENT_HANDLER_SELECT, FDEVENT_HANDLER_SOLARIS_DEVPOLL, FDEVENT_HANDLER_SOLARIS_PORT, FDEVENT_HANDLER_UNSET, specific_config::force_lowercase_filenames, log_error_write(), server_config::port, buffer::ptr, server::srvconf, specific_config::ssl_enabled, specific_config::ssl_pemfile, server::tmp_buf, server_config::upload_temp_file_size, server_config::upload_tempdirs, array::used, and data_string::value.
Referenced by main().