server.c File Reference
#include `first.h`
*
#include `server.h`
*
#include `buffer.h`
*
#include `network.h`
*
#include `log.h`
*
#include `keyvalue.h`
*
#include `rand.h`
*
#include `response.h`
*
#include `request.h`
*
#include `chunk.h`
*
#include `http_chunk.h`
*
#include `fdevent.h`
*
#include `connections.h`
*
#include `stat_cache.h`
*
#include `plugin.h`
*
#include `joblist.h`
*
#include `network_backends.h`
*
#include `version.h`
*
#include <sys/types.h>
*
#include <sys/time.h>
*
#include <sys/stat.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <fcntl.h>
*
#include <unistd.h>
*
#include <stdlib.h>
*
#include <time.h>
*
#include <signal.h>
*
#include <assert.h>
*
#include <locale.h>
*
#include <stdio.h>
*
Macros
#define CLEAN(x) srv->x = buffer_init();
#define CLEAN(x) srv->x = array_init();
#define CLEAN(x) buffer_free(srv->x);
#define CLEAN(x) array_free(srv->x);
#define TEXT_SSL
#define TEXT_SSL
Functions
static server * server_init (void)
static void server_free (server *srv)
static void remove_pid_file (server *srv, int *pid_fd)
static server_socket * server_oneshot_getsock (server *srv, sock_addr *cnt_addr)
static int server_oneshot_init (server *srv, int fd)
static void show_version (void)
static void show_features (void)
static void show_help (void)
int main (int argc, char **argv)
Variables
static int oneshot_fd = 0
static volatile sig_atomic_t srv_shutdown = 0
static volatile sig_atomic_t graceful_shutdown = 0
static volatile sig_atomic_t handle_sig_alarm = 1
static volatile sig_atomic_t handle_sig_hup = 0
static volatile sig_atomic_t forwarded_sig_hup = 0
Macro Definition Documentation
#define CLEAN(x) srv->x = buffer_init();
Referenced by server_free(), and server_init().
#define CLEAN(x) srv->x = array_init();
#define CLEAN(x) buffer_free(srv->x);
#define CLEAN(x) array_free(srv->x);
#define TEXT_SSL
Referenced by show_help(), and show_version().
#define TEXT_SSL
Function Documentation
int main (int argc, char ** argv)
check all connections for timeouts
References array_get_element(), buffer_append_string_len(), buffer_copy_int(), buffer_copy_string(), buffer_reset(), buffer_string_is_empty(), connection::bytes_written, connection::bytes_written_cur_second, server_config::changeroot, connection::close_timeout_ts, CON_STATE_CLOSE, CON_STATE_ERROR, CON_STATE_READ, CON_STATE_WRITE, connection::conf, server::config_context, server::config_deprecated, config_read(), config_set_defaults(), server::config_storage, server::config_touched, server::config_unsupported, connection_get_state(), connection_set_state(), connection::connection_start, connection_state_machine(), connections_free(), server::conns, CONST_BUF_LEN, CONST_STR_LEN, server::cur_fds, server::cur_ts, array::data, specific_config::document_root, server_config::dont_daemonize, connection::dst_addr_buf, server_config::enable_cores, server::ev, server::event_handler, connection::fd, server_socket::fd, fd_close_on_exec(), server_socket::fde_ndx, fdevent_event_del(), fdevent_event_get_fd(), fdevent_event_get_interest, fdevent_event_get_revent(), fdevent_event_next_fdndx(), fdevent_event_set(), fdevent_fcntl_set_nb_cloexec_sock(), fdevent_get_context(), fdevent_get_handler(), FDEVENT_HANDLER_SELECT, FDEVENT_IN, fdevent_init(), fdevent_open_cloexec(), fdevent_poll(), fdevent_register(), fdevent_sched_run(), fdevent_unregister(), server::fdwaitqueue, fdwaitqueue_unshift(), server::gid, specific_config::global_bytes_per_second_cnt_ptr, server_config::groupname, HANDLER_ERROR, HANDLER_GO_ON, specific_config::high_precision_timestamps, server_config::high_precision_timestamps, HTTP_LINGER_TIMEOUT, connection::in_joblist, server::joblist, specific_config::kbytes_per_second, connection::keep_alive_idle, li_rand_reseed(), server_config::loadavg, server_config::loadts, log_error_close(), log_error_cycle(), log_error_open(), log_error_write(), specific_config::log_request_handling, specific_config::log_timeouts, server_config::max_conns, server::max_conns, server_config::max_fds, server::max_fds, specific_config::max_read_idle, server_config::max_worker, specific_config::max_write_idle, server_config::modules_dir, network_close(), network_init(), network_register_fdevents(), openDevNull(), server_config::pid_file, plugins_call_handle_sighup(), plugins_call_handle_trigger(), plugins_call_init(), plugins_call_set_defaults(), plugins_free(), server_config::port, server_config::preflight_check, buffer::ptr, connections::ptr, server_socket_array::ptr, connection::read_idle_ts, remove_pid_file(), connection::request, connection::request_count, server_free(), server_init(), server_oneshot_init(), show_features(), show_help(), show_version(), sigaction_handler(), server::sockets_disabled, server::srv_sockets, server::srvconf, server::stat_cache, server_config::stat_cache_engine, stat_cache_handle_fdevent(), stat_cache_init(), stat_cache_trigger_cleanup(), connection::state, server::tmp_buf, connection::traffic_limit_reached, server::uid, request::uri, array::used, connections::used, server_socket_array::used, server_config::username, server::want_fds, write_all(), and connection::write_request_ts.
static void remove_pid_file (server * srv, int * pid_fd) [static]
References buffer_string_is_empty(), server_config::changeroot, log_error_write(), server_config::pid_file, buffer::ptr, and server::srvconf.
Referenced by main().
static void server_free (server * srv) [static]
References array_free(), buffer_free(), CLEAN, server::config_context, server::config_storage, server::conns, specific_config::document_root, specific_config::error_handler, specific_config::error_handler_404, specific_config::errorfile_prefix, server::ev, fdevent_free(), fdevent_unregister(), server::fdwaitqueue, fdwaitqueue_free(), FILE_CACHE_MAX, server::joblist, joblist_free(), li_rand_cleanup(), specific_config::mimetypes, server_config::modules, server::mtime_cache, specific_config::server_name, specific_config::server_tag, server::split_vals, server::srvconf, specific_config::ssl_ca_file, specific_config::ssl_cipher_list, specific_config::ssl_dh_file, specific_config::ssl_ec_curve, server::ssl_is_init, specific_config::ssl_pemfile, specific_config::ssl_verifyclient_username, server::stat_cache, stat_cache_free(), mtime_cache_type::str, and array::used.
Referenced by main().
static server* server_init (void) [static]
References array_init(), buffer_init(), buffer_init_string(), CLEAN, server::conns, server::cur_ts, server::empty_string, server::errorlog_fd, server::errorlog_mode, server::fdwaitqueue, FILE_CACHE_MAX, force_assert, server_config::high_precision_timestamps, server_config::http_header_strict, server_config::http_host_normalize, server_config::http_host_strict, server::joblist, li_rand_reseed(), server_config::loadavg, server_config::max_request_field_size, server_config::modules, server_config::modules_dir, mtime_cache_type::mtime, server::mtime_cache, server_config::network_backend, server_config::reject_expect_100_with_417, server::split_vals, server::srvconf, server::startup_ts, mtime_cache_type::str, server_config::upload_tempdirs, and server_config::xattr_name.
Referenced by main().
static server_socket* server_oneshot_getsock (server * srv, sock_addr * cnt_addr) [static]
References server_socket::addr, sock_addr::ipv4, log_error_write(), sock_addr::plain, server_socket_array::ptr, server::srv_sockets, and server_socket_array::used.
Referenced by server_oneshot_init().
static int server_oneshot_init (server * srv, int fd) [static]
References connection_accepted(), connection_state_machine(), log_error_write(), network_accept_tcp_nagle_disable(), sock_addr::plain, and server_oneshot_getsock().
Referenced by main().
static void show_features (void) [static]
References show_version().
Referenced by main().
static void show_help (void) [static]
References PACKAGE_DESC, TEXT_SSL, and write_all().
Referenced by main().
static void show_version (void) [static]
References PACKAGE_DESC, TEXT_SSL, and write_all().
Referenced by main(), and show_features().
Variable Documentation
volatile sig_atomic_t forwarded_sig_hup = 0 [static]
volatile sig_atomic_t graceful_shutdown = 0 [static]
volatile sig_atomic_t handle_sig_alarm = 1 [static]
volatile sig_atomic_t handle_sig_hup = 0 [static]
int oneshot_fd = 0 [static]
volatile sig_atomic_t srv_shutdown = 0 [static]