splaytree.c File Reference
#include `splaytree.h`
*
#include <stdlib.h>
*
#include <assert.h>
*
Macros
#define compare(i, j) ((i)-(j))
#define node_size splaytree_size
Functions
splay_tree * splaytree_splay (splay_tree *t, int i)
splay_tree * splaytree_insert (splay_tree *t, int i, void *data)
splay_tree * splaytree_delete (splay_tree *t, int i)
Macro Definition Documentation
#define compare(i, j) ((i)-(j))
Referenced by splaytree_delete(), splaytree_insert(), and splaytree_splay().
#define node_size splaytree_size
Referenced by splaytree_insert(), and splaytree_splay().
Function Documentation
splay_tree* splaytree_delete (splay_tree * t, int i)
References compare, tree_node::key, tree_node::left, tree_node::right, tree_node::size, and splaytree_splay().
Referenced by stat_cache_free(), and stat_cache_trigger_cleanup().
splay_tree* splaytree_insert (splay_tree * t, int i, void * data)
References assert, compare, tree_node::key, tree_node::left, node_size, tree_node::right, tree_node::size, and splaytree_splay().
Referenced by stat_cache_get_entry().
splay_tree* splaytree_splay (splay_tree * t, int i)
References compare, tree_node::key, tree_node::left, node_size, tree_node::right, and tree_node::size.
Referenced by splaytree_delete(), splaytree_insert(), stat_cache_get_entry(), and stat_cache_trigger_cleanup().