splaytree.h File Reference
#include `first.h`
*
Classes
struct tree_node
Macros
#define splaytree_size(x) (((x)==NULL) ? 0 : ((x)->size))
Typedefs
typedef struct tree_node splay_tree
Functions
splay_tree * splaytree_splay (splay_tree *t, int key)
splay_tree * splaytree_insert (splay_tree *t, int key, void *data)
splay_tree * splaytree_delete (splay_tree *t, int key)
splay_tree * splaytree_size (splay_tree *t)
Macro Definition Documentation
#define splaytree_size(x) (((x)==NULL) ? 0 : ((x)->size))
Typedef Documentation
typedef struct tree_node splay_tree
Function Documentation
splay_tree* splaytree_delete (splay_tree * t, int key)
References compare, tree_node::key, tree_node::left, tree_node::right, tree_node::size, and splaytree_splay().
Referenced by stat_cache_free(), and stat_cache_trigger_cleanup().
splay_tree* splaytree_insert (splay_tree * t, int key, void * data)
References assert, compare, tree_node::key, tree_node::left, node_size, tree_node::right, tree_node::size, and splaytree_splay().
Referenced by stat_cache_get_entry().
splay_tree* splaytree_size (splay_tree * t)
Referenced by stat_cache_free(), stat_cache_get_entry(), and stat_cache_trigger_cleanup().
splay_tree* splaytree_splay (splay_tree * t, int key)
References compare, tree_node::key, tree_node::left, node_size, tree_node::right, and tree_node::size.
Referenced by splaytree_delete(), splaytree_insert(), stat_cache_get_entry(), and stat_cache_trigger_cleanup().