stat_cache.c File Reference
#include `first.h`
*
#include `log.h`
*
#include `stat_cache.h`
*
#include `fdevent.h`
*
#include `etag.h`
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <stdio.h>
*
#include <fcntl.h>
*
#include <assert.h>
*
Macros
#define lstat stat
#define O_NOCTTY 0
#define O_NONBLOCK 0
#define O_NOFOLLOW 0
Functions
stat_cache * stat_cache_init (void)
static stat_cache_entry * stat_cache_entry_init (void)
static void stat_cache_entry_free (void *data)
void stat_cache_free (stat_cache *sc)
static uint32_t hashme (buffer *str)
handler_t stat_cache_get_entry (server *srv, connection *con, buffer *name, stat_cache_entry **ret_sce)
int stat_cache_open_rdonly_fstat (server *srv, connection *con, buffer *name, struct stat *st)
static int stat_cache_tag_old_entries (server *srv, splay_tree *t, int *keys, size_t *ndx)
int stat_cache_trigger_cleanup (server *srv)
Macro Definition Documentation
#define lstat stat
#define O_NOCTTY 0
Referenced by stat_cache_open_rdonly_fstat().
#define O_NOFOLLOW 0
Referenced by stat_cache_open_rdonly_fstat().
#define O_NONBLOCK 0
Referenced by fdevent_fcntl_set_nb(), fdevent_socket_nb_cloexec(), and stat_cache_open_rdonly_fstat().
Function Documentation
static uint32_t hashme (buffer * str) [static]
References buffer::ptr, and uint32_t.
Referenced by stat_cache_get_entry().
static void stat_cache_entry_free (void * data) [static]
References buffer_free(), stat_cache_entry::content_type, stat_cache_entry::etag, and stat_cache_entry::name.
Referenced by stat_cache_free(), stat_cache_get_entry(), and stat_cache_trigger_cleanup().
static stat_cache_entry* stat_cache_entry_init (void) [static]
References buffer_init(), stat_cache_entry::content_type, stat_cache_entry::etag, force_assert, and stat_cache_entry::name.
Referenced by stat_cache_get_entry().
void stat_cache_free (stat_cache * sc)
References buffer_free(), tree_node::data, stat_cache::dir_name, stat_cache::files, force_assert, stat_cache::hash_key, tree_node::key, tree_node::size, splaytree_delete(), splaytree_size(), and stat_cache_entry_free().
Referenced by server_free().
handler_t stat_cache_get_entry (server * srv, connection * con, buffer * name, stat_cache_entry ** ret_sce)
References buffer_append_int(), buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), connection::conf, stat_cache_entry::content_type, server::cur_ts, tree_node::data, array::data, stat_cache::dir_name, stat_cache_entry::etag, etag_create(), connection::etag_flags, stat_cache::files, specific_config::follow_symlink, force_assert, HANDLER_ERROR, HANDLER_GO_ON, stat_cache::hash_key, hashme(), tree_node::key, log_error_write(), specific_config::mimetypes, stat_cache_entry::name, buffer::ptr, splaytree_insert(), splaytree_size(), splaytree_splay(), server::srvconf, stat_cache_entry::st, server::stat_cache, server_config::stat_cache_engine, stat_cache_entry_free(), stat_cache_entry_init(), stat_cache_entry::stat_ts, specific_config::use_xattr, array::used, data_string::value, and server_config::xattr_name.
Referenced by build_doc_root(), CONNECTION_FUNC(), connection_handle_write_prepare(), deflate_file_to_file(), fcgi_response_parse(), http_chunk_append_file_open_fstat(), http_response_prepare(), http_response_send_file(), magnet_stat(), mod_evhost_uri_handler(), PHYSICALPATH_FUNC(), script_cache_get_script(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), and webdav_get_live_property().
stat_cache* stat_cache_init (void)
References buffer_init(), stat_cache::dir_name, force_assert, and stat_cache::hash_key.
Referenced by main().
int stat_cache_open_rdonly_fstat (server * srv, connection * con, buffer * name, struct stat * st)
References connection::conf, specific_config::follow_symlink, O_BINARY, O_LARGEFILE, O_NOCTTY, O_NOFOLLOW, O_NONBLOCK, buffer::ptr, and UNUSED.
Referenced by cache_parse_lua(), and http_chunk_append_file_open_fstat().
static int stat_cache_tag_old_entries (server * srv, splay_tree * t, int * keys, size_t * ndx) [static]
remove stat() from cache which havn't been stat()ed for more than 10 seconds
walk though the stat-cache, collect the ids which are too old and remove them in a second loop
References server::cur_ts, tree_node::data, tree_node::key, tree_node::left, tree_node::right, and stat_cache_entry::stat_ts.
Referenced by stat_cache_trigger_cleanup().
int stat_cache_trigger_cleanup (server * srv)
References tree_node::data, stat_cache::files, force_assert, tree_node::key, tree_node::size, splaytree_delete(), splaytree_size(), splaytree_splay(), server::stat_cache, stat_cache_entry_free(), and stat_cache_tag_old_entries().
Referenced by main().