stat_cache.h File Reference
#include `first.h`
*
#include `base.h`
*
Functions
stat_cache * stat_cache_init (void)
void stat_cache_free (stat_cache *fc)
handler_t stat_cache_get_entry (server *srv, connection *con, buffer *name, stat_cache_entry **fce)
handler_t stat_cache_handle_fdevent (server *srv, void *_fce, int revent)
int stat_cache_open_rdonly_fstat (server *srv, connection *con, buffer *name, struct stat *st)
int stat_cache_trigger_cleanup (server *srv)
Function Documentation
void stat_cache_free (stat_cache * fc)
References buffer_free(), tree_node::data, stat_cache::dir_name, stat_cache::files, force_assert, stat_cache::hash_key, tree_node::key, tree_node::size, splaytree_delete(), splaytree_size(), and stat_cache_entry_free().
Referenced by server_free().
handler_t stat_cache_get_entry (server * srv, connection * con, buffer * name, stat_cache_entry ** fce)
References buffer_append_int(), buffer_copy_buffer(), buffer_free(), buffer_init(), buffer_is_empty(), buffer_is_equal(), buffer_reset(), buffer_string_is_empty(), buffer_string_length(), buffer_string_set_length(), connection::conf, stat_cache_entry::content_type, server::cur_ts, tree_node::data, array::data, stat_cache::dir_name, stat_cache_entry::etag, etag_create(), connection::etag_flags, stat_cache::files, specific_config::follow_symlink, force_assert, HANDLER_ERROR, HANDLER_GO_ON, stat_cache::hash_key, hashme(), tree_node::key, log_error_write(), specific_config::mimetypes, stat_cache_entry::name, buffer::ptr, splaytree_insert(), splaytree_size(), splaytree_splay(), server::srvconf, stat_cache_entry::st, server::stat_cache, server_config::stat_cache_engine, stat_cache_entry_free(), stat_cache_entry_init(), stat_cache_entry::stat_ts, specific_config::use_xattr, array::used, data_string::value, and server_config::xattr_name.
Referenced by build_doc_root(), CONNECTION_FUNC(), connection_handle_write_prepare(), deflate_file_to_file(), fcgi_response_parse(), http_chunk_append_file_open_fstat(), http_response_prepare(), http_response_send_file(), magnet_stat(), mod_evhost_uri_handler(), PHYSICALPATH_FUNC(), script_cache_get_script(), SUBREQUEST_FUNC(), URIHANDLER_FUNC(), and webdav_get_live_property().
handler_t stat_cache_handle_fdevent (server * srv, void * _fce, int revent)
Referenced by main().
stat_cache* stat_cache_init (void)
References buffer_init(), stat_cache::dir_name, force_assert, and stat_cache::hash_key.
Referenced by main().
int stat_cache_open_rdonly_fstat (server * srv, connection * con, buffer * name, struct stat * st)
References connection::conf, specific_config::follow_symlink, O_BINARY, O_LARGEFILE, O_NOCTTY, O_NOFOLLOW, O_NONBLOCK, buffer::ptr, and UNUSED.
Referenced by cache_parse_lua(), and http_chunk_append_file_open_fstat().
int stat_cache_trigger_cleanup (server * srv)
References tree_node::data, stat_cache::files, force_assert, tree_node::key, tree_node::size, splaytree_delete(), splaytree_size(), splaytree_splay(), server::stat_cache, stat_cache_entry_free(), and stat_cache_tag_old_entries().
Referenced by main().