status_counter.c File Reference
#include `first.h`
*
#include `status_counter.h`
*
#include <stdlib.h>
*
Functions
data_integer * status_counter_get_counter (server *srv, const char *s, size_t len)
int status_counter_inc (server *srv, const char *s, size_t len)
int status_counter_dec (server *srv, const char *s, size_t len)
int status_counter_set (server *srv, const char *s, size_t len, int val)
Function Documentation
int status_counter_dec (server * srv, const char * s, size_t len)
References status_counter_get_counter(), and data_integer::value.
Referenced by fcgi_proc_load_dec().
data_integer* status_counter_get_counter (server * srv, const char * s, size_t len)
The status array can carry all the status information you want the key to the array is <module-prefix>.<name> and the values are counters
example: fastcgi.backends = 10 fastcgi.active-backends = 6 fastcgi.backend.<key>.load = 24 fastcgi.backend.<key>....
fastcgi.backend.<key>.disconnects = ...
References array_get_element(), array_get_unused_element(), array_insert_unique(), buffer_copy_string_len(), data_integer_init(), server::status, TYPE_INTEGER, and data_integer::value.
Referenced by magnet_status_get(), status_counter_dec(), status_counter_inc(), and status_counter_set().
int status_counter_inc (server * srv, const char * s, size_t len)
References status_counter_get_counter(), and data_integer::value.
Referenced by fcgi_proc_load_inc(), and fcgi_write_request().
int status_counter_set (server * srv, const char * s, size_t len, int val)
References status_counter_get_counter(), and data_integer::value.
Referenced by fcgi_host_assign(), fcgi_host_reset(), fcgi_proc_load_dec(), fcgi_proc_load_inc(), and magnet_status_set().