fdevents Struct Reference
#include <fdevent.h>
Public Attributes
struct server * srv
fdevent_handler_t type
fdnode ** fdarray
size_t maxfds
int highfd
int(* reset)(struct fdevents *ev)
void(* free)(struct fdevents *ev)
int(* event_set)(struct fdevents *ev, int fde_ndx, int fd, int events)
int(* event_del)(struct fdevents *ev, int fde_ndx, int fd)
int(* event_get_revent)(struct fdevents *ev, size_t ndx)
int(* event_get_fd)(struct fdevents *ev, size_t ndx)
int(* event_next_fdndx)(struct fdevents *ev, int ndx)
int(* poll)(struct fdevents *ev, int timeout_ms)
int(* fcntl_set)(struct fdevents *ev, int fd)
Detailed Description
fd-event handler for select(), poll() and rt-signals on Linux 2.4
Member Data Documentation
int(* fdevents::event_del)(struct fdevents *ev, int fde_ndx, int fd)
Referenced by fdevent_event_del().
int(* fdevents::event_get_fd)(struct fdevents *ev, size_t ndx)
Referenced by fdevent_event_get_fd().
int(* fdevents::event_get_revent)(struct fdevents *ev, size_t ndx)
Referenced by fdevent_event_get_revent().
int(* fdevents::event_next_fdndx)(struct fdevents *ev, int ndx)
Referenced by fdevent_event_next_fdndx().
int(* fdevents::event_set)(struct fdevents *ev, int fde_ndx, int fd, int events)
Referenced by fdevent_event_add(), fdevent_event_clr(), and fdevent_event_set().
int(* fdevents::fcntl_set)(struct fdevents *ev, int fd)
Referenced by fdevent_fcntl_set(), fdevent_fcntl_set_nb(), and fdevent_fcntl_set_nb_cloexec_sock().
fdnode** fdevents::fdarray
Referenced by fdevent_event_add(), fdevent_event_clr(), fdevent_event_del(), fdevent_event_set(), fdevent_free(), fdevent_get_context(), fdevent_get_handler(), fdevent_init(), fdevent_register(), fdevent_sched_close(), fdevent_sched_run(), and fdevent_unregister().
void(* fdevents::free)(struct fdevents *ev)
Referenced by fdevent_free().
int fdevents::highfd
Referenced by fdevent_init(), fdevent_sched_close(), and fdevent_sched_run().
size_t fdevents::maxfds
Referenced by fdevent_free(), and fdevent_init().
int(* fdevents::poll)(struct fdevents *ev, int timeout_ms)
Referenced by fdevent_poll().
int(* fdevents::reset)(struct fdevents *ev)
Referenced by fdevent_reset().
struct server* fdevents::srv
Referenced by fdevent_freebsd_kqueue_init(), fdevent_init(), fdevent_libev_init(), fdevent_linux_sysepoll_init(), fdevent_poll_init(), fdevent_solaris_devpoll_init(), and fdevent_solaris_port_init().
fdevent_handler_t fdevents::type
The documentation for this struct was generated from the following file:
fdevent.h