plugin Struct Reference
#include <plugin.h>
Public Attributes
size_t version
buffer * name
void *(* init)()
handler_t(* set_defaults)(server *srv, void *p_d)
handler_t(* cleanup)(server *srv, void *p_d)
handler_t(* handle_trigger)(server *srv, void *p_d)
handler_t(* handle_sighup)(server *srv, void *p_d)
handler_t(* handle_uri_raw)(server *srv, connection *con, void *p_d)
handler_t(* handle_uri_clean)(server *srv, connection *con, void *p_d)
handler_t(* handle_docroot)(server *srv, connection *con, void *p_d)
handler_t(* handle_physical)(server *srv, connection *con, void *p_d)
handler_t(* handle_request_done)(server *srv, connection *con, void *p_d)
handler_t(* handle_connection_close)(server *srv, connection *con, void *p_d)
handler_t(* handle_subrequest_start)(server *srv, connection *con, void *p_d)
handler_t(* handle_subrequest)(server *srv, connection *con, void *p_d)
handler_t(* handle_response_start)(server *srv, connection *con, void *p_d)
handler_t(* connection_reset)(server *srv, connection *con, void *p_d)
void * data
void * lib
Member Data Documentation
handler_t(* plugin::cleanup)(server *srv, void *p_d)
Referenced by mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_plugin_init(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), and mod_webdav_plugin_init().
handler_t(* plugin::connection_reset)(server *srv, connection *con, void *p_d)
Referenced by mod_authn_gssapi_plugin_init(), mod_cgi_plugin_init(), mod_deflate_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_rewrite_plugin_init(), mod_scgi_plugin_init(), mod_setenv_plugin_init(), mod_ssi_plugin_init(), and mod_webdav_plugin_init().
void* plugin::data
Referenced by connection_handle_shutdown(), mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_plugin_init(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), mod_webdav_plugin_init(), and plugins_call_init().
handler_t(* plugin::handle_connection_close)(server *srv, connection *con, void *p_d)
Referenced by mod_deflate_plugin_init(), mod_fastcgi_plugin_init(), mod_proxy_plugin_init(), mod_scgi_plugin_init(), and mod_uploadprogress_plugin_init().
handler_t(* plugin::handle_docroot)(server *srv, connection *con, void *p_d)
Referenced by mod_evhost_plugin_init(), mod_mysql_vhost_plugin_init(), and mod_simple_vhost_plugin_init().
handler_t(* plugin::handle_physical)(server *srv, connection *con, void *p_d)
Referenced by mod_alias_plugin_init(), mod_cml_plugin_init(), mod_flv_streaming_plugin_init(), mod_magnet_plugin_init(), mod_rewrite_plugin_init(), mod_secdownload_plugin_init(), mod_userdir_plugin_init(), and mod_webdav_plugin_init().
handler_t(* plugin::handle_request_done)(server *srv, connection *con, void *p_d)
Referenced by mod_accesslog_plugin_init(), mod_extforward_plugin_init(), mod_rrdtool_plugin_init(), mod_status_plugin_init(), and mod_uploadprogress_plugin_init().
handler_t(* plugin::handle_response_start)(server *srv, connection *con, void *p_d)
Referenced by mod_deflate_plugin_init(), and mod_expire_plugin_init().
handler_t(* plugin::handle_sighup)(server *srv, void *p_d)
Referenced by mod_accesslog_plugin_init().
handler_t(* plugin::handle_subrequest)(server *srv, connection *con, void *p_d)
Referenced by mod_cgi_plugin_init(), mod_fastcgi_plugin_init(), mod_proxy_plugin_init(), mod_scgi_plugin_init(), mod_ssi_plugin_init(), and mod_webdav_plugin_init().
handler_t(* plugin::handle_subrequest_start)(server *srv, connection *con, void *p_d)
Referenced by mod_access_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_dirlisting_plugin_init(), mod_fastcgi_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_scgi_plugin_init(), mod_ssi_plugin_init(), and mod_staticfile_plugin_init().
handler_t(* plugin::handle_trigger)(server *srv, void *p_d)
Referenced by mod_cgi_plugin_init(), mod_fastcgi_plugin_init(), mod_proxy_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_status_plugin_init(), and mod_trigger_b4_dl_plugin_init().
handler_t(* plugin::handle_uri_clean)(server *srv, connection *con, void *p_d)
Referenced by mod_access_plugin_init(), mod_auth_plugin_init(), mod_evasive_plugin_init(), mod_fastcgi_plugin_init(), mod_magnet_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_scgi_plugin_init(), mod_setenv_plugin_init(), mod_skeleton_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_usertrack_plugin_init(), and mod_webdav_plugin_init().
handler_t(* plugin::handle_uri_raw)(server *srv, connection *con, void *p_d)
Referenced by mod_extforward_plugin_init(), and mod_rewrite_plugin_init().
void*(* plugin::init)()
Referenced by mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_plugin_init(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), mod_webdav_plugin_init(), and plugins_call_init().
void* plugin::lib
Referenced by plugin_free(), and plugins_load().
buffer* plugin::name
Referenced by connection_handle_shutdown(), mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_plugin_init(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_handle_server_config(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), mod_webdav_plugin_init(), plugin_free(), and plugins_call_init().
handler_t(* plugin::set_defaults)(server *srv, void *p_d)
Referenced by mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_plugin_init(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), and mod_webdav_plugin_init().
size_t plugin::version
Referenced by mod_access_plugin_init(), mod_accesslog_plugin_init(), mod_alias_plugin_init(), mod_auth_plugin_init(), mod_authn_file_plugin_init(), mod_authn_gssapi_plugin_init(), mod_authn_ldap_plugin_init(), mod_authn_mysql_plugin_init(), mod_cgi_plugin_init(), mod_cml_plugin_init(), mod_compress_plugin_init(), mod_deflate_plugin_init(), mod_dirlisting_plugin_init(), mod_evasive_plugin_init(), mod_evhost_plugin_init(), mod_expire_plugin_init(), mod_extforward_plugin_init(), mod_fastcgi_plugin_init(), mod_flv_streaming_plugin_init(), mod_geoip_plugin_init(), mod_indexfile_plugin_init(), mod_magnet_plugin_init(), mod_mysql_vhost_plugin_init(), mod_proxy_plugin_init(), mod_redirect_plugin_init(), mod_rewrite_plugin_init(), mod_rrdtool_plugin_init(), mod_scgi_plugin_init(), mod_secdownload_plugin_init(), mod_setenv_plugin_init(), mod_simple_vhost_plugin_init(), mod_skeleton_plugin_init(), mod_ssi_plugin_init(), mod_staticfile_plugin_init(), mod_status_plugin_init(), mod_trigger_b4_dl_plugin_init(), mod_uploadprogress_plugin_init(), mod_userdir_plugin_init(), mod_usertrack_plugin_init(), mod_webdav_plugin_init(), and plugins_call_init().
The documentation for this struct was generated from the following file:
plugin.h