test_buffer.c File Reference
#include `first.h`
*
#include `buffer.h`
*
Functions
static void run_buffer_path_simplify (buffer *psrc, buffer *pdest, const char *in, size_t in_len, const char *out, size_t out_len)
static void test_buffer_path_simplify_with (buffer *psrc, buffer *pdest)
static void test_buffer_path_simplify ()
int main ()
Function Documentation
int main (void)
References test_buffer_path_simplify().
static void run_buffer_path_simplify (buffer * psrc, buffer * pdest, const char * in, size_t in_len, const char * out, size_t out_len) [static]
References buffer_copy_buffer(), buffer_copy_string_len(), buffer_is_equal_string(), buffer_path_simplify(), and buffer::ptr.
Referenced by test_buffer_path_simplify_with().
static void test_buffer_path_simplify () [static]
References buffer_free(), buffer_init(), and test_buffer_path_simplify_with().
Referenced by main().
static void test_buffer_path_simplify_with (buffer * psrc, buffer * pdest) [static]
References CONST_STR_LEN, and run_buffer_path_simplify().
Referenced by test_buffer_path_simplify().