test_configfile.c File Reference
#include `configfile-glue.c`
*
#include <assert.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
Functions
static void test_configfile_addrbuf_eq_remote_ip_mask (void)
int main (void)
void fd_close_on_exec (int fd)
Variables
xx xx xx xx xx xx xx xx xx
struct {
 const char * string
 const char * rmtstr
 int rmtfamily
 int expect
} rmtmask []
Function Documentation
void fd_close_on_exec (int fd)
References force_assert, and UNUSED.
int main (void)
References test_configfile_addrbuf_eq_remote_ip_mask().
static void test_configfile_addrbuf_eq_remote_ip_mask (void) [static]
References assert, buffer_copy_string(), buffer_free(), buffer_init(), config_addrbuf_eq_remote_ip_mask(), expect, sock_addr::ipv4, buffer::ptr, rmtfamily, rmtmask, and rmtstr.
Referenced by main().
Variable Documentation
int expect
Referenced by test_configfile_addrbuf_eq_remote_ip_mask().
int rmtfamily
Referenced by test_configfile_addrbuf_eq_remote_ip_mask().
const { ... } rmtmask[]
Initial value:
= {
    { "1.0.0.1/1", "1.0.0.1", AF_INET, 1 }
   ,{ "254.254.254.254/1", "254.0.0.1", AF_INET, 1 }
   ,{ "254.254.254.252/31", "254.254.254.253", AF_INET, 1 }
   ,{ "254.254.254.253/31", "254.254.254.254", AF_INET, 0 }
   ,{ "254.254.254.253/32", "254.254.254.254", AF_INET, 0 }
   ,{ "254.254.254.254/32", "254.254.254.254", AF_INET, 1 }
}
Referenced by test_configfile_addrbuf_eq_remote_ip_mask().
const char* rmtstr
Referenced by test_configfile_addrbuf_eq_remote_ip_mask().
const char* string