test_base64.c File Reference
#include `first.h`
*
#include `base64.h`
*
Functions
static void check_all_len_0 ()
static void check_all_len_1 ()
static void check_all_len_2 ()
static void check_all_len_3 ()
int main ()
Function Documentation
static void check_all_len_0 () [static]
References BASE64_STANDARD, BASE64_URL, buffer_append_base64_decode(), buffer_free(), buffer_init(), buffer_is_equal_string(), buffer_reset(), force_assert, li_to_base64_no_padding(), and buffer::ptr.
Referenced by main().
static void check_all_len_1 () [static]
References BASE64_STANDARD, BASE64_URL, buffer_append_base64_decode(), buffer_free(), buffer_init(), buffer_is_equal_string(), buffer_reset(), force_assert, li_to_base64_no_padding(), and buffer::ptr.
Referenced by main().
static void check_all_len_2 () [static]
References BASE64_STANDARD, BASE64_URL, buffer_append_base64_decode(), buffer_free(), buffer_init(), buffer_is_equal_string(), buffer_reset(), force_assert, li_to_base64_no_padding(), and buffer::ptr.
Referenced by main().
static void check_all_len_3 () [static]
References BASE64_STANDARD, BASE64_URL, buffer_append_base64_decode(), buffer_free(), buffer_init(), buffer_is_equal_string(), buffer_reset(), force_assert, li_to_base64_no_padding(), and buffer::ptr.
Referenced by main().
int main (void)
References check_all_len_0(), check_all_len_1(), check_all_len_2(), and check_all_len_3().